### PR TITLE
fix(noPrecisionLoss): correctly handle large hex literals

### LINKED ISSUE #8145: 💅 correctness/noPrecisionLoss incorrectly flags hex literals above or equal to 2^53 even if valid
### Environment information

```bash
CLI:
  Version:                      2.3.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  unset
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noImportantStyles
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useIndexOf
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useExhaustiveDependencies
    correctness/useGraphqlNamedOperations
    correctness/useHookAtTopLevel
    correctness/useImportExtensions
    correctness/useIsNan
    correctness/useParseIntRadix
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noGlobalEval
    style/noDescendingSpecificity
    style/useArrayLiterals
    style/useConst
    style/useDeprecatedReason
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useShorthandFunctionType
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noBiomeFirstException
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noNonNullAssertedOptionalChain
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noQuickfixBiome
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noTsIgnore
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noUselessEscapeInString
    suspicious/noUselessRegexBackrefs
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useBiomeIgnoreFolder
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useIterableCallbackReturn
    suspicious/useNamespaceKeyword

Workspace:
  Open Documents:               0
```

### Rule name

correctness/noPrecisionLoss

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&trailingCommas=none&bracketSameLine=true&lintRules=noPrecisionLoss&code=YwBvAG4AcwB0ACAAVABXAE8AXwBQAE8AVwBfADUAMwBfAEgARQBYACAAPQAgADAAeAAyADAAXwAwADAAMAAwAF8AMAAwADAAMABfADAAMAAwADAAOwAKAGMAbwBuAHMAdAAgAFQAVwBPAF8AUABPAFcAXwA1ADMAXwBEAEUAQwAgAD0AIAA5ADAAMAA3ADEAOQA5ADIANQA0ADcANAAwADkAOQAyADsACgAKAGMAbwBuAHMAdAAgAFQAVwBPAF8AUABPAFcAMgBfAEgARQBYACAAPQAgADAAeAAzADAAXwAwADAAMAAwAF8AMAAwADAAMABfADAAMAAwADAAOwAKAGMAbwBuAHMAdAAgAFQAVwBPAF8AUABPAFcAMgBfAEQARQBDACAAPQAgADEAMwA1ADEAMAA3ADkAOAA4ADgAMgAxADEAMQA0ADgAOAA7AA%3D%3D

### Expected result

Emit no errors for hex literals that are correctly represented in JS via f64

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by JeremyMoeglich**
Disclaimer: large parts of this PR were written by Gemini 3, I reviewed each change manually and made some changes.

## Summary

Fixes #8145, hex literals like 0x20_0000_0000_0000 or 0x30_0000_0000_0000 would previously be incorrectly flagged, instead of correctly checking if the provided literal is exactly representable as an f64 it would just check if it's in the safe integer range.
While working on this I also noticed a problem that affects another lint rule noConstantMathMinMaxClamp where large hex literals above 2^63 - 1 would never trigger the error because as_number() internally tried to parse into an i64 which is incorrect.

## Test Plan

There are existing tests along with some newly added ones.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs [hunk 1]
```diff
@@ -120,21 +117,64 @@ fn is_precision_lost_in_base_10(num: &str) -> Option<bool> {
...
+            Some(d) => d,
+            None => return false, // Should not happen for valid literals
+        };
+
+        // Check bits of the digit
+        let bits_per_digit = match radix {
+            16 => 4,
+            8 => 3,
+            2 => 1,
+            _ => unreachable!("radix must be 2, 8, or 16"),
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs]: nit: add a comment to explain how this is unreachable

File: crates/biome_js_analyze/tests/specs/correctness/noConstantMathMinMaxClamp/invalid_large_hex.js.snap [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+# Diagnostics
+```
+invalid_large_hex.js:2:1 lint/correctness/noConstantMathMinMaxClamp  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━
+
+  × This Math.min/Math.max combination leads to a constant result.
+  
+    1 │ // Large hex literals, previously failed as they exceed i64
+  > 2 │ Math.min(0x10000000000000000, Math.max(0x20000000000000000, x));
+      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noConstantMathMinMaxClamp/invalid_large_hex.js.snap]: Is this case supposed to be valid or invalid?

If this is supposed to be an invalid case, then remove the "previously failed" part of the comment at least.

File: .changeset/odd-kings-obey.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#8145](https://github.com/biomejs/biome/issues/8145): handling of large hex literals, which previously caused both false positives and false negatives.
+
+This affects [`no-precision-loss`](https://biomejs.dev/linter/rules/no-precision-loss/) and [`no-constant-math-min-max-clamp`](https://biomejs.dev/linter/rules/no-constant-math-min-max-clamp/).
```
Comment (dyc3) [inline .changeset/odd-kings-obey.md]:
```suggestion
This affects [`noPrecisionLoss`](https://biomejs.dev/linter/rules/no-precision-loss/) and [`noConstantMathMinMaxClamp`](https://biomejs.dev/linter/rules/no-constant-math-min-max-clamp/).
```

File: crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/invalid.js [hunk 4]
```diff
@@ -33,4 +33,10 @@ var x = 0B10000000000_0000000000000000000000000000_000000000000001
...
 var x = 0x2_0000000000001
-var x = 0X200000_0000000_1
\ No newline at end of file
+var x = 0X200000_0000000_1
+// From repro_issue.js
+var x = 0x20000000000001; // 2^53 + 1 (Invalid, precision loss)
+var x = 9007199254740993; // 2^53 + 1 (Invalid, precision loss)
+var x = 0x10000000000000000000000001; // 2^100 + 1 (Invalid, precision loss)
+// 2^1024 (Overflow, Invalid)
+var x = 0x10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/invalid.js]: Need to also test binary and octals.

File: crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/invalid.js [hunk 5]
```diff
@@ -33,4 +33,10 @@ var x = 0B10000000000_0000000000000000000000000000_000000000000001
 var x = 0o4_00000000000000_001
 var x = 0O4_0000000000000000_1
 var x = 0x2_0000000000001
-var x = 0X200000_0000000_1
\ No newline at end of file
+var x = 0X200000_0000000_1
+// From repro_issue.js
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/invalid.js]: nit: 
```suggestion
```

File: crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/valid.js [hunk 6]
```diff
@@ -76,4 +76,10 @@ var x = 0X1_FFF_FFFF_FFF_FFF
 123_00000000000000000000_00.0_0;
 
 var MAX = 1.7976931348623157e+308;
-var MIN = 5e-324;
\ No newline at end of file
+var MIN = 5e-324;
+// From repro_issue.js
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noPrecisionLoss/valid.js]: nit:
```suggestion
```

File: crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs (hunk 1 above)
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs]: If possible let's remove `unreachable` because it panics. Let's find a safer solution

File: crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs [hunk 7]
```diff
@@ -120,21 +117,64 @@ fn is_precision_lost_in_base_10(num: &str) -> Option<bool> {
...
 fn is_precision_lost_in_base_other(num: &str, radix: u8) -> bool {
-    let parsed = match i64::from_str_radix(num, radix as u32) {
-        Ok(x) => x,
-        Err(e) => {
-            return matches!(
-                e.kind(),
-                IntErrorKind::PosOverflow | IntErrorKind::NegOverflow
-            );
+    let mut msb: Option<u64> = None;
+    let mut lsb: Option<u64> = None;
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs]: Can we have more descriptive names please?

File: crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs [hunk 8]
```diff
@@ -120,21 +117,64 @@ fn is_precision_lost_in_base_10(num: &str) -> Option<bool> {
...
+        // Check bits of the digit
+        let bits_per_digit = match radix {
+            16 => 4,
+            8 => 3,
+            2 => 1,
+            _ => unreachable!("radix must be 2, 8, or 16"),
+        };
+
+        for i in 0..bits_per_digit {
+            if (digit >> i) & 1 == 1 {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/no_precision_loss.rs]: This code is very cryptic. Can we:
1. Add a comment that explains what we're doing 
2. Or refactor it, so it's clearer
