### PR TITLE
fix: allow overriding rule group by each rule

### LINKED ISSUE #5456: 💅 [v2] Overrides not working when all linter category rules are on
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.13.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.1.42

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /Users/kevinwolfcr/Developer/github.com/kevinwolfcr/biome-repro-v2-overrides/biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  unset
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noBlankTarget
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noBannedTypes
    complexity/noEmptyTypeParameters
    complexity/noExcessiveCognitiveComplexity
    complexity/noExcessiveNestedTestSuites
    complexity/noExtraBooleanCast
    complexity/noForEach
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessEmptyExport
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringConcat
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/noVoid
    complexity/noWith
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    complexity/useSimplifiedLogicExpression
    complexity/useWhile
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noFlatMapIdentity
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidNewBuiltin
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noNewSymbol
    correctness/noNodejsModules
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noPrivateImports
    correctness/noRenderReturnValue
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUndeclaredDependencies
    correctness/noUndeclaredVariables
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noUselessContinue
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useArrayLiterals
    correctness/useExhaustiveDependencies
    correctness/useHookAtTopLevel
    correctness/useImportExtensions
    correctness/useIsNan
    correctness/useJsxKeyInIterable
    correctness/useValidForDirection
    correctness/useYield
    nursery/noAwaitInLoop
    nursery/noBitwiseOperators
    nursery/noCommonJs
    nursery/noConstantBinaryExpression
    nursery/noDescendingSpecificity
    nursery/noDestructuredProps
    nursery/noDocumentCookie
    nursery/noDocumentImportInPage
    nursery/noDuplicateCustomProperties
    nursery/noDuplicateElseIf
    nursery/noDuplicateFields
    nursery/noDuplicateProperties
    nursery/noDynamicNamespaceImportAccess
    nursery/noEnum
    nursery/noExportedImports
    nursery/noFloatingPromises
    nursery/noGlobalDirnameFilename
    nursery/noHeadElement
    nursery/noHeadImportInDocument
    nursery/noImgElement
    nursery/noImportCycles
    nursery/noIrregularWhitespace
    nursery/noMissingVarFunction
    nursery/noNestedTernary
    nursery/noNoninteractiveElementInteractions
    nursery/noOctalEscape
    nursery/noProcessEnv
    nursery/noProcessGlobal
    nursery/noRestrictedImports
    nursery/noRestrictedTypes
    nursery/noSecrets
    nursery/noStaticElementInteractions
    nursery/noSubstr
    nursery/noTemplateCurlyInString
    nursery/noTsIgnore
    nursery/noUnknownAtRule
    nursery/noUnknownPseudoClass
    nursery/noUnknownPseudoElement
    nursery/noUnknownTypeSelector
    nursery/noUnwantedPolyfillio
    nursery/noUselessEscapeInRegex
    nursery/noUselessEscapeInString
    nursery/noUselessStringRaw
    nursery/noUselessUndefined
    nursery/noValueAtRule
    nursery/useAdjacentOverloadSignatures
    nursery/useAriaPropsSupportedByRole
    nursery/useAtIndex
    nursery/useCollapsedIf
    nursery/useComponentExportOnlyModules
    nursery/useConsistentCurlyBraces
    nursery/useConsistentMemberAccessibility
    nursery/useConsistentObjectDefinition
    nursery/useDeprecatedReason
    nursery/useExplicitType
    nursery/useExportsLast
    nursery/useForComponent
    nursery/useGoogleFontDisplay
    nursery/useGoogleFontPreconnect
    nursery/useGuardForIn
    nursery/useNamedOperation
    nursery/useNamingConvention
    nursery/useParseIntRadix
    nursery/useSortedClasses
    nursery/useStrictMode
    nursery/useSymbolDescription
    nursery/useTrimStartEnd
    nursery/useValidAutocomplete
    performance/noAccumulatingSpread
    performance/noBarrelFile
    performance/noDelete
    performance/noReExportAll
    performance/useTopLevelRegex
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noArguments
    style/noCommaOperator
    style/noDefaultExport
    style/noDoneCallback
    style/noImplicitBoolean
    style/noInferrableTypes
    style/noNamespace
    style/noNamespaceImport
    style/noNegationElse
    style/noNonNullAssertion
    style/noParameterAssign
    style/noParameterProperties
    style/noRestrictedGlobals
    style/noShoutyConstants
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/noYodaExpression
    style/useAsConstAssertion
    style/useBlockStatements
    style/useCollapsedElseIf
    style/useConsistentArrayType
    style/useConsistentBuiltinInstantiation
    style/useConst
    style/useDefaultParameterLast
    style/useDefaultSwitchClause
    style/useEnumInitializers
    style/useExplicitLengthCheck
    style/useExponentiationOperator
    style/useExportType
    style/useFilenamingConvention
    style/useForOf
    style/useFragmentSyntax
    style/useImportType
    style/useLiteralEnumMembers
    style/useNamingConvention
    style/useNodeAssertStrict
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useNumericLiterals
    style/useSelfClosingElements
    style/useShorthandArrayType
    style/useShorthandAssign
    style/useShorthandFunctionType
    style/useSingleCaseStatement
    style/useSingleVarDeclarator
    style/useTemplate
    style/useThrowNewError
    style/useThrowOnlyError
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConsole
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noDuplicateTestHooks
    suspicious/noEmptyBlock
    suspicious/noEmptyBlockStatements
    suspicious/noEmptyInterface
    suspicious/noEvolvingTypes
    suspicious/noExplicitAny
    suspicious/noExportsInTest
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFocusedTests
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisplacedAssertion
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noPrototypeBuiltins
    suspicious/noReactSpecificProps
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSkippedTests
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noVar
    suspicious/useAwait
    suspicious/useDefaultSwitchClauseLast
    suspicious/useErrorMessage
    suspicious/useGetterReturn
    suspicious/useIsArray
    suspicious/useNamespaceKeyword
    suspicious/useNumberToFixedDigitsArgument
    suspicious/useValidTypeof

Workspace:
  Open Documents:               0
```

### Rule name

nursery/useExplicitType

### Playground link

https://github.com/kevinwolfcr/biome-repro-v2-overrides

### Expected result

For the below configuration, the `overrides` are not properly overriding the `nursery/useExplicitType` rule:

```json

{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "linter": {
    "rules": {
      "a11y": "on",
      "complexity": "on",
      "correctness": "on",
      "nursery": "on",
      "performance": "on",
      "security": "on",
      "style": "on",
      "suspicious": "on"
    }
  },
  "overrides": [
    {
      "includes": ["**/*"],
      "linter": {
        "rules": {
          "nursery": {
            "useExplicitType": "off"
          }
        }
      }
    }
  ]
}
```

However, if the rule is manually enabled (not using `all` on the group) and then overrode, it does properly override it:

```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "linter": {
    "rules": {
      "a11y": "on",
      "complexity": "on",
      "correctness": "on",
      "nursery": {
        "useExplicitType": "error"
      },
      "performance": "on",
      "security": "on",
      "style": "on",
      "suspicious": "on"
    }
  },
  "overrides": [
    {
      "includes": ["**/*"],
      "linter": {
        "rules": {
          "nursery": {
            "useExplicitType": "off"
          }
        }
      }
    }
  ]
}
```

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by siketyan**
## Summary

Fixed #5456 

Previously, merging a rule configuration into a rule group configuration was not supported.
Added a merge implementation as expanding the group and merge specific rules.

## Test Plan

Test added.

### CODE REVIEW

File: crates/biome_configuration/src/analyzer/mod.rs [hunk 1]
```diff
@@ -727,14 +747,26 @@ where
...
+                let mut lhs = lhs.clone();
+                lhs.merge_with(rhs);
+                Self::Group(lhs)
+            }
+            (Self::Plain(lhs), Self::Group(rhs)) => {
+                let mut lhs = G::from(*lhs);
+                lhs.merge_with(rhs);
+                Self::Group(lhs)
+            }
+            (Self::Group(_), Self::Plain(rhs)) => Self::Plain(rhs),
```
Comment (siketyan) [inline crates/biome_configuration/src/analyzer/mod.rs:769]: This is ugly, but there is a moved value issue :(

**Review by ematipico — APPROVED** [review]
Looks good! Just some linting to fix
