### PR TITLE
fix(core): use deterministic ordering

### LINKED ISSUE #5756: 🐛 user-provided comparison function does not correctly implement a total order
### Environment information

```block
CLI:
  Version:                      2.0.0-beta.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         yarn/4.9.1
```

### What happened?

```shell
yarn biome check --write --no-errors-on-unmatched
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: library/core/src/slice/sort/shared/smallsort.rs:865:5
Thread Name: biome::workspace_worker_10
Message: user-provided comparison function does not correctly implement a total order

/home/oliver/projects/kitten-science/themes/contrib/pal.json internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: user-provided comparison function does not correctly implement a total order
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
```

The referenced `pal.json` is: <https://github.com/kitten-science/themes/blob/0f69d9ed05accc42270fcdb6ffce1298b7fe92c7/contrib/pal.json>

Relates to #5700 

### Expected result

Problem did not exist in pre-2.0.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes #5756 

@Conaclos I traced the issue to `Collator::cmp`. The two `loop` weren't exhaustive, and there were cases where we didn't return a proper value in the `cmp` function.

To be honest, I don't know if the fix is correct, I would like your input on the matter.

### CODE REVIEW

File: crates/biome_string_case/src/lib.rs [hunk 1]
```diff
@@ -445,71 +445,48 @@ pub trait Collator {
...
+                        (Some(_), None) => {
+                            return Ordering::Greater;
+                        }
+                        (Some(next1), Some(next2)) => {
+                            c1 = next1;
+                            c2 = next2;
                         }
                     }
-                    match self.weight(&c1).cmp(&self.weight(&c2)) {
-                        Ordering::Equal => {}
```
Comment (ematipico) [inline crates/biome_string_case/src/lib.rs:496]: First bug

File: crates/biome_string_case/src/lib.rs [hunk 2]
```diff
@@ -445,71 +445,48 @@ pub trait Collator {
...
+                        }
+                        (Some(_), None) => {
+                            return Ordering::Greater;
+                        }
+                        (None, Some(_)) => {
+                            return Ordering::Less;
                         }
+                        (None, None) => return number_ordering,
                     }
+                    return number_ordering;
```
Comment (ematipico) [inline crates/biome_string_case/src/lib.rs:482]: Second bug: `number_ordering` wasn't always returned at the end

File: crates/biome_string_case/src/lib.rs [hunk 3]
```diff
@@ -445,71 +445,48 @@ pub trait Collator {
     ) -> Ordering {
         let mut iter1 = iter1.into_iter();
         let mut iter2 = iter2.into_iter();
-        loop {
-            match (iter1.next(), iter2.next()) {
-                (Some(c1), Some(c2)) if c1 == c2 => {}
```
Comment (ematipico) [inline crates/biome_string_case/src/lib.rs:450]: Third bug

**Comment by Conaclos** [comment]
I don't think this is coming from `biome_string_case::Collator`. If you change `ascii_nat_cmp` with the Rust native `cmp`, the issue is still here.
Actually this could even comes from another part of Biome because adding a `panic` at the start of the `run` method of `useSOrtedKeys` doesn't change anything. The code of the rule seems not to be run at all.

File: crates/biome_string_case/src/lib.rs (hunk 3 above)
Comment (Conaclos) [reply crates/biome_string_case/src/lib.rs:450]: I think that this code is right. The `loop`and this empty block are important: we are comparing strings, you have to continue the comparison while the characters are equal.

File: crates/biome_string_case/src/lib.rs (hunk 1 above)
Comment (Conaclos) [reply crates/biome_string_case/src/lib.rs:496]: we are comparing strings, you have to continue the comparison while the characters are equal.

**Comment by Conaclos** [comment]
I mistakenly checked JavaScript's `useSortedKeys`. I will take a look at JSON's `useSortedKeys` later.

**Comment by Conaclos** [comment]
The bug is coming from the way we compare numbers. I am unsure yet where is the problem.

File: crates/biome_string_case/src/lib.rs [hunk 4]
```diff
@@ -447,48 +447,81 @@ pub trait Collator {
...
+                        match (self.as_ascii_digit(&c1), self.as_ascii_digit(&c2)) {
+                            (None, None) => {
+                                if number_ordering == Ordering::Equal {
+                                    // The numbers are equal, we have to compare `c1` and `c2` that are not digits.
+                                    break;
                                 }
+                                return number_ordering;
                             }
-                            match (self.as_ascii_digit(&c1), self.as_ascii_digit(&c2)) {
-                                (Some(n1), Some(_n2)) => {
```
Comment (Conaclos) [inline crates/biome_string_case/src/lib.rs:475]: A part of the bug was coming from here: note the underscore `_` in front of `n2`.

File: crates/biome_string_case/src/lib.rs [hunk 5]
```diff
@@ -447,48 +447,81 @@ pub trait Collator {
...
+                (Some(_), None) => {
+                    // `iter2` is a prefix of `iter1`.
+                    return Ordering::Greater;
+                }
+                (Some(c1), Some(c2)) if c1 == c2 => {
+                    // For now, all characters of `iter1` and `iter2` are equal.
+                }
                 (Some(mut c1), Some(mut c2)) => {
-                    if let (Some(n1), Some(n2)) =
-                        (self.as_ascii_digit(&c1), self.as_ascii_digit(&c2))
```
Comment (Conaclos) [inline crates/biome_string_case/src/lib.rs:453]: The main part of the bug was coming from here.
This is too aggressive as condition. I mainly added it as a way of avoiding the loop.
Now we always enter in the loop.

**Comment by Conaclos** [comment]
The bug is fixed. I took the opportunity of improving the code of useSOrtedKeys because it had a correctness issue: the impl of `Eq` and `PartialEq` were not aligned with `cmp`. I also reduced the test case of the issue.

This problem makes me wonder if we could improve the number comparison a bit.
We are not able to recognize hexadecimal numbers.
So `00F < 001` will hold. A user might expect the order to be `001 < 00F`.
I checked other libs that provide natural sorting, they don't handle hexadecimal numbers either.
Not sure if we should try to do something here.

**Comment by oliversalzburg** [comment]
> This makes me wonder if we could improve the number comparison a bit.

I feel like it might be best not to overthink it. Because:

1. The document is a color palette. The order of the entries will never be "correct".
2. If I had not normalized the palette before running into the issue, the palette had contained HTML short notations like `FFF`, for `FFFFFF`. The source data also used named colors, like `white`.
3. As this is from a JavaScript context, assuming JavaScript default sort order (compare UTF-16 code points) would seem intuitive. As in `Object.keys({ö:null,a:null,ä:null,1:null,ü:null,o:null,"02":null,111:null,9:null,88:null}).sort();`
4. If that default is not deemed "correct", then you're closing in on requiring a locale for the sorted keys feature.
