### PR TITLE
fix(core): fix symlink handling

### LINKED ISSUE #4941: 📎 Improve symlink handling with `DependencyGraph`
### Description

Monorepo setups often use symlinks in their `node_modules` to link projects to one another. Currently the `DependencyGraph` doesn’t yet canonicalize paths, so these can lead to duplicate entries for files. If we don’t resolve that, we would likely parse files multiple times and fail to update them properly when the watcher is implemented.

This task involves implementing `ResolverCache::canonicalize()` in `resolver_cache.rs` and resolving the `FIXME` in `dependency_graph.tests.rs`.

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

Fix #4941. We can now handle symlinks when resolving the dependency graph, which should allow us to handle many monorepo situations.

Also used `Utf8Path` a bit more internally, as I think I managed to work around some of the conversions I was struggling with.

## Test Plan

Updated test case.

### CODE REVIEW

File: crates/biome_dependency_graph/src/resolver_cache.rs [hunk 1]
```diff
@@ -88,14 +92,69 @@ impl<'a> ResolverCache<'a> {
...
+        // Check if this thread is already canonicalizing. If so, we have found a circular symlink.
+        // If a different thread is canonicalizing, OnceLock will queue this thread to wait for the result.
+        let tid = THREAD_ID.with(|t| *t);
+        if path.canonicalizing.load(Ordering::Acquire) == tid {
+            return Err(io::Error::new(io::ErrorKind::NotFound, "Circular symlink").into());
+        }
+
+        path.canonicalized
+            .get_or_init(|| {
+                path.canonicalizing.store(tid, Ordering::Release);
```
Comment (ematipico) [inline crates/biome_dependency_graph/src/resolver_cache.rs:116]: Thread ordering is quite a niche and a bit complex. Would you mind adding a comment explaining why we use `Ordering::Release`?

**Review by ematipico — APPROVED** [review]
I'm not really sure what's going on 😅 It would be nice to eventually have real test, to avoid possible regressions

File: crates/biome_dependency_graph/src/resolver_cache.rs (hunk 1 above)
Comment (arendjr) [reply crates/biome_dependency_graph/src/resolver_cache.rs:116]: This is just copied from `oxc-resolver`, which they copied from Parcel (hence the link at the top). I also didn't take the time to understand the intricacies of it. I do sometimes dabble with these `Ordering` semantics, but every time it takes me at least an hour to understand the intricacies again, so I don't think a comment is even going to help here. Either you're in a state of mind where you can follow why it works, or the comment is meaningless too :rofl:

**Comment by ematipico** [comment]
You did?? Ah shoot, sorry! I was expecting **a real test** , like a mini pnpm project or something

**Comment by arendjr** [comment]
Yeah, the fixtures effectively recreated a real-world monorepo setup with two packages side-by-side, `package.json` files depending on each other, and a symlink from the `node_modules` of one pointing to the other, the same way pnpm does when you run `pnpm` install. Maybe the only thing that's not real is there's no top-level `package.json`, so you can't run in `pnpm install` in there :)
