### PR TITLE
fix(cli): apply `--skip-parse-errors` to lint, check and ci commands

### LINKED ISSUE #3859: 🐛 `--skip-errors` CLI option is ignored
### Environment information

```block
CLI:
  Version:                      1.9.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v22.7.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/4.0.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

The `--skip-errors` CLI option does not seem to work. When running `biome check ./file.js --skip-errors` on a file with syntax errors, biome still throws an error. According to the [documentation](https://biomejs.dev/reference/cli/#biome-check) it should just ignore the file.

```js
// file.js

((

))
```

### Expected result

It should not throw an error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by unvalley**
## Summary

Closes #3859 
This PR applies the `--skip-parse-errors` option to below commands.

- `biome lint`
- `biome check`
- `biome ci` 

`biome format` is already applied the option.

Since there is no need to display parse errors in analyze and format respectively, parse errors in format executed later are not output as messages (commented in code).

## Test Plan

Added snapshot test

### CODE REVIEW

File: crates/biome_cli/src/execute/process_file/check.rs [hunk 1]
```diff
@@ -56,22 +64,26 @@ pub(crate) fn check_file<'ctx>(
...
-            Ok(status) => {
-                if status.is_changed() {
-                    changed = true
-                }
-                if let FileStatus::Message(msg) = status {
-                    if msg.is_failure() {
-                        has_failures = true;
+        if ctx.execution.should_ignore_errors() && skipped_parse_error {
+            // skip format to parse error files, a message for it already pushed by analyzer
+        } else {
```
Comment (unvalley) [inline crates/biome_cli/src/execute/process_file/check.rs:69]: do nothing if already skipped parse error on the analyze phase.

**Comment by ematipico** [comment]
I'm wondering if we should rename this flag. I introduced this option at the very beginning, when there was only a formatter. Now the meaning of "error" is different, and now there's a linter too.

What do you think?

**Comment by unvalley** [comment]
@ematipico

Here’s the current description of --skip-errors:

> `–skip-errors` — Skip files with syntax errors instead of emitting an error diagnostic.

Because the flag only deals with parse errors, how about renaming it to `--skip-parse-errors`?
I’d also suggest making it a sub-command option rather than a global one. Commands like `lint`, `format`, `check`, and `ci` need it, but the others don’t.

**Comment by ematipico** [comment]
`--skip-parse-errors` seems good!

**Comment by unvalley** [comment]
@ematipico Can we include the renaming to v2.0.0 release? 
If so, I think we can rename `--skip-errors` to `--skip-parse-errors` without the deprecation phase.

**Comment by ematipico** [comment]
>Can we include the renaming to v2.0.0 release? 

Yes, that was the idea :)

**Review by ematipico — APPROVED** [review]
Awesome!
