### PR TITLE
fix(lint/useExpect): reject asymmetric matchers and utilities as assertions

### LINKED ISSUE #9174: 💅 `useExpect` produces false negatives for Vitest asymmetric test matchers/`expect.extend`
### Environment information

N/A

### Rule name

`lint/nursery/useExpect`

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&lintRules=useExpect&analyzerFixMode=safeAndUnsafeFixes&code=aQB0ACgAIgArACIALAAgACgAKQAgAD0APgAgAHsACgAgACAAZQB4AHAAZQBjAHQALgBzAHQAcgBpAG4AZwBDAG8AbgB0AGEAaQBuAGkAbgBnACgAJwBmAG8AbwAnACkACgB9ACkACgAKAGkAdAAoACIAbgBvAHQAIABhAG4AIABhAHMAcwBlAHIAdABpAG8AbgAiACwAIAAoACkAIAA9AD4AIAB7AAoAIAAgAGUAeABwAGUAYwB0AC4AZQB4AHQAZQBuAGQAKAB7AG0AeQBGAG8AbwBNAGEAdABjAGgAZQByAH0AKQAKAH0AKQA%3D

### Expected result

This should produce an error - `expect.stringContaining` is not an assertion and should not be treated as one - it is a vitest asymmetric matcher whose only purpose is to be passed to an `expect` call or similar.
As for `expect.extend`, it augments Vitest's `extend` syntax with the provided function, and is similarly not actually testing anything.

NB: From what I can tell, there's no easy way to tell what asymmetric matchers a consumer may have defined with [`expect.extend`](https://vitest.dev/api/expect.html#expect-extend), as it will add both asymmetric matchers AND custom assertion functions with the same name.

```ts
it("a", () => {
  expect.extend({myFooMatcher});

  // these are both valid syntaxes
  expect(new Foo()).toBe(expect.myFooMatcher());
  expect(new Foo()).myFooMatcher();
});
```

If nothing else, it may be wise to mention this limitation inside the rule itself.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by omar-y-abdi**
## Summary

Closes #9174

`useExpect` produced false negatives for Vitest constructs like `expect.stringContaining()`, `expect.extend()`, and `expect.not.objectContaining()`. These are asymmetric matchers and utilities, not assertions, but the rule counted them as valid assertions and did not flag the test.

The root cause was in `is_expect_expression` in `playwright.rs`. The `JsStaticMemberExpression` branch unconditionally recursed on the object expression, so any `expect.anything()` pattern was treated as a valid assertion chain.

## Fix

When the object of a static member expression is a bare `expect` identifier (not a call like `expect(value)`), the member name is now checked against an allowlist of assertion-qualifying members: `soft`, `poll`, `assertions`, `hasAssertions`. All other members on bare `expect` (asymmetric matchers, `extend`, `not` prefix for negated matchers) are correctly rejected.

Chained assertions like `expect(value).not.toBe(1)` and `expect.soft(page).toBeVisible()` are unaffected because their object is a call expression, not a bare identifier.

## Test plan

- Added `invalid/asymmetric-matchers.js` with 3 cases: `expect.stringContaining()`, `expect.extend()`, `expect.not.objectContaining()` — all now correctly flagged
- Added `valid/assertion-counts.js` with 5 cases: `expect.assertions()`, `expect.hasAssertions()`, `expect.assertions(0)`, `expect.soft()`, `expect.poll()` — all correctly pass
- All 6 `use_expect` spec tests pass
- All 7 `is_expect_call` unit tests pass (no regression)
- All 66 `no_playwright_*` spec tests pass (no regression)
- All 2 `no_conditional_expect` spec tests pass (no regression)

Closes #9174

## AI disclosure

This PR was written with assistance from Claude Code (code comprehension, tracing the bug through the AST traversal logic, and drafting the implementation). All code was reviewed and verified by the author.

### CODE REVIEW

File: crates/biome_js_analyze/src/frameworks/playwright.rs [hunk 1]
```diff
@@ -219,12 +219,28 @@ fn is_expect_expression(expr: &AnyJsExpression) -> bool {
...
-            // expect.soft(), expect.poll(), expect(...).method(), expect(...).not.method()
             if let Ok(object) = member.object() {
-                // Recursively check the object - this handles chained member expressions
-                // like expect(page).not where the object is itself a member expression
-                // NB: This is overly permissive for certain Vitest constructs (ex: `expect.stringContaining()`)
-                // that do not assert anything in and of themselves (see issue #9174)
+                // When the object is a bare `expect` identifier, only allow known
+                // assertion-qualifying members. This prevents asymmetric matchers
+                // like `expect.stringContaining()` and utilities like `expect.extend()`
+                // from being counted as assertions (see issue #9174).
```
Comment (ematipico) [inline crates/biome_js_analyze/src/frameworks/playwright.rs]: Instead of adding the issue, which will be closed eventually why don't you add a link to the docs of these new matchers?

**Comment by omar-y-abdi** [comment]
Addressed both review items:
- Replaced the issue reference in the comment with a link to the Vitest asymmetric matchers docs
- Added changeset file

File: .changeset/fix-use-expect-false-negatives.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#9174](https://github.com/biomejs/biome/issues/9174): [`useExpect`](https://biomejs.dev/linter/rules/use-expect/) now correctly rejects Vitest [asymmetric matchers](https://vitest.dev/api/expect.html#expect-stringcontaining) like `expect.stringContaining()`, `expect.objectContaining()`, and utilities like `expect.extend()` that are not valid assertions. Previously these constructs caused false negatives, allowing tests without real assertions to pass the lint rule.
```
Comment (siketyan) [inline .changeset/fix-use-expect-false-negatives.md]:
```suggestion
Fixed [#9174](https://github.com/biomejs/biome/issues/9174): [`useExpect`](https://biomejs.dev/linter/rules/use-expect/) now correctly rejects [asymmetric matchers](https://vitest.dev/api/expect.html#expect-stringcontaining) in Vitest or Jest like `expect.stringContaining()`, `expect.objectContaining()`, and utilities like `expect.extend()` that are not valid assertions. Previously these constructs caused false negatives, allowing tests without real assertions to pass the lint rule.
```

**Review by siketyan — APPROVED** [review]

**Comment by omar-y-abdi** [comment]
@ematipico Hey, this is ready to merge whenever you get a chance.

**Comment by dyc3** [comment]
@omar-y-abdi there is still failing CI
