### PR TITLE
fix(useStrictMode): strict directive insertion logic

### LINKED ISSUE #4841: 💅 useStrictMode mangles leading comments and shebangs in .cjs files
### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.12.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.22"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false
  Enabled rules:
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  suspicious/useNamespaceKeyword
  a11y/useValidLang
  complexity/noUselessEmptyExport
  complexity/noMultipleSpacesInRegularExpressionLiterals
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noDuplicateParameters
  suspicious/noDuplicateSelectorsKeyframeBlock
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  correctness/noUnknownProperty
  style/useTemplate
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  correctness/noSwitchDeclarations
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noDuplicateObjectKeys
  suspicious/noUnsafeDeclarationMerging
  correctness/noUnreachable
  complexity/noUselessThisAlias
  complexity/noThisInStatic
  correctness/noInnerDeclarations
  suspicious/noDuplicateCase
  style/noParameterAssign
  a11y/useValidAnchor
  correctness/noSelfAssign
  correctness/noInvalidBuiltinInstantiation
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  correctness/noInvalidDirectionInLinearGradient
  suspicious/noImportantInKeyframe
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  complexity/noStaticOnlyClass
  style/useWhile
  style/noInferrableTypes
  style/useNumericLiterals
  complexity/useSimpleNumberKeys
  suspicious/noImportAssign
  a11y/noInteractiveElementToNoninteractiveRole
  suspicious/noLabelVar
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  correctness/noGlobalObjectCalls
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  correctness/noUnknownUnit
  suspicious/noSparseArray
  a11y/useIframeTitle
  suspicious/noPrototypeBuiltins
  correctness/noVoidElementsWithChildren
  suspicious/noSuspiciousSemicolonInJsx
  style/useAsConstAssertion
  suspicious/noDebugger
  style/useExportType
  complexity/noUselessLoneBlockStatements
  style/noArguments
  a11y/useValidAriaValues
  suspicious/noGlobalAssign
  suspicious/noCommentText
  correctness/noUnmatchableAnbSelector
  suspicious/noMisleadingInstantiator
  suspicious/noThenProperty
  suspicious/noDuplicateJsxProps
  suspicious/useGetterReturn
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  security/noDangerouslySetInnerHtmlWithChildren
  suspicious/noExtraNonNullAssertion
  suspicious/noShorthandPropertyOverrides
  correctness/noRenderReturnValue
  security/noGlobalEval
  style/useConst
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  suspicious/noGlobalIsFinite
  suspicious/noSelfCompare
  suspicious/noAsyncPromiseExecutor
  suspicious/noDuplicateFontNames
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  complexity/noWith
  nursery/useStrictMode
  complexity/noExtraBooleanCast
  suspicious/noDuplicateClassMembers
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  correctness/noUnknownFunction
  correctness/noInvalidPositionAtImportRule
  suspicious/noConfusingLabels
  suspicious/noConfusingVoidType
  suspicious/noFocusedTests
  a11y/noAriaUnsupportedElements
  correctness/noInvalidGridAreas
  correctness/noFlatMapIdentity
  a11y/noBlankTarget
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useGenericFontNames
  a11y/useAnchorContent
  complexity/noUselessRename
  complexity/noUselessConstructor
  a11y/noAccessKey
  style/useExponentiationOperator
  nursery/useAriaPropsSupportedByRole
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/noDuplicateAtImportRules
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  suspicious/noMisrefactoredShorthandAssign
  suspicious/noEmptyBlock
  suspicious/noClassAssign
  suspicious/noFunctionAssign

Workspace:
  Open Documents:               0
```

### Rule name

useStrictMode

### Playground link

https://biomejs.dev/playground/?lintRules=all&files.main.cjs=LwAvACAAYwBvAG0AbQBlAG4AdAA%3D

### Expected result

When the input file has extension .cjs, and does not have a "use strict" directive, and the first line of the file is a comment or a shebang, it will apply an incorrect fix.

With leading comments -

Input file:
```js
// leading comment
```

After applying fix:
```js
// leading comment
"use strict"; // leading comment
```

With shebang -

Input file:
```js
#!/usr/bin/env node
```

After applying fix:
```js
#!/usr/bin/env node"use strict";
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by bushuai**
## Summary
closes #4841 
- improve the rule logic for cjs files with shebang and comments
  - will not report for files containing only a shebang/comment or both in cjs files (aligning the behavior with eslint) [playground](https://eslint.org/play/#eyJ0ZXh0IjoiIyEvdXNyL2Jpbi9lbnYgbm9kZVxuXG4vLyBjb21tZW50XG4iLCJvcHRpb25zIjp7InJ1bGVzIjp7InN0cmljdCI6WyJlcnJvciIsImdsb2JhbCJdfSwibGFuZ3VhZ2VPcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fX0sInNvdXJjZVR5cGUiOiJjb21tb25qcyJ9fX0=) and [source](https://github.com/eslint/eslint/blob/1c87b415313b4aacda496b3b26efc4e0b93dc13a/lib/rules/strict.js#L246)
- add test cases

### comment only
- before
```
//·comment"use·strict";//·comment    <<<--- duplicated comment and no line break here
```

- after(keep it as is)
```
// comment
```

### shebang only
- before
```
#! /usr/bin/env node"use strict";
```

- after(keep it as is)
```
#! /usr/bin/env node
```

### with shebang
- before
```diff
#!·/usr/bin·node"use·strict";
let some_variable = "some value";
```
- after
```diff
#! /usr/bin node
"use strict";
let some_variable = "some value";
```

### with comment
- before 
```diff
// comment
"use strict";// comment    <<<--- duplicated comment and no line break here
let some_variable = "some value";
```

- after 
```diff
"use strict";
// comment
let some_variable = "some value";
```

### with shebang and comment
- before
```diff
#! /usr/bin node"use strict";
// comment
let some_variable = "some value";
```

- after
```diff
#! /usr/bin node
"use strict";
// comment
let some_variable = "some value";
```

## Test Plan
- added more test cases
- updated the snapshots

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs [hunk 1]
```diff
@@ -91,22 +95,62 @@ impl Rule for UseStrictMode {
...
+        // check if the first statement has a newline as the first trivia.
+        let is_statement_first_trivia_newline = node
+            .statements()
+            .syntax()
+            .first_leading_trivia()
+            .map_or(false, |f| {
+                f.pieces()
+                    .next()
+                    .map_or(false, |piece| piece.kind() == TriviaPieceKind::Newline)
+            });
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs:108]:
```suggestion
            .map(|f| {
                f.pieces()
                    .next()
                    .map_or(false, |piece| piece.kind() == TriviaPieceKind::Newline)
            }).unwrap_of_default();
```

Since `map_or` returns the default value, it's usually more common to use `unwrap_or_default`

**Review by ematipico — APPROVED** [review]
That's a great fix, I just suggested a small nit

File: crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs (hunk 1 above)
Comment (bushuai) [reply crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs]: thank you so much for the suggestion! i've fixed it :D

File: crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs [hunk 2]
```diff
@@ -91,22 +95,62 @@ impl Rule for UseStrictMode {
...
+
+        // check if the first statement has a newline as the first trivia.
+        let is_statement_first_trivia_newline = node
+            .statements()
+            .syntax()
+            .first_leading_trivia()
+            .map(|f| {
+                f.pieces()
+                    .next()
+                    .map_or(false, |piece| piece.kind() == TriviaPieceKind::Newline)
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs:107]: You can use https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some_and

**Comment by bushuai** [comment]
> Thanks a lot for this! Do you want to add a [changeset entry](https://github.com/biomejs/biome/blob/next/CONTRIBUTING.md#writing-a-changeset)?

85fe57e2848da44e4cd818342275a67b1c4cfe4c changelog is added here :)

File: crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs (hunk 2 above)
Comment (bushuai) [reply crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs]: fixed

**Comment by bushuai** [comment]
I made some corrections to the typos in the changelog file. please take a moment to review it again. :D
@arendjr @ematipico

**Review by ematipico — APPROVED** [review]
