### PR TITLE
fix(linter): exclude dependencies from `noPrivateImports`

### LINKED ISSUE #6214: 🐛 noPrivateImports false positives for imports from node_modules in 2.0.0-beta.6
### Environment information

```block
CLI:
  Version:                      2.0.0-beta.6
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/10.10.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:
```

### What happened?

After upgrading from Biome 2.0.0-beta.5 to 2.0.0-beta.6 `noPrivateImports` rule started to get false positives for imports from node_modules. See path in photo which references pnpm node modules.
Image

I assume expanded scanner support caused it and `.get_import_path_by_js_node(node)` now returns node_modules which before it didnt? https://github.com/biomejs/biome/blob/d42c38ca437f12a47651e98cf9108fff31860ac1/crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs#L230-L232

### Expected result

No error reported for imports from node_modules

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

Fixes #6214.

@minht11 I've made the decision to restrict `noPrivateImports` to relative imports only to prevent this. This means path aliases are excluded too, which to me feels right, because if you set up an alias for those paths, you probably _intent_ for their exports to be available everywhere, but let me know your thoughts on this!

## Test Plan

Tests updated.

### CODE REVIEW

**Comment by siketyan** [comment]
> This means path aliases are excluded too, which to me feels right, because if you set up an alias for those paths, you probably intent for their exports to be available everywhere, but let me know your thoughts on this!

I think most of projects using path aliases don't setup aliases granularly. For example, consider a path alias `@/` as the absolute path from the `src` directory. In this case **every module** in the project is always accessible regardless it's intended to be used outside or not. In my company, this kind of TypeScript setup is pretty common, unfortunately. 😔

**Comment by arendjr** [comment]
@siketyan Yeah, that's fair, but do you think it's likely that a codebase such as that would be a consumer of this rule at all? Setting up such path aliases is ultimately a choice of convenience above all, whereas this rule sacrifices convenience for better module organisation. I wonder how compatible those mindsets are...

**Comment by minht11** [comment]
Personally at my work and the codebase linked in the issue I use this rule root path alias `@/*` `~/*`, it would be major downgrade to lose support for it.

**Comment by arendjr** [comment]
Alright, I hear you.

What I could do instead is filter out all matches that resolve to a path inside `node_modules`. That's probably the better option anyway :)

**Comment by siketyan** [comment]
@arendjr 

> do you think it's likely that a codebase such as that would be a consumer of this rule at all?

I think it's possible, at least in my codebase some `@package` annotations restrict their usage, even if it's referenced by the path alias. (I haven't migrated from eslint-plugin-import-access to noPrivateImports yet)

File: crates/biome_resolver/src/lib.rs [hunk 1]
```diff
@@ -581,7 +581,7 @@ fn resolve_path_info(
     }
 }
 
-fn is_relative_specifier(specifier: &str) -> bool {
+pub fn is_relative_specifier(specifier: &str) -> bool {
```
Comment (minht11) [inline crates/biome_resolver/src/lib.rs:584]: This does not need to public?

Comment (arendjr) [reply crates/biome_resolver/src/lib.rs:584]: True, but I think I’ll leave it. It’s a useful utility anyway.
