### PR TITLE
fix(analyzer): noUselessEscapeInRegex preserves required v-flag escapes

### LINKED ISSUE #10034: 🐛 noUselessEscapeInRegex incorrectly removes required escapes in v-flag regex character classes
### Environment information

<details>

```bash

CLI:
  Version:                      2.4.12
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v24.2.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         deno/2.7.12

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /Users/vitaly/git/typescript-projects/paseri/biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false
  HTML full support enabled:    unset

Workspace:
  Open Documents:               0



```

</details>

### What happened?

https://biomejs.dev/playground/?tab=analyzer-fixes&pane=Diagnostics&code=YwBvAG4AcwB0ACAAcgBlACAAPQAgAC8AWwBhAC0AegBcACYAXQAvAHYAOwA%3D

### Expected result

The `\` before the `&` must not be stripped, as that results in an invalid regex.
Per the [ECMAScript spec](https://tc39.es/ecma262/#prod-ClassSetCharacter), the following characters are individually reserved inside v-mode character classes and must be escaped: &, !, #, %, ,, :, ;, <, =, >, @, `, ~.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by jiwon79**
## Summary

Fix #10034 
`noUselessEscapeInRegex` was treating the 13 `ClassSetReservedPunctuator` characters (`&`, `!`, `#`, `%`, `,`, `:`, `;`, `<`, `=`, `>`, `@`, `` ` ``, `~`) the same as the 5 doubled-only punctuators (`$`, `*`, `+`, `.`, `?`) when evaluating escapes inside a `v`-flag character class. Per [ECMA-262](https://tc39.es/ecma262/#prod-ClassSetReservedPunctuator), the first group is reserved as individual code points in `v`-mode, so the escape is required even for a single occurrence — not only when doubled.

As a result, patterns like `/[a-z\&]/v` were flagged as having a useless escape, and the safe auto-fix stripped the backslash, producing a regex that is invalid per the strict spec.

## Test Plan

- Added `valid.js` cases for each of the 13 reserved punctuators, both as single (`/[\&]/v`) and doubled (`/[\&\&]/v`) escapes.
- Removed the corresponding cases from `invalid.js` that assumed the old buggy behavior.
- Existing tests for the 5 doubled-only punctuators are unchanged.

## Docs

Rustdoc updated inline.

+) Developed with Claude Code assistance. Direction and review were mine; code and test drafts were AI-assisted.

### CODE REVIEW

**Comment by jiwon79** [comment]
> 
> 
> <details>
> <summary>🧹 Nitpick comments (1)</summary><blockquote>
> 
> <details>
> <summary>crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js (1)</summary><blockquote>
> 
> `103-134`: **Nice thorough fixture expansion.** One tiny gap for symmetry.
> 
> The doubled-escape block (lines 122–133) covers 12 of the 13 reserved punctuators but is missing `/[\%\%]/v;`. The single case on line 111 already exercises the same code path, so this is purely cosmetic completeness.
> 
> <details>
> <summary>🧹 Optional symmetry tweak</summary>
> 
> ```diff
>  /[\#\#]/v;
> +/[\%\%]/v;
>  /[\,\,]/v;
> ```
> </details>
> 
> <details>
> <summary>🤖 Prompt for AI Agents</summary>
> 
> ```
> Verify each finding against the current code and only fix it if needed.
> 
> In
> `@crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js`
> around lines 103 - 134, The doubled-escape block for reserved punctuators is
> missing the percent pair; add the symmetric doubled-escape `/[\%\%]/v;` into the
> same doubled-escape section (the block containing `/[\&\&]/v;`, `/[\!\!]/v;`,
> etc.) so that all 13 ClassSetReservedPunctuator characters are covered (there is
> already a single-escape `/[\%]/v;` earlier).
> ```
> 
> </details>
> 
> </blockquote></details>
> 
> </blockquote></details>
> 
> <details>
> <summary>🤖 Prompt for all review comments with AI agents</summary>
> 
> ```
> Verify each finding against the current code and only fix it if needed.
> 
> Nitpick comments:
> In
> `@crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js`:
> - Around line 103-134: The doubled-escape block for reserved punctuators is
> missing the percent pair; add the symmetric doubled-escape `/[\%\%]/v;` into the
> same doubled-escape section (the block containing `/[\&\&]/v;`, `/[\!\!]/v;`,
> etc.) so that all 13 ClassSetReservedPunctuator characters are covered (there is
> already a single-escape `/[\%]/v;` earlier).
> ```
> 
> </details>
> 
> ---
> 
> <details>
> <summary>ℹ️ Review info</summary>
> 
> <details>
> <summary>⚙️ Run configuration</summary>
> 
> **Configuration used**: Path: .coderabbit.yaml
> 
> **Review profile**: CHILL
> 
> **Plan**: Pro
> 
> **Run ID**: `d4eb55a8-f50f-4be9-90f1-339a5341a550`
> 
> </details>
> 
> <details>
> <summary>📥 Commits</summary>
> 
> Reviewing files that changed from the base of the PR and between bc05a2429bf8dccf24896611b1442d331857c04c and dcbffa8b55240f929bc3af2033a29cb305f1f598.
> 
> </details>
> 
> <details>
> <summary>⛔ Files ignored due to path filters (2)</summary>
> 
> * `crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/invalid.js.snap` is excluded by `!**/*.snap` and included by `**`
> * `crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js.snap` is excluded by `!**/*.snap` and included by `**`
> 
> </details>
> 
> <details>
> <summary>📒 Files selected for processing (4)</summary>
> 
> * `.changeset/bumpy-moose-allow.md`
> * `crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs`
> * `crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/invalid.js`
> * `crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js`
> 
> </details>
> 
> <details>
> <summary>💤 Files with no reviewable changes (1)</summary>
> 
> * crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/invalid.js
> 
> </details>
> 
> </details>
> 
> 

Apply it at https://github.com/biomejs/biome/commit/77bfd17e46ad8cec59a40523c6cb4f839eb37b77

File: crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs [hunk 1]
```diff
@@ -126,10 +126,15 @@ impl Rule for NoUselessEscapeInRegex {
                                     b'p' | b'P' | b'k' | b'q' if is_unicode_aware => {}
                                     // Invalid speccial characters in char class under the `v` flag.
                                     b'(' | b')' | b'[' | b'{' | b'}' | b'/' | b'|' if has_v_flag => {}
-                                    // Perhaps a doubled punctuator
-                                    b'&' | b'!' | b'#' | b'$' | b'%' | b'*' | b'+' | b','
-                                    | b'.' | b':' | b';' | b'<' | b'=' | b'>' | b'?'
-                                    | b'@' | b'`' | b'~' if has_v_flag => {
+                                    // `ClassSetReservedPunctuator`: reserved as individual
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:129]: It's not clear what "ClassSetReservedPunctuator" is referring to. Is this something in the spec you linked? If so, we should also link it here.

File: crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs [hunk 2]
```diff
@@ -126,10 +126,15 @@ impl Rule for NoUselessEscapeInRegex {
...
+                                    // characters inside a `v`-mode character class, so the
+                                    // escape is always required.
+                                    b'&' | b'!' | b'#' | b'%' | b',' | b':' | b';'
+                                    | b'<' | b'=' | b'>' | b'@' | b'`' | b'~' if has_v_flag => {}
+                                    // Characters that form a `ClassSetReservedDoublePunctuator`
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:135]: same here for "ClassSetReservedDoublePunctuator"

File: crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs (hunk 1 above)
Comment (jiwon79) [reply crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:129]: Added spec link

File: crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs (hunk 2 above)
Comment (jiwon79) [reply crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:135]: Added spec link too

**Review by dyc3 — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs [hunk 3]
```diff
@@ -40,6 +36,10 @@ declare_lint_rule! {
     /// ```js
     /// /[\b]/
     /// ```
+    ///
+    /// ```js
+    /// /[\&]/v
+    /// ```
```
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:42]: @jiwon79 this might be valid

[the remark this answers is not in the document]
Comment (jiwon79) [reply crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs:42]: @dyc3 V8 accepts both `/[&]/v` and `/[\&]/v`, but per [ECMA-262 `ClassSetCharacter`](<https://tc39.es/ecma262/#prod-ClassSetCharacter>), an unescaped `&` isn't valid — it's a [`ClassSetReservedPunctuator`](<https://tc39.es/ecma262/#prod-ClassSetReservedPunctuator>). Current PR follows strict spec.
