### PR TITLE
fix(lsp): register formatter dynamically if possible

### LINKED ISSUE #1584: 🐛 Multiple entries in the list of formatters
## what happened
1. Install Biome VSCode extension v2.1.1 in a devcontainer and put it in devcontainer extensions to be auto-installed.
2. Open preferences (Cmd+Shift+P), "format document with..." -> Biome appears twice in the list.
3. Rebuild the devcontainer -> Biome appears another two times every time I rebuild
 
## what is expected
Biome VSCode extension should only appear once in the list of formatters and should not increase every time the devcontainer is rebuilt.

### PR DESCRIPTION
**Pull request by nhedger**
## Summary

This PR changes the way the formatting providers are registered by the LSP to prevent registering a formatter twice.

### The problem

Some LSP clients do not support dynamic registration for formatting providers, so in PR #1042 , we explicitly enabled static registration of the formatters. Unfortunately, this caused clients that support dynamic registration to show two formatters (the statically registered one, and the dynamically registered one).

### The solution

This PR adds logic to detect whether the clients supports dynamic registration of formatters, and skips the static registration when they do.

## Test Plan

- Ensure only one formatter is registered in VS Code's `Format Document with...` menu.

Fixes #1584

### CODE REVIEW

File: crates/biome_lsp/src/capabilities.rs [hunk 1]
```diff
@@ -19,12 +40,24 @@ pub(crate) fn server_capabilities(capabilities: &ClientCapabilities) -> ServerCa
...
-        document_range_formatting_provider: Some(OneOf::Left(true)),
-        document_on_type_formatting_provider: Some(DocumentOnTypeFormattingOptions {
-            first_trigger_character: String::from("}"),
-            more_trigger_character: Some(vec![String::from("]"), String::from(")")]),
-        }),
+        document_formatting_provider: if supports_formatter_dynamic_registration {
+            None
+        } else {
+            Some(OneOf::Left(true))
+        },
```
Comment (nhedger) [inline crates/biome_lsp/src/capabilities.rs:47]: If you can thing of a more elegant way to write this, I'm all ears!

Comment (ematipico) [reply crates/biome_lsp/src/capabilities.rs:47]: This `supports_formatter_dynamic_registration` comes from a chain of `Option`; we can remove the `unwrap_or`, and change it to a `map`:

```rs
    let supports_on_type_formatter_dynamic_registration = capabilities
        .text_document
        .as_ref()
        .and_then(|text_document| text_document.on_type_formatting.as_ref())
        .and_then(|on_type_formatting| on_type_formatting.dynamic_registration)
		.map(|supports_it| {
			if supports_it {
				None
			} else {
				Some(OneOf::Left(true))
			}
		});

```

Comment (nhedger) [reply crates/biome_lsp/src/capabilities.rs:47]: Great suggestion, thanks!

Comment (nhedger) [reply crates/biome_lsp/src/capabilities.rs]: Actually, map didnt seem to work.

I went with the following instead.

```rust
.and_then(|supported| {
	if supported {
		None
	} else {
		Some(OneOf::Left(true))
	}
})
```

Comment (ematipico) [reply crates/biome_lsp/src/capabilities.rs]: Yeah I always make a mistake between them ahah

**Review by ematipico — APPROVED** [review]
It looks great! Can you add a changelog line before merging?

**Comment by nhedger** [comment]
> It looks great! Can you add a changelog line before merging?

I've added the changelog entry under a new `LSP` header, hope that makes sense.

**Comment by ematipico** [comment]
Cool, you'll have to run `just gen-web`, commit and merge :D thank you!

File: CHANGELOG.md [hunk 2]
```diff
@@ -14,6 +14,10 @@ Read our [guidelines for writing a good changelog entry](https://github.com/biom
 
 ### CLI
 
+### LSP
+
+- Fix [#1584](https://github.com/biomejs/biome/issues/1584). Ensure the LSP only registers the formatter once. Contributed by @nhedger
+
```
[the remark this answers is not in the document]
Comment (nhedger) [reply CHANGELOG.md]: Right x)

**Comment by nhedger** [comment]
Thanks for the assist, much appreciated!
