### PR TITLE
fix(formatter): dedent logic inconsistent with prettier where the indent-style is space and the indent-width is not 2.

### LINKED ISSUE #2037: 📝 Inconsistent print behavior of nested `align`s with Prettier
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Space
  Indent size:                  0
  Indent width:                 8
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              true
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 8
  }
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&indentWidth=8&code=YQAKACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAbwB1AHQAZQByAAoAIAAgACAAIAAgACAAeAAKACAAIAAgACAAOgAgAC8ALwAgAGUAbABzAGUAIABvAHUAdABlAHIACgAgACAAIAAgACAAIABiAAoAIAAgACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAaQBuAG4AZQByAAoAIAAgACAAIAAgACAAIAAgAHkACgAgACAAIAAgACAAIAA6ACAALwAvACAAZQBsAHMAZQAgAGkAbgBuAGUAcgAKACAAIAAgACAAIAAgACAAIAB6ADsACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by mdm317**
## Summary
I created a stack named 'indent_stack' to store the records of indentations in order to remove the nearest indention when StartDedent and restore indention when EndDedent

Fixes #2037 

## Test Plan
I couldn't add test code because errors occurred only in settings where the indent-style is space and the indent-width is not 2.
We can check through the playground.

### CODE REVIEW

**Comment by mdm317** [comment]
Thank you for the review!!
I will investigate changing prettier options for testing or using a different approach for testing.
Please give me more time

**Comment by Sec-ant** [comment]
@mdm317 I think we can just put the test cases in `biome_cli` tests for now: `biome/crates/biome_cli/tests/commands/format.rs`. There're existing test cases there to show to how add a config file to the memory fs.

And #2168 seems also a valid test case for this fix. You may want to check it out.

**Comment by mdm317** [comment]
Big thanks @Sec-ant. With your help, I was able to  add test to the `biome_cli`

File: crates/biome_formatter/src/printer/call_stack.rs [hunk 1]
```diff
@@ -233,3 +232,123 @@ impl<'a> CallStack for FitsCallStack<'a> {
...
+    fn end_dedent(&mut self) {
+        if self.temp_stack_mut().is_empty() {
+            return;
+        }
+        let indent = self.temp_stack_mut().pop().unwrap();
+        self.stack_mut().push(indent);
+    }
+    fn pop(&mut self) -> Indention {
+        self.stack_mut().pop().unwrap()
+    }
```
[the remark this answers is not in the document]
Comment (mdm317) [reply crates/biome_formatter/src/printer/call_stack.rs]: Thank you for letting me know. I learned from you that using 'unwrap' can lead to a panic state. I used 'unwrap_or_else' instead. Is this okay?

File: crates/biome_formatter/src/printer/mod.rs [hunk 2]
```diff
@@ -841,9 +872,12 @@ impl Indention {
...
             // Convert the existing align to an indent
-            Indention::Align { level: indent, .. } => Indention::Align {
-                level: indent + 1,
-                align: count,
+            Indention::Align {
+                level: indent,
+                align,
+            } => Indention::Align {
+                level: indent,
+                align: align.saturating_add(count.get()),
```
[the remark this answers is not in the document]
Comment (mdm317) [reply crates/biome_formatter/src/printer/mod.rs:880]: This issue happen when indent_style is `space` and indent_width is not 2
For example 
If you run the code below:

> This code is a part of https://github.com/biomejs/biome/pull/2134/commits/f7e6d79f53d81bc5716f93ddb9f406c0e396e467# code.

```
    let context = SimpleFormatContext::new(SimpleFormatOptions {
        indent_width: IndentWidth::try_from(8).unwrap(),
        indent_style: IndentStyle::Space,
        ..SimpleFormatOptions::default()
    });

    let elements = format!(
        context,
        [
            text("root"),
            align(
                2,
                &format_args![
                    hard_line_break(),
                    text("Aligned"),
                    indent(&format_args![
                        hard_line_break(),
                        text("Aligned, and indented"),
                        dedent(&format_args![
                            hard_line_break(),
                            text("aligned, not Intended"),
                        ]),
                    ])
                ]
            ),
            dedent(&format_args![hard_line_break(), text("root level")])
        ]
    )?;
```
`Previously  biome` result is
```
root
  Aligned
          Aligned, and indented
        aligned, not Intended
root level
```
`this branch` result is
```
root
  Aligned
          Aligned, and indented
  aligned, not Intended
root level
```

And I may not understand the entire prettier logic, but I think prettier also record align and indent state
https://github.com/prettier/prettier/blob/d970deed6b6cabe21fdb35249265d766932b5718/src/document/printer.js#L67-L70

Feel free to share your thoughts with me anytime.

[the remark this answers is not in the document]
Comment (ah-yu) [reply crates/biome_formatter/src/printer/mod.rs:880]: This PR truly fixes the problem you mentioned, but it might alter the behavior when `indent_style` is `tab`. I had some observations when solving https://github.com/biomejs/biome/pull/1581 

### Biome behavior
- Biome only keeps the most inner `Align`, when encountering another `Align`, Biome will automatically convert the preceding `Align` to `Indent`.
https://github.com/biomejs/biome/blob/62fbec86467946e8d71dcd0098e3d90443208f78/crates/biome_formatter/src/printer/mod.rs#L844-L847
  Let us use [playground](https://biomejs.dev/playground/?indentStyle=space&indentWidth=0&code=YQAKACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAbwB1AHQAZQByAAoAIAAgACAAIAAgACAAeAAKACAAIAAgACAAOgAgAC8ALwAgAGUAbABzAGUAIABvAHUAdABlAHIACgAgACAAIAAgACAAIABiAAoAIAAgACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAaQBuAG4AZQByAAoAIAAgACAAIAAgACAAIAAgAHkACgAgACAAIAAgACAAIAA6ACAALwAvACAAZQBsAHMAZQAgAGkAbgBuAGUAcgAKACAAIAAgACAAIAAgACAAIAB6ADsACgA%3D)(I adjust indent width to 0 for easy understanding) as an example
  ```
  // indent_style: space
  // for b
  [Indent, Align] => [Indent, Align]
  // for y 
  [Indent, Align, Align] => [Indent, Indent, Align]
  ```
  I guess the reason the fix works is you prevent `Align` from automatically converting to `Indent`. There is no `dedent` in the formatter IR.

- When `indent_style` is `tab`, the most inner `Align`(if exists) will be automatically converted to `Indent` when encountering `Indent`
  https://github.com/biomejs/biome/blob/c35697124a95fc42a11481ecfa7bc534ae8c9e50/crates/biome_formatter/src/printer/mod.rs#L810

  ```
  // indent_style: tab
  [indent, Align, Indent] => [Indent, Indent, Indent]
  ```

### Prettier behavior
- Prettier keeps all `Align`s when `indent_style` is space
- Prettier converts all preceding `Align`s to `Indents` when encountering `Indent` if `indent_style` is `tab`
  ```
  [Indent, Align, Align] => [Indent, Align, Align]
  [Indent, Align, Align, Indent] => [indent, Indent, Indent, Indent]
  [Indent, Align, Align, Indent, Dedent] => [Indent, Align, Align]
  [Indent, Align, Align, Indent, Indent, Dedent] => [Indent, Indent, Indent, Indent]
  ```
  You can see Prettier record the number of `Align`s
  https://github.com/prettier/prettier/blob/d970deed6b6cabe21fdb35249265d766932b5718/src/document/printer.js#L93
  And convert these `Align`s to `Indent`s when encountering `Indent`
  https://github.com/prettier/prettier/blob/d970deed6b6cabe21fdb35249265d766932b5718/src/document/printer.js#L80
 

This is all I can remember, and I'm not sure if it's correct or not, but I hope it helps you.

File: crates/biome_formatter/src/printer/mod.rs [hunk 3]
```diff
@@ -768,7 +811,11 @@ enum Indention {
     Level(u16),
 
     /// Indent the content by n-`level`s using the indention sequence specified by the printer options and `align` spaces.
-    Align { level: u16, align: NonZeroU8 },
+    Align {
```
Comment (ah-yu) [inline crates/biome_formatter/src/printer/mod.rs:814]: Wonder if it is possible to change the `Indention` to 
```rust
enum Indention {
  Level,
  Align(NonZeroU8)
}
```
then the indent stack would be like `[Indent, align(1), Indent]`. 

Consequently, the `indent` in `PrintElementArgs` 
https://github.com/biomejs/biome/blob/fbab39f57d5a3544c0f2b99918575ec14bf17f89/crates/biome_formatter/src/printer/call_stack.rs#L29
would become redundant because we can calculate indentation based on the indent stack. What do you think?

Comment (mdm317) [reply crates/biome_formatter/src/printer/mod.rs:814]: Thank you so much for the review.
I also worried about redundant at first.
I might be wrong, but when I try to eliminate duplication, I realized that every time we need to calculate the indentation, we have to iterate through the entire indent stack to calculate it. I don't think it's a huge performance issue, but that's why I just left it as is.

I'm still not sure which method is the best.
@Sec-ant 
If you have any thoughts, please let me know.

Comment (ah-yu) [reply crates/biome_formatter/src/printer/mod.rs:814]: That depends on what is more important to you: the performance gain or easy maintenance.

Comment (Sec-ant) [reply crates/biome_formatter/src/printer/mod.rs:814]: @mdm317 Sorry I didn't have time to catch up with the conversation. I think @ah-yu has a better understanding on this than I do. If you worry about the code performance I think you can request a review from the core contributors like @ematipico, @Conaclos.

Comment (ematipico) [reply crates/biome_formatter/src/printer/mod.rs:814]: Performance is at stake here, and I believe the indentation calculation could be considered a hot path.

Maintenance friction could be partially compensated with good internal documentation.

We could use both approaches and benchmark both of them. 

We have some benchmarks around formatting in `xtask/bench`.

Comment (ah-yu) [reply crates/biome_formatter/src/printer/mod.rs:814]: Thank you! It appears there is an obvious performance degradation for large files.

> To eliminate redundancy, how about moving the methods that calculate indentation, which are currently implemented in the PrintElementArgs struct, to the IndentStack trait, without changing the structure of indentation?

I think it is a good way to go.

Comment (mdm317) [reply crates/biome_formatter/src/printer/mod.rs:821]: While moving the indentation logic, I found that if the current element is a LineSuffix, the current indention is saved and used later when flush_line_suffixes is called. Therefore, I implemented the SuffixStack trait to save the current indentation at this [commit](https://github.com/biomejs/biome/pull/2134/commits/d70c7c9a37621924d375b5655e361dc955786c46).

File: crates/biome_formatter/src/printer/mod.rs [hunk 4]
```diff
@@ -807,29 +861,23 @@ impl Indention {
         match self {
             Indention::Level(count) => Indention::Level(count + 1),
             // Increase the indent AND convert the align to an indent
-            Indention::Align { level, .. } if indent_style.is_tab() => Indention::Level(level + 2),
+            Indention::Align {
+                level,
+                previous_align_count,
+                ..
+            } if indent_style.is_tab() => Indention::Level(level + previous_align_count + 2),
```
Comment (ah-yu) [inline crates/biome_formatter/src/printer/mod.rs:868]:
```suggestion
            } if indent_style.is_tab() => Indention::Level(level + previous_align_count + 1),
```

File: crates/biome_formatter/src/printer/mod.rs [hunk 5]
```diff
@@ -807,29 +861,23 @@ impl Indention {
...
             Indention::Align {
                 level: indent,
                 align,
+                previous_align_count,
             } => Indention::Align {
                 level: indent + 1,
                 align,
+                previous_align_count: previous_align_count + 1,
```
Comment (ah-yu) [inline crates/biome_formatter/src/printer/mod.rs:876]:
```suggestion
                previous_align_count,
```

**Review by ah-yu — APPROVED** [review]
Looks good! Left some nitpicks

File: CHANGELOG.md [hunk 6]
```diff
@@ -283,6 +283,7 @@ our [guidelines for writing a good changelog entry](https://github.com/biomejs/b
 
 - Fix discrepancies on file source detection. Allow module syntax in `.cts` files ([#2114](https://github.com/biomejs/biome/issues/2114)). Contributed by @Sec-ant
 
+- Fix dedent logic inconsistent with prettier where the indent-style is space and the indent-width is not 2. Contributed by @mdm317
```
Comment (Sec-ant) [inline CHANGELOG.md:286]: This changelog entry should be moved to the unreleased section.

File: crates/biome_formatter/src/printer/mod.rs (hunk 4 above)
Comment (mdm317) [reply crates/biome_formatter/src/printer/mod.rs:868]: Thanks for the review, it’s been really helpful.

I think the variable name `previous_align_count` is confusing.
When I named the variable 'previous_align_count', I intended it to mean that it does not include the current align count.

I will show an example below.

> assuming the indent stack [Indent, Align(2), Align(2)]
> **indent**
> ```
> Indention::Level(1)
> ```
> **align(2)**
> ```
> Indention::Align{
>     level:1
>     align:2
>     previous_align_count:0
> }
> ```
> **align(2)**
> ```
> Indention::Align{
>     level:1
>     align:4
>     previous_align_count:1
> }
> ``` 

I want to choose a variable name that is not confusing.

I have some suggestion
1. How about changing the variable name from 'previous_align_count' to 'align_count', and including the current align in the count?
2. Add comment `The variable previous_align_count does not include the current align count.` and not including the current align in the count?
3. Add comment `The variable previous_align_count include the current align count.` and including the current align in the count?

If you have a better idea, let me know.

Comment (ah-yu) [reply crates/biome_formatter/src/printer/mod.rs:868]: > How about changing the variable name from 'previous_align_count' to 'align_count', and including the current align in the count?

I am in favor of this suggestion since `align_count` is not be used until it meets an `Indent`

File: crates/biome_cli/tests/snapshots/main_commands_format/format_conditional_expression_when_indent_width_is_not_2.snap [hunk 7]
```diff
@@ -0,0 +1,42 @@
+---
```
Comment (ah-yu) [inline crates/biome_cli/tests/snapshots/main_commands_format/format_conditional_expression_when_indent_width_is_not_2.snap:1]: It seems this snapshot is unneeded now.

**Review by ematipico — APPROVED** [review]
Great contribution @mdm317, and amazing reviews @ah-yu and @Sec-ant! ❤️
