### PR TITLE
fix(lint/useSingleVarDeclarator): output valid code when declarators are on multilines

### LINKED ISSUE #728: 💅 useSingleVarDeclarator suggests non-working code
### Environment information

```bash
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useSingleVarDeclarator

### Playground link

https://biomejs.dev/playground/?code=IAAgACAAIABjAG8AbgBzAHQACgAgACAAIAAgACAAIABBACAAPQAgADEAMAAwACwACgAgACAAIAAgACAAIABCACAAPQAgADEANQAwACwACgAgACAAIAAgACAAIABEACAAPQAgADEAMgAwACwACgAgACAAIAAgACAAIABFACAAPQAgAEQAIAAvACAAQgAsAAoAIAAgACAAIAAgACAARgAgAD0AIAB7AGgAZQBpAGcAaAB0ADoAIABCACwAIAB3AGkAZAB0AGgAOgAgAEEAfQA7AA%3D%3D

### Expected result

Code should work after lint fix :) 

```diff
-     const
-       A = 100,
-       B = 150,
-       D = 120,
-       E = D / B,
-       F = {height: B, width: A};
+     constA = 100;    constB = 150;    constD = 120;    constE = D / B;    constF = {height: B, width: A};
```

Expected result was 
```ts
    const A = 100;
    const B = 150;
    const D = 120;
    const E = D / B;
    const F = {height: B, width: A};
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #728.

I also take the opportunity of adding more details in the rule description.

## Test Plan

I added an anti-regression test and other tests.

### CODE REVIEW

File: crates/biome_js_analyze/src/analyzers/style/use_single_var_declarator.rs [hunk 1]
```diff
@@ -5,28 +5,41 @@ use biome_console::markup;
...
-use biome_rowan::{AstNode, AstNodeExt, AstSeparatedList, BatchMutationExt, TriviaPiece};
 
 use crate::JsRuleAction;
 
 declare_rule! {
     /// Disallow multiple variable declarations in the same variable statement
     ///
+    /// In JavaScript, multiple variables can be declared within a single `car`, `const` or `let` declaration.
+    /// It is often considered a best practice to declare every variable separately.
+    /// That is what this rule enforces.
```
Comment (ematipico) [inline crates/biome_js_analyze/src/analyzers/style/use_single_var_declarator.rs:22]:
```suggestion
    /// In JavaScript, multiple variables can be declared within a single `var`, `const` or `let` declaration.
    /// It is often considered a best practice to declare every variable separately.
    /// That is what this rule enforces.
```
