### PR TITLE
fix(configuration): enabled rules calculation

### LINKED ISSUE #2028: 💅 Regression: Disabling one nursery rule disables all nursery rules
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.7.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  Recommended:                  false
  All:                          true
  Rules:                        nursery/noConsole = "off"

Workspace:
  Open Documents:               0
```

### Rule name

all nursery rules

### Playground link
using CBS, since the playground does not allow modifying the biome config on a rule-level.
https://codesandbox.io/p/devbox/suspicious-hermann-cdnhdx?workspaceId=23165e9f-6758-4f08-8321-45be43925a49

Sidenote: Biome in the CBS is outdated, the installed version there is 1.1.2. Took me a moment to realize that that was why the nursery rules didn't exist.

### Expected result

Disabling one nursery rule should not disable all nursery rules. (The following code can also be found in the CBS.)

```ts
const x = 5;
const a = x ? true : true; // violates "noUselessTernary" from the nursery

console.info(a); // violates "noConsole" from the nursery

// Running `biome lint src` will report no issue at all,
// even though only "noConsole" has been disabled in the biome.json.
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

It turns out the existing function `as_enabled_rules` was calculating the enabled rules in a wrong way. The function is generated by codegen, so I fixed the logic in `xtask/codegen/src/generate_configuration.rs` and regenerated that file. I summarize the correct logic as follows:

### For non-nursery groups

- Group-level `all` and group-level `recommend` should take precedence over their top-level alternatives.
- When group-level `all` or group-level `recommend` is not present, it should fallback to check top-level `all` or top-level `recommend`.
- If the whole group-level config is not present, it should check top-level `all` or top-level `recommend`.

### For nursery group

- Group-level `all` and group-level `recommend` should take precedence over top-level alternatives. (same as non-nursery groups)
- When group-level `all` or group-level `recommend` is not present, it should fallback to check top-level `all` or top-level `recommend` **only in unstable releases**.
- If the whole group-level config is not present, it should check top-level `all` or top-level `recommend` **only in unstable releases**.

Fixes #2028.

## Test Plan

Since the nursery group is unstable because the rules in it may be promoted in later releases, I didn't add test cases for the nursery group. But I tested it locally and it works as expected.

I added a test case called `top_level_all_down_level_empty`. It's to check whether the non-recommended rules belonging to a group will be enabled if we have a top-level `all` as `true` and an empty config of that group. The expected result is they should be kept enabled. In current release (`v1.6.1`) they are wrongly disabled. I guess the reason why this issue isn't discovered earlier is because most rules under a group are recommended rules.

### CODE REVIEW

File: xtask/codegen/src/generate_configuration.rs [hunk 1]
```diff
@@ -91,21 +91,27 @@ pub(crate) fn generate_rules_configuration(mode: Mode) -> Result<()> {
...
+                    &mut enabled_rules,
+                    &mut disabled_rules,
+                );
                 enabled_rules.extend(&group.get_enabled_rules());
                 disabled_rules.extend(&group.get_disabled_rules());
-            } else if self.is_all() {
+            } else if #global_all {
                 enabled_rules.extend(#group_struct_name::all_rules_as_filters());
-            } else if self.is_not_all() {
-                disabled_rules.extend(#group_struct_name::all_rules_as_filters());
```
Comment (Conaclos) [inline xtask/codegen/src/generate_configuration.rs:108]: Could you justify why this lines are deleted?

If `all` is explicitly set to `false`, we should certainly add the rules to `disabled_rules`?

Comment (Sec-ant) [reply xtask/codegen/src/generate_configuration.rs:108]: These rules are not in `enabled_rules`, so we don't have to put them in `disabled_rules`.

Comment (Conaclos) [reply xtask/codegen/src/generate_configuration.rs:108]: Thanks for the clarification. LGTM!

**Review by Conaclos — APPROVED** [review]

**Comment by Conaclos** [comment]
LGTM. It could be great to add a changelog entry.
You have to add the `Unreleased` section. See our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#changelog) for more details :)
