### PR TITLE
fix(lint/useHookAtTopLevel): fix false positives, don't require hook config

### LINKED ISSUE #610: 🐛 `useHookAtTopLevel`: unconditional hook usage flagged as conditionally called
### Environment information

```block
https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAYwByAGUAYQB0AGUAQwBvAG4AdABlAHgAdAAsACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACwAIAB1AHMAZQBDAG8AbgB0AGUAeAB0ACAAfQAgAGYAcgBvAG0AIAAnAHIAZQBhAGMAdAAnADsACgAKAGMAbwBuAHMAdAAgAEMAbwBuAHQAZQB4AHQAIAA9ACAAYwByAGUAYQB0AGUAQwBvAG4AdABlAHgAdAAoAHsAfQApADsACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAdQBzAGUASwBlAHkAKABrAGUAeQA6ACAAcwB0AHIAaQBuAGcAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAB1AHMAZQBDAG8AbgB0AGUAeAB0ACgAQwBvAG4AdABlAHgAdAApAFsAawBlAHkAXQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIAB1AHMAZQBTAHQAdQBmAGYAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAHsACgAgACAAIAAgAGEAYgBjADoAIAB1AHMAZQBDAGEAbABsAGIAYQBjAGsAKAAoACkAIAA9AD4AIABuAHUAbABsACwAIABbAF0AKQAKACAAIAB9ADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAHUAcwBlAFMAdAB1AGYAZgAyACgAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABbAHUAcwBlAEMAYQBsAGwAYgBhAGMAawAoACgAKQAgAD0APgAgAG4AdQBsAGwALAAgAFsAXQApAF0AOwAKAH0ACgA%3D
```

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAYwByAGUAYQB0AGUAQwBvAG4AdABlAHgAdAAsACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACwAIAB1AHMAZQBDAG8AbgB0AGUAeAB0ACAAfQAgAGYAcgBvAG0AIAAnAHIAZQBhAGMAdAAnADsACgAKAGMAbwBuAHMAdAAgAEMAbwBuAHQAZQB4AHQAIAA9ACAAYwByAGUAYQB0AGUAQwBvAG4AdABlAHgAdAAoAHsAfQApADsACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAdQBzAGUASwBlAHkAKABrAGUAeQA6ACAAcwB0AHIAaQBuAGcAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAB1AHMAZQBDAG8AbgB0AGUAeAB0ACgAQwBvAG4AdABlAHgAdAApAFsAawBlAHkAXQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIAB1AHMAZQBTAHQAdQBmAGYAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAHsACgAgACAAIAAgAGEAYgBjADoAIAB1AHMAZQBDAGEAbABsAGIAYQBjAGsAKAAoACkAIAA9AD4AIABuAHUAbABsACwAIABbAF0AKQAKACAAIAB9ADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAHUAcwBlAFMAdAB1AGYAZgAyACgAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABbAHUAcwBlAEMAYQBsAGwAYgBhAGMAawAoACgAKQAgAD0APgAgAG4AdQBsAGwALAAgAFsAXQApAF0AOwAKAH0ACgA%3D

### What happened?

Biome flags these hooks as being conditionally called when they are not.

### Expected result

No issues reported.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### LINKED ISSUE #871: 💅 False Positive on `lint/correctness/useHookAtTopLevel` for arrow functions with implicit return
### Environment information

```bash
CLI:
  Version:                      1.3.3-nightly.38797b7
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.13"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

`lint/correctness/useHookAtTopLevel`

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUATQBlAG0AbwAgAH0AIABmAHIAbwBtACAAJwByAGUAYQBjAHQAJwAKAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABlAHgAcABsAGkAYwBpAHQAUgBlAHQAdQByAG4AIAA9ACAAKAB4ACkAIAA9AD4AIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAdQBzAGUATQBlAG0AbwAoACgAKQAgAD0APgAgAHgALAAgAFsAeABdACkAOwAKAH0ACgAKAGUAeABwAG8AcgB0ACAAYwBvAG4AcwB0ACAAaQBtAHAAbABpAGMAaQB0AFIAZQB0AHUAcgBuACAAPQAgACgAeAApACAAPQA%2BACAAdQBzAGUATQBlAG0AbwAoACgAKQAgAD0APgAgAHgALAAgAFsAeABdACkAOwAKAAoACgA%3D

### Expected result

`lint/correctness/useHookAtTopLevel` should not flag any issues in the provided playground link

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

As demonstrated in #871, the `useHookAtTopLevel` rule would trigger false positives when a hook was triggered directly from an arrow function. Similarly, in #610 false positives are reported when hooks are invoked inside array or object expressions, as well as one where components themselves are implemented inside an object literal.

I first attempted naive fixes so that hook invocations in those places would correctly identify their enclosing function, but this revealed another problem in the case of arrow functions: Hook invocations inside any kind of nested functions were only coincidentally detected and my fix triggered a test failure as a result.

To fix this, I introduced another `is_nested_function()` check so that hook invocations inside nested anonymous functions will always be reported as well.

Finally, I have made one more (possibly controversial) change: I have changed the logic for detecting whether a function call is a hook call to no longer depend on the hook configuration. The effect of this can be witnessed with the `customHook.js` test case, which no longer requires a custom configuration to pass. The rationale for this change is simple: Since Biome validates files individually, the old approach would never be able to detect conditional hook invocations for custom hooks if the implementation of the custom hook is in another file (and the user didn’t manually configure all their custom hooks). So instead, we now follow React's official guidelines to determine whether a function call is a hook call: **Hook names must start with `use` followed by a capital letter** Source: https://react.dev/learn/reusing-logic-with-custom-hooks#hook-names-always-start-with-use

If necessary, I can separate the last change from the rest of this PR.

Fixes #871 
Fixes #610.

## Test Plan

Tests are included.

### CODE REVIEW

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 1]
```diff
@@ -299,48 +310,65 @@ impl Rule for UseHookAtTopLevel {
         let options = ReactExtensiveDependenciesOptions::new(options.clone());
 
         let FunctionCall(call) = ctx.query();
-        let hook_name_range = call.callee().ok()?.syntax().text_trimmed_range();
-        if react_hook_configuration(call, &options.hooks_config).is_some() {
```
Comment (arendjr) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:303]: I have replaced `hook_name_range` with a `get_hook_name_range` closure so that the trimmed range doesn't get calculated if there is nothing to report.

I also replaced the outer `if` with an early return to avoid another level of indentation inside most of this function.

File: crates/biome_css_formatter/src/css/any/dimension.rs [hunk 2]
```diff
@@ -9,8 +9,8 @@ impl FormatRule<AnyCssDimension> for FormatAnyCssDimension {
     fn fmt(&self, node: &AnyCssDimension, f: &mut CssFormatter) -> FormatResult<()> {
         match node {
             AnyCssDimension::CssRegularDimension(node) => node.format().fmt(f),
-            AnyCssDimension::CssPercentage(node) => node.format().fmt(f),
             AnyCssDimension::CssUnknownDimension(node) => node.format().fmt(f),
+            AnyCssDimension::CssPercentage(node) => node.format().fmt(f),
```
Comment (arendjr) [inline crates/biome_css_formatter/src/css/any/dimension.rs:13]: This change was the result of running `just ready`.

**Comment by arendjr** [comment]
Dunno what's going on with the performance checks. Hopefully someone can chime in there!

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 3]
```diff
@@ -85,40 +83,108 @@ declare_rule! {
     }
 }
 
+#[derive(Clone)]
+enum AnyJsFunctionOrMethod {
+    Function(AnyJsFunction),
+    ObjectMethod(JsMethodObjectMember),
```
Comment (arendjr) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:89]: It could be argued I should add a variant for `ClassMethod` too here, but the reason I didn't is because implementing components inside an object literal still seems like a somewhat reasonable use case if you want to use the object as a lookup table for which component to use (and indeed it was reported by a user). But implementing them inside class methods seems a horrible idea in my opinion. Anyone doing that would need to create class instances before being able to invoke the component, which means you may run into issues with component identities and need to be very careful to memoize the class instances at least. Then there's the issue class methods would expect `this` to be set correctly, but React won't do this for you when invoking the component. All of that can be worked around and it's technically possible, but it seems far-fetched enough to me that I would wait to hear if any user even expects this to work.

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 4]
```diff
@@ -85,40 +83,108 @@ declare_rule! {
...
+    match next {
+        Some(next) if AnyJsFunctionOrMethod::can_cast(next.kind()) => {
+            AnyJsFunctionOrMethod::cast(next)
+        }
+        Some(next) => {
+            JsFunctionBody::cast(next).and_then(|body| body.parent::<AnyJsFunctionOrMethod>())
+        }
+        None => None,
+    }
+}
```
Comment (faultyserver) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:178]: Could you add a comment to this block explaining why there needs to be two different checks? Just an example of the different syntaxes that each arm is checking would be great. I _think_ it's because `call` could be either an expression value (like `() => call()`) which the immediate parent is the function, _or_ it could be an expression inside of a body (like `() => { call() }`) where the `JsFunctionBody` node is an intermediary between the two, but without the foreknowledge of that AST structure, it's not immediately clear why this is needed.

**Review by faultyserver — COMMENTED** [review]
Very nice! I think using the convention over the configured hooks is a good change, since the option is really meant for exhaustive deps checking and not just saying "these are all of the hooks that exist". For example, a hook that doesn't take deps would never need to be configured there, but should still get checked for conditionality.

BTW, the Codspeed CI failure is expected for now, so it can be ignored.

Just a couple suggestions throughout, but I think this is pretty much ready to go otherwise.

File: crates/biome_js_analyze/src/react/hooks.rs [hunk 5]
```diff
@@ -107,9 +105,28 @@ pub(crate) fn react_hook_configuration<'a>(
...
+
+    let name = name.text_trimmed();
+    name.starts_with("use")
+        && name
+            .chars()
+            .skip(3)
+            .take(1)
+            .next()
+            .map(char::is_uppercase)
+            .unwrap_or_default()
```
[the remark this answers is not in the document]
Comment (arendjr) [reply crates/biome_js_analyze/src/react/hooks.rs:129]: Ah yeah, good suggestion!

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 6]
```diff
@@ -85,40 +83,108 @@ declare_rule! {
...
 // of the component
-fn enclosing_function_if_call_is_at_top_level(call: &JsCallExpression) -> Option<AnyJsFunction> {
+fn enclosing_function_if_call_is_at_top_level(
+    call: &JsCallExpression,
+) -> Option<AnyJsFunctionOrMethod> {
     let next = call.syntax().ancestors().find(|x| {
         !matches!(
             x.kind(),
-            JsSyntaxKind::JS_STATEMENT_LIST
+            |JsSyntaxKind::JS_ARRAY_ELEMENT_LIST| JsSyntaxKind::JS_ARRAY_EXPRESSION
```
[the remark this answers is not in the document]
Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:147]: Thanks! I was also a little bumped about how it got formatted, but didn't realize the formatter would respect it if I remove the first `|` :)

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 4 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:178]: Ah, upon second thought, I had overcomplicated this block anyway. Your interpretation was correct; sometimes there's a `JsFunctionBody` intermediary and sometimes there isn't. But I could just simplify the whole thing by ignoring the function body through the big `matches!` test above.

**Comment by arendjr** [comment]
Thanks for the review! All updated now :)

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 7]
```diff
@@ -292,55 +326,73 @@ impl Rule for UseHookAtTopLevel {
     type Query = FunctionCall;
     type State = Suggestion;
     type Signals = Option<Self::State>;
-    type Options = HooksOptions;
+    type Options = ();
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:329]: This is a breaking change @arendjr , we can't remove options from from one minor to another.

My suggestion is to keep the options and **don't read them**. Then you'll have to update the deserialization of the options and add a diagnostic for deprecated options.

**Review by ematipico — CHANGES_REQUESTED** [review]
Blocking because there are breaking chances that we don't want to publish. We should first deprecate these options and then remove them in a major release,

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 7 above)
Comment (Conaclos) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:329]: We could also add a warning telling that the option does nothing?

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:329]: The options are still used for the `useExhaustiveDependencies` rule, so they're not gone. My understanding is that wouldn't invalidate any configs, or am I mistaken?

But indeed, if necessary I guess the best way to deal with it is a deprecation notice saying the options aren't used for this rule anymore.

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:329]: Oh wait, I see. They can indeed be passed to a rule-specific `options` object, which indeed would no longer be valid then. I'll re-add the dependency and indeed print a deprecation warning when anything is set for this rule.

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs]: I have added a `DeprecatedHooksOptions` type for this linter that accepts the `hooks` array from `HooksOptions`, but prints a deprecation warning when it encounters this.

I have also added a test case for this. Unfortunately it doesn't capture the diagnostic, but at least it shows the old config is still accepted.

**Review by ematipico — APPROVED** [review]
Thank you @arendjr 

I wrote some changelog and added a new API for adding a new deprecation. Don't be scared to add new public functions if you think the existing ones aren't enough :)

**Comment by ematipico** [comment]
@arendjr I am testing this locally, it seems that the diagnostic doesn't show up...

**Comment by ematipico** [comment]
Please check [`538cc57` (#1393)](https://github.com/biomejs/biome/pull/1393/commits/538cc570f60f50f012f19aa4580a33811e190f15) to see how I fixed the deprecation :)

**Comment by arendjr** [comment]
Thanks for the cleanup!
