### PR TITLE
fix(linter): recognize stable hook results declared with `let`

### LINKED ISSUE #8907: 💅 `useExhaustiveDependencies` mistakenly reports setters returned from `useState()` and refs declared with `let` as required effect dependencies
### Environment information

The code below results in a linter error report saying that `setA` and `b` should be added to the dependencies of `useEffect()`.

```js
import { useEffect, useState, useRef } from "react";

export const Component = () => {
  let [a, setA] = useState(0);
  let b = useRef("");

  useEffect(() => {
    setA(1);
    b.current = "test";
  }, []);
};
```

The error appears with the variables declared with `let` and the `useConst` rule set to `off`.

Linting such code with v2.3.11 and earlier wouldn't produce this error.

This issue was initially reported as a [comment to another issue](https://github.com/biomejs/biome/issues/8885#issuecomment-3805181627), yet this one requires a different setup described above, as it turned out.

### Rule name

lint/correctness/useExhaustiveDependencies

### Playground link

https://biomejs.dev/playground/?lintRules=useExhaustiveDependencies&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUARQBmAGYAZQBjAHQALAAgAHUAcwBlAFMAdABhAHQAZQAsACAAdQBzAGUAUgBlAGYAIAB9ACAAZgByAG8AbQAgACIAcgBlAGEAYwB0ACIAOwAKAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABDAG8AbQBwAG8AbgBlAG4AdAAgAD0AIAAoACkAIAA9AD4AIAB7AAoAIAAgAGwAZQB0ACAAWwBhACwAIABzAGUAdABBAF0AIAA9ACAAdQBzAGUAUwB0AGEAdABlACgAMAApADsACgAgACAAbABlAHQAIABiACAAPQAgAHUAcwBlAFIAZQBmACgAIgAiACkAOwAKAAoAIAAgAHUAcwBlAEUAZgBmAGUAYwB0ACgAKAApACAAPQA%2BACAAewAKACAAIAAgACAAcwBlAHQAQQAoADEAKQA7AAoAIAAgACAAIABiAC4AYwB1AHIAcgBlAG4AdAAgAD0AIAAiAHQAZQBzAHQAIgA7AAoAIAAgAH0ALAAgAFsAXQApADsACgB9ADsACgA%3D

### Expected result

`setA` and `b` shouldn't be required as an effect dependencies, as they are stable.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by littleKitchen**
## Summary

When `useState` setters or `useRef` values are destructured into `let` bindings, they should still be recognized as stable and not require inclusion in dependency arrays.

## Problem

```js
let [a, setA] = useState(0);
let b = useRef("");

useEffect(() => {
  setA(1);
  b.current = "test";
}, []); // ❌ Biome incorrectly reports setA and b as missing dependencies
```

The `useExhaustiveDependencies` rule was returning early for non-const declarations without checking if the initializer was a stable hook call.

## Solution

Check stable hook results for both `let` and `const` declarations. For `let` declarations, only stable hook results (like `useState` setters at index 1, or `useRef` identity) are considered stable.

## Test Plan

- Added `issue8907.js` test case
- All 56 `useExhaustiveDependencies` tests pass

Fixes #8907

### CODE REVIEW

**Comment by dyc3** [comment]
cc @mdevils

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs [hunk 1]
```diff
@@ -709,19 +709,48 @@ fn is_stable_binding(
...
             else {
-                // This shouldn't happen because we check for `const` above
-                return true;
+                // No initializer - only `const` without initializer is stable
+                // (this shouldn't happen for valid code, but handle gracefully)
+                return declaration.is_const();
             };
 
+            // For non-const declarations, only stable hook results (like useState setters
+            // or useRef) are considered stable. Other values may be reassigned.
```
Comment (mdevils) [inline crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs]: > Other values may be reassigned.

All lets may be reassigned. `eslint` rule checks specifically if it was reassigned in case of stable hook results. Please check all writes of the binding to make sure it wasn't rewritten.

File: crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue8907.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+// Issue #8907: useState setters and refs declared with `let` should be stable
+export const Component = () => {
+  let [a, setA] = useState(0);
+  let b = useRef("");
+
+  useEffect(() => {
+    setA(1);
+    b.current = "test";
+  }, []);
+};
```
Comment (mdevils) [inline crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue8907.js:14]: Please add test where you reassign `setA`.

**Comment by littleKitchen** [comment]
I see, thanks for the review.

**Comment by mdevils** [comment]
@littleKitchen thank you for your quick response and fixes!

Please include a changeset for your changes.

Here is an example changeset: https://github.com/biomejs/biome/blob/main/.changeset/ninety-tigers-fetch.md

You can create a new changeset using `just new-changeset` command.

**Comment by mdevils** [comment]
@littleKitchen thank you for your contribution!

**Comment by littleKitchen** [comment]
Thanks!
