### PR TITLE
fix(cli): allow --stdin-file-path outside files.includes

### LINKED ISSUE #6783: bug: `biome format` with `--stdin-file-path` fails if `includes` is missing the value in `--stdin-file-path`.
### Environment information

```block
Version:                      2.0.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-kitty
  JS_RUNTIME_VERSION:           v24.3.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/10.12.4

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Workspace:
  Open Documents:               0
```

### What happened?

1. create a biome.json with the following contents:
```json
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"files": {
		"includes": [
			"apps/**/*.{json,md,toml,ts,tsx,yaml,yml}",
			"packages/**/*.{json,md,toml,ts,tsx,yaml,yml}"
		]
	},
	"formatter": {
		"enabled": true
	}
}
```

2. run `echo '' | biome format --stdin-file-path 'a.tsx' --files-ignore-unknown=false`
3. Observe
```
The content was not formatted because the formatter is currently disabled.
stdin ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The contents aren't fixed. Use the `--write` flag to fix them.
```

### Expected result

The fact that `a.tsx` isn't in my includes shouldn't cause format to stop working.

you have to put whatever file you have in `stdin-file-path` in your includes for it to work:
```
```json
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"files": {
		"includes": [
			"apps/**/*.{json,md,toml,ts,tsx,yaml,yml}",
			"packages/**/*.{json,md,toml,ts,tsx,yaml,yml}",
			"a.tsx"
		]
	},
	"formatter": {
		"enabled": true
	}
}
```

however this is impractical for command line tools that integrate with biome outside of the editor directly

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by tt-a1i**
## Summary

Fixes #6783.

When running `biome format`, `biome check`, or `biome lint` with `--stdin-file-path` and the provided path **doesn't exist on disk** (i.e. it’s a virtual path), `files.includes` no longer causes the stdin content to be treated as ignored.

This keeps the existing behavior for real files (paths that exist on disk), and still respects VCS ignores / feature-specific ignores.

## Test Plan

- Added a new CLI snapshot test: `format_stdin_formats_virtual_path_outside_includes`
- `cargo test -p biome_cli --test main`

## AI Assistance Disclosure

This PR was written with assistance from OpenAI Codex CLI (used for review and iterative debugging).

### CODE REVIEW

File: crates/biome_service/src/workspace.rs [hunk 1]
```diff
@@ -109,13 +109,20 @@ pub enum ServiceNotification {
...
 #[derive(Debug, serde::Serialize, serde::Deserialize)]
 #[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
 #[serde(rename_all = "camelCase")]
 pub struct SupportsFeatureParams {
     pub project_key: ProjectKey,
     pub path: BiomePath,
     pub features: FeatureName,
+
+    #[serde(default, skip_serializing_if = "is_false")]
+    pub ignore_includes: bool,
```
Comment (ematipico) [inline crates/biome_service/src/workspace.rs]: Calling it `ignore_includes` is a bit reductive, because we also check VCS-ignored files. I suggest a more generic a more generic name e.g. `skip_ignore_check`

File: .changeset/warm-houses-switch.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#6783](https://github.com/biomejs/biome/issues/6783): stdin formatting using `--stdin-file-path` is no longer blocked by `files.includes` when the provided path doesn't exist on disk.
```
Comment (ematipico) [inline .changeset/warm-houses-switch.md]:
```suggestion
Fixed [#6783](https://github.com/biomejs/biome/issues/6783): now, when a path is provided via `--stdin-file-path`, Biome checks whether the file exists within the current project. If the path doesn't exist, ignore checks - `files.includes` and VCS-ignore files - are skipped, and the file is handled. 
```

What do you think of this suggestion? I think it is a bit clearer for our end users. Feel free to change it, but the idea is that we need to mention VCS too, and making the phrase generic towards stdin, not formatting.

**Comment by tt-a1i** [comment]
Good call — I’ve added a note to the `--stdin-file-path` docs in the CLI help text (check/lint/format) to clarify the interaction with `files.includes`:

- virtual path (doesn’t exist on disk): `files.includes` won’t block stdin processing
- existing path: `files.includes` applies as usual

Pushed in `docs(cli): clarify stdin-file-path and files.includes`.

If you’d prefer this documented somewhere else as well (e.g. the website docs), happy to follow up.

**Comment by ematipico** [comment]
I still think we shouldn't mention `files.includes` specifically, because there's also VCS ignore files in the mix

**Comment by tt-a1i** [comment]
Yep, that’s fair — mentioning `files.includes` alone is a bit misleading since VCS ignores can also make stdin behave as “ignored”.

I reworded the help text to be more generic (talks about ignore behaviour / project file set, and explicitly calls out VCS ignore files as an example), without singling out `files.includes`.

Pushed in `docs(cli): clarify stdin-file-path ignore behavior`.

**Comment by tt-a1i** [comment]
FYI: I fixed the CI failures from the previous run:

- cargo lint was failing on clippy::too_many_arguments / clippy::blocks_in_conditions in Projects::get_file_features (refactored to a params struct + simpler control flow)
- help snapshots (check_help / format_help / lint_help) updated to match the updated --stdin-file-path wording

New CI run is in progress.

File: .changeset/warm-houses-switch.md (hunk 2 above)
Comment (ematipico) [reply .changeset/warm-houses-switch.md]: @tt-a1i what do you think of this suggestion?

File: crates/biome_service/src/workspace.rs (hunk 1 above)
Comment (ematipico) [reply crates/biome_service/src/workspace.rs]: What do you think of this suggestion @tt-a1i ?

**Comment by tt-a1i** [comment]
done — renamed to `skip_ignore_check` and updated the changeset wording. thanks for the suggestions!

File: crates/biome_cli/src/commands/mod.rs [hunk 3]
```diff
@@ -181,6 +181,11 @@ pub enum BiomeCommand {
         /// Also, if you have overrides configured and/or nested configurations,
         /// the path may determine the settings being applied.
         ///
+        /// The provided path may also affect whether the input is treated as
+        /// ignored. If the path doesn't exist on disk (virtual path), Biome
+        /// won't require it to be part of the project file set, but ignore rules
+        /// may still apply (e.g. VCS ignore files).
```
Comment (ematipico) [inline crates/biome_cli/src/commands/mod.rs]:
```suggestion
        /// If the provided path doesn't exist in the project, Biome doesn't check if 
        /// it's ignored (VCS, `files.includes`, etc.). 
```

File: crates/biome_cli/src/commands/mod.rs [hunk 4]
```diff
@@ -287,6 +292,11 @@ pub enum BiomeCommand {
         ///
         /// The file doesn't need to exist on disk, what matters is the extension of the file. Based on the extension, Biome knows how to lint the code.
         ///
+        /// The provided path may also affect whether the input is treated as
+        /// ignored. If the path doesn't exist on disk (virtual path), Biome
+        /// won't require it to be part of the project file set, but ignore rules
+        /// may still apply (e.g. VCS ignore files).
```
Comment (ematipico) [inline crates/biome_cli/src/commands/mod.rs]:
```suggestion
        /// If the provided path doesn't exist in the project, Biome doesn't check if 
        /// it's ignored (VCS, `files.includes`, etc.). 
```

File: crates/biome_cli/src/commands/mod.rs [hunk 5]
```diff
@@ -345,6 +355,11 @@ pub enum BiomeCommand {
         ///
         /// The file doesn't need to exist on disk, what matters is the extension of the file. Based on the extension, Biome knows how to format the code.
         ///
+        /// The provided path may also affect whether the input is treated as
+        /// ignored. If the path doesn't exist on disk (virtual path), Biome
+        /// won't require it to be part of the project file set, but ignore rules
+        /// may still apply (e.g. VCS ignore files).
```
Comment (ematipico) [inline crates/biome_cli/src/commands/mod.rs]:
```suggestion
        /// If the provided path doesn't exist in the project, Biome doesn't check if 
        /// it's ignored (VCS, `files.includes`, etc.). 
```

File: crates/biome_service/src/projects.rs [hunk 6]
```diff
@@ -231,16 +244,40 @@ impl Projects {
...
-                    .is_path_ignored_for_feature(path, feature)
-                    || settings.is_path_ignored_for_feature(path, feature)
-                {
-                    file_features.set_ignored(feature);
+            let is_ignored = {
+                let is_ignored_by_top_level_config = if skip_ignore_check {
+                    project_data
+                        .root_settings
+                        .vcs_settings
+                        .is_ignored(path, Some(project_data.path.as_path()))
```
Comment (ematipico) [inline crates/biome_service/src/projects.rs]: Why did we change the initial proposed logic?

Comment (tt-a1i) [reply crates/biome_service/src/projects.rs]: > Why did we change the initial proposed logic?

  Right now, when --stdin-file-path points to a path that doesn’t exist on disk, we only bypass
  the files.includes “file set” check — we still apply VCS ignore (and per-feature ignore) so
  --stdin-file-path can’t be used to bypass ignore rules.

  That’s why I didn’t take the doc suggestion as-is: “doesn’t check if it’s ignored (VCS,
  includes, etc.)” would be inaccurate with the current behavior.

  We changed from the initial “skip ignore entirely” idea because the goal of #6783 was “don’t
  let files.includes block virtual stdin paths”, not “ignore .gitignore”.

  If you’d rather have the stronger behavior (skip VCS/feature ignores too for virtual paths), I
  can adjust the implementation + tests + changeset — just want to confirm the intended
  semantics first.

Comment (ematipico) [reply crates/biome_service/src/projects.rs]: It would be very hard to justify to the users **why** we skip `files.includes` but we don't skip VCS ignore files. Just because a user used one way to ignore files, doesn't exclude the use of VCS ignore files. Both tools achieve the same objective - ignoring files. 

So yes, we should skip both checks.

Comment (tt-a1i) [reply crates/biome_service/src/projects.rs]: > It would be very hard to justify to the users **why** we skip `files.includes` but we don't skip VCS ignore files. Just because a user used one way to ignore files, doesn't exclude the use of VCS ignore files. Both tools achieve the same objective - ignoring files.
> 
> So yes, we should skip both checks.

Makes sense — updated. When skip_ignore_check is true we now skip the whole ignore block (both
  files.includes and VCS ignore). Also updated the CLI help text + changeset to match.

**Comment by tt-a1i** [comment]
hi @ematipico, just checking in - anything else needed on this one? happy to make more changes if needed!
