### PR TITLE
fix(organizeImports): doesn't add a blank line between a never-matched group and a matched group

### LINKED ISSUE #8596: 🐛 `organizeImports` in vue SFC throws false warnings
### Environment information

```block
CLI:
  Version:                      2.3.10
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.4.1
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         yarn/1.22.22

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false
  HTML full support enabled:    true

Workspace:
  Open Documents:               0
```

### What happened?

When using the `organizeImports` source action with groups separated with a `:BLANK_LINE:` biome gets confused when a document only contains imports for the 2nd group. This results in biome throwing `The imports and exports are not sorted.` despite them being so.

I have created [a basic repo to easier reproduce](https://github.com/cobsen/biome-repro-1762177411003) this error.

### Expected result

Biome not complaining when the imports are already sorted.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### LINKED ISSUE #9097: Astro - Assist `organizeImports` with `:BLANK_LINE:` group breaks
### Environment information

<details>

```bash

CLI:
  Version:                      2.4.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v24.13.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/11.8.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            false
  Linter enabled:               false
  Assist enabled:               true
  VCS enabled:                  true
  HTML full support enabled:    unset

Workspace:
  Open Documents:           

```

</details>

### What happened?

When using `organizeImports` with any `:BLANK_LINE:` groups, some Astro frontmatter sections are breaking by suggesting to 
- remove the opening `---` 
- add a blank line.

Removing the `:BLANK_LINE:` groups works.  The above issue seems to only happen in some Astro files in our project, not all.

Minimal reproduction repository: https://github.com/setchy/biome-astro-organize-imports

```
> biome check

src/index.astro:2:1 assist/source/organizeImports  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The imports and exports are not sorted.
  
    1 │ ---
  > 2 │ import Page from "./page.astro";
      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 │ ---
    4 │ 
  
  ℹ Safe fix: Organize Imports (Biome)
  
    1 1 │   
      2 │ + 
    2 3 │   import Page from "./page.astro";
    3 4 │   
  

Checked 4 files in 1991µs. No fixes applied.
Found 1 error.
check ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Some errors were emitted while running checks.
```

### Expected result

Organize imports correctly

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix https://github.com/biomejs/biome/issues/9097.
Fix https://github.com/biomejs/biome/issues/8596.

Given the following configuration...

```json
{
  "assist": {
    "actions": {
      "source": {
        "organizeImports": {
          "level": "on",
          "options": { "groups": [":NODE:", ":BLANK_LINE:", ":PACKAGE:", ":BLANK_LINE:", ":PATH:"] }
        }
      }
    }
  }
}
```

The import organizer was adding two blank lines to the following code:

```diff
+
  // Comment
  import "package";
+
  import "./file.js";
```

A blank line was added even though the group ':NODE:' doesn't match any imports here.
`:BLANK_LINE:` between never-matched groups and matched groups are now ignored.
The code is now organized as:

```diff
  // Comment
  import "package";
+
  import "./file.js";
```

## Test Plan

I added a test

## Docs

I added a changeset.

### CODE REVIEW

File: crates/biome_js_analyze/src/assist/source/organize_imports.rs [hunk 1]
```diff
@@ -767,19 +767,22 @@ impl Rule for OrganizeImports {
         let sort_order = options.identifier_order.unwrap_or_default();
         let mut chunk: Option<ChunkBuilder> = None;
         let mut prev_kind: Option<JsSyntaxKind> = None;
-        let mut prev_group = 0;
+        let mut prev_group = None;
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/assist/source/organize_imports.rs:770]: Using `u16::MAX` could have the same effect. However, using `None` makes the code cleaner.

**Review by dyc3 — APPROVED** [review]

File: .changeset/deep-beans-pick.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [`organizeImports`](https://biomejs.dev/assist/actions/organize-imports/)
+that added an extra newline at the start of a file when `:BLANK_LINE:` is used.
```
Comment (ematipico) [inline .changeset/deep-beans-pick.md]:
```suggestion
Fixed [#9097](https://github.com/biomejs/biome/issues/9097):  [`organizeImports`](https://biomejs.dev/assist/actions/organize-imports/)
no longer adds extra newline at the start of a file when `:BLANK_LINE:` is used.
```

File: crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js [hunk 3]
```diff
@@ -0,0 +1,4 @@
+/* should not generate diagnostics */
+import A from "a";
+import "chunked";
+import B from "b";
```
Comment (ematipico) [inline crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js:4]: This example doesn't reflect the configuration, there are no node Imports. Why?

**Review by ematipico — APPROVED** [review]
I don't understand the fix, but the example doesn't make sense. Changeset needs to fixed

File: crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js (hunk 3 above)
Comment (Conaclos) [reply crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js:4]: This is part of the bug. We need a group that is not matched then a `:BLANK_LINE:`. I chose `:NODE:`, however this could be anything.

File: .changeset/deep-beans-pick.md (hunk 2 above)
Comment (Conaclos) [reply .changeset/deep-beans-pick.md]: The issue is not completely fixed as explained in [a comment](https://github.com/biomejs/biome/issues/9097#issuecomment-4300274474). I could write `Fixed partially #XXXX`? Or open another issue and closed this issue with this PR.

File: crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js (hunk 3 above)
Comment (ematipico) [reply crates/biome_js_analyze/tests/specs/source/organizeImports/no-leaading-extra-newline.js:4]: Still, I'm walking in the dark. The PR description doesn't explain the bug (technical side), and neither the solution. How can we understand the test or the changeset?

File: .changeset/deep-beans-pick.md (hunk 2 above)
Comment (ematipico) [reply .changeset/deep-beans-pick.md]: Unfortunately I don't have an actionable suggestion because I don't understand the issue. Sorry. My only suggestion is just make sure a user understands what we fixed.

**Comment by Conaclos** [comment]
@ematipico I improved the changeset. This should now be easier to understand the fix. Unfortuantely the changeset is a bit lengthy...
