### PR TITLE
fix(lint/useJsxKeyInIterable): flag jsx in variable declarations

### LINKED ISSUE #2590: 💅 `useJsxKeyInIterable` bugs
### Environment information

```bash
Playground
```

### Rule name

useJsxKeyInIterable

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ACgAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABbAF0ALgBtAGEAcAAoACgAaQB0AGUAbQApACAAPQA%2BACAAewAKACAAIAAgACAAYwBvAG4AcwB0ACAAZABpAHYAIAA9ACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0AIAAvAD4AOwAKAAoAIAAgACAAIAAvAC8AIABPAEsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAaQB0AGUAbQAuAGMAbwBuAGQAaQB0AGkAbwBuACAAPwAgAGQAaQB2ACAAOgAgADwAZABpAHYAIABrAGUAeQA9AHsAaQB0AGUAbQAuAGkAZAB9AD4AewBkAGkAdgB9ADwALwBkAGkAdgA%2BADsACgAgACAAfQApADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAFQAZQBzAHQAMQAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAWwBdAC4AbQBhAHAAKAAoAGkAdABlAG0AKQAgAD0APgAgAHsACgAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAZgBsAGEAZwAgAHQAaABpAHMACgAgACAAIAAgAGMAbwBuAHMAdAAgAGQAaQB2ACAAPQAgADwAZABpAHYAIAAvAD4AOwAKAAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAGkAdABlAG0ALgBjAG8AbgBkAGkAdABpAG8AbgAgAD8AIABkAGkAdgAgADoAIAA8AGQAaQB2ACAAawBlAHkAPQB7AGkAdABlAG0ALgBpAGQAfQA%2BAHsAZABpAHYAfQA8AC8AZABpAHYAPgA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADIAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIABjAG8AbgBzAHQAIABkAGkAdgAgAD0AIAA8AGQAaQB2ACAAawBlAHkAPQB7AGkAdABlAG0ALgBpAGQAfQAgAC8APgA7AAoACgAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAbgBvAHQAIABmAGwAYQBnACAAdABoAGkAcwAKACAAIAAgACAAcgBlAHQAdQByAG4AIAA8AD4AewBpAHQAZQBtAC4AYwBvAG4AZABpAHQAaQBvAG4AIAA%2FACAAZABpAHYAIAA6ACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0APgB7AGQAaQB2AH0APAAvAGQAaQB2AD4AfQA8AC8APgA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADMAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIABpAGYAIAAoAGkAdABlAG0ALgBjAG8AbgBkAGkAdABpAG8AbgApACAAewAKACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0AIAAvAD4AOwAKACAAIAAgACAAfQAKAAoAIAAgACAAIAAvAC8AIABPAEsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAbgB1AGwAbAA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADQAKAB7ACAAZABhAHQAYQAgAH0AKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AD4ACgAgACAAIAAgACAAIAB7AFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAaQB0AGUAbQAuAGMAbwBuAGQAaQB0AGkAbwBuACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIABrAGUAeQA9AHsAaQB0AGUAbQAuAGkAZAB9ACAALwA%2BADsACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAbgBvAHQAIABmAGwAYQBnACAAdABoAGkAcwAKACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgAG4AdQBsAGwAOwAKACAAIAAgACAAIAAgAH0AKQB9AAoAIAAgACAAIAAgACAAewAvACoAIABzAGgAbwB1AGwAZAAgAG4AbwB0ACAAZgBsAGEAZwAgAHQAaABpAHMAIAAqAC8AfQAKACAAIAAgACAAIAAgAHsAZABhAHQAYQAuAHIAZQBkAHUAYwBlACgAKAB0AG8AdABhAGwALAAgAG4AZQB4AHQAKQAgAD0APgAgAHQAbwB0AGEAbAAgACsAIABuAGUAeAB0AC4AdgBhAGwAdQBlACwAIAAwACkAfQAKACAAIAAgACAAPAAvAD4ACgAgACAAKQA7AAoAfQA%3D

### Expected result

I found some false positives when enabling this rule in our codebase.
Looks like there are discrepancies when the array or returned value are not wrapped in JSX.

Also, Biome warns
>Cannot determine whether this child has the required key prop.

I don't find this message helpful, it's not actionable, what do you want me to do?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

The rule will now catch snippets like below:
```jsx
// invalid
[].map((item) => {
	const div = <div>{item}</div>;
	return div;
});
```

fully resolves #2590

## Test Plan

Added more snapshot tests
```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Awesome! Just left some comments to polish the code, but the logic looks good

**Comment by ematipico** [comment]
I forgot to submit the comments... -.- hold on

File: crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs [hunk 1]
```diff
@@ -180,24 +169,49 @@ fn handle_iterators(node: &JsCallExpression, model: &SemanticModel) -> Option<Ve
...
         }
         _ => None,
     }
 }
 
+fn handle_function_body(
+    node: &JsFunctionBody,
+    model: &SemanticModel,
+    is_inside_jsx: bool,
+) -> Option<Vec<TextRange>> {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:184]: Few things we could address:
- `Option` isn't needed here, let the cooler wrap with `Some`
- Use `iter` instead of `into_iter`.
- When the name of a function isn't enough to express what it does, we should provide some documentation to address it. For example "handle" somebody doesn't tell us anything. We should rename the function and/or provide a better name

**Review by ematipico — APPROVED** [review]
