### PR TITLE
fix(config): don't conceal a previous override with the base settings

### LINKED ISSUE #3176: 🐛 Override behavior with multiple matches
### Discussed in https://github.com/biomejs/biome/discussions/3166

<div type='discussions-op-text'>

<sup>Originally posted by **redbmk** June 10, 2024</sup>
I'm not sure if this is a bug so starting it out as a discussion.

I expected to be able to add multiple blocks of "overrides" and have items that have multiple matches pick up all of the overrides.

Here's a simplified example of my setup:

```jsonc
{
  "$schema": "https://biomejs.dev/schemas/1.7.1/schema.json",
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": { "all": true, "noUndeclaredVariables": "error" },
      "suspicious": { "noConsoleLog": "warn" }
    }
  },
  "overrides": [
    { "include": ["scripts/k6.js"], "javascript": { "globals": ["__ENV", "__VU"] } },
    {
      "include": ["scripts"],
      "linter": { "rules": { "suspicious": { "noConsoleLog": "off" } } }
    }
  ]
}
```

and lets say somewhere in `scripts/k6.js` I have `console.log({ __ENV, __VU })`

If I have it set up like this, then `scripts/k6.js` throws errors that `__ENV` and `__VU` are undeclared. If I swap the order of the two override sections, it picks up on the globals but then throws warnings that I'm using `console.log`.

I'm having trouble finding documentation on how exactly the `overrides` work.

Is there a way I can update the overrides so that `scripts/k6.js` has both those overrides without having to repeat the noConsoleLog override?</div>

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #3176

When we convert the Biome Configuration to Workspace settings, we use the base settings to set the missing settings in every override. This results in overrides that conceal previous overrides.

For example, the following config:

```json
  {
    "linter": {
      "rules": {
        "suspicious": { "noDebugger": "off" }
      }
    },
    "overrides": [
      {
        "include": ["index.js"],
        "linter": {
          "rules": {
            "suspicious": { "noDebugger": "warn" }
          }
        }
      }, {
        "include": ["index.js"]
      }
    ]
  }
```

was resolved to:

```json
  {
    "linter": {
      "rules": {
        "suspicious": { "noDebugger": "off" }
      }
    },
    "overrides": [
      {
        "include": ["index.js"],
        "linter": {
          "rules": {
            "suspicious": { "noDebugger": "warn" }
          }
        }
      }, {
        "include": ["index.js"],
        "linter": {
          "rules": {
            "suspicious": { "noDebugger": "off" }
          }
        }
      }
    ]
  }
```

The current PR fixes the issue by removing the propagation of the base configuration to every override.

I also fixed several erroneous implementations.
For example, we took the first `override.{linter.formatter.organizeImports}.enabled` into account, while we have to take the last one.

I think there are still some issues. Some fields such as `jsx_runtime` are not behind an `Option` in `overrides`.
This means that every `overrides` has a default value for this field.
This is a change for a future PR.

## Test Plan

I added new tests to avoid any regressions.

### CODE REVIEW

**Review by Sec-ant — COMMENTED** [review]
~~Sorry I tried to rebase and update the snapshots, but I forgot to accept them before commiting them. 🥺~~

Fixed

File: crates/biome_service/src/settings.rs [hunk 1]
```diff
@@ -778,195 +769,158 @@ impl OverrideSettings {
...
             .iter()
-            .fold(base_set.as_ref(), |globals, pattern| {
-                let included = pattern.include.matches_path(path);
-                let excluded = pattern.exclude.matches_path(path);
-
-                if included && !excluded {
-                    pattern.languages.javascript.globals.as_ref()
+            // Reverse the traversal as only the last override takes effect
+            .rev()
+            .find_map(|pattern| {
```
Comment (ematipico) [inline crates/biome_service/src/settings.rs:774]: Damn, I will never understand overrides, my brain just fails to get them 😓

**Review by ematipico — APPROVED** [review]
