### PR TITLE
fix(js_analyze): temporal global

### LINKED ISSUE #9464: 📎 Add `Temporal` to list of globals
### Description

`Temporal` is a proposal that reached stage 4 yesterday and has been implemented and enabled by default in Chrome and Firefox, with platforms like node looking to enable it soon. we should add it to our globals list so that lint rules like `noUndeclaredVariables` don't trigger a false positive

### PR DESCRIPTION
**Pull request by Netail**
## Summary

Added Temporal to the globals list, as it reached Stage 4

Closes #9464

### CODE REVIEW

File: crates/biome_js_analyze/src/globals/javascript/web.rs [hunk 1]
```diff
@@ -1142,6 +1142,7 @@ pub const SERVICE_WORKER: &[&str] = &[
     "ServiceWorkerMessageEvent",
     "ServiceWorkerRegistration",
     "SubtleCrypto",
+    "Temporal",
```
[the remark this answers is not in the document]
Comment (Netail) [reply crates/biome_js_analyze/src/globals/javascript/web.rs:1146]: scheisse

File: crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js.snap
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js.snap:1]: do we know why this diff is here?

Comment (Netail) [reply crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js.snap:1]: Oops, as crates are excluded from the biome config, it used my IDE formatter. reverted
