### PR TITLE
fix(lint): fix `noConfusingVoidType` to accept generic types in a union type

### LINKED ISSUE #604: 🐛 `noConfusingVoidType`: allow `Promise<void> | void`
### Environment information

```block
CLI:
  Version:                      1.3.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v21.1.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

```ts
export async function test(fn: () => Promise<void> | void) {
  await fn();
  return 'ok';
}
```

We use this pattern in our codebase, we pass functions that may or may not be async, so
- we have the `Promise<void>` return type for async functions, combined with the [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) allows us to ensure we don't forget to `await` it
- we have the `void` return type for sync functions, otherwise TS would complain

### Expected result

[no-invalid-void-type](https://typescript-eslint.io/rules/no-invalid-void-type/) considers this union to be valid, but Biome doesn't. I'd expect parity.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by unvalley**
## Summary
Closes #604

Fix `noConfusingVoidType` 
- to accept generic types in a union type: #604 
- to report void used in generic function type argument: to pass test

## Test Plan
`cargo test -p biome_js_analyze no_confusing_void_type`

~~Existing test plans should pass, and add a test case that filed on #604~~
Update test cases by referencing typescript-eslint no-invalid-void-type test cases.

### CODE REVIEW

**Comment by Conaclos** [comment]
Thanks for your reactivity! :)

Could you explain the nature of the change?

I wonder: should we accept all unions including `void` in a return type and in generic positions?

**Comment by unvalley** [comment]
@Conaclos 

> Could you explain the nature of the change?

If `void` is included in a union type with generic types, we accept that. (It might be better to check if the contents of the generic type are `void`)

> More tests could also help.
Yes, right. I should add tests in this PR, at least tests for `allowGenericTypeArguments` option.

> I wonder: should we accept all unions including void in a return type and in generic positions?

Probably yes, because we don't have an option to get generic type identifier to accept.  

```json
// typescript-eslint no-invalid-void-type test case example
{
      code: 'type voidPromiseUnion = void | Promise<void>;',
      options: [{ allowInGenericTypeArguments: ['Promise'] }],
},
```

Our `noConfusingVoidType` is always true to the original [no-invalid-void-type 's allowInGenericTypeArguments](https://typescript-eslint.io/rules/no-invalid-void-type/#allowingenerictypearguments).

File: crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs [hunk 1]
```diff
@@ -53,63 +54,67 @@ declare_rule! {
...
     }
 }
 
-fn node_in(node: &SyntaxNode<Language>) -> Option<VoidTypeIn> {
+fn decide_void_type_context(node: &SyntaxNode<JsLanguage>) -> Option<VoidTypeContext> {
     for parent in node.parent()?.ancestors() {
         match parent.kind() {
+            JsSyntaxKind::TS_UNION_TYPE_VARIANT_LIST => {
+                // checks if the union type contains generic type
+                for children in parent.descendants() {
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs:98]: I am not sure that descendants is the best choice here because it traverses the entire subtree. Instead, we should traverse every constituent and verify if the type is `void` or a parametrized type with `void` as argument.

This is the [approach used by the ESLint rule](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/no-invalid-void-type.ts#L148-L165).

File: website/src/content/docs/linter/rules/no-confusing-void-type.md [hunk 2]
```diff
@@ -100,7 +100,6 @@ function doSomething(this: void) {}
 
 ```ts
 function printArg<T = void>(arg: T) {}
-printArg<void>(undefined);
```
Comment (unvalley) [inline website/src/content/docs/linter/rules/no-confusing-void-type.md:103]: This is incorrect case. so I remove it.

File: crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs [hunk 3]
```diff
@@ -53,88 +53,100 @@ declare_rule! {
...
+            JsSyntaxKind::TS_TYPE_ARGUMENT_LIST => {
+                // handle generic function that has a void type argument
+                // e.g. functionGeneric<void>(undefined);
+                let Some(grand_parent) = parent.grand_parent() else {
+                    continue;
+                };
+                if grand_parent.kind() == JsSyntaxKind::JS_CALL_EXPRESSION {
+                    return Some(VoidTypeContext::Unknown);
+                }
+                return None;
```
Comment (unvalley) [inline crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs:134]: We need to address the scenario where `fn<void>(undefined)`.
I discovered this issue when I adde tests, so I addressed.

Comment (Conaclos) [reply crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs:134]: What the issue?

Comment (unvalley) [reply crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs:134]: I think this `void` in function's generic type may confuse developers because the `void` is useless to be generic.

**Review by Conaclos — APPROVED** [review]
