### PR TITLE
fix(format/html): keep at most 1 empty line between elements

### LINKED ISSUE #3973: 📝 HTML: should preserve at most one newline trivia between elements
### Environment information

```bash
playground
```

### Configuration

_No response_

### Playground link

https://biomejs.dev/playground/?files.main.html=PABkAGkAdgA%2BAAoAPABwAD4ATABvAHIAZQBtADwALwBwAD4ACgA8AHAAPgBpAHAAcwB1AG0APAAvAHAAPgAKAAoAPABwAD4ATgB1AG4AYwA8AC8AcAA%2BAAoACgAKAAoACgA8AHAAPgBOAGEAbQA8AC8AcAA%2BAAoAPAAvAGQAaQB2AD4A

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

Prettier preserves at most 1 empty line (2 newlines) between tags. This PR makes it so that Biome matches the newline preserving behavior of Prettier.

It feels a bit hacky, but it gets the job done. Since this was originally ported from the `JsxChildList` behavior, this code makes a bunch of assumptions about the parsing that are not true for the HTML parser. Planning to go through it eventually to clean it up and simplify it, which will be a lot easier to do when we have sufficient tests.

> [!CAUTION]
> This PR is stacked on the following PRs. **Do not merge it without merging the others and rebasing this branch.** To review this PR, look at the last commit only.
> - #4056

fixes #3973

## Test Plan

Added a few tests.

### CODE REVIEW

File: crates/biome_html_formatter/src/html/lists/element_list.rs [hunk 1]
```diff
@@ -106,6 +105,7 @@ impl FormatHtmlElementList {
 
         while let Some(child) = children_iter.next() {
             let mut child_breaks = false;
+            // dbg!(child);
```
Comment (ematipico) [inline crates/biome_html_formatter/src/html/lists/element_list.rs:108]: To remove

File: crates/biome_html_formatter/src/utils/children.rs [hunk 2]
```diff
@@ -236,9 +238,43 @@ where
...
                 }
+                prev_was_content = true;
             }
             child => {
+                let text = child.to_string();
+                let mut chunks = HtmlSplitChunksIterator::new(&text).peekable();
+
+                // Text starting with a whitespace
+                if let Some((_, HtmlTextChunk::Whitespace(_whitespace))) = chunks.peek() {
+                    match chunks.next() {
```
Comment (ematipico) [inline crates/biome_html_formatter/src/utils/children.rs:249]: Nit: you could `unwrap()` because it's a safe operation since the peek is already `Some`, and add a `// SAFETY: ` comment.

With this, you have less branching, and we do this in other areas of the code

**Review by ematipico — APPROVED** [review]
