### PR TITLE
fix(format/html): make element children break if attributes break

### LINKED ISSUE #5026: 📝 HTML element content must break when attributes break
### Environment information

```bash
playground
```

### Configuration

```JSON

```

### Playground link

https://biomejs.dev/playground/?bracketSameLine=true&lintRules=all&files.main.html=PAAhAC0ALQAgAEMAbwBuAHQAZQBuAHQAIABiAHIAZQBhAGsAcwAgAGIAZQBjAGEAdQBzAGUAIABhAHQAdAByAGkAYgB1AHQAZQBzACAAYgByAGUAYQBrACAALQAtAD4ACgA8AGQAaQB2ACAAYQB0AHQAcgBpAGIAdQB0AGUAPQAiAHIAZQBhAGwAbAB5ACAAbABvAG4AZwAgAGYAbwByACAAdABoAGkAcwAgAGUAeABhAG0AcABsAGUAIgAgAAoAIAAgAGEAYwB0AHUAYQBsAGwAeQA9ACIAcwBvACAAbABvAG4AZwAgAGkAdAAgAHMAaABvAHUAbABkACAAYgByAGUAYQBrACAAYQBuAGQAIABiAGUAYwBvAG0AZQAgAG0AdQBsAHQAaQBsAGkAbgBlACIACgA%2BAHQAaQBuAHkAIABjAG8AbgB0AGUAbgB0ADwALwBkAGkAdgA%2BAAoACgA8ACEALQAtACAAQwBvAG4AdABlAG4AdAAgAGQAbwBlAHMAIABuAG8AdAAgAGIAcgBlAGEAawAgAC0ALQA%2BAAoAPABkAGkAdgAgAGEAdAB0AHIAPQAiAHQAaQBuAHkAIgAKAD4AdABpAG4AeQAgAGMAbwBuAHQAZQBuAHQAPAAvAGQAaQB2AD4A

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

closes #5026

## Test Plan

Added a snapshot test, and none of the other tests are affected.

### CODE REVIEW

File: crates/biome_html_formatter/src/html/auxiliary/element.rs [hunk 1]
```diff
@@ -130,10 +132,16 @@ impl FormatNodeRule<HtmlElement> for FormatHtmlElement {
...
+                        [
+                            // If the attribute group breaks, prettier always breaks the children as well.
+                            &if_group_breaks(&expanded_children).with_group_id(Some(attr_group_id)),
+                            // Otherwise, we can do whatever fits best for the children.
+                            &if_group_fits_on_line(&best_fitting![
+                                format_args![flat_children],
+                                format_args![expanded_children]
+                            ])
+                            .with_group_id(Some(attr_group_id))
+                        ]
```
Comment (dyc3) [inline crates/biome_html_formatter/src/html/auxiliary/element.rs:144]: I can't seem to figure out why this sometimes doesn't emit content. The ordering of these lines also appears to change the outcome.

**Review by ematipico — APPROVED** [review]
