### PR TITLE
fix(format/html): preserve block indentation if already present in some cases

### LINKED ISSUE #9099: 📝 HTML formatter collapses inline element content onto single line in Svelte files
### Environment information

When formatting Svelte files with experimentalFullSupportEnabled, the HTML formatter collapses inline element content (like <span> or custom components) with embedded expressions onto a single line, instead of keeping them on separate lines.
This affects both css and strict whitespace sensitivity modes, producing different but equally incorrect results.
Input
```
 <ul>
            <li>
              <div>
              
                {name}

              
              </div>
            </li>
        </ul>
```
Expected output (matches Prettier with htmlWhitespaceSensitivity: "css")
```
<ul>
  <li>
    <div>
      {name}
    </div>
  </li>
</ul>

```
Actual output
With whitespaceSensitivity: "css" (default):
```
<ul>
	<li>
		<div>{name}</div>
	</li>
</ul>
```
With whitespaceSensitivity: "strict":
```
<ul>
	<li> <div> {name} </div> </li>
</ul>
```

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### LINKED ISSUE #9450: 📝 Unnecessary line breaks with added spaces.
### Environment information

<details>

```bash

CLI:
  Version:                      2.4.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.12.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/11.7.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true
  HTML full support enabled:    true

Formatter:
  Format with errors:           unset
  Indent style:                 Tab
  Indent width:                 unset
  Line ending:                  LF
  Line width:                   120
  Attribute position:           unset
  Bracket spacing:              unset
  Includes:                     unset

JavaScript Formatter:
  Enabled:                      unset
  JSX quote style:              unset
  Quote properties:             unset
  Trailing commas:              ES5
  Semicolons:                   As needed
  Arrow parentheses:            As needed
  Bracket spacing:              true
  Bracket same line:            true
  Quote style:                  Single Quotes
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset

JSON Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset
  Expand lists:                 unset

CSS Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  unset

GraphQL Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0

```

</details>

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/2.4.6/schema.json",
	"vcs": {
		"enabled": true,
		"clientKind": "git",
		"useIgnoreFile": true
	},
	"files": {
		"ignoreUnknown": false
	},
	"formatter": {
		"enabled": true,
		"indentStyle": "tab",
		"lineWidth": 120,
		"lineEnding": "lf"
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true
		}
	},
	"html": {
		"formatter": { "enabled": true },
		"experimentalFullSupportEnabled": true
	},
	"javascript": {
		"formatter": {
			"arrowParentheses": "asNeeded",
			"bracketSameLine": true,
			"bracketSpacing": true,
			"quoteStyle": "single",
			"semicolons": "asNeeded",
			"trailingCommas": "es5"
		}
	},
	"assist": {
		"enabled": true,
		"actions": {
			"source": {
				"organizeImports": "on"
			}
		}
	},
	"overrides": [
		{
			"includes": ["**/*.svelte", "**/*.astro", "**/*.vue"],
			"linter": {
				"rules": {
					"style": {
						"useConst": "off",
						"useImportType": "off"
					},
					"correctness": {
						"noUnusedVariables": "off",
						"noUnusedImports": "off"
					}
				}
			}
		}
	]
}
```

### Playground link

https://biomejs.dev/playground/?code=PABzAGMAcgBpAHAAdAAgAGwAYQBuAGcAPQAiAHQAcwAiACAAcwBlAHQAdQBwAD4ACgBjAG8AbgBzAHQAIABzAHQAbwByAGUAIAA9ACAAdQBzAGUAQwBvAG4AZgBpAHIAbQBhAHQAaQBvAG4ATQBvAGQAYQBsAFMAdABvAHIAZQAoACkACgA8AC8AcwBjAHIAaQBwAHQAPgAKAAoAPAB0AGUAbQBwAGwAYQB0AGUAPgAKAAkAPABVAE0AbwBkAGEAbAAKAAkACQB2AC0AbQBvAGQAZQBsADoAbwBwAGUAbgA9ACIAcwB0AG8AcgBlAC4AaQBzAE8AcABlAG4AIgAKAAkACQA6AHQAaQB0AGwAZQA9ACIAcwB0AG8AcgBlAC4AbwBwAHQAaQBvAG4AcwAuAHQAaQB0AGwAZQAiAAoACQAJADoAZABpAHMAbQBpAHMAcwBpAGIAbABlAD0AIgBzAHQAbwByAGUALgBvAHAAdABpAG8AbgBzAC4AZABpAHMAbQBpAHMAcwBpAGIAbABlACIACgAJAAkAOgB1AGkAPQAiAHsAIABvAHYAZQByAGwAYQB5ADoAIAAnAHoALQAyADAAMAAnACwAIABjAG8AbgB0AGUAbgB0ADoAIAAnAHoALQAyADAAMQAnACAAfQAiAAoACQAJAEAAYwBsAG8AcwBlADoAcAByAGUAdgBlAG4AdAA9ACIAcwB0AG8AcgBlAC4AYwBhAG4AYwBlAGwAIgAKAAkAPgAKAAkACQA8AHQAZQBtAHAAbABhAHQAZQAgACMAYgBvAGQAeQA%2BAAoACQAJAAkAPABwAD4AewB7ACAAcwB0AG8AcgBlAC4AbwBwAHQAaQBvAG4AcwAuAHQAZQB4AHQAIAB9AH0APAAvAHAAPgAKAAkACQA8AC8AdABlAG0AcABsAGEAdABlAD4ACgAJAAkAPAB0AGUAbQBwAGwAYQB0AGUAIAAjAGYAbwBvAHQAZQByAD4ACgAJAAkACQA8AFUAQgB1AHQAdABvAG4AIAB2AC0AYgBpAG4AZAA9ACIAcwB0AG8AcgBlAC4AbwBwAHQAaQBvAG4AcwAuAGMAYQBuAGMAZQBsAEIAdQB0AHQAbwBuACIAIABAAGMAbABpAGMAawA9ACIAcwB0AG8AcgBlAC4AYwBhAG4AYwBlAGwAIgAgAC8APgAKAAkACQAJADwAVQBCAHUAdAB0AG8AbgAgAHYALQBiAGkAbgBkAD0AIgBzAHQAbwByAGUALgBvAHAAdABpAG8AbgBzAC4AYwBvAG4AZgBpAHIAbQBCAHUAdAB0AG8AbgAiACAAQABjAGwAaQBjAGsAPQAiAHMAdABvAHIAZQAuAGMAbwBuAGYAaQByAG0AIgAgAC8APgAKAAkACQA8AC8AdABlAG0AcABsAGEAdABlAD4ACgAJADwALwBVAE0AbwBkAGEAbAA%2BAAoAPAAvAHQAZQBtAHAAbABhAHQAZQA%2BAAoA&language=vue&ruleDomains.react=recommended

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

The change is pretty small, but the logic is pretty complex. However, this does result in a small improvement to our prettier snapshots.

generated by opus 4.6. with very heavy guidance

fixes #9099
fixes #9450

## Test Plan

snapshots

### CODE REVIEW

File: crates/biome_html_formatter/src/html/lists/element_list.rs [hunk 1]
```diff
@@ -313,6 +313,12 @@ struct ChildrenMeta {
     /// `true` if children contains a block-like element
     has_block_element: bool,
 
+    /// `true` if children contains any non-text child (element, expression, etc.)
+    has_non_text_child: bool,
+
+    /// `true` if children contains text (Word) content
+    has_word: bool,
```
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_html_formatter/src/html/lists/element_list.rs:321]: this one seems like it makes sense

File: crates/biome_html_formatter/src/html/auxiliary/element.rs [hunk 2]
```diff
@@ -175,8 +174,30 @@ impl FormatHtmlElement {
...
+        // This is distinct from `content_has_leading_whitespace` which also matches spaces.
+        let content_has_leading_newline =
+            opening_element.r_angle_token().ok().is_some_and(|tok| {
+                tok.trailing_trivia()
+                    .pieces()
+                    .any(|p| p.text().contains('\n'))
+            }) || children.syntax().first_token().is_some_and(|tok| {
+                tok.leading_trivia()
+                    .pieces()
+                    .any(|p| p.text().contains('\n'))
```
Comment (ematipico) [inline crates/biome_html_formatter/src/html/auxiliary/element.rs]: We have trivia for new lines. We shouldn't do these checks. If we do, something is wrong in the parser

File: crates/biome_html_formatter/src/html/lists/element_list.rs [hunk 3]
```diff
@@ -313,6 +313,12 @@ struct ChildrenMeta {
     /// `true` if children contains a block-like element
     has_block_element: bool,
 
+    /// `true` if children contains any non-text child (element, expression, etc.)
+    has_non_text_child: bool,
+
+    /// `true` if children contains text (Word) content
```
Comment (ematipico) [inline crates/biome_html_formatter/src/html/lists/element_list.rs:319]: Please document whether comments are part of "word"

File: crates/biome_html_formatter/tests/quick_test.rs [hunk 4]
```diff
@@ -28,6 +22,26 @@ fn quick_test() {
...
+                    }),
+                    ..Default::default()
+                }),
+                ..Default::default()
+            },
+            workspace_directory: None,
+            extended_configurations: Default::default(),
+            module_graph_resolution_kind: ModuleGraphResolutionKind::None,
+        })
+        .unwrap();
```
Comment (ematipico) [inline crates/biome_html_formatter/tests/quick_test.rs:43]: Was this needed?

File: crates/biome_html_formatter/tests/specs/html/svelte/html.svelte.snap [hunk 5]
```diff
@@ -18,7 +18,9 @@ info: svelte/html.svelte
 # Formatted
 
 ```svelte
-<article>{@html content}</article>
+<article>
+	{@html content}
+</article>
```
Comment (ematipico) [inline crates/biome_html_formatter/tests/specs/html/svelte/html.svelte.snap:23]: Is this correct?

File: crates/biome_html_formatter/tests/quick_test.rs (hunk 4 above)
Comment (dyc3) [reply crates/biome_html_formatter/tests/quick_test.rs:43]: Yes, the quick test was non functional for non html files otherwise

File: crates/biome_html_formatter/tests/specs/html/svelte/html.svelte.snap (hunk 5 above)
Comment (dyc3) [reply crates/biome_html_formatter/tests/specs/html/svelte/html.svelte.snap:23]: I believe so

https://biomejs.dev/playground/?tab=formatter&pane=Diagnostics&code=PABhAHIAdABpAGMAbABlAD4ACgAJAHsAQABoAHQAbQBsACAAYwBvAG4AdABlAG4AdAB9AAoAPAAvAGEAcgB0AGkAYwBsAGUAPgA%3D&language=svelte

File: crates/biome_html_formatter/src/html/auxiliary/opening_element.rs [hunk 6]
```diff
@@ -47,6 +48,35 @@ impl FormatRuleWithOptions<HtmlOpeningElement> for FormatHtmlOpeningElement {
...
+        }
+
+        // Check if the source had newlines around the dangling comments.
+        // If so, use hard_block_indent to preserve the multiline layout.
+        // This handles: <div>\n  <!-- comment -->\n</div>
+        let has_source_newline = node
+            .parent::<HtmlElement>()
+            .and_then(|el| el.closing_element().ok())
+            .and_then(|c| c.l_angle_token().ok())
+            .is_some_and(|tok| tok.has_leading_whitespace_or_newline());
```
[the remark this answers is not in the document]
Comment (ematipico) [reply crates/biome_html_formatter/src/html/auxiliary/opening_element.rs:69]: @dyc3 can you confirm whether this comment is valid?

File: crates/biome_html_formatter/src/html/lists/element_list.rs [hunk 7]
```diff
@@ -334,8 +341,12 @@ impl FormatHtmlElementList {
                     }
                 }
                 HtmlChild::Verbatim(_) => {
+                    meta.has_non_text_child = true;
                     block_element_count += 1;
```
[the remark this answers is not in the document]
Comment (ematipico) [reply crates/biome_html_formatter/src/html/lists/element_list.rs:346]: cc @dyc3

**Review by ematipico — APPROVED** [review]
Seems ok, however there are a couple of comments from coderabbit that might need some attention

File: crates/biome_html_formatter/src/html/auxiliary/opening_element.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_html_formatter/src/html/auxiliary/opening_element.rs:69]: no, its not valid
image

File: crates/biome_html_formatter/src/html/lists/element_list.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_html_formatter/src/html/lists/element_list.rs:346]: This is intentional behavior.
