### PR TITLE
fix(lint/noSelfAssign): don't panic

### LINKED ISSUE #548: 🐛 `processing panicked: internal error: entered unreachable code: you should map the correct references`
### Environment information

```block
Version: 1.3.0
macOS Sonoma 14.0
```

### What happened?

Run: 
```shell
git clone https://github.com/cubing/cubing.js && cd cubing.js
git checkout https://github.com/cubing/cubing.js
make lint
```

This fails with:

```
./src/cubing/puzzle-geometry/PuzzleGeometry.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: internal error: entered unreachable code: you should map the correct references
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  ```

### Expected result

No internal error?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #548

## Test Plan

regerssion test added.

### CODE REVIEW

File: crates/biome_js_analyze/src/analyzers/correctness/no_self_assign.rs [hunk 1]
```diff
@@ -713,7 +713,7 @@ impl TryFrom<(AnyNameLike, AnyNameLike)> for IdentifiersLike {
                 AnyNameLike::AnyJsLiteralExpression(right),
             ) => Ok(Self::Literal(left, right)),
 
-            _ => unreachable!("you should map the correct references"),
+            _ => Err(()),
```
Comment (ematipico) [inline crates/biome_js_analyze/src/analyzers/correctness/no_self_assign.rs:716]: the `unreachable` was there for a **reason**, which means we haven't mapped a specific type that we should

Comment (Conaclos) [reply crates/biome_js_analyze/src/analyzers/correctness/no_self_assign.rs:716]: I don't think so. Otherwise, why not implement `From`? Moreover, all branches of the match checks that the two values have the same type. This is a wrong assumption.

**Review by ematipico — APPROVED** [review]
Yeah, maybe using `unreachable` wasn't the safest choice. Let's ship it! 🚢
