### PR TITLE
fix(lsp): quick fix code actions

### LINKED ISSUE #2161: 🐛 VSCode ignore biome config linter.enable false
### VS Code version

1.87.2

### Extension version

v2.2.2

### Biome version

1.6.1

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

Screenshot 2024-03-22 at 15 51 48
LSP error even `"linter": { "enabled": false }` and if `"quickfix.biome": "explicit"`, biome adds `type`.

After adding `"useImportType": "off"` to biome config, formatting stopped.

### Steps to reproduce

Open [minimum reproduce repo](https://github.com/keidarcy/biome-vscode-extension-test) in VSCode.
Open index.ts, check error message, save file check formatting.

### Expected behavior

When `"linter": { "enabled": false }`, don't report linter issue.

### Does this issue occur when using the CLI directly?

No

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

- Quick fix shouldn't pull lint fix actions when the linter is disabled in the config.
- Also fix some errors in the changelog.

Closes #2161.

## Test Plan

I didn't figure out a way to add test cases for this fix. I tested it locally with the VSCode Extension and it works as expected.

### CODE REVIEW

File: crates/biome_lsp/src/handlers/analysis.rs [hunk 1]
```diff
@@ -149,11 +149,25 @@ pub(crate) fn code_actions(
...
             }
+            // Filter out quickfix.biome action when lint is not supported.
+            // But keep JavaScript parse rules because they're not configurable
+            // and should be considered as a parse action
+            if action.category.matches("quickfix.biome")
+                && action.rule_name.as_ref().map_or(true, |(_, name)| {
+                    name != "noDuplicatePrivateClassMembers"
+                        && name != "noInitializerWithDefinite"
+                        && name != "noSuperWithoutExtends"
+                })
```
Comment (Sec-ant) [inline crates/biome_lsp/src/handlers/analysis.rs:166]: To be honest, I don't know if we want to do this...

Comment (ematipico) [reply crates/biome_lsp/src/handlers/analysis.rs:166]: I don't think we should

Comment (Sec-ant) [reply crates/biome_lsp/src/handlers/analysis.rs]: Okay, I dropped them in d4f6acc

**Review by ematipico — APPROVED** [review]
