### PR TITLE
fix(js_formatter): fix handling ts references from array types in argument grouping

### LINKED ISSUE #1208: 📝 Biome differs from prettier for Array.reduce when second arg is long
### Environment information

```bash
CLI:
  Version:                      1.4.1-nightly.e087146
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.3.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
  "javascript": {
    "formatter": {
      "lineWidth": 100
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=100&indentStyle=space&bracketSameLine=true&code=dAB5AHAAZQAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwAgAD0AIABzAHQAcgBpAG4AZwA7AAoACgAvAC8AIABCAGkAbwBtAGUAIABmAG8AcgBtAGEAdABzACAAcgBlAGQAdQBjAGUAIAAiAGMAdQBkAGQAbABlAGQAIgA7ACAAcwB0AGEAcgB0AGkAbgBnACAAbwBuACAAdABoAGUAIABzAGEAbQBlACAAbABpAG4AZQAuAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABmAG8AbwBRAHUAeAAgAD0AIAAoAGQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBzADoAIABEAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAWwBdACkAOgAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0AIAA9AD4ACgAgACAAWwAuAC4ALgBkAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAcwBdAC4AcgBlAGQAdQBjAGUAKAAoAGEAYwBjACwAIABjAHUAcgByACkAIAA9AD4AIAB7AAoAIAAgACAAIABpAGYAIAAoAGMAdQByAHIAIAA9AD0APQAgACcAJwApACAAewAKACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAYQBjAGMAOwAKACAAIAAgACAAfQAKACAAIAAgACAAcgBlAHQAdQByAG4AIABbAC4ALgAuAGEAYwBjACwAIABjAHUAcgByAF0AOwAKACAAIAB9ACwAIABbAF0AIABhAHMAIABzAHQAcgBpAG4AZwBbAF0AKQA7AAoACgAvAC8AIABCAGkAbwBtAGUAIABmAG8AcgBtAGEAdABzACAAcgBlAGQAdQBjAGUAIABiAHkAIABvAHAAZQBuAGkAbgBnACAAYQAgAG4AZQB3ACAAbABpAG4AZQAuACAACgAvAC8AIABUAGgAZQAgAG8AbgBsAHkAIABjAGgAYQBuAGcAZQAgAGkAcwAgAHUAcwBpAG4AZwAgACIAYQBzACAARABlAGwAaQB2AGUAcgB5AFcAaQBuAGQAbwB3AFsAXQAiACAAaQBuAHMAdABlAGEAZAAgAG8AZgAgACIAYQBzACAAcwB0AHIAaQBuAGcAWwBdACIALgAKAGUAeABwAG8AcgB0ACAAYwBvAG4AcwB0ACAAZgBvAG8AUQB1AHgAMgAgAD0AIAAoAGQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBzADoAIABEAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAWwBdACkAOgAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0AIAA9AD4ACgAgACAAWwAuAC4ALgBkAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAcwBdAC4AcgBlAGQAdQBjAGUAKAAKACAAIAAgACAAKABhAGMAYwAsACAAYwB1AHIAcgApACAAPQA%2BACAAewAKACAAIAAgACAAIAAgAGkAZgAgACgAYwB1AHIAcgAgAD0APQA9ACAAJwAnACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAYQBjAGMAOwAKACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgAFsALgAuAC4AYQBjAGMALAAgAGMAdQByAHIAXQA7AAoAIAAgACAAIAB9ACwACgAgACAAIAAgAFsAXQAgAGEAcwAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0ALAAgAAoAIAAgACkAOwAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by faultyserver**
Fixes #1208 

## Summary

`is_simple_ts_type` was recently changed to support extracting types from nested arrays and generics, but in the case that an extracted array type was _not_ a generic _and_ was not a primitive type, it was falling back to the _original_ type that was passed in. That meant it would fail the simplicity check that happened afterward and cause functions to expand pre-emptively.

```
// This should collapse, because `MyCustomType` is simple, and only within one array type
foo(() => {
    foo
  },
  bar as MyCustomType[],
);
```

I also fixed a mistyped match against `TsObjectLiteralType`, which was meant to represent the `object` keyword, but that's actually `TsNonPrimitiveLiteralType`.

## Test Plan

Added a whole set of tests around simple arguments for TS expressions to cover both of these changes, as well as all of the nesting extraction from a previous PR.

### CODE REVIEW

File: crates/biome_js_formatter/src/js/expressions/call_arguments.rs [hunk 1]
```diff
@@ -902,14 +902,16 @@ fn is_simple_ts_type(ty: &AnyTsType) -> bool {
     //     Foo<number, string> => Foo<number, string>
     let extracted_generic_type = match &extracted_array_type {
         Some(AnyTsType::TsReferenceType(generic)) => {
-            generic.type_arguments().and_then(|type_arguments| {
+            if let Some(type_arguments) = generic.type_arguments() {
```
Comment (faultyserver) [inline crates/biome_js_formatter/src/js/expressions/call_arguments.rs:905]: The issue was that this `and_then` would return `None` if the `type_arguments` was `None`, but we actually want it to return the `extracted_array_type`.

This could possibly be written a different way, but I think it's clear enough as is, and definitely avoids this implicit issue now.

**Review by ematipico — APPROVED** [review]
