### PR TITLE
fix(auto_search): `biome.jsonc` resolution

### LINKED ISSUE #2008: 🐛 biome.jsonc is not being used.
### Environment information

```block
// biome.jsonc -- disable formatter, linter, and import-organizer for demonstration purposes
{
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "formatter": {
        "enabled": false
    },
    "linter": {
        "enabled": false
    },
    "organizeImports": {
        "enabled": false
    }
}


CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

`biome` does not use the `biome.jsonc` file; instead, it uses the defaults.

### Expected result

Using the provided `biome.jsonc` file in the "Environment Info" section, `biome check .` should produce output similar to the following:

```
Checked 0 files in 71ms. No fixes needed.
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No files were processed in the specified paths.
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

I refactored the `auto_search` function in `crates/biome_fs/src/fs.rs` a bit. It was trying to search in parent directories first and then alternatives (`biome.jsonc`). This approach led to an issue where the mutable `file_path` variable was erroneously set to the root path `/` upon searching for the next alternative, thereby causing an incorrect `file_directory_path`.

I switched the loops so it will search alternatives first and then traverse up to parent directories. Additionally, I have made adjustments to error handling to align with this new search logic. However, I am uncertain if this modification aligns with the expected behavior and would greatly appreciate confirmation.

Fixes #2008.

## Test Plan

I tested it locally by running `cargo build -p biome_cli` first and tested that binary in another folder with a `biome.jsonc` file by running the `rage` command. It is now able to correctly resolve the `biome.jsonc` config file.

I attempted to add a test in `crates/biome_cli/tests/commands/rage.rs` but I couldn't figure out how to use absolute file paths and change `cwd` in a memory file system. So I included only a draft of the intended test and am seeking assistance to properly implement this test.

### CODE REVIEW

File: crates/biome_cli/tests/commands/rage.rs [hunk 1]
```diff
@@ -83,6 +83,41 @@ fn with_configuration() {
...
+  }
+}"#,
+    );
+
+    // TODO: but how to cd into dir and run rage?
+    let result = run_rage(
+        DynRef::Borrowed(&mut fs),
+        &mut console,
+        Args::from([("rage")].as_slice()),
+    );
```
Comment (ematipico) [inline crates/biome_cli/tests/commands/rage.rs:108]: You can use `--config-path` to tell Biome to load the configuration from a different path. In case it should be `--config-path=/dir`.

The problem is that `auto_search` won't kick in, but I suppose it's fine, right? Alt least for the rage command

Comment (Sec-ant) [reply crates/biome_cli/tests/commands/rage.rs:108]: I maybe used an ambiguous name for the test. But my initial intention to add this test is to check whether `auto_search` works correctly or not 😅. Is this achievable?

Comment (ematipico) [reply crates/biome_cli/tests/commands/rage.rs:108]: Oh, I see. I think just setting the path `Path::new("biome.jsonc")` is sufficient for the current test case. You also tested it locally, I think it's more than enough :)

Comment (Sec-ant) [reply crates/biome_cli/tests/commands/rage.rs]: This is addressed in cdbedb3. Should I be worried about the codspeed report?

**Review by ematipico — APPROVED** [review]
