### PR TITLE
fix(lint): mark whole fragment as incorrect if without key 

### LINKED ISSUE #5490: 💅 `useJsxKeyInIterable` does not recognize unnamed fragment
### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.4.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  suspicious/noClassAssign
  style/useImportType
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  suspicious/useNamespaceKeyword
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noAssignInExpressions
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  suspicious/noDuplicateParameters
  suspicious/noDuplicateSelectorsKeyframeBlock
  correctness/noUnknownProperty
  style/useTemplate
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  a11y/noAutofocus
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noConstEnum
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  a11y/noLabelWithoutControl
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noImplicitAnyLet
  suspicious/noFallthroughSwitchClause
  suspicious/noUnsafeDeclarationMerging
  complexity/noUselessThisAlias
  correctness/noUnreachable
  a11y/useKeyWithClickEvents
  suspicious/noDuplicateObjectKeys
  complexity/noThisInStatic
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  a11y/useValidAnchor
  complexity/useRegexLiterals
  correctness/noSelfAssign
  correctness/noInvalidBuiltinInstantiation
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  correctness/noInvalidDirectionInLinearGradient
  suspicious/noImportantInKeyframe
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  complexity/noStaticOnlyClass
  style/useWhile
  suspicious/noConsole
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  style/useNumericLiterals
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  suspicious/noImportAssign
  suspicious/noLabelVar
  correctness/noGlobalObjectCalls
  suspicious/useDefaultSwitchClauseLast
  correctness/noUnknownUnit
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  correctness/noVoidElementsWithChildren
  suspicious/noPrototypeBuiltins
  style/useAsConstAssertion
  correctness/useJsxKeyInIterable
  style/useExportType
  complexity/noUselessLoneBlockStatements
  style/noArguments
  suspicious/noDebugger
  a11y/useValidAriaValues
  suspicious/noCommentText
  a11y/useFocusableInteractive
  correctness/noUnmatchableAnbSelector
  suspicious/noGlobalAssign
  suspicious/noDuplicateJsxProps
  suspicious/noMisleadingInstantiator
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  security/noDangerouslySetInnerHtmlWithChildren
  a11y/useKeyWithMouseEvents
  suspicious/noExtraNonNullAssertion
  suspicious/noShorthandPropertyOverrides
  correctness/noRenderReturnValue
  correctness/useExhaustiveDependencies
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  correctness/noUnusedVariables
  correctness/useHookAtTopLevel
  style/useConst
  suspicious/noGlobalIsFinite
  suspicious/noAsyncPromiseExecutor
  suspicious/noDuplicateFontNames
  suspicious/noSelfCompare
  suspicious/noThenProperty
  security/noDangerouslySetInnerHtml
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  suspicious/noArrayIndexKey
  complexity/noWith
  suspicious/useGetterReturn
  suspicious/noDuplicateClassMembers
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  correctness/noUnknownFunction
  correctness/noInvalidPositionAtImportRule
  suspicious/noConfusingLabels
  suspicious/noConfusingVoidType
  suspicious/noFocusedTests
  a11y/useButtonType
  a11y/useSemanticElements
  a11y/noAriaUnsupportedElements
  correctness/noInvalidGridAreas
  correctness/noFlatMapIdentity
  suspicious/noSuspiciousSemicolonInJsx
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useGenericFontNames
  correctness/noUnknownMediaFeatureName
  a11y/useAnchorContent
  complexity/noUselessRename
  complexity/noUselessConstructor
  a11y/noAccessKey
  correctness/noUnusedFunctionParameters
  style/noUnusedTemplateLiteral
  complexity/noUselessSwitchCase
  style/useExponentiationOperator
  style/useSingleVarDeclarator
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/noDuplicateAtImportRules
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  suspicious/noMisrefactoredShorthandAssign
  suspicious/noEmptyBlock
  complexity/noForEach
  correctness/noUnusedImports
  suspicious/noFunctionAssign

Workspace:
  Open Documents:               0
```

### Rule name

useJsxKeyInIterable

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=LwAvACAAaQBuAGMAbwByAHIAZQBjAHQAbAB5ACAAdwBhAHIAbgBzACAAbwBuACAAPABwAD4ACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAEMAbwBtAHAAbwBuAGUAbgB0AEEAIAA9ACAAKAApACAAPQA%2BACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAcwBlAGMAdABpAG8AbgA%2BAAoAIAAgACAAIAAgACAAewBbADEALAAgADIALAAgADMAXQAuAG0AYQBwACgAeAAgAD0APgAgACgACgAgACAAIAAgACAAIAA8AD4ACgAgACAAIAAgACAAIAAgACAAPABwAD4AewB4AH0APAAvAHAAPgAKACAAIAAgACAAIAAgADwALwA%2BAAoAIAAgACAAIAAgACAAKQApAH0ACgAgACAAIAAgADwALwBzAGUAYwB0AGkAbwBuAD4ACgAgACAAKQAKAH0ACgAKAC8ALwAgAGMAbwByAHIAZQBjAHQAbAB5ACAAdwBhAHIAbgBzACAAbwBuACAAZgByAGEAZwBtAGUAbgB0AAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABDAG8AbQBwAG8AbgBlAG4AdABCACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AHMAZQBjAHQAaQBvAG4APgAKACAAIAAgACAAIAAgAHsAWwAxACwAIAAyACwAIAAzAF0ALgBtAGEAcAAoAHgAIAA9AD4AIAAoAAoAIAAgACAAIAAgACAAPABSAGUAYQBjAHQALgBGAHIAYQBnAG0AZQBuAHQAPgAKACAAIAAgACAAIAAgACAAIAA8AHAAIABrAGUAeQA9AHsAeAB9AD4AewB4AH0APAAvAHAAPgAKACAAIAAgACAAIAAgADwALwBSAGUAYQBjAHQALgBGAHIAYQBnAG0AZQBuAHQAPgAKACAAIAAgACAAIAAgACkAKQB9AAoAIAAgACAAIAA8AC8AcwBlAGMAdABpAG8AbgA%2BAAoAIAAgACkACgB9AA%3D%3D

### Expected result

The rule triggers incorrectly when just using `<></>` for a fragment. Then the first descendant is the one getting the error.

But when using `<React.Fragment></React.Fragment>` the error is shown correctly for the fragment.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by DerTimonius**
## Summary

This PR fixes an issue with the `useJsxKeyInIterable` that did not match the original ESLint plugin: when a fragment does not have a key in a `.map` (or similar) call, it's children are marked as incorrect, not the whole fragment.

Looking more closely at the [original rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-key.md#checkfragmentshorthand-default-false) I also noticed that `checkShorthandFragment` is an opt-in check.
Therefore I added the related option.

Closes #5490

## Test Plan

Adapted the snapshots, removed invalid code that was found in `valid.jsx` (for example: even if all children of a fragment would have keys, the fragment is still marked as incorrect in the original rule), and added an additional snapshot with the option to check shorthand fragments.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs [hunk 1]
```diff
@@ -36,6 +38,16 @@ declare_lint_rule! {
     /// data.map((x) => <Hello key={x.id}>{x}</Hello>);
     /// ```
     ///
+    /// ## Options
+    ///
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:42]: Can you please **explain** the option to our users? Also, you can add an example that **uses** these options: https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#using-rule-options

File: crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs [hunk 2]
```diff
@@ -56,19 +68,29 @@ declare_node_union! {
     pub ReactComponentExpression = JsxTagExpression | JsCallExpression
 }
 
+#[derive(Debug, Default, Clone, Serialize, Deserialize, Deserializable, Eq, PartialEq)]
+#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
+#[serde(rename_all = "camelCase", deny_unknown_fields, default)]
+pub struct UseJsxKeyInIterableOptions {
+    check_shorthand_fragments: bool,
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:75]: These options are exposed to our users via the JSON schema, so we need to provide documentation via doc comments (`/// It checks...`)

**Review by ematipico — CHANGES_REQUESTED** [review]

File: crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs [hunk 3]
```diff
@@ -36,6 +38,27 @@ declare_lint_rule! {
...
+    ///
+    /// React fragments can not only be created with `<React.Fragment>`, but also with shorthand
+    /// fragments (`<></>`). To also check if those require a key, pass `true` to this option.
+    ///
+    /// #### Usage example
+    ///
+    /// ```jsx,expect_diagnostic,use_options
+    /// data.map((x) => <>{x}</>);
+    /// ```
+    ///
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:61]:
```suggestion
    /// ## Options
    ///
    /// ### checkShorthandFragments
    ///
    /// React fragments can not only be created with `<React.Fragment>`, but also with shorthand
    /// fragments (`<></>`). To also check if those require a key, pass `true` to this option.
    ///
    /// ```json,options
    /// {
    ///     "options": {
    ///         "checkShorthandFragments": true
    ///     }
    /// }
    /// ```    
    /// ```jsx,expect_diagnostic,use_options
    /// data.map((x) => <>{x}</>);
    /// ```
    ///
```

**Review by ematipico — APPROVED** [review]
Thank you!
