### PR TITLE
fix(core): computed scan kind

### LINKED ISSUE #6357: 🐛 Monorepo - disable at root level, enable at child level
### Environment information

```block
biome rage of root folder:

CLI:
  Version:                      HEAD-be9076b
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            false
  Linter enabled:               false
  Assist enabled:               false
  VCS enabled:                  false

Workspace:
  Open Documents:               0


biome rage of subfolder with own biome.jsonc

CLI:
  Version:                      HEAD-be9076b
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /Users/.../.../biome.jsonc
  Formatter enabled:            false
  Linter enabled:               false
  Assist enabled:               false
  VCS enabled:                  false

Workspace:
  Open Documents:               0
```

### What happened?

**Description**

We manage a large monorepo and are planning a gradual migration to Biome. Our goal is to set up default Biome configurations at the root level, while initially disabling all Biome features globally. This will allow us to progressively migrate individual sub-projects (each represented by a subdirectory) at our own pace.

As part of this approach, we intend to enable and customize Biome features within each subdirectory’s biome.jsonc file as we migrate them. This should allow us to tailor the configuration for each sub-project while keeping the rest of the monorepo unaffected.

**Problem Encountered**

However, we’ve encountered a significant issue: once a feature is disabled at the root level, it cannot be re-enabled in a subdirectory’s configuration. This limitation prevents us from incrementally enabling Biome features for sub-projects without affecting the entire monorepo.

The biome.jsonc in the root folder looks like this:
```
{
    "files": {
        "ignoreUnknown": false
    },
    "assist": {
        "enabled": false
    },
    "vcs": {
        "enabled": false,
        "clientKind": "git",
        "useIgnoreFile": true,
        "defaultBranch": "develop"
    },
    "formatter": {
        "enabled": false,
        "indentStyle": "space",
        "indentWidth": 4
    },
    "linter": {
        "enabled": false,
        "rules": {
            "recommended": true,
            "style": {
                "noParameterAssign": "off"
            }
        }
    },
    "javascript": {
        "formatter": {
            "quoteStyle": "single"
        }
    }
}
```

The biome.jsonc in the subfolder looks like this:
```
{
    "root": false,
    "extends": "//",
    "assist": {
        "enabled": true
    },
    "vcs": {
        "enabled": true,
        "clientKind": "git"
    },
    "formatter": {
        "enabled": true
    },
    "linter": {
        "enabled": true,
        "rules": {}
    }
}
```

### Expected result

When configuring Biome in a monorepo setup, we expect that features disabled at the root level can be selectively re-enabled and customized in the configuration files of individual subdirectories (sub-projects). This would allow us to:
	•	Apply a default, minimal configuration globally at the root.
	•	Gradually migrate each sub-project by enabling and adjusting Biome features in their respective biome.jsonc files.
	•	Maintain isolated configuration changes, so enabling features in a subdirectory does not affect unrelated parts of the repository.
	•	Seamlessly support incremental adoption of Biome across the monorepo, without requiring all sub-projects to migrate at once.

This approach would provide flexibility and control over the migration process, making it possible to adopt Biome in a phased, non-disruptive manner.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes #6357 

There two bugs:
- the `Bool` type had an incorrect implementation of the `Merge` trait
- the computed `scan_kind` wasn't correct in case the top level linter is disabled

I also removed the code of the derive `Partial`, which we don't use anymore, and I forgot to delete.

## Test Plan

Added new tests

### CODE REVIEW

File: crates/biome_cli/src/commands/mod.rs [hunk 1]
```diff
@@ -898,9 +898,21 @@ pub(crate) trait CommandRunner: Sized {
...
-                ScanKind::KnownFiles
+        let scan_kind = get_forced_scan_kind(&execution, &configuration).unwrap_or({
+            if open_project_result.scan_kind == ScanKind::None {
+                if configuration.use_ignore_file()
+                    // The linter might be enabled in some nested project, and the linter
+                    // is the only feature that might require project features.
+                    //
+                    // We decide to scan only known files on purpose, even though we don't know
+                    // if nested configuration files enable project-wide rules.
+                    // In this case, the use must run Biome from the package, and not from the root folder.
```
Comment (arendjr) [inline crates/biome_cli/src/commands/mod.rs]: I guess this may need to be documented, although I wouldn't know where :sweat_smile: 

```suggestion
                    // In this case, the user must run Biome from the package, and not from the root folder.
```

File: crates/biome_cli/src/commands/scan_kind.rs [hunk 2]
```diff
@@ -11,13 +12,26 @@ use biome_service::workspace::ScanKind;
...
+pub(crate) fn get_forced_scan_kind(
+    execution: &Execution,
+    configuration: &Configuration,
+) -> Option<ScanKind> {
+    // We want to keep the `match`, so if we add new traversal modes,
+    // the compiler will error and we will need to handle the new variant
+    match execution.traversal_mode() {
+        TraversalMode::Migrate { .. } => Some(ScanKind::KnownFiles),
+        TraversalMode::Format { .. } | TraversalMode::Search { .. } => {
+            if configuration.use_ignore_file() || configuration.is_root() {
```
Comment (arendjr) [inline crates/biome_cli/src/commands/scan_kind.rs]: I thought this is only called from the root configuration? That would make the `is_root()` check redundant.

File: crates/biome_cli/src/commands/scan_kind.rs [hunk 3]
```diff
@@ -28,7 +42,7 @@ mod tests {
     use biome_configuration::analyzer::RuleSelector;
 
     #[test]
-    fn should_return_none_for_lint_command() {
+    fn should_return_known_files_for_lint_command() {
```
Comment (arendjr) [inline crates/biome_cli/src/commands/scan_kind.rs]: It seems this new name doesn't match the actual expectation... Maybe you forgot to revert it?

File: crates/biome_cli/src/commands/mod.rs (hunk 1 above)
Comment (ematipico) [reply crates/biome_cli/src/commands/mod.rs]: Yes, I mentioned that in the original issue.

File: crates/biome_cli/src/commands/scan_kind.rs (hunk 2 above)
Comment (ematipico) [reply crates/biome_cli/src/commands/scan_kind.rs]: Actually, now that you mention it, we shouldn't check `is_root`. This can be called from a nested package, and it would return incorrect information. Will address that

File: crates/biome_cli/tests/snapshots/main_cases_monorepo/should_not_lint_when_root_is_disabled_but_nested_is_enabled.snap [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+  - <TEMP_DIR>/should_not_lint_when_root_is_disabled_but_nested_is_enabled
+  
+
+
+```
+
+# Emitted Messages
+
+```block
+Checked 0 files in <TIME>. No fixes applied.
```
Comment (arendjr) [inline crates/biome_cli/tests/snapshots/main_cases_monorepo/should_not_lint_when_root_is_disabled_but_nested_is_enabled.snap]: I think you may have overlooked something here.

File: crates/biome_cli/src/commands/scan_kind.rs [hunk 5]
```diff
@@ -41,19 +49,21 @@ mod tests {
             skip_parse_errors: false,
         });
 
-        assert_eq!(get_forced_scan_kind(&execution), None);
+        assert_eq!(get_forced_scan_kind(&execution,), None);
     }
 
     #[test]
-    fn should_return_known_files_for_format_command() {
+    fn should_return_none_for_format_command() {
```
Comment (arendjr) [inline crates/biome_cli/src/commands/scan_kind.rs]: The name of the test still doesn't align with the assertion.

**Review by arendjr — CHANGES_REQUESTED** [review]

File: crates/biome_service/src/configuration.rs [hunk 6]
```diff
@@ -768,7 +768,7 @@ impl<'a> ProjectScanComputer<'a> {
         } else {
             // There's no need to scan further known files if the VCS isn't enabled
             if !self.configuration.use_ignore_file() {
-                ScanKind::None
+                ScanKind::NoScanner
```
Comment (arendjr) [inline crates/biome_service/src/configuration.rs:771]: Meh :p
