### PR TITLE
fix(lint): deduplicate missing dependencies in useExhaustiveDependencies

### LINKED ISSUE #6278: `useExhaustiveDependencies` adds dependencies multiple times
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v22.11.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useExhaustiveDependencies
    correctness/useHookAtTopLevel
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noDescendingSpecificity
    style/noInferrableTypes
    style/noParameterAssign
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useConsistentArrayType
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useEnumInitializers
    style/useExponentiationOperator
    style/useExportType
    style/useForOf
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConsole
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyBlockStatements
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useAwait
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useNamespaceKeyword

Workspace:
  Open Documents:               0
```

### Rule name

useExhaustiveDependencies

### How to reproduce

`useExhaustiveDependencies` adds dependencies multiple times if the `useCallback` function uses the missing function more than once:

Consider this function and notice that `setIsFactoryWarrantyDeviating` is being called twice whilst not being referenced in the dependencies list.

```typescript
  const fn = useCallback(
    (event) => {
      if (oldDate && event.value) {
        myFn(
          getDateOnlyISOString(event.value) !== getDateOnlyISOString(oldDate)
        );

        return;
      }

      myFn(false);
    },
    [oldDate]
  );
```

Using the quick fix results in this:
```typescript
  const fn = useCallback(
    (event) => {
      if (oldDate && event.value) {
        myFn(
          getDateOnlyISOString(event.value) !== getDateOnlyISOString(oldDate)
        );

        return;
      }

      myFn(false);
    },
    [oldDate, myFn, myFn]
  );
```

### Reproduction
https://github.com/Arnagos/biome-repro-1749631009924

### Expected behavior

`myFn` only gets added to the dependencies once.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by siketyan**
## Summary

Fixes #6278 

The missing dependency was duplicated in the code fix if it is used multiple times in the hook. A single diagnostic of the rule is only for **one** dependency to add, so we should add only one instance of it.

I also improved the diagnostics slightly.

## Test Plan

Snapshot updated.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs [hunk 1]
```diff
@@ -974,22 +974,18 @@ impl Rule for UseExhaustiveDependencies {
                 let mut diag = RuleDiagnostic::new(
                     rule_category!(),
                     function_name_range,
-                    markup! {"This hook does not specify all of its dependencies: "{capture_text.as_ref()}""},
```
Comment (siketyan) [inline crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:977]: A diagnostic tells about only one dependency in the hook, so "all of" is unnecessary/misleading.

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs [hunk 2]
```diff
@@ -974,22 +974,18 @@ impl Rule for UseExhaustiveDependencies {
...
+                        "This dependency is being used here, but not specified in the hook dependency list.",
                     );
                 }
 
                 if dependencies_array.elements().len() == 0 {
-                    diag = if captures_range.len() == 1 {
-                        diag.note("Either include it or remove the dependency array")
-                    } else {
-                        diag.note("Either include them or remove the dependency array")
-                    }
```
Comment (siketyan) [inline crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:992]: Here "captures" is where the dependency is used, but we only need to add the used dependency itself. So what we should add here is always only one thing.

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs [hunk 3]
```diff
@@ -1077,27 +1073,29 @@ impl Rule for UseExhaustiveDependencies {
 
         let message = match state {
             Fix::AddDependency {
-                captures: (_, nodes),
+                captures: (_, captures),
                 dependencies_array,
                 ..
             } => {
+                let new_elements = captures.first().into_iter().filter_map(|node| {
```
Comment (siketyan) [inline crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:1080]: This part is the fix for #6278, which I added `.first()` to pick only one instance of captures.

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs (hunk 1 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:977]: I think this may be a grammar thing, but I think “all of” was the correct wording here. After all, the hook invocation _does_ specify its dependencies, just not all of them, and we’ll point out the missing ones. I find the new wording slightly less clear than the old.

Maybe you were thinking about “does not specify **any** of its dependencies”? That would be misleading indeed.

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs [hunk 4]
```diff
@@ -974,22 +974,18 @@ impl Rule for UseExhaustiveDependencies {
...
                     function_name_range,
-                    markup! {"This hook does not specify all of its dependencies: "{capture_text.as_ref()}""},
+                    markup! {"This hook does not specify its dependencies: "<Emphasis>{capture_text.as_ref()}</Emphasis>""},
                 );
 
                 for range in captures_range {
                     diag = diag.detail(
                         range.text_trimmed_range(),
-                        "This dependency is not specified in the hook dependency list.",
+                        "This dependency is being used here, but not specified in the hook dependency list.",
```
Comment (arendjr) [inline crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs]:
```suggestion
                        "This dependency is being used here, but is not specified in the hook dependency list.",
```

**Review by arendjr — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs (hunk 1 above)
Comment (siketyan) [reply crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:977]: In the following situation:

```js
useEffect(() => {
  if (foo) {
    bar();
  }
}, []);
```

Two diagnostics will be emitted:

- This hook does not specify all of its dependencies: foo
- This hook does not specify all of its dependencies: bar

I think we expect all required dependencies are listed after "all of its dependencies:" _in a single diagnostic_, but it's not yet supported. Indeed just removing "all of" seems incorrect, maybe "its dependenc**y**:" is much better?

The diagnostics will be:

- This hook does not specify its dependency: foo
- This hook does not specify its dependency: bar

**Review by ematipico — APPROVED** [review]
Remember to add a changeset for the fix. Feel free to merge it after we've done with the release (still going on)

**Comment by siketyan** [comment]
I thought I can skip a changeset as the code fix was introduced in v2, but I was too late 😓

**Comment by ematipico** [comment]
Ah sorry, I didn't know that, it wasn't explained in the PR. Regardless, let's try to keep the `main` clean just in case

File: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs (hunk 1 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:977]: Let's try to make it a smooth sentence then: "This hook does not specify its dependency on **foo**".
