### PR TITLE
fix(html/astro): keep a blank after the frontmatter

### LINKED ISSUE #8038: 📎 Keep a blank line after the frontmatter section in Astro files
### Description

As discussed in #8033, it might be better to keep a blank line after the frontmatter section.

### PR DESCRIPTION
**Pull request by PFiS1737**
## Summary

> No AI

Biome now keeps a blank line after the frontmatter section in Astro files.

Fix #8038 

## Test Plan

I added some blank lines to the `full_support` test case to ensure that multiple blank lines are formatted into a single one.

Note that some snapshot files were removed — I guess this means some leftover differences with Prettier have been eliminated. 🎉

### CODE REVIEW

File: crates/biome_html_formatter/src/html/auxiliary/root.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ impl FormatNodeRule<HtmlRoot> for FormatHtmlRoot {
         }
 
         if let Some(frontmatter) = frontmatter {
-            write!(f, [frontmatter.format(), hard_line_break()])?;
+            write!(f, [frontmatter.format(), hard_line_break(), empty_line()])?;
```
Comment (dyc3) [inline crates/biome_html_formatter/src/html/auxiliary/root.rs]: I think that this becomes 3 line breaks, which gets compressed into 2 which produces the empty line. Try this, it should work the same.

```suggestion
            write!(f, [frontmatter.format(), empty_line()])?;
```

**Review by dyc3 — APPROVED** [review]
thank you!
