### PR TITLE
fix(css_parser): add active-view-transition-type() (#6973)

### LINKED ISSUE #6973: 🐛 [css] Parser breaks on `active-view-transition-type()` pseudo-class with a user-defined identifier
### Environment information

```block
CLI:
  Version:                      2.1.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v18.18.2
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/8.10.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Workspace:
  Open Documents:               0
```

### What happened?

Using `active-view-transition-type()` with a custom identifier breaks the parser. Reproduction in [playground](https://biomejs.dev/playground/?code=aAB0AG0AbAA6AGEAYwB0AGkAdgBlAC0AdgBpAGUAdwAtAHQAcgBhAG4AcwBpAHQAaQBvAG4ALQB0AHkAcABlACgAYgBhAGMAawB3AGEAcgBkAHMAKQAgAHsACgAgACAAJgA6ADoAdgBpAGUAdwAtAHQAcgBhAG4AcwBpAHQAaQBvAG4ALQBvAGwAZAAoAGcAcgBvAHUAcAApACAAewAKACAAIAAgACAAYgBvAHgALQBzAGgAYQBkAG8AdwA6ACAAdgBhAHIAKAAtAC0AbgBlAHMAdABlAGQALQBjAGEAbgB2AGEAcwAtAHMAaABhAGQAbwB3ACkAOwAKACAAIAB9AAoAfQAKAAoAaAB0AG0AbAA6AGEAYwB0AGkAdgBlAC0AdgBpAGUAdwAtAHQAcgBhAG4AcwBpAHQAaQBvAG4ALQB0AHkAcABlACgAZgBvAHIAdwBhAHIAZABzACkAIAB7AAoAIAAgACYAOgA6AHYAaQBlAHcALQB0AHIAYQBuAHMAaQB0AGkAbwBuAC0AbgBlAHcAKABnAHIAbwB1AHAAKQAgAHsACgAgACAAIAAgAGIAbwB4AC0AcwBoAGEAZABvAHcAOgAgAHYAYQByACgALQAtAG4AZQBzAHQAZQBkAC0AYwBhAG4AdgBhAHMALQBzAGgAYQBkAG8AdwApADsACgAgACAAfQAKAH0A&language=css).

Input:
```css
html:active-view-transition-type(forwards) {
  &::view-transition-new(group) {
    box-shadow: var(--nested-canvas-shadow);
  }
}
```

Result:
```
main.css:7:34 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ expected `,` but instead found `forwards`
  
    5 │ }
    6 │ 
  > 7 │ html:active-view-transition-type(forwards) {
      │                                  ^^^^^^^^
    8 │   &::view-transition-new(group) {
    9 │     box-shadow: var(--nested-canvas-shadow);
```

According to the W3C spec [0], the `active-view-transition-type()` pseudo-class accepts a custom user-defined identifier where the parameter (`forwards` in this case) should be treated as valid [1].

[0] https://www.w3.org/TR/css-view-transitions-2/#the-active-view-transition-type-pseudo
[1] https://www.w3.org/TR/css-values-4/#identifier-value

### Expected result

Parser should not throw an error.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by denbezrukov**
## Summary

- Fix #6973

- Replace tokens with CssIdentifiers in the CSS grammar for pseudo-selectors to ensure consistency and provide a more convenient API.

## Test Plan

new snapshorts

### CODE REVIEW

File: crates/biome_css_semantic/src/semantic_model/specificity.rs [hunk 1]
```diff
@@ -53,9 +53,9 @@ fn evaluate_any_pseudo_class(class: &AnyCssPseudoClass) -> Specificity {
         AnyCssPseudoClass::CssPseudoClassFunctionNth(_) => CLASS_SPECIFICITY,
         AnyCssPseudoClass::CssPseudoClassFunctionRelativeSelectorList(selector_list) => {
             if let Some(base) = selector_list
-                .name_token()
+                .name()
                 .ok()
-                .and_then(|name| evaluate_pseudo_function_selector(name.text()))
+                .and_then(|name| evaluate_pseudo_function_selector(&name.to_trimmed_text()))
```
Comment (dyc3) [inline crates/biome_css_semantic/src/semantic_model/specificity.rs]: nit: `to_trimmed_text()` _can_ allocate a string.  I don't think it matters that much for this PR though, because `name()` consists of only 1 token, which is the case where this doesn't allocate memory. IMO, it would be better to chain another `and_then` to get the `&str` or `TokenText` of the token to prevent future changes accidentally causing this to allocate.

**Review by dyc3 — APPROVED** [review]

File: crates/biome_css_semantic/src/semantic_model/specificity.rs (hunk 1 above)
Comment (denbezrukov) [reply crates/biome_css_semantic/src/semantic_model/specificity.rs]: Thank you!
Indeed, it's a good suggestion, I totally agree!

**Review by ematipico — APPROVED** [review]
