### PR TITLE
fix(assist): skip sorting specifiers if it contains any bogus nodes

### LINKED ISSUE #5710: 🐛 Parser crashes
### Environment information

```block
main
```

### What happened?

The [following code](https://next.biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAaQBuAGoAZQBjAHQALAAgAEkAbgBqAGUAYwB0AGEAYgBsAGUALAAgAGkAbgBqAGUAYwB0ACAAfQAgAGYAcgBvAG0AIAAnAEAAYQBuAGcAdQBsAGEAcgAvAGMAbwByAGUAJwA7AA%3D%3D&ruleDomains.solid=recommended) should raise a parse diagnostic, but it doesnt: 

```js
import { inject, Injectable, inject } from '@angular/core';
```

As you notice, the playground is from the **beta**. The current version of Biome, instead, raises a diagnostic correctly: https://biomejs.dev/playground/?attributePosition=multiline&code=aQBtAHAAbwByAHQAIAB7ACAAaQBuAGoAZQBjAHQALAAgAEkAbgBqAGUAYwB0AGEAYgBsAGUALAAgAGkAbgBqAGUAYwB0ACAAfQAgAGYAcgBvAG0AIAAnAEAAYQBuAGcAdQBsAGEAcgAvAGMAbwByAGUAJwA7AA%3D%3D

### Expected result

It should raise a diagnostic, or not crash and emit a bogus CST.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by siketyan**
## Summary

Fixes #5710 

The `organizeImports` assist assumes the import is unsorted even if there are any bogus nodes. This causes an infinite loop when Biome apply code actions in multipass. Assuming the import is already sorted if any bogus nodes there so we no longer get stuck from the loop.

## Test Plan

Added a snapshot test to ensure any diagnostics won't be emitted for the bogus code.

### CODE REVIEW

**Review by Conaclos — APPROVED** [review]
Oh, thanks! A little mistake on my side.

File: crates/biome_js_analyze/tests/specs/source/organizeImports/issue-5710.js.snap [hunk 1]
```diff
@@ -0,0 +1,10 @@
+---
+source: crates/biome_js_analyze/tests/spec_tests.rs
+expression: issue-5710.js
+---
+# Input
+```js
```
Comment (Conaclos) [inline crates/biome_js_analyze/tests/specs/source/organizeImports/issue-5710.js.snap:6]: I think we don't need any change set because the new import sorter is not released yet in a stable release.

**Comment by Conaclos** [comment]
Note that I made the same error for import attributes. We could fix it in this PR. See line 609 of `biome_js_analyze/src/assist/source/organize_imports.rs`

**Comment by siketyan** [comment]
@Conaclos Sure, I fixed that one too :) However, I couldn't reproduce the infinite loop in that case 🤔
