### PR TITLE
fix(cli): prevent panic when searching across different file types

### LINKED ISSUE #5979: 🐛 `biome search` fails, tries to treat CSS files as JS?
### Environment information

```block
CLI:
  Version:                      2.0.0-beta.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         yarn/3.6.3

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         /home/[redacted]/biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Workspace:
  Open Documents:               0
```

### What happened?

```
$ yarn biome search '`console.log`'
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue.

When opening the issue, please provide a minimal reproduction, or identify and share the file/code that triggers it. Without a way to reproduce the error, the error can't be fixed:

Source Location: /home/runner/work/biome/biome/crates/biome_parser/src/lib.rs:687:13
Thread Name: biome::workspace_worker_2
Message: could not downcast root node to language biome_js_syntax::syntax_node::JsLanguage
```

This seems to happen for CSS files:

```
/path/to/some/file.ts:319:3 search 
  319 │   console.log("some message!");

/path/to/app/globals.css internalError/panic  INTERNAL
```

### Expected result

`biome search` should gracefully handle files of the wrong type.

It may well throw an error message, although that wouldn't be very user-friendly. It should definitely not panic.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by unvalley**
## Summary

Closes #5979 

This PR updates the `biome search` command to check the file type and pattern language before performing a search.
By default, biome search assumes JavaScript, but it would previously panic if a CSS file was included in the search targets.
With this change, the command no longer panics.

## Test Plan

I also tested on the repro: https://github.com/Sjlver/biome-repro-1747046861198

### CODE REVIEW

File: crates/biome_cli/src/execute/process_file/search.rs [hunk 1]
```diff
@@ -53,3 +75,19 @@ pub(crate) fn search_with_guard<'ctx>(
...
+    matches!(
+        (file_source, pattern_language),
+        (
+            DocumentFileSource::Js(_),
+            GritTargetLanguage::JsTargetLanguage(_)
+        ) | (
+            DocumentFileSource::Css(_),
+            GritTargetLanguage::CssTargetLanguage(_)
+        )
+    )
```
Comment (siketyan) [inline crates/biome_cli/src/execute/process_file/search.rs]: It will be a bit redundant, but I'd prefer using a `match` for Grit target languages, so we don't forget to add a pattern here when we add a variant to the `GritTargetLanguage` enum.

```suggestion
    match pattern_language {
        GritTargetLanguage::JsTargetLanguage(_) => matches!(file_source, DocumentFileSource::Js(_)),
        GritTargetLanguage::CssTargetLanguage(_) => matches!(file_source, DocumentFileSource::Css(_)),
    }
```

File: crates/biome_cli/src/execute/process_file/search.rs [hunk 2]
```diff
@@ -31,6 +34,25 @@ pub(crate) fn search_with_guard<'ctx>(
...
+    let pattern_language = match &_ctx.execution.traversal_mode {
+        TraversalMode::Search {
+            language: Some(pattern_language),
+            ..
+        } => pattern_language,
+        TraversalMode::Search { language: None, .. } => {
+            // Default to JavaScript when no language is specified
+            &GritTargetLanguage::JsTargetLanguage(JsTargetLanguage)
+        }
+        _ => return Ok(FileStatus::Ignored), // unreachable
```
Comment (siketyan) [inline crates/biome_cli/src/execute/process_file/search.rs:48]:
```suggestion
        _ => unreachable!(),
```

Comment (arendjr) [reply crates/biome_cli/src/execute/process_file/search.rs:48]: I'd prefer to keep it as is, as otherwise we'd panic again if it turns out we made a mistake (either now or after a refactor).

**Review by arendjr — APPROVED** [review]
Thanks!
