### PR TITLE
fix(biome_js_analyze): fix useValidLang rejecting BCP 47 language tags with script subtags

### LINKED ISSUE #8117: 🐛 useValidLang rule incorrectly rejects valid BCP 47 language tags that include script subtags, such as zh-Hans-CN
### Environment information

```block
CLI:
  Version:                      2.3.5
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v24.3.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.3.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```

### What happened?

The `useValidLang` rule incorrectly rejects valid BCP 47 language tags that include script subtags, such as `zh-Hans-CN` (Simplified Chinese as used in China).

### Expected result

According to [BCP 47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) and [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), these tags should be valid:

```
<html lang="zh-Hans-CN" />  // ✅ Should be valid (Simplified Chinese, China)
<html lang="zh-Hant-TW" />  // ✅ Should be valid (Traditional Chinese, Taiwan)
<html lang="sr-Cyrl-RS" />  // ✅ Should be valid (Serbian, Cyrillic script, Serbia)
```

### Valid BCP 47 Language Tag Format

BCP 47 language tags follow this structure:
```
language [-script] [-region] [-variant] [-extension] [-privateuse]
```

## Root Cause
The current implementation in use_valid_lang.rs only supports the simple language-country format:
```rust
let mut split_value = attribute_text.split('-');
match (split_value.next(), split_value.next()) {
    (Some(language), Some(country)) => {
        // Validates as language-country only
        if !is_valid_language(language) { /* ... */ }
        else if !is_valid_country(country) { /* ... */ }
        else if split_value.next().is_some() {
            // Rejects any additional subtags
            return Some(UseValidLangState {
                invalid_kind: InvalidKind::Value,
            });
        }
    }
    // ...
```

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ghost**
## Summary

Closes #8117.

This PR fixes an issue where the useValidLang rule incorrectly rejected valid BCP 47 tags that include a script subtag (such as `zh-Hans-CN`).

## Test Plan

New rules were added to:

* `crates/biome_js_analyze/tests/specs/a11y/useValidLang/invalid.jsx`
* `crates/biome_js_analyze/tests/specs/a11y/useValidLang/valid.jsx`

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs [hunk 1]
```diff
@@ -66,9 +66,9 @@ impl Rule for UseValidLang {
             let attribute_static_value = attribute_value.as_static_value()?;
             let attribute_text = attribute_static_value.text();
             let mut split_value = attribute_text.split('-');
-            match (split_value.next(), split_value.next()) {
-                (Some(language), Some(country)) => {
-                    if !is_valid_language(language) {
+            match (split_value.next(), split_value.next(), split_value.next()) {
+                (Some(language), Some(script), Some(country)) => {
+                    if !is_valid_language(&format!("{}-{}", language, script)) {
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs]: `format!` will allocate a new string, and i think that could be avoided here. `is_valid_language` could also take `script` as an additional parameter.

File: crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs [hunk 2]
```diff
@@ -86,7 +86,23 @@ impl Rule for UseValidLang {
...
 
-                (Some(language), None) => {
+                (Some(language), Some(script_or_country), None) => {
+                    if !is_valid_language(language) {
+                        return Some(UseValidLangState {
+                            attribute_range: attribute_value.range(),
+                            invalid_kind: InvalidKind::Language,
+                        });
+                    } else if !is_valid_country(script_or_country)
+                        && !is_valid_language(&format!("{}-{}", language, script_or_country))
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs]: same here

File: crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs (hunk 1 above)
Comment (ghost) [reply crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs]: I amended the PR so that it no longer uses `format!` to allocate a new string.

File: crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs [hunk 3]
```diff
@@ -66,9 +66,9 @@ impl Rule for UseValidLang {
             let attribute_static_value = attribute_value.as_static_value()?;
             let attribute_text = attribute_static_value.text();
             let mut split_value = attribute_text.split('-');
-            match (split_value.next(), split_value.next()) {
-                (Some(language), Some(country)) => {
-                    if !is_valid_language(language) {
+            match (split_value.next(), split_value.next(), split_value.next()) {
+                (Some(language), Some(script), Some(country)) => {
+                    if !is_valid_language(&attribute_text[0..(language.len() + 1 + script.len())]) {
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs]: This is a bit confusing.

File: crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs [hunk 4]
```diff
@@ -86,7 +86,23 @@ impl Rule for UseValidLang {
...
+                        });
+                    } else if !is_valid_country(script_or_country)
+                        && !is_valid_language(&format!("{}-{}", language, script_or_country))
+                    {
+                        return Some(UseValidLangState {
+                            attribute_range: attribute_value.range(),
+                            invalid_kind: InvalidKind::Country,
+                        });
+                    }
+                }
```
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_js_analyze/src/lint/a11y/use_valid_lang.rs:125]: This seems important. Would it make sense to add a `fn is_valid_script()`?

**Comment by ghost** [comment]
@dyc3 I made requested changes and added a changeset.

**Review by dyc3 — APPROVED** [review]
Thank you!
