### PR TITLE
fix(file_handler): svelte & vue script language parsing

### LINKED ISSUE #2245: 🐛 In Svelte context=module Scripts error "import { type x ident }' are a TypeScript only feature."
### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Have a Svelte component with code below
```svelte
<script context="module" lang="ts">
	import { timeline, type TimelineSegment } from 'motion'
</script>
```
2. Observe that type imports produce "import { type x ident }' are a TypeScript only feature". If imports are moved into regular svelte block, things work correctly.

### Expected result

No error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

Use the JSX flavor JavaScript parser to parse the opening tags of the script blocks in Svelte and Vue files so we can parse the language of the script in them more reliably.

Closes #2245.

## Test Plan

Test cases are added.

### CODE REVIEW

File: crates/biome_service/src/file_handlers/mod.rs [hunk 1]
```diff
@@ -558,6 +559,44 @@ pub(crate) fn is_diagnostic_error(
     severity >= Severity::Error
 }
 
+/// Parse the "lang" attribute from the opening tag of the "\<script\>" block in Svelte or Vue files.
+/// This function will return the language based on the existence or the value of the "lang" attribute.
+/// We use the JSX parser at the moment to parse the opening tag. So the opening tag should be first
+/// matched by regular expressions.
+///
+/// TODO: We should change the parser when HTMLish languages are supported.
```
Comment (ematipico) [inline crates/biome_service/src/file_handlers/mod.rs:567]:
```suggestion
// TODO: We should change the parser when HTMLish languages are supported.
```

The `TODO` shouldn't be a doc comment

**Review by ematipico — APPROVED** [review]
I must admit, that was a very clever solution :)
