### PR TITLE
fix(parse/css): fix parsing `--*: initial;` with tailwindDirectives enabled

### LINKED ISSUE #7843: 🐛 @theme At-Rule with Tailwind CSS internal variable (--*: initial;) causes multiple CSS parser errors
### Environment information

```block
CLI:
  Version:                      2.3.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v24.3.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.3.1

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```

### What happened?

https://biomejs.dev/playground/?cssModules=true&code=QABpAG0AcABvAHIAdAAgACIAdABhAGkAbAB3AGkAbgBkAGMAcwBzACIAOwAKAAoAQAB0AGgAZQBtAGUAIAB7AAoAIAAgAC0ALQAqADoAIABpAG4AaQB0AGkAYQBsADsACgB9AAoA&language=css

When a CSS file contains the Tailwind CSS @theme at-rule along with its internal CSS variable declaration (--*: initial;), the Biome CSS Linter fails to parse the file correctly, resulting in a series of parsing and linting errors.

This is commonly used when adopting Tailwind CSS v4 or using the PostCSS Nesting plugin with Tailwind.

### Expected result

The Biome CSS Parser and Linter should correctly parse the file without errors. The declaration --*: initial; is an intentional part of the Tailwind CSS configuration for managing CSS layers, and its usage is documented by Tailwind [here](https://tailwindcss.com/docs/theme#using-a-custom-theme).

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

fixes #7843

I wanted to keep the parsing of things like `--color-*` to remain the same where `--color` is the identifier, but if I just blindly did that for the `--*` case, then the identifier would be `-`, which would be confusing for lint rule authors.

## Test Plan

added a snapshot test

### CODE REVIEW

File: crates/biome_css_parser/src/syntax/property/mod.rs [hunk 1]
```diff
@@ -160,7 +160,11 @@ const END_OF_COMPOSES_CLASS_TOKEN_SET: TokenSet<CssSyntaxKind> =
 #[inline]
 fn is_at_generic_property(p: &mut CssParser) -> bool {
     is_at_identifier(p)
-        && (p.nth_at(1, T![:]) || (p.nth_at(1, T![-]) && p.nth_at(2, T![*]) && p.nth_at(3, T![:])))
+        && (p.nth_at(1, T![:])
+        // handle --*:
+        || (p.nth_at(1, T![*]) && p.nth_at(2, T![:]))
+        // handle --color-*:
+        || (p.nth_at(1, T![-]) && p.nth_at(2, T![*]) && p.nth_at(3, T![:])))
 }
```
[the remark this answers is not in the document]
Comment (dyc3) [reply crates/biome_css_parser/src/syntax/property/mod.rs:170]: We actually don't want to gate the behavior behind the parser option. We need the lexer to emit the right tokens so that the parser can detect the incorrect syntax when the option is disabled, and emit a good diagnostic to the user.

File: .changeset/itchy-aliens-ask.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+The css parser with `tailwindDirectives` enabled will now correctly parse `--*: initial;`.
```
Comment (ematipico) [inline .changeset/itchy-aliens-ask.md]: The bot was correct in a sense. The changeset should include "Fixed [#7843]() ..."

File: crates/biome_css_parser/src/lexer/mod.rs [hunk 3]
```diff
@@ -1011,6 +1011,12 @@ impl<'src> CssLexer<'src> {
             && current == b'-'
             && self.peek_byte() == Some(b'*')
         {
+            // HACK: handle `--*` correctly
```
Comment (ematipico) [inline crates/biome_css_parser/src/lexer/mod.rs]:
```suggestion
            // HACK: handle `--*`
```

Nit: An hack seems to contradict the "correctly"

File: crates/biome_css_parser/src/syntax/property/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (ematipico) [reply crates/biome_css_parser/src/syntax/property/mod.rs:170]: FYI you need to start the message with `@coderabbitai` to it can process it and learn

File: crates/biome_css_parser/tests/css_test_suite/ok/tailwind/theme/custom-theme.css [hunk 4]
```diff
@@ -0,0 +1,5 @@
+/* From tailwind docs: https://tailwindcss.com/docs/theme#using-a-custom-theme */
+
+@theme {
+	--*: initial;
+}
```
Comment (ematipico) [inline crates/biome_css_parser/tests/css_test_suite/ok/tailwind/theme/custom-theme.css:5]: Should we create a normal CSS file and make sure that it throws a diagnostic?
