### PR TITLE
fix(exhaustiveDeps): perform nested capture check in a correct way

### LINKED ISSUE #1012: 💅 useExhaustiveDependencies nested access check relies on the source format
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

The `correctness/useExhaustiveDependencies` rule works in different ways when the formatting differs.

[Playground Link](https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAB7AHUAcwBlAEMAYQBsAGwAYgBhAGMAawB9ACAAZgByAG8AbQAgACcAcgBlAGEAYwB0ACcAOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAQQBwAHAAKAApACAAewAKACAAIABjAG8AbgBzAHQAIABhACAAPQAgAHsACgAgACAAIAAgAGIAOgAgAE0AYQB0AGgALgByAGEAbgBkAG8AbQAoACkACgAgACAAfQAKAAoAIAAgAC8ALwAgAEIAcgBvAGsAZQBuAAoAIAAgAHUAcwBlAEMAYQBsAGwAYgBhAGMAawAoACgAKQAgAD0APgAgAHsACgAgACAAIAAgAGEAbABlAHIAdAAoAGEACgAgACAAIAAgACAAIAAuAGIAKQAKACAAIAB9ACwAIABbAGEALgBiAF0AKQA7AAoACgAgACAALwAvACAAVwBvAHIAawBzAAoAIAAgAHUAcwBlAEMAYQBsAGwAYgBhAGMAawAoACgAKQAgAD0APgAgAHsACgAgACAAIAAgAGEAbABlAHIAdAAoAGEALgBiACkACgAgACAAfQAsACAAWwBhAC4AYgBdACkAOwAKAH0ACgAKAA%3D%3D)

### Expected result

The formatting shouldn't matter.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by XiNiHa**
## Summary

Fix to correctly perform the nested capture check, rather than doing source string comparisons.
This allows the rule to work correctly for member expressions with line breaks (`a\n.b`) and computed property accesses with a string literal. (`a['b']`)

Fixes #1012

## Test Plan

Modified existing tests to also work on edge cases.

### CODE REVIEW

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs [hunk 1]
```diff
@@ -524,6 +524,55 @@ fn is_out_of_function_scope(
     )
 }
 
+fn into_member_vec(node: &JsSyntaxNode) -> Vec<String> {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs:527]: We should document what this function does because the name isn't very descriptive

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs [hunk 2]
```diff
@@ -524,6 +524,55 @@ fn is_out_of_function_scope(
...
+            }
+        }
+    }
+
+    vec
+}
+
+fn compare_member_depth(a: &JsSyntaxNode, b: &JsSyntaxNode) -> (bool, bool) {
+    let mut a_member_iter = into_member_vec(a).into_iter();
+    let mut b_member_iter = into_member_vec(b).into_iter();
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs:557]: Here's a suggestion. Instead of retuning a `Vec<String>`, why don't we create an iterator? Considering that we use `a_member_iter` and `b_member_iter` in a loop, we can achieve the same result without **allocating strings**.

Here's some meta code as a suggestion:

```rs
struct MemberIterator<'a> {
	current_node: &'a JsSyntaxNode,
	// a boolean that tells us when we have stop iterating
	has_members: true
}

impl Iterator for MemberIterator {
	type Item = TokenText

	fn next(&mut self) -> Option<Self::Item> {
		// here, we put more or less the same logic of into_member_vec
	}
}

impl FusedIterator  for MemberIterator {}
```

File: crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap [hunk 3]
```diff
@@ -242,4 +248,56 @@ function MyComponent22() {
...
+    122 │       console.log(
+    123 │ 				a
+  
+  i This dependency is not specified in the hook dependency list.
+  
+    121 │     useEffect(() => {
+    122 │       console.log(
+  > 123 │ 				a
+        │ 				^
+  > 124 │ 			  		.b
```
Comment (arendjr) [inline crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap:271]: I think this is an unintended side-effect of this PR. When `a` is listed as a dependency, `a.b` is implicitly covered as well.

**Review by arendjr — CHANGES_REQUESTED** [review]

**Comment by ematipico** [comment]
> Looks good as far am I'm concerned :+1:
> 
> I do agree with your comments though!

Unfortunately having an iterator is a massive effort, because the check is bottom-up.

I think we can leave with this for now
