### PR TITLE
fix(useArrowFunction): make useArrowFunction rule fixer safer

### LINKED ISSUE #7616: 📝 useArrowFunction rule does not pay attention to use of arguments, breaks functions that use it
### Environment information

```bash
CLI:
  Version:                      2.2.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-ghostty
  JS_RUNTIME_VERSION:           v24.5.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Formatter:
  Format with errors:           unset
  Indent style:                 Space
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset
  Bracket spacing:              unset
  Includes:                     unset

JavaScript Formatter:
  Enabled:                      unset
  JSX quote style:              unset
  Quote properties:             unset
  Trailing commas:              unset
  Semicolons:                   unset
  Arrow parentheses:            unset
  Bracket spacing:              unset
  Bracket same line:            unset
  Quote style:                  Double Quotes
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset

JSON Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset
  Expand lists:                 unset

CSS Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  unset

GraphQL Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/2.2.4/schema.json",
  "vcs": {
    "enabled": false,
    "clientKind": "git",
    "useIgnoreFile": false
  },
  "files": {
    "ignoreUnknown": false,
    "includes": ["app/**"]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space"
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": {
        "noNestedComponentDefinitions": "off",
        "useExhaustiveDependencies": "off",
        "noUnusedVariables": {
          "level": "error",
          "options": {
            "ignoreRestSiblings": true
          }
        }
      },
      "suspicious": {
        "noArrayIndexKey": "off",
        "noExplicitAny": "off",
        "useIterableCallbackReturn": "off"
      },
      "a11y": {
        "noLabelWithoutControl": "off",
        "useKeyWithClickEvents": "off",
        "noStaticElementInteractions": "off",
        "noSvgWithoutTitle": "off",
        "useAriaPropsSupportedByRole": "off",
        "useSemanticElements": "off",
        "useFocusableInteractive": "off",
        "useAriaPropsForRole": "off"
      },
      "style": {
        "noNonNullAssertion": "off"
      }
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "double"
    }
  },
  "assist": {
    "enabled": true,
    "actions": {
      "source": {
        "organizeImports": "on"
      }
    }
  }
}
```

### Playground link

https://github.com/tmcw/biome-repro-1759176063262

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by tmcw**
## Summary

- Fixes #7616

This avoids auto-fixing functions if they refer to the arguments object, because arguments is not defined for arrow functions. Even though there are newer ways to use arguments in JavaScript, there's a lot of legacy code that still uses the `arguments` object, and it's a bummer for biome to break that code.

Note that this change is a little more intensive than I had hoped: the useArrowFunction rule previously worked only by traversing the AST, whereas in order to figure out if an arguments object has been redefined, it need to use a semantic model, and I couldn't find a way to _add_ that to the existing approach, so this switches it to use the `Semantic<>` style of rule, and traversing with the preorder iterator instead of a visitor. If there's a better way to do this, I'm all ears!

Also notably that pattern of being able to resassign arguments like

```ts
function x() {
	const arguments = 10;
}
```

This only works in script mode. So, an alternative solution would be to simply never fix a function if it both mentions arguments in any way, and is in script mode.

## Test Plan

This includes updates to the test snapshots for the cases where it should fix & not fix functions that mention arguments.

### CODE REVIEW

**Comment by dyc3** [comment]
we can definitely detect if a file is in script mode. `JsFileSource` should have that info in `module_kind`.

File: crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs [hunk 1]
```diff
@@ -59,6 +59,13 @@ declare_lint_rule! {
     ///     return 0;
     /// }
     /// ```
+    /// Functions that reference the arguments object
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs]: We should add a link to arguments. Without a special explanation, and format, newbies won't know what arguments is

File: .changeset/yellow-mangos-clean.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+---
+"@biomejs/biome": patch
+---
+
+Make useArrowFunction fixer safer
```
Comment (ematipico) [inline .changeset/yellow-mangos-clean.md]: - start sentences with the past (as per guidelines, please read them)
- use backticks for the rule name 
- add a link to the rule 
- change "fixer" with "code fix", that's how we document it in the docs

**Comment by tmcw** [comment]
Thanks for the review, I've rewritten the changeset and doc comment and hopefully clarified them.

**Review by dyc3 — APPROVED** [review]

File: .changeset/yellow-mangos-clean.md [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+"@biomejs/biome": patch
+---
+
+Fixed an edge case in the [`useArrowFunction`](https://biomejs.dev/linter/rules/use-arrow-function/) rule.
+
+The rule no longer emits diagnostics for or offers to fix functions that reference
+the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments),
+because that object is undefined for arrow functions.
+
+#### Valid:
```
Comment (ematipico) [inline .changeset/yellow-mangos-clean.md]:
```suggestion
**Valid example:**
```

**Review by ematipico — APPROVED** [review]
