### PR TITLE
fix(lint/useForOf): handle shorthand property

### LINKED ISSUE #1653: 💅 `useForOf` - false-positive when using `index` as a shorthand value
### Environment information

```bash
Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.8.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useForOf

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=YwBvAG4AcwB0ACAAYQByAHIAYQB5ACAAPQAgAFsAJwBhACcALAAgACcAYgAnACwAIAAnAGMAJwBdADsACgBmAG8AcgAgACgAbABlAHQAIABpAG4AZABlAHgAIAA9ACAAMAA7ACAAaQBuAGQAZQB4ACAAPAAgAGEAcgByAGEAeQAuAGwAZQBuAGcAdABoADsAIABpAG4AZABlAHgAKwArACkAIAB7AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBpAG4AZgBvACgAaQBuAGQAZQB4ACkAOwAKAH0ACgAKAGYAbwByACAAKABsAGUAdAAgAGkAbgBkAGUAeAAgAD0AIAAwADsAIABpAG4AZABlAHgAIAA8ACAAYQByAHIAYQB5AC4AbABlAG4AZwB0AGgAOwAgAGkAbgBkAGUAeAArACsAKQAgAHsACgAgACAAYwBvAG4AcwBvAGwAZQAuAGkAbgBmAG8AKAB7ACAAaQBuAGQAZQB4ACAAfQApADsACgB9AAoACgBmAG8AcgAgACgAbABlAHQAIABpAG4AZABlAHgAIAA9ACAAMAA7ACAAaQBuAGQAZQB4ACAAPAAgAGEAcgByAGEAeQAuAGwAZQBuAGcAdABoADsAIABpAG4AZABlAHgAKwArACkAIAB7AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBpAG4AZgBvACgAewAgAGkAbgBkAGUAeAA6ACAAaQBuAGQAZQB4ACAAfQApADsACgB9AAoACgBmAG8AcgAgACgAbABlAHQAIABpAG4AZABlAHgAIAA9ACAAMAA7ACAAaQBuAGQAZQB4ACAAPAAgAGEAcgByAGEAeQAuAGwAZQBuAGcAdABoADsAIABpAG4AZABlAHgAKwArACkAIAB7AAoAIAAgAGMAbwBuAHMAbwBsAGUALgBpAG4AZgBvACgAewAgAGkAbgBkAGUAeAA6ACAAaQBuAGQAZQB4ACAAKwAgADEAMQAgAH0AKQA7AAoAfQAKAAoAZgBvAHIAIAAoAGwAZQB0ACAAaQBuAGQAZQB4ACAAPQAgADAAOwAgAGkAbgBkAGUAeAAgADwAIABhAHIAcgBhAHkALgBsAGUAbgBnAHQAaAA7ACAAaQBuAGQAZQB4ACsAKwApACAAewAKACAAIABjAG8AbgBzAG8AbABlAC4AaQBuAGYAbwAoAGAAJAB7AGkAbgBkAGUAeAB9AGAAKQA7AAoAfQAKAAoA

### Expected result

Should not show lint error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by togami2864**
## Summary
close #1653 

## Test Plan
add snaps for cases

### CODE REVIEW

**Comment by Conaclos** [comment]
Would you mind adding a changelog entry?

File: crates/biome_js_analyze/src/lib.rs [hunk 1]
```diff
@@ -243,8 +243,9 @@ mod tests {
             String::from_utf8(buffer).unwrap()
         }
 
-        const SOURCE: &str = r#"xdescribe('foo', () => {});
-        "#;
+        const SOURCE: &str = r#"for (let i = 0; i < array.length; i++) {
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/lib.rs:246]: Could you undo the changes in that file?

**Review by Conaclos — APPROVED** [review]
