### PR TITLE
fix(biome-service): override all formatter options with user configured overrides

### LINKED ISSUE #6638: 📝 `overrides` configuration doesn't override all specified formatter options
### Environment information

```bash
CLI:
  Version:                      2.0.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v20.18.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Formatter:
  Format with errors:           unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset
  Bracket spacing:              unset
  Includes:                     **/*.ts, **/*.json

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              unset
  Quote properties:             unset
  Trailing commas:              unset
  Semicolons:                   unset
  Arrow parentheses:            unset
  Bracket spacing:              unset
  Bracket same line:            unset
  Quote style:                  Double Quotes
  Indent style:                 Tab
  Indent width:                 2
  Line ending:                  unset
  Line width:                   300
  Attribute position:           unset

JSON Formatter:
  Enabled:                      true
  Indent style:                 Tab
  Indent width:                 4
  Line ending:                  unset
  Line width:                   160
  Trailing Commas:              unset
  Expand lists:                 Always

CSS Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  unset

GraphQL Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"vcs": {
		"enabled": true,
		"clientKind": "git",
		"useIgnoreFile": true
	},
	"files": {
		"ignoreUnknown": true
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true
		}
	},
	"formatter": {
		"includes": [
			"**/*.ts",
			"**/*.json"
		]
	},
	"json": {
		"formatter": {
			"enabled": true,
			"expand": "always",
			"lineWidth": 160,
			"indentWidth": 4,
			"indentStyle": "tab"
		}
	},
	"javascript": {
		"formatter": {
			"enabled": true,
			"quoteStyle": "double",
			"expand": "always",
			"lineWidth": 300,
			"indentWidth": 2,
			"indentStyle": "tab"
		}
	},
	"assist": {
		"enabled": true,
		"actions": {
			"source": {
				"organizeImports": "on"
			}
		}
	},
	"overrides": [
		{
			"includes": [
				"src/overrides/**/*.ts"
			],
			"javascript": {
				"formatter": {
					"enabled": true,
					"quoteStyle": "single",
					"expand": "never",
					"lineWidth": 300
				}
			}
		}
	]
}
```

### Playground link

https://github.com/marko-hologram/biome-overrides-bug

I couldn't reproduce this in Playground because I didn't see a way to specify `overrides` config for Biome there. Attached a repo with instructions how to reproduce the issue.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by marko-hologram**
## Summary

Hello, first time contributor here! I opened an issue (#6638) because I noticed formatter overrides weren't being applied for all specified options. Looking through the code I found that `expand` option in JS formatter and `bracketSpacing` in JSON formatter weren't being overwritten when specified in `overrides`.

I followed existing code while fixing this. Although a better solution would be to somehow map over all possible options and apply them, but my Rust experience/knowledge is non-existent so I really don't know how would I do this.

I also wanted to write a test that verifies that override options are being applied, but that test wouldn't automatically cover any options that would be added in the future so it wouldn't catch missing options later on. And since my Rust knowledge is zero, I had a bit of trouble actually writing that test.

Fixes #6638 

## Test Plan

I've used the repo mentioned in my issue #6638. Built a new Biome binary with these changes and ran current version and new binary one after another and observer the printed code.

Here is a before and after terminal output for JS formatting:

| Before | After |
|--------|-------|
| image | image |

It's clearly visible `expand` option is now being properly overridden in the "after" case for files that are included for the override.

Here is a before and after terminal output for JSON formatting:

| Before | After |
|--------|-------|
| image | image |

It's clearly visible `bracketSpacing` option is now being properly overridden in the "after" case for files that are included for the override.

### CODE REVIEW

File: crates/biome_service/src/settings.rs [hunk 1]
```diff
@@ -1443,6 +1446,10 @@ impl OverrideSettingPattern {
         if let Some(expand_lists) = json_formatter.expand {
```
Comment (siketyan) [inline crates/biome_service/src/settings.rs]:
```suggestion
        if let Some(expand_lists) = json_formatter.expand.or(formatter.expand) {
```

Comment (marko-hologram) [reply crates/biome_service/src/settings.rs]: Hey, thanks for the review. I'll fix this.

I'm curious why trailing_commas option above doesn't have that .or() call?

```rs
if let Some(trailing_commas) = json_formatter.trailing_commas {
    options.set_trailing_commas(trailing_commas);
}
```

Comment (siketyan) [reply crates/biome_service/src/settings.rs]: @marko-hologram That's because we don't have the `trailingComma` option in the global `formatter` section: https://biomejs.dev/reference/configuration/#formatter. The option is only available in JS or JSON, and it has the different possible values between JS (none, es5, all) and JSON (none, all).

Comment (marko-hologram) [reply crates/biome_service/src/settings.rs]: Ohhh I see. Thanks for the detailed explanation 😄

Btw I added the code you proposed. Let me know if I need to to anything else.

File: .changeset/many-weeks-lose.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#6638](https://github.com/biomejs/biome/issues/6638). Javascript formatter `overrides` options now correctly override `expand` option. JSON formatter `overrides` options now correctly override `bracketSpacing` option.
```
Comment (siketyan) [inline .changeset/many-weeks-lose.md]: Nit:

```suggestion
Fixed [#6638](https://github.com/biomejs/biome/issues/6638): JavaScript formatter `overrides` options now correctly override `expand` option. JSON formatter `overrides` options now correctly override `bracketSpacing` and `expand` options.
```

Comment (marko-hologram) [reply .changeset/many-weeks-lose.md]: Sorry didn't notice your comment immediately. Updated changelog with your proposed changes since they do reflect better what was updated.

Comment (siketyan) [reply .changeset/many-weeks-lose.md]: No worries!

**Comment by marko-hologram** [comment]
> I wonder if we could add a test, so we won't have regressions

I'll look into it later today. Haven't worked with Rust really, but I guess I could try.

**Comment by ematipico** [comment]
You just need to follow the same tests as the others. Here's an example. You just need to use an unique name for the test, same as for the snapshot, and update the contents of the file to match the case you're fixing. 

The contribution guide explains how to work with snapshot tests

https://github.com/biomejs/biome/blob/92964a7ae076b9b08b83da329e2b8a5825e30da9/crates/biome_cli/tests/cases/overrides_formatter.rs#L730-L775

**Comment by marko-hologram** [comment]
@ematipico sorry I didn't get to this on Friday.

I added two snapshot tests, one for JS and one for JSON. I tried defining all options in base formatter config and then override basically all of those options and asserting that base file uses default formatting and override file uses override config formatting.

Hopefully this is what you expected from tests. If I can do anything else, please just let me know.

**Review by ematipico — APPROVED** [review]
