### PR TITLE
fix(organizeImports): merge bare exports

### LINKED ISSUE #7583: 🐛 `oragnizeImports` doesn't organize bare `export`
### Environment information

```block
Main branch
```

### What happened?

Running `oragnizeImports` on the following code:

```ts
export { f, e, d };
export { g };
export { b, a, c } from './files.js';
```

provides the following results:

```ts
export { f, e, d };
export { g };
export { a, b, c } from './files.js';
```

Note that the `export` without a `from` clause are not organized and merged.

### Expected result

A user could expect the following organized code:

```ts
export { d, e, f, g };
export { a, b, c } from './files.js';
```

This looks more complex that it seems. Because if we use the current rule logic, then we have to define an order between `export from` and `export`. For example, if we decide that `export from` is always placed first, then the resulting code could be:

```ts
export { a, b, c } from './files.js';
export { d, e, f, g };
```

If it is a bug fix or a breaking change is up to debate.
We face [some complains](https://github.com/biomejs/biome/discussions/6389) about the fact that `organizeImports`  organizes exports.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #7583. Follow-up of #9353. `organizeImports` now merges bare exports:
Here is an example of bare export merging:

```diff
- export { a };
- export { b };
+ export { a, b };
```

Bare `export` are now sorted with other exports.
Bare exports are placed after `export from`. This is why I manually re-implemented `Ord for ImportKey`.
Here is an example:

```diff
- export { A };
  export * as path from "node:path";
+ export { A };
```

I chose this order because:
- bare `export` are often placed at the end
- `export from` statements are between `import` and `export`.
  Imports are usually placed first, then bare exports should be placed last (`export from` are in-between). 
- `import` `with` attributes are placed above `import` without attributes.
  Thus, placing exports with a `from` clause above exports without it follows the same logic.

Finally, this PR solves another issue reported some weeks or months ago about a missing blank line between imports and a bare export. Unfortunately, I didn't find the issue or discussion that brought it up.
Here is an example of the fix:

```diff
  import { A } from "package";
+
  export { A };
```

## Test Plan

I added several tests.

## Docs

I edited the changeset of #9353 to cover this PR.

### CODE REVIEW

File: crates/biome_rule_options/src/organize_imports/import_groups.rs [hunk 1]
```diff
@@ -21,7 +21,6 @@ impl ImportGroups {
     /// If no group contains `candidate`, then the returned value corresponds to the index of the implicit group.
     /// The index of the implicit group correspond to the number of groups.
     pub fn index(&self, candidate: &ImportCandidate<'_>) -> u16 {
-        candidate.source.as_str();
```
Comment (Conaclos) [inline crates/biome_rule_options/src/organize_imports/import_groups.rs:24]: This was a useless code. Strangely, this was not reported by Clippy.
