### PR TITLE
fix(biome_js_analyze): produce diagnogstics for top-level useless fragment that is in a return statement

### LINKED ISSUE #6530: 💅 `noUselessFragments` does not run for top-level fragments
### Environment information

```bash
CLI:
  Version:                      2.0.5
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.14.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/9.7.1

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    ...

Workspace:
  Open Documents:               0
```

### Rule name

lint/complexity/noUselessFragments

### Playground link

[playground](https://v1.biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAZgAoACkAIAB7AAoAIAAgACAAIAAvAC8AIABTAGgAbwB1AGwAZAAgAGIAZQAgAGYAbABhAGcAZwBlAGQAIABhAHMAIAB1AHMAZQBsAGUAcwBzAAoACQByAGUAdAB1AHIAbgAgACgACgAJAAkAPAA%2BAAoACQAJAAkAPABkAGkAdgA%2BADwALwBkAGkAdgA%2BAAoACQAJADwALwA%2BAAoACQApADsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABmADIAKAApACAAewAKAAkAcgBlAHQAdQByAG4AIAAoAAoACQAJADwAZABpAHYAPgAKAAkACQAJADwAPgAKAAkACQAJAAkAPABkAGkAdgA%2BADwALwBkAGkAdgA%2BAAoACQAJAAkAPAAvAD4ACgAJAAkAPAAvAGQAaQB2AD4ACgAJACkAOwAKAH0ACgA%3D)

### Expected result

Should flag the first fragment as useless

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by daivinhtran**
Fixes #6530

### CODE REVIEW

File: crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx.snap [hunk 1]
```diff
@@ -4,16 +4,37 @@ expression: issue_3668.jsx
 ---
 # Input
 ```jsx
-// should not trigger
 function Component2() {
-    const str = 'str';
-    return (<>{str}</>);
+	const str = "str";
+	// should trigger
+	return <>{str}</>;
```
Comment (Loskir) [inline crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx.snap]: This one can actually be unsafe (returning `string` instead of `JSX.Element`) so it can be a regression (see #4059 and #6508)

Comment (tidefield) [reply crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx.snap]: I put the PR back to draft so I can fix it. I'll let you know when I'm done.

Comment (tidefield) [reply crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx.snap]: The PR is ready for review. Thanks for pointing out the regressions.

**Review by Loskir — APPROVED** [review]

**Comment by tidefield** [comment]
> A changeset is missing. You can check our contribution guide for creating one

@ematipico Thanks! PTAL. It's always a joy to contribute on this codebase.

File: .changeset/slick-toes-yawn.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#6536](https://github.com/biomejs/biome/issues/6530). Produce diagnogstics for top-level useless fragment that is in a return statement.
```
Comment (ematipico) [inline .changeset/slick-toes-yawn.md]:
```suggestion
Fixed [#6536](https://github.com/biomejs/biome/issues/6530). Now the rule `noUselessFragments` produces diagnostics for a top-level useless fragment that is in a return statement.
```

**Review by ematipico — APPROVED** [review]
Thank you @daivinhtran
