### PR TITLE
fix(parse/css): parse tailwind `@utility` with slash in the name

### LINKED ISSUE #8897: 📝 parser error with forward slash in tailwind directive
### Environment information

A forward slash within a `@utility` tailwind directive name throws an error when parsing it, as in the repro

Prettier is able to parse this kind of css, while biome throws an ```expected `{` but instead found `/` ``` error

While the css is not valid, tailwind automatically escapes it, incidentally there is also an issue where tailwind doesn't allow the pre-escaped utility name which would work with biome. Still, maybe this is worth a fix on both sides

### Configuration

```JSON

```

### Playground link

https://biomejs.dev/playground/?code=QAB1AHQAaQBsAGkAdAB5ACAAYQAvAGIAIAB7AAoAIAAgAGMAbwBsAG8AcgA6ACAAcgBlAGQAOwAKAH0A&language=css

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

Allows the css parser to parse `@utility a/b {}`.

fixes #8897

## Test Plan

snapshots

### CODE REVIEW

File: crates/biome_css_parser/src/lexer/mod.rs [hunk 1]
```diff
@@ -1010,7 +1021,11 @@ impl<'src> CssLexer<'src> {
     ///
     /// Returns the consumed character wrapped in `Some` if it is part of an identifier,
     /// and `None` if it is not.
-    fn consume_ident_part(&mut self, current: u8) -> Option<char> {
+    fn consume_ident_part(&mut self, current: u8, allow_slash: bool) -> Option<char> {
+        if allow_slash && current == b'/' {
```
Comment (ematipico) [inline crates/biome_css_parser/src/lexer/mod.rs]: nit: At line 1042 we do a lookup of byte table. Maybe we should move it here and update the checks.

**Review by chansuke — APPROVED** [review]

**Comment by ematipico** [comment]
@dyc3 should this PR be merged?

**Comment by dyc3** [comment]
Ah, yes. Slipped through. I'll fix the ci
