### PR TITLE
fix(`overrides`): `json.formatter.trailingCommas` should work

### LINKED ISSUE #2009: 📝 Can't override `json.formatter.trailingCommas`
I configured overrides for the `b.json` so that it should format with trailingCommas=all and lineWidth=20, but when I run `npx @biomejs/biome check --apply {a,b}.json` biome doesn't add missing commas in b.json

### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent size:                  0
  Indent width:                 0
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              true
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              None

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"formatter": {
		"enabled": true
	},
	"json": {
		"parser": {
			"allowComments": false,
			"allowTrailingCommas": false
		},
		"formatter": {
			"enabled": true,
			"trailingCommas": "none"
		}
	},
	"overrides": [
		{
			"include": ["b.json"],
			"json": {
				"parser": {
					"allowComments": true,
					"allowTrailingCommas": true
				},
				"formatter": {
					"enabled": true,
					"trailingCommas": "all",
					"lineWidth": 20
				}
			}
		}
	]
}
```

### Playground link

https://codesandbox.io/p/devbox/overrides-s4g9zw?file=%2Fbiome.json%3A4%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltj4jn8b0005356bja36b6lm%2522%252C%2522sizes%2522%253A%255B56.879255064532686%252C43.120744935467314%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltj4jn8a0002356bbhofn3ww%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltj4jn8a0003356ba609rune%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltj4jn8b0004356bbl2aitvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltj4jn8a0002356bbhofn3ww%2522%253A%257B%2522id%2522%253A%2522cltj4jn8a0002356bbhofn3ww%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltj4zcw50002356cb3su6mdd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fa.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltj55mpx0002356clzt1gb43%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fbiome.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltj55mpx0002356clzt1gb43%2522%257D%252C%2522cltj4jn8b0004356bbl2aitvj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltj4jn8b0004356bbl2aitvj%2522%257D%252C%2522cltj4jn8a0003356ba609rune%2522%253A%257B%2522id%2522%253A%2522cltj4jn8a0003356ba609rune%2522%252C%2522activeTabId%2522%253A%2522cltj55r6j0040356cb1vwf7yy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltj55r6j0040356cb1vwf7yy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltj55st70030djip7dqm3wob%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.405700864585256%257D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

- Respect `json.formatter.trailingCommas` option in `overrides`
- Rename internal `trailing_comma`-named json-related vars to `trailing_commas` for consistency

Fixes #2009

## Test Plan

Several tests are added in `crates/biome_cli/tests/commands/format.rs` to show that `json.formatter.trailingCommas` works in `overrides`.

### CODE REVIEW

File: crates/biome_service/src/configuration/json.rs [hunk 1]
```diff
@@ -71,7 +71,7 @@ pub struct JsonFormatter {
 
     /// Print trailing commas wherever possible in multi-line comma-separated syntactic structures. Defaults to "none".
     #[partial(bpaf(long("json-formatter-trailing-commas"), argument("none|all"), optional))]
-    pub trailing_commas: Option<TrailingCommas>,
```
Comment (ematipico) [inline crates/biome_service/src/configuration/json.rs:74]: I would like to keep this consistent with the rest of the CLI options.

**Review by ematipico — APPROVED** [review]
That's a great fix! 🥳 I just left a comment for consistency

File: crates/biome_service/src/configuration/json.rs (hunk 1 above)
Comment (Sec-ant) [reply crates/biome_service/src/configuration/json.rs]: I reverted them in c0d3ab2.

There're some failures in CI tests, I'll take a look at them tomorrow.

**Comment by flazouh** [comment]
still doesn't work
Screenshot 2024-09-02 at 02 22 12

**Comment by Conaclos** [comment]
@flazouh I think your `$schema` field is outdated.
