### PR TITLE
fix(lint/noUselessFragments): apply the same logic for shorthand fragments and Fragment elements

### LINKED ISSUE #6688: 💅 Invalid unnecessary fragment warning for HTML entities
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v23.9.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/9.15.9

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            false
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    nursery/useUniqueElementIds
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noDescendingSpecificity
    style/useArrayLiterals
    style/useConst
    style/useDeprecatedReason
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useShorthandFunctionType
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useNamespaceKeyword

Workspace:
  Open Documents:               0
```

### Rule name

lint/complexity/noUselessFragments

### Playground link

https://biomejs.dev/playground/?analyzerFixMode=safeAndUnsafeFixes&code=aQBtAHAAbwByAHQAIAB7ACAARgByAGEAZwBtAGUAbgB0ACAAfQAgAGYAcgBvAG0AIAAiAHIAZQBhAGMAdAAiADsACgAKAGYAdQBuAGMAdABpAG8AbgAgAEMAbwBtAHAAbwBuAGUAbgB0ACgAKQAgAHsACgAJAGMAbwBuAHMAdAAgAGMAbwBuAGQAIAA9ACAAdAByAHUAZQA7AAoACQByAGUAdAB1AHIAbgAgADwAZABpAHYAPgB7AGMAbwBuAGQAIAAmACYAIAA8AEYAcgBhAGcAbQBlAG4AdAA%2BACwAIAAmAG4AYgBzAHAAOwA8AC8ARgByAGEAZwBtAGUAbgB0AD4AfQA8AC8AZABpAHYAPgA7AAoAfQAKAA%3D%3D

### Expected result

No `noUselessFragments` warning should be displayed and autofix should do nothing if a `Fragment` containing a HTML entity is encountered.

(Currently the autofix breaks it since `<Fragment>&nbsp;</Fragment>` has completely different semantics from `"&nbsp;"` - the latter just displays the text as-is)

This specifically seems to happen for `<Fragment>`, not `<>`: [(see another playground for errorless version)](https://biomejs.dev/playground/?analyzerFixMode=safeAndUnsafeFixes&code=ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKAAkAYwBvAG4AcwB0ACAAYwBvAG4AZAAgAD0AIAB0AHIAdQBlADsACgAJAHIAZQB0AHUAcgBuACAAPABkAGkAdgA%2BAHsAYwBvAG4AZAAgACYAJgAgADwAPgAsACAAJgBuAGIAcwBwADsAPAAvAD4AfQA8AC8AZABpAHYAPgA7AAoAfQAKAA%3D%3D)

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by siketyan**
## Summary

Fixes #6688 

Fixed the `noUselessFragments` rule used different logic for shorthand fragments (`<></>`) and Fragment elements (`<Fragment></Fragment>`), causing some false positives only on the latter.

## Test Plan

Updated snapshot tests.

### CODE REVIEW

File: crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap [hunk 1]
```diff
@@ -1,11 +1,12 @@
 ---
 source: crates/biome_js_analyze/tests/spec_tests.rs
 expression: withJsxElementInvalid.jsx
-snapshot_kind: text
 ---
 # Input
 ```jsx
 <><Component /></>
+<Fragment><Component /></Fragment>
```
Comment (unvalley) [inline crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap]: Should a diagnostic be reported in this case?

Comment (siketyan) [reply crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap]: I think so but not sure. Do you have any reference that it shouldn't be reported?

Comment (unvalley) [reply crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap]: I mean the case should be invalid but we don't have diagnostics for that in this snap file, sorry if I'm missing something.

Comment (siketyan) [reply crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap]: Ah you're right! And it is because I didn't insert a `;` so the code was actually invalid. ([diff](https://github.com/biomejs/biome/compare/c326f757757d5a06622c3dc9b4fc6ed7e6e03b77..9d589bfc49ed985c947e4b4208bb0836ed170a27))
