### PR TITLE
fix(lint): support some of wrapped hook calls in useExhaustiveDependencies

### LINKED ISSUE #1597: 💅 Biome throw useExhaustiveDependencies error when useRef type is defined using type assertion
### Environment information

```bash
CLI:
  Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.10.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useExhaustiveDependencies

### Playground link

https://codesandbox.io/p/devbox/biome-shnrcy?file=%2Fsrc%2FApp.tsx

### Expected result

If useRef type is define using type assertion and when ref is used in any react hook, exhaustive deps breaks. 

Works fine
```
import { useEffect, useRef } from "react";

const App = () => {
  const ref = useRef<HTMLDivElement>();

  useEffect(() => {
    console.log(ref.current);
  }, []);

  return <div>Hello World</div>;
};

export default App;
```

Throw error `This hook does not specify all of its dependencies.`
```
import { type MutableRefObject, useEffect, useRef } from "react";

const App = () => {
  const ref = useRef() as MutableRefObject<HTMLDivElement>;

  useEffect(() => {
    console.log(ref.current);
  }, []);

  return <div>Hello World</div>;
};

export default App;
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by siketyan**
## Summary

Fixes #1597 (except more edge cases)

This pull request adds support of some different styles of hook calls that are considered as "stable", including:

- Parenthesized calls `(useRef())`
- Sequencial calls with a comma operator `(doSomething(), useRef())`
- Calls with a TS Non-null assertion `useRef()!`
- Calls with a TS `as` operator `useRef() as T`
- Calls with a TS `satisfies` operator `useRef() satisfies T`

Note this _doesn't_ cover all of edge cases.

## Test Plan

Tests added.

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
Great, thanks!

Could you rebase this against the `next` branch and add a [changeset entry](https://github.com/biomejs/biome/blob/next/CONTRIBUTING.md#writing-a-changeset)? Thanks!

**Comment by siketyan** [comment]
@arendjr Thank you for your review. I will rebase it soon!
Out of curiosity, should we create pull requests to next branch even if it does not introduce any new rules? If so, it will be great if that is noted in the pull request template then we can notice it :)

**Comment by ematipico** [comment]
> should we create pull requests to next branch

Yes, that's preferable. We did a bunch of internal refactoring, even to internal Rust methods and APIs

**Comment by siketyan** [comment]
@ematipico Thank you for clarification!

And I rebased to next branch & added a changeset. 🙏

File: crates/biome_js_analyze/src/react/hooks.rs [hunk 1]
```diff
@@ -474,6 +474,30 @@ pub fn is_binding_react_stable(
     })
 }
 
+/// Unwrap the expression to a call expression without changing the result of the expression,
+/// such as type assertions.
+fn unwrap_to_call_expression(expression: AnyJsExpression) -> Option<JsCallExpression> {
+    match expression {
+        AnyJsExpression::JsCallExpression(expr) => Some(expr),
+        AnyJsExpression::JsParenthesizedExpression(expr) => {
+            expr.expression().ok().and_then(unwrap_to_call_expression)
```
Comment (ematipico) [inline crates/biome_js_analyze/src/react/hooks.rs:483]: This is a recursion, which we tend to avoid when working with CSTs. Can you make it a loop? It shouldn't be too difficult.

Comment (siketyan) [reply crates/biome_js_analyze/src/react/hooks.rs]: @ematipico Sorry, I didn't know that. I turned it into a loop in [45e9668](https://github.com/biomejs/biome/pull/4964/commits/45e96689950cd85bc863dcae9a8c039cee41a3b3).

**Comment by arendjr** [comment]
Thanks!
