### PR TITLE
fix(noParametersOnlyUsedInRecursion): compare bindings for recursion detection

### LINKED ISSUE #8004: 💅 noParametersOnlyUsedInRecursion false positives
### Environment information

```bash
CLI:
  Version:                      2.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.15.1
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  unset
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementInteractions
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExcessiveCognitiveComplexity
    complexity/noExcessiveNestedTestSuites
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noForEach
    complexity/noImplicitCoercions
    complexity/noImportantStyles
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringConcat
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/noVoid
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useIndexOf
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    complexity/useWhile
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalDirnameFilename
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNestedComponentDefinitions
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noProcessGlobal
    correctness/noReactPropAssignments
    correctness/noRenderReturnValue
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUndeclaredDependencies
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useExhaustiveDependencies
    correctness/useGraphqlNamedOperations
    correctness/useHookAtTopLevel
    correctness/useIsNan
    correctness/useJsonImportAttributes
    correctness/useJsxKeyInIterable
    correctness/useParseIntRadix
    correctness/useSingleJsDocAsterisk
    correctness/useUniqueElementIds
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    nursery/noEmptySource
    nursery/noFloatingPromises
    nursery/noImportCycles
    nursery/noJsxLiterals
    nursery/noMisusedPromises
    nursery/noParametersOnlyUsedInRecursion
    nursery/noReactForwardRef
    nursery/noUnknownAttribute
    nursery/noUnusedExpressions
    nursery/noUselessCatchBinding
    nursery/noUselessUndefined
    nursery/useConsistentArrowReturn
    nursery/useExhaustiveSwitchCases
    performance/noAccumulatingSpread
    performance/noAwaitInLoops
    performance/noBarrelFile
    performance/noDelete
    performance/noDynamicNamespaceImportAccess
    performance/noNamespaceImport
    performance/noReExportAll
    performance/useGoogleFontPreconnect
    performance/useTopLevelRegex
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noDefaultExport
    style/noDescendingSpecificity
    style/noDoneCallback
    style/noEnum
    style/noExportedImports
    style/noInferrableTypes
    style/noNamespace
    style/noNegationElse
    style/noNestedTernary
    style/noNonNullAssertion
    style/noParameterAssign
    style/noProcessEnv
    style/noShoutyConstants
    style/noSubstr
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/noYodaExpression
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useAtIndex
    style/useBlockStatements
    style/useCollapsedElseIf
    style/useCollapsedIf
    style/useConsistentArrayType
    style/useConsistentBuiltinInstantiation
    style/useConsistentMemberAccessibility
    style/useConsistentObjectDefinitions
    style/useConsistentTypeDefinitions
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useEnumInitializers
    style/useExplicitLengthCheck
    style/useExponentiationOperator
    style/useExportType
    style/useExportsLast
    style/useFilenamingConvention
    style/useForOf
    style/useGroupedAccessorPairs
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodeAssertStrict
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useNumericSeparators
    style/useObjectSpread
    style/useReactFunctionComponents
    style/useReadonlyClassProperties
    style/useSelfClosingElements
    style/useShorthandAssign
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useSymbolDescription
    style/useTemplate
    style/useThrowNewError
    style/useThrowOnlyError
    style/useTrimStartEnd
    style/useUnifiedTypeSignatures
    suspicious/noAlert
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noBiomeFirstException
    suspicious/noBitwiseOperators
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConsole
    suspicious/noConstEnum
    suspicious/noConstantBinaryExpressions
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noDuplicateTestHooks
    suspicious/noEmptyBlock
    suspicious/noEmptyBlockStatements
    suspicious/noEvolvingTypes
    suspicious/noExplicitAny
    suspicious/noExportsInTest
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFocusedTests
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisplacedAssertion
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noNonNullAssertedOptionalChain
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noQuickfixBiome
    suspicious/noRedeclare
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSkippedTests
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noTsIgnore
    suspicious/noUnassignedVariables
    suspicious/noUnknownAtRules
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noUselessEscapeInString
    suspicious/noUselessRegexBackrefs
    suspicious/noVar
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useBiomeIgnoreFolder
    suspicious/useDefaultSwitchClauseLast
    suspicious/useErrorMessage
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useGuardForIn
    suspicious/useIsArray
    suspicious/useNamespaceKeyword
    suspicious/useNumberToFixedDigitsArgument
    suspicious/useStaticResponseMethods
    suspicious/useStrictMode

Workspace:
  Open Documents:               0
```

### Rule name

noParametersOnlyUsedInRecursion

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=ZgB1AG4AYwB0AGkAbwBuACAAbgBvAHQAUgBlAGMAdQByAHMAaQB2AGUAKABhAHIAZwApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAGEAcgBnADsACgB9AAoACgBjAG8AbgBzAHQAIABvAGIAagAgAD0AIAB7AAoAIAAgAG4AbwB0AFIAZQBjAHUAcgBzAGkAdgBlACgAYQByAGcAKQAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAbgBvAHQAUgBlAGMAdQByAHMAaQB2AGUAKABhAHIAZwApADsACgAgACAAfQAKAH0A&language=js

### Expected result

It should not flag parameters of non-recursive functions.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by matanshavit**
## Summary
Compare function bindings in addition to names for recursion detection. This prevents false positives when a method has the same name as an outer function but calls the outer function (not itself). Fixes #8004 
related - #7970 refactors and additional comments that were requested for the rule file

## AI assistance notice
This PR was written primarily by Claude Code, with changes from the author. As the human author, I have reviewed the code thoroughly and take full responsibility for its contents.

## Test Plan

Added a valid test and snapshot for the example shown in the issue. The test fails without the production change, confirming the issue, and passes after the production file change, confirming the solution.

## Docs

Doc comment on new method for function bindings

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs [hunk 1]
```diff
@@ -250,6 +255,50 @@ fn get_function_name(parent_function: &AnyJsParameterParentFunction) -> Option<T
...
+                    break;
+                }
+            }
+            None
+        }
+        // Methods are property names, not bindings.
+        // In these cases, rely on the name-based comparison
+        // because methods are scoped to the object or class
+        _ => None,
+    }
```
[the remark this answers is not in the document]
Comment (matanshavit) [reply crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs:304]: Good point! Addressed with new commit, including a new test case

[the remark this answers is not in the document]
Comment (matanshavit) [reply crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs:304]: see current lines 290-300

File: crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs [hunk 2]
```diff
@@ -250,6 +255,63 @@ fn get_function_name(parent_function: &AnyJsParameterParentFunction) -> Option<T
...
+            .id()
+            .and_then(|any_binding| any_binding.as_js_identifier_binding().cloned())
+            .map(|id| model.as_binding(&id)),
+        AnyJsParameterParentFunction::JsArrowFunctionExpression(arrow) => {
+            // For arrow functions, find the binding from the surrounding context
+            let arrow_syntax = arrow.syntax();
+            for ancestor in arrow_syntax.ancestors() {
+                if ancestor == *arrow_syntax {
+                    continue;
+                }
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs]: Same mistake as before. You can use `skip(1)`

File: crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs [hunk 3]
```diff
@@ -348,7 +415,35 @@ fn is_recursive_call(call: &JsCallExpression, function_name: Option<&TokenText>)
...
     // Simple identifier: foo()
     if let Some(ref_id) = expr.as_js_reference_identifier() {
-        return ref_id.name().ok().is_some_and(|n| n.text() == name.text());
+        // First check for a matching name
+        let name_matches = ref_id.name().ok().is_some_and(|n| n.text() == name.text());
+        if !name_matches {
+            return false;
+        }
+
+        // Try to resolve the binding of the reference
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs]:
```suggestion
```

Make sure you leave comments that are useful

File: crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs [hunk 4]
```diff
@@ -348,7 +415,35 @@ fn is_recursive_call(call: &JsCallExpression, function_name: Option<&TokenText>)
...
+        let called_binding = model.binding(&ref_id);
+
+        // Compare bindings
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs]:
```suggestion
```

File: crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs [hunk 5]
```diff
@@ -348,7 +415,35 @@ fn is_recursive_call(call: &JsCallExpression, function_name: Option<&TokenText>)
 
     // Simple identifier: foo()
     if let Some(ref_id) = expr.as_js_reference_identifier() {
-        return ref_id.name().ok().is_some_and(|n| n.text() == name.text());
+        // First check for a matching name
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/nursery/no_parameters_only_used_in_recursion.rs]:
```suggestion
```

**Review by ematipico — CHANGES_REQUESTED** [review]

**Comment by ematipico** [comment]
Also, changeset is missing...

File: .changeset/cute-moons-obey.md [hunk 6]
```diff
@@ -0,0 +1,25 @@
+---
+"@biomejs/biome": patch
+---
+
+---
+
+## "@biomejs/biome": patch
```
Comment (ematipico) [inline .changeset/cute-moons-obey.md]:
```suggestion
```

File: .changeset/cute-moons-obey.md [hunk 7]
```diff
@@ -0,0 +1,24 @@
+---
+"@biomejs/biome": patch
+---
+
+---
+
+
```
Comment (dyc3) [inline .changeset/cute-moons-obey.md]: nit: there's an extra fence here
```suggestion
```

**Review by dyc3 — APPROVED** [review]
