### PR TITLE
fix(cli): prevent overwriting paths when using `--staged` or `--changed` options

### LINKED ISSUE #3069: 🐛 --staged regression in v1.8.0
### Environment information

```block
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

As of v1.8.0, the `--staged` flag doesn’t seem to work properly anymore. In v1.7.3, it would **only** run on staged files. But in v1.8.0, we get reports in files that are not staged (not even touched, for that matter). 

I _suspect_ the error to be related to [this merge-request](https://github.com/biomejs/biome/pull/2726), since it updated which files would end up being considered. I may be wrong.

### Expected result

Only the files that are staged by git (or whatever VCS is supported) should be linted when running Biome with the --staged flag.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by unvalley**
## Summary

Closes #3069 

### Context: 

The PR #2726 overwrite the `biome (lint|format|check|ci)` command's target path when the path is empty.
But, when using `--staged` and `--changed` options, the path would be **intentionally** empty. When there is no file in staging (`--staged`) or there is no difference from a certain branch (`--changed`), the file to be executed need not exist.

So, in this PR, make sure that paths are not overwritten when either `--staged` or `--changed` is used.

## Test Plan

Added snapshot cases.
And manually tested `--staged` and `--changed` commands.

### CODE REVIEW

**Review by Conaclos — APPROVED** [review]

File: crates/biome_cli/src/execute/traverse.rs [hunk 1]
```diff
@@ -38,14 +38,19 @@ pub(crate) fn traverse(
...
+        match &execution.traversal_mode {
             TraversalMode::Check { .. }
             | TraversalMode::Lint { .. }
             | TraversalMode::Format { .. }
-            | TraversalMode::CI { .. } => match current_dir() {
-                Ok(current_dir) => inputs.push(current_dir.into_os_string()),
-                Err(err) => return Err(CliDiagnostic::io_error(err)),
-            },
+            | TraversalMode::CI { .. } => {
+                // The `--staged` or `--changed` flags are intentionally empty, so we ignore them.
```
Comment (unvalley) [inline crates/biome_cli/src/execute/traverse.rs:46]:
```suggestion
                // If `--staged` or `--changed` is specified, it's acceptable for them to be empty, so ignore it.
```
