### PR TITLE
feat: apply fix to use consistent method signatures

### LINKED ISSUE #8780: 📎 Add code fix for `useConsistentMethodSignatures`
### Description

Port [`method-signature-style`](https://typescript-eslint.io/rules/method-signature-style/) from TSEslint.

Originally https://github.com/biomejs/biome/discussions/8497

EDIT: As of #8786, the rule has been implemented but no rule fix exists as of yet.

### PR DESCRIPTION
**Pull request by ViniciusDev26**
> This PR was written with the assistance of Claude Code (AI). The implementation,
  > decisions, and review were done collaboratively with the AI.

  ## Summary

  Adds an unsafe auto-fix to the `useConsistentMethodSignatures` rule, which was
  left open in #8786.

  Closes #8780.

  The fix converts between method-style and property-style signatures depending
  on the configured `style` option:

  - **method → property** (default): `method(arg: string): void` → `method: (arg: string) => void`
  - **property → method** (`style: "method"`): `method: (arg: string) => void` → `method(arg: string): void`

  The fix is intentionally skipped in cases where conversion would be unsafe:
  - **Overloaded methods**: converting multiple signatures with the same name would
    require generating intersection types (e.g. `((x: string) => void) & ((x: number) => void)`).
  - **`readonly` properties**: methods cannot have a `readonly` modifier.

  ## Test Plan

  Existing snapshot tests were updated to include the fix output. All spec tests pass:

  ```shell
  cargo test -p biome_js_analyze use_consistent_method_signatures
```
  Docs

  No new options were added. Documentation is already present in the rule's inline rustdoc from #8786.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/nursery/use_consistent_method_signatures.rs [hunk 1]
```diff
@@ -183,9 +188,7 @@ declare_lint_rule! {
         recommended: false,
         issue_number: Some("8780"),
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/nursery/use_consistent_method_signatures.rs]: This would close the issue right? If so, we can remove `issue_number`.

File: crates/biome_js_analyze/src/lint/nursery/use_consistent_method_signatures.rs [hunk 2]
```diff
@@ -247,6 +250,157 @@ impl Rule for UseConsistentMethodSignatures {
...
+    Some(builder.build())
+}
+
+/// Returns `true` if `node` is one of multiple overloads — i.e. the parent type member list
+/// contains more than one method signature with the same name.
+fn has_method_overloads(node: &TsMethodSignatureTypeMember) -> bool {
+    inner(node).unwrap_or(false)
+}
+
+fn inner(node: &TsMethodSignatureTypeMember) -> Option<bool> {
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/nursery/use_consistent_method_signatures.rs]: nit: the name of this function could be better
