### PR TITLE
fix(lint): preserve ternary branch comments in noNegationElse

### LINKED ISSUE #9629: 🐛 `noNegationElse` improperly handles comments in ternaries
### Environment information

<details>

```bash

CLI:
  Version:                      2.4.9
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v24.9.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/10.31.0

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false
  HTML full support enabled:    unset

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExcessiveCognitiveComplexity
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noImportantStyles
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringConcat
    complexity/noUselessStringRaw
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefined
    complexity/noUselessUndefinedInitialization
    complexity/noVoid
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useIndexOf
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useSimpleNumberKeys
    complexity/useWhile
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noPrivateImports
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUndeclaredDependencies
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useGraphqlNamedOperations
    correctness/useIsNan
    correctness/useParseIntRadix
    correctness/useSingleJsDocAsterisk
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    nursery/noFloatingPromises
    nursery/noMisusedPromises
    nursery/noMultiAssign
    nursery/noMultiStr
    nursery/noNestedPromises
    nursery/noParametersOnlyUsedInRecursion
    nursery/noProto
    nursery/noReturnAssign
    nursery/noShadow
    nursery/useArraySortCompare
    nursery/useExhaustiveSwitchCases
    nursery/useFind
    nursery/useRegexpExec
    nursery/useSpread
    performance/noAccumulatingSpread
    performance/noBarrelFile
    performance/noDelete
    performance/noDynamicNamespaceImportAccess
    performance/noNamespaceImport
    security/noBlankTarget
    security/noGlobalEval
    style/noCommonJs
    style/noDefaultExport
    style/noDescendingSpecificity
    style/noNamespace
    style/noNegationElse
    style/noNestedTernary
    style/noParameterAssign
    style/noParameterProperties
    style/noRestrictedTypes
    style/noShoutyConstants
    style/noSubstr
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/noYodaExpression
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useAtIndex
    style/useBlockStatements
    style/useCollapsedElseIf
    style/useCollapsedIf
    style/useConsistentArrayType
    style/useConsistentBuiltinInstantiation
    style/useConsistentObjectDefinitions
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useExplicitLengthCheck
    style/useExportType
    style/useFilenamingConvention
    style/useForOf
    style/useGroupedAccessorPairs
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useObjectSpread
    style/useReadonlyClassProperties
    style/useShorthandAssign
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useThrowNewError
    style/useThrowOnlyError
    style/useTrimStartEnd
    suspicious/noApproximativeNumericConstant
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noBiomeFirstException
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noConstantBinaryExpressions
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noEvolvingTypes
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportCycles
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noNonNullAssertedOptionalChain
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noQuickfixBiome
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noTsIgnore
    suspicious/noUnknownAtRules
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noUselessEscapeInString
    suspicious/noUselessRegexBackrefs
    suspicious/noVar
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useBiomeIgnoreFolder
    suspicious/useDefaultSwitchClauseLast
    suspicious/useErrorMessage
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useGuardForIn
    suspicious/useIsArray
    suspicious/useIterableCallbackReturn
    suspicious/useNamespaceKeyword
    suspicious/useNumberToFixedDigitsArgument

Workspace:
  Open Documents:               0

```

</details>

### What happened?

There seems to be a bug with the `noNegationElse` fixer, it's not handling comments properly in ternaries (2.4.9):
```diff
   const keyName =
-    obj[val] !== undefined
+    obj[val] === undefined
       ? // TS reverse mapped enum
-        (obj[val] as string)
-      : // Normal enum / `const object`
         // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
-        (testEnumValueToKey(obj as NormalEnum<E>, val) as string);
+        (testEnumValueToKey(obj as NormalEnum<E>, val) as string)
+      : (obj[val] as string);
```
```ts
// before
  const keyName =
    obj[val] !== undefined
      ? // TS reverse mapped enum <-- not moved, becomes wrongly positioned after fixer is run
        (obj[val] as string)
      : // Normal enum / `const object` <-- deleted entirely
        // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
        (testEnumValueToKey(obj as NormalEnum<E>, val) as string);
// after
  const keyName =
    obj[val] === undefined
      ? // TS reverse mapped enum <-- now in the wrong spot
        // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
        (testEnumValueToKey(obj as NormalEnum<E>, val) as string)
      : (obj[val] as string);
```

Minimal reproduction: https://github.com/DayKev/no-negation-else
(The playground doesn't seem to be applying the fixer for `noNegationElse` for some reason ([example](https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&lintRules=noNegationElse&analyzerFixMode=safeAndUnsafeFixes&tab=formatter&pane=Diagnostics&code=IAAgAGMAbwBuAHMAdAAgAGsAZQB5AE4AYQBtAGUAIAA9AAoAIAAgACAAIABvAGIAagBbAHYAYQBsAF0AIAAhAD0APQAgAHUAbgBkAGUAZgBpAG4AZQBkAAoAIAAgACAAIAAgACAAPwAgAC8ALwAgAFQAUwAgAHIAZQB2AGUAcgBzAGUAIABtAGEAcABwAGUAZAAgAGUAbgB1AG0ACgAgACAAIAAgACAAIAAgACAAKABvAGIAagBbAHYAYQBsAF0AIABhAHMAIABzAHQAcgBpAG4AZwApAAoAIAAgACAAIAAgACAAOgAgAC8ALwAgAE4AbwByAG0AYQBsACAAZQBuAHUAbQAgAC8AIABgAGMAbwBuAHMAdAAgAG8AYgBqAGUAYwB0AGAACgAgACAAIAAgACAAIAAgACAALwAvACAAVABPAEQATwA6ACAARgBpAGcAdQByAGUAIABvAHUAdAAgAGEAIAB3AGEAeQAgAHQAbwAgAGMAYQBjAGgAZQAgAHQAaABlACAAbgBhAG0AZQBzACAAbwBmACAAYwBvAG0AbQBvAG4AbAB5AC0AdQBzAGUAZAAgAGUAbgB1AG0AIABuAHUAbQBiAGUAcgBzACAAZgBvAHIAIABwAGUAcgBmAG8AcgBtAGEAbgBjAGUAIABpAGYAIABuAGUAZQBkAGUAZAAKACAAIAAgACAAIAAgACAAIAAoAHQAZQBzAHQARQBuAHUAbQBWAGEAbAB1AGUAVABvAEsAZQB5ACgAbwBiAGoAIABhAHMAIABOAG8AcgBtAGEAbABFAG4AdQBtADwARQA%2BACwAIAB2AGEAbAApACAAYQBzACAAcwB0AHIAaQBuAGcAKQA7AA%3D%3D&language=ts)) so I made a repo instead)

### Expected result

I would expect the diff to look something like this:
```diff
   const keyName =
-    obj[val] !== undefined
-      ? // TS reverse mapped enum
-        (obj[val] as string)
-      : // Normal enum / `const object`
+    obj[val] === undefined
+      ? // Normal enum / `const object`
         // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
-        (testEnumValueToKey(obj as NormalEnum<E>, val) as string);
+        (testEnumValueToKey(obj as NormalEnum<E>, val) as string)
+      : // TS reverse mapped enum
+        (obj[val] as string);
```
Or in other words:
```ts
// input
const keyName =
  obj[val] !== undefined
    ? // TS reverse mapped enum
      (obj[val] as string)
    : // Normal enum / `const object`
      // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
      (testEnumValueToKey(obj as NormalEnum<E>, val) as string);

// expected output
const keyName =
  obj[val] === undefined
    ? // Normal enum / `const object`
      // TODO: Figure out a way to cache the names of commonly-used enum numbers for performance if needed
      (testEnumValueToKey(obj as NormalEnum<E>, val) as string)
    : // TS reverse mapped enum
      (obj[val] as string);
```

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by raashish1601**
## Summary
- preserve branch comments when style/noNegationElse inverts ternary expressions
- swap the ? / : trivia alongside the consequent and alternate expressions
- update the existing spec snapshot to lock in the corrected fixer output

## Testing
- cargo test -p biome_js_analyze --test spec_tests no_negation_else

Closes #9629.

### CODE REVIEW

File: crates/biome_js_analyze/tests/specs/style/noNegationElse/invalid.js [hunk 1]
```diff
@@ -20,6 +20,7 @@ if (a !== b) {
 !condition ? consequent : alternate;
 a != b ? consequent : alternate;
 a !== b ? consequent : alternate;
+!spaced ? left   : right;
 
 let a = !test ? c : d;
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/style/noNegationElse/invalid.js:25]: this does not demonstrate that the bug is fixed
