### PR TITLE
fix(lint): rename `noSemicolonInJsx` to `noSuspiciousSemicolonInJsx`

### LINKED ISSUE #2217: 💅 Rename `noSemicolonInJsx` rule?
### Environment information

```bash
irrelevant
```

### Rule name

noSemicolonInJsx

### Playground link

https://biomejs.dev/playground/?code=LwAvACAAaABhAGQAIAB0AG8AIABmAGkAbABsACAAdABoAGUAIAAiAFAAbABhAHkAZwByAG8AdQBuAGQAIABsAGkAbgBrACIAIABmAGkAZQBsAGQAIAB3AGkAdABoACAAcwBvAG0AZQB0AGgAaQBuAGcALgAuAC4A

### Expected result

The rule does not disallow all semicolons in JSX, only suspicious ones, so I find the name inadequate.
I had originally [proposed](https://github.com/biomejs/biome/issues/927#issuecomment-1829602600) "`noSuspiciousSemicolonInJSX`", which is better IMO. I'm open to alternatives.
I do realize that it'll end up under the `suspicious` group though, so maybe that's why it was named `noSemicolonInJsx`? Still not all semicolons in jsx are suspicious.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by fujiyamaorange**
## Summary
- Closes #2217 

## Test Plan
N/A

### CODE REVIEW

File: crates/biome_diagnostics_categories/src/categories.rs [hunk 1]
```diff
@@ -123,8 +123,8 @@ define_categories! {
     "lint/nursery/noNodejsModules": "https://biomejs.dev/linter/rules/no-nodejs-modules",
     "lint/nursery/noReExportAll": "https://biomejs.dev/linter/rules/no-re-export-all",
     "lint/nursery/noRestrictedImports": "https://biomejs.dev/linter/rules/no-restricted-imports",
-    "lint/nursery/noSemicolonInJsx": "https://biomejs.dev/linter/rules/no-semicolons-in-jsx",
     "lint/nursery/noSkippedTests": "https://biomejs.dev/linter/rules/no-skipped-tests",
+    "lint/nursery/noSuspiciousSemicolonInJsx": "https://biomejs.dev/linter/rules/no-suspicious-semicolons-in-jsx",
```
Comment (Sec-ant) [inline crates/biome_diagnostics_categories/src/categories.rs:127]: Is it `no-suspicious-semicolons-in-jsx` or `no-suspicious-semicolon-in-jsx`?

Comment (fujiyamaorange) [reply crates/biome_diagnostics_categories/src/categories.rs:127]: Thank you for the comment!
I'll fix it. 👍

Comment (fujiyamaorange) [reply crates/biome_diagnostics_categories/src/categories.rs]: Fixed in https://github.com/biomejs/biome/pull/2220/commits/4158fe8bf961da862ff4ceb3384ea7ae1958dc46

Please review it again when you have time!

**Review by Sec-ant — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/nursery/no_suspicious_semicolon_in_jsx.rs [hunk 2]
```diff
@@ -42,14 +42,14 @@ declare_rule! {
     /// }
     /// ```
     ///
-    pub NoSemicolonInJsx {
+    pub NoSuspiciousSemicolonInJsx {
         version: "1.6.0",
```
Comment (Sec-ant) [inline crates/biome_js_analyze/src/lint/nursery/no_suspicious_semicolon_in_jsx.rs:46]: Sorry for not being able to point this out early. I'm not sure if we should update this? @ematipico

Comment (ematipico) [reply crates/biome_js_analyze/src/lint/nursery/no_suspicious_semicolon_in_jsx.rs:46]: You're right. This new be `"next"` instead of `"1.6.0"`. @fujiyamaorange can you apply the change and run `just gen-lint` again?

**Review by Sec-ant — APPROVED** [review]

**Review by ematipico — APPROVED** [review]
