### PR TITLE
fix(lint/useJsxKeyInIterable): handle ternaries properly

### LINKED ISSUE #2468: 💅 `useJsxKeyInIterable` incorrect behavior: Cannot determine whether this child has the required key prop.
### Environment information

```bash
CLI:
  Version:                      1.7.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.20.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.7"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        style/noNonNullAssertion = "off"
                                suspicious/noExplicitAny = "off"

Workspace:
  Open Documents:               0
```

### Rule name

lint/correctness/useJsxKeyInIterable

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=YwBvAG4AcwB0ACAAYgByAGUAYQBkAGMAcgB1AG0AYgBzACAAPQAgAFsAewAgAHQAaQB0AGwAZQA6ACAAIgAxADEAMQAiACwAIABwAGEAdABoADoAIAAiAC8AIgAgAH0AXQA7AAoACgBjAG8AbgBzAHQAIABBAHAAcAAgAD0AIAAoACkAIAA9AD4AIAB7AAoACQByAGUAdAB1AHIAbgAgACgACgAJAAkAPABkAGkAdgA%2BAAoACQAJAAkAewBiAHIAZQBhAGQAYwByAHUAbQBiAHMALgBtAGEAcAAoACgAdgAsACAAaQApACAAPQA%2BAAoACQAJAAkACQBpACAAPQA9AD0AIAB0AGgAaQBzAC4AYgByAGUAYQBkAGMAcgB1AG0AYgBzAC4AbABlAG4AZwB0AGgAIAAtACAAMQAgAD8AIAAoAAoACQAJAAkACQAJADwAcwBwAGEAbgAgAGsAZQB5AD0AewB2AC4AcABhAHQAaAB9AD4AewB2AC4AdABpAHQAbABlAH0APAAvAHMAcABhAG4APgAKAAkACQAJAAkAKQAgADoAIAAoAAoACQAJAAkACQAJADwAZABpAHYAIABrAGUAeQA9AHsAdgAuAHAAYQB0AGgAfQA%2BAHsAdgAuAHQAaQB0AGwAZQB9ADwALwBkAGkAdgA%2BAAoACQAJAAkACQApAAoACQAJAAkAKQB9AAoACQAJADwALwBkAGkAdgA%2BAAoACQApADsACgB9ADsACgA%3D

### Expected result

no error tip

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

This is a continuation of #2667, and as such fixes somethings related to #2590.

Specifically, it handles ternaries in expressions like this:

```jsx
<>{data.map(a => a > 4 ? <h1 key={a}>{a}</h1> : <h2 key={a}>{a}</h2>)}</>
```

related to: #2590
fixes #2468

## Test Plan

Added tests.

```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

### CODE REVIEW

**Review by vohoanglong0107 — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs [hunk 1]
```diff
@@ -206,6 +206,19 @@ fn handle_potential_react_component(
...
 
     if is_inside_jsx {
+        if let AnyJsExpression::JsConditionalExpression(node) = node {
+            let results = [node.consequent().ok()?, node.alternate().ok()?]
+                .into_iter()
+                .filter_map(|node| handle_potential_react_component(node, model, is_inside_jsx))
+                .flatten()
+                .collect::<Vec<_>>();
+
+            return if !results.is_empty() {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:216]: We shouldn't create **a new vector**, only to check if it's empty. Can't we just call the handle function on the two nodes and check both results? A KISS solution fits better in this case

Comment (dyc3) [reply crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs:216]: Yeah tbh I didn't really like the potential unnecessary heap allocation here.

**Review by ematipico — APPROVED** [review]
Much better!
