### PR TITLE
fix(semantic): resolve Svelte $store references in semantic model

### LINKED ISSUE #6316: 💅 Svelte store dollar syntax unsupported
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           v22.16.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  false
  Enabled rules:
    complexity/noAdjacentSpacesInRegex
    complexity/noExtraBooleanCast
    complexity/noForEach
    complexity/noStaticOnlyClass
    complexity/noUselessCatch
    complexity/noUselessEscapeInRegex
    complexity/noUselessSwitchCase
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/useDateNow
    complexity/useFlatMap
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noSwitchDeclarations
    correctness/noUndeclaredVariables
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    style/noCommonJs
    style/noNamespace
    style/noSubstr
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useAtIndex
    style/useCollapsedIf
    style/useExplicitLengthCheck
    style/useFilenamingConvention
    style/useForOf
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useThrowNewError
    style/useTrimStartEnd
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCompareNegZero
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noEmptyBlockStatements
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noImportAssign
    suspicious/noIrregularWhitespace
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noShadowRestrictedNames
    suspicious/noSparseArray
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noWith
    suspicious/useErrorMessage
    suspicious/useGetterReturn
    suspicious/useNamespaceKeyword
    suspicious/useNumberToFixedDigitsArgument

Workspace:
  Open Documents:               0
```

### Rule name

lint/correctness/noUndeclaredVariables

### Playground link

https://github.com/immich-app/immich/pull/19145

### Expected result

Any instances of a svelte store that is being accessed with the `$` syntax gets flagged as an undeclared variable.

```
src\lib\components\admin-page\jobs\jobs-panel.svelte:132:20 lint/correctness/noUndeclaredVariables ━━━━━━━━━━━━━━━━━

  × The $t variable is undeclared.

    130 │       subtitle: $t('admin.video_conversion_job_description'),
    131 │       allText: $t('all'),
  > 132 │       missingText: $t('missing'),
        │                    ^^
    133 │     },
    134 │     [JobName.StorageTemplateMigration]: {
```

This currently seems like th main cause of false positives over at https://github.com/immich-app/immich , where we're trying out alternatives to eslint :)

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Hugo-Polloli**
Fixes #6316

> This PR was created with AI assistance (Codex), I reviewed every single line.

## Summary

This PR enforces one invariant across the pipeline: in Svelte-flavored code, `$store` must resolve consistently to the backing `store` binding (or report consistently when missing).

The fix spans semantic extraction, analyzer policy, rename, and service routing because the bug crossed those layers. Keeping any layer on old behavior reintroduced mismatches.

- Added/propagated `SemanticFlavor` so Svelte-specific identifier behavior is modeled in semantic extraction/builder paths.
- Resolved `$store` read behavior semantically while preserving unresolved diagnostics for real misses.
- Prevented write-sensitive false positives for Svelte store assignment syntax (`$store = ...`) in rules relying on semantic writes.
- Tightened `noUndeclaredVariables` fallback policy: `$name -> name` fallback applies to configured globals and embedded bindings, but not generic env globals (for example avoids `$location` false negatives).
- Fixed rename for Svelte store references so transformed names preserve `$` and collision checks validate the effective transformed name.
- Made capability routing path-aware for Svelte source modules (`.svelte.js` and `.svelte.ts`) so they use JS capabilities, while `.svelte` component documents keep Svelte handler behavior.

This also establishes reusable Svelte semantic infrastructure (flavor + routing/plumbing consistency) that future Svelte 5 rune semantics can build on without another cross-layer refactor.

## Test Plan

- Verified semantic model behavior for Svelte flavor:
  - `$store` resolves to declared `store` bindings,
  - rune-like names are not misnormalized,
  - multi-`$` edge cases remain diagnostic,
  - type-only value mismatch cases remain diagnostic.
- Verified undeclared-variable behavior across file shapes:
  - `.svelte`, `.svelte.ts`, and `.svelte.js` store dereference scenarios,
  - configured-global store fallback,
  - built-in-global false-negative guard (`$location` now reports undeclared unless explicitly backed by policy/binding).
- Verified write-sensitive rule behavior:
  - valid Svelte store assignments do not trigger `noConstAssign`/`noImportAssign` false positives.
- Verified rename behavior:
  - store dereference renames preserve `$` prefix,
  - transformed-name collision cases are correctly rejected.
- Verified service capability routing:
  - `.svelte.js` and `.svelte.ts` source modules expose JS capabilities (including rename and pull diagnostics/actions),
  - `.svelte` component files keep Svelte capability behavior.

## Docs

- Not required for this bugfix.

### CODE REVIEW

File: crates/biome_js_syntax/src/file_source.rs [hunk 1]
```diff
@@ -182,6 +182,16 @@ pub struct JsFileSource {
...
 
 impl JsFileSource {
+    const SVELTE_FILE_SUFFIXES: [&str; 7] = [
+        ".svelte",
+        ".svelte.js",
+        ".svelte.ts",
+        ".svelte.test.ts",
+        ".svelte.test.js",
+        ".svelte.spec.ts",
+        ".svelte.spec.js",
```
Comment (dyc3) [inline crates/biome_js_syntax/src/file_source.rs]: can you point to docs that say these are valid suffixes?

**Comment by Hugo-Polloli** [comment]
(this is just some targetted tests for now, not ready for review, I'd prefer a real "semantic" resolution over the current monkey patch of this PR, trying to see how big a proper fix would be)

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs [hunk 2]
```diff
@@ -148,3 +160,40 @@ fn is_global(reference_name: &str, source_type: &JsFileSource) -> bool {
         Language::TypeScript { .. } => is_js_global(reference_name) || is_ts_global(reference_name),
     }
 }
+
+fn is_svelte_store_reference_in_scope(
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: I would rather we treat the `$foo` reference as a reference to `foo` in the actual semantic model, so that it can affect all rules that use the semantic model.

**Review by dyc3 — CHANGES_REQUESTED** [review]

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs (hunk 2 above)
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: yeah exactly i'm looking into it right now, sorry you wasted your time I was till working on this that's why I set it to draft sry !

Comment (dyc3) [reply crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: no worries. I reviewed it to list out the issues so you can resolve them as you see fit.

File: crates/biome_js_syntax/src/file_source.rs (hunk 1 above)
Comment (Hugo-Polloli) [reply crates/biome_js_syntax/src/file_source.rs]: For the `.test` ones, the doc [here ](https://svelte.dev/docs/svelte/testing) mentions `multiplier.svelte.test.js` (and I inferred ts too)
For `.spec`, this is a widely used convention across test frameworks, so I inferred valid use for that too

I could narrow if you prefer to?

Comment (dyc3) [reply crates/biome_js_syntax/src/file_source.rs]: naw that's enough justification for me :+1:

**Comment by Hugo-Polloli** [comment]
@dyc3
Just pushed a version that implements the semantic-model approach !
It includes globals/rename coverage and `$$...` regression handling :)

Also, as a side-note, running `just r` currently regenerates `FormatAnyHtmlAttributeInitializer`/`FormatAnySvelteBindingProperty` into code that conflicts with existing `.with_options(true)` call sites, which appears to stem from the earlier HTML/Svelte formatter work in #8719; I kept this PR scoped to #6316 to avoid unrelated churn, but I can include that follow-up fix if you prefer.

File: crates/biome_js_semantic/src/events.rs [hunk 3]
```diff
@@ -1151,6 +1080,147 @@ impl SemanticEventExtractor {
...
+                        // An import namespace imported as a type can only be
+                        // used in a qualified name, e.g `Namespace.Type`.
+                        // Thus, the reference is unresolved.
+                        // Note that we don't need to forward the reference in a parent scope,
+                        // because an import namespace is already in the root scope.
+                        self.stash.push_back(SemanticEvent::UnresolvedReference {
+                            is_read: !reference.is_write(),
+                            range: reference.range(),
+                        });
+                    }
```
[the remark this answers is not in the document]
Comment (Hugo-Polloli) [reply crates/biome_js_semantic/src/events.rs:1218]: Addressed this in a follow-up commit.
For unqualified namespace type-import references, we still emit an unresolved reference (so noUndeclaredVariables reports correctly), but we also keep usage tracking (so noUnusedImports does not regress and incorrectly mark the import as unused)

This dual behavior is temporary and reflects a current semantic-model limitation: we cannot yet represent “invalid reference for declaration semantics” separately from “counts as import usage for unused-import analysis.” I added linked TODOs (semantic-invalid-namespace-type-ref) in semantic extraction and semantic-model tests to make that explicit and track the architectural follow-up.

Also addressed the remaining nits from that review batch

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs [hunk 4]
```diff
@@ -80,17 +88,22 @@ impl Rule for NoUndeclaredVariables {
...
                 }
 
-                let embedded_bindings = ctx
-                    .get_service::<EmbeddedBindings>()
-                    .expect("embedded bindings service");
-                if embedded_bindings.contains_binding(text) {
+                if embedded_bindings.contains_binding(text)
+                    || svelte_store_name
+                        .is_some_and(|store_name| embedded_bindings.contains_binding(store_name))
+                {
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: It's not really clear to me why the changes to the rule are necessary if the fix is in the semantic model.

File: crates/biome_js_semantic/src/semantic_model.rs [hunk 5]
```diff
@@ -41,6 +41,37 @@ pub use scope::*;
...
+impl SemanticFlavor {
+    pub fn from_source_type_and_path(source_type: &JsFileSource, file_path: &str) -> Self {
+        if source_type.as_embedding_kind().is_svelte()
+            || JsFileSource::is_svelte_file_path(file_path)
+        {
+            Self::Svelte
+        } else {
+            Self::Vanilla
+        }
+    }
```
Comment (ematipico) [inline crates/biome_js_semantic/src/semantic_model.rs]: If the file path isn't saved, it's not needed. And it's not actually needed because `JsFileSource` must be our source of truth

File: crates/biome_js_semantic/src/semantic_model.rs [hunk 6]
```diff
@@ -41,6 +41,37 @@ pub use scope::*;
...
+
+    pub fn from_file_path(file_path: &str) -> Self {
+        if JsFileSource::is_svelte_file_path(file_path) {
+            Self::Svelte
+        } else {
+            Self::Vanilla
+        }
+    }
```
Comment (ematipico) [inline crates/biome_js_semantic/src/semantic_model.rs]: Remove

File: crates/biome_js_syntax/src/file_source.rs [hunk 7]
```diff
@@ -360,6 +379,35 @@ impl JsFileSource {
         &self.embedding_kind
     }
 
+    /// Returns true for Svelte component files and Svelte module variants.
+    pub fn is_svelte_file_path(path: &str) -> bool {
+        let path = path.to_ascii_lowercase_cow();
+        Self::SVELTE_FILE_SUFFIXES
+            .iter()
+            .any(|suffix| path.ends_with(suffix))
+    }
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs]: We already have `try_from_well_known`, which must cover these new cases. Let's not stray too much from the patterns we use internally

File: crates/biome_js_syntax/src/file_source.rs [hunk 8]
```diff
@@ -360,6 +379,35 @@ impl JsFileSource {
...
+
+    pub fn is_svelte_rune(name: &str) -> bool {
+        Self::SVELTE_RUNES.contains(&name)
+    }
+
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs]: This function doesn't belong to `JsFileSource`. At most, it belongs to the semantic model

File: crates/biome_js_syntax/src/file_source.rs [hunk 9]
```diff
@@ -360,6 +379,35 @@ impl JsFileSource {
...
+    /// Returns the store binding name for Svelte auto-subscription references (`$store` -> `store`).
+    /// It only matches a single leading `$` and excludes runes.
+    pub fn svelte_store_reference_name(reference_name: &str) -> Option<&str> {
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs]: Ditto, this doesn't belong to `JsFileSource`. Also, when you move this into the semantic model, this **can't** be a static method. If we're inside a Vanilla semantic model, `reference_name` will **never** be a rune.

File: crates/biome_js_syntax/src/file_source.rs [hunk 10]
```diff
@@ -360,6 +379,35 @@ impl JsFileSource {
...
+            return None;
+        }
+        let store_name = reference_name.strip_prefix('$')?;
+        if store_name.is_empty() || store_name.starts_with('$') {
+            return None;
+        }
+        Some(store_name)
+    }
+
+    pub fn svelte_runes() -> &'static [&'static str; 7] {
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs]: Same, it doesn't belong to `JsFileSource`.

File: crates/biome_service/src/file_handlers/html.rs [hunk 11]
```diff
@@ -1005,20 +999,31 @@ pub(crate) fn parse_embedded_script(
...
-            };
+            js_document_services_for_snippet(settings, path, &file_source, &embedded_content);
 
         Some((embedded_content, js_services, file_source))
     } else {
         None
     }
 }
 
+fn js_document_services_for_snippet(
```
Comment (ematipico) [inline crates/biome_service/src/file_handlers/html.rs]: Doc strings are missing

File: crates/biome_service/src/file_handlers/javascript.rs [hunk 12]
```diff
@@ -1364,6 +1346,13 @@ fn rename(
     }
 }
 
+fn semantic_model_options_for_path(path: &BiomePath) -> SemanticModelOptions {
+    SemanticModelOptions {
+        flavor: SemanticFlavor::from_file_path(path.as_path().as_str()),
+        ..SemanticModelOptions::default()
+    }
+}
```
Comment (ematipico) [inline crates/biome_service/src/file_handlers/javascript.rs]: This could be implemented using `impl From<&BiomePath> for SemanticModelOptions`. It feels more idiomatic. Plus we should use `JsFileSource`

File: crates/biome_service/src/workspace/document/mod.rs [hunk 13]
```diff
@@ -376,10 +376,13 @@ pub struct JsDocumentServices {
 }
 
 impl JsDocumentServices {
-    pub fn with_js_semantic_model(mut self, root: &AnyJsRoot) -> Self {
+    pub fn with_js_semantic_model(mut self, root: &AnyJsRoot, flavor: SemanticFlavor) -> Self {
```
Comment (ematipico) [inline crates/biome_service/src/workspace/document/mod.rs]: I would prefer keep this function as is, or provide the `&JsFileSource` instead of the flavor, so we can do `SemanticModelOptions::from(file_source)`

**Review by ematipico — CHANGES_REQUESTED** [review]
There are changes I would like to see. Many functions are in the wrong place

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs (hunk 4 above)
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: the semantic fix covers the lexical case where `$store` resolves to an actual `store` binding in scope. But `noUndeclaredVariables` also has its own policy layer for things like `javascript.globals` config and embedded bindings, which don't flow through the semantic model end-to-end yet. So without the rule-side change those cases would misbehave

**Comment by Hugo-Polloli** [comment]
> There are changes I would like to see. Many functions are in the wrong place

hey so i've reworked this from the ground up and it ended up getting pretty big. I had to add some pretty important new internal plumbing, that is for now tentatively named SemanticFlavor (so that we can interpret .svelte.js and .svelte.ts modules properly)
but this is quite important groundwork (it opens the door to first-class Svelte 5 rune semantics), so I'm open to any pushback or if you had any other way in mind

File: crates/biome_service/src/file_handlers/html.rs (hunk 11 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/file_handlers/html.rs]: added

File: crates/biome_js_analyze/src/utils/rename.rs [hunk 14]
```diff
@@ -260,7 +262,20 @@ impl RenameSymbolExtensions for BatchMutation<JsLanguage> {
                 continue;
             };
 
-            let new_name = make::ident(new_name);
+            let next_reference_name = renamed_reference_name_for_svelte_store(
```
Comment (Hugo-Polloli) [inline crates/biome_js_analyze/src/utils/rename.rs]: There is one speicific policy point I’d like your guidance on: here we could block rename targets that would turn store refs into known rune names (eg. `store` -> `state` producing `$state`). Do we keep the current (permissive) behavior or do you want to formalize rune-aware rename constraints now?

Comment (dyc3) [reply crates/biome_js_analyze/src/utils/rename.rs]: For the sake of simplicity, we can keep the permissive behavior.

File: crates/biome_cli/tests/cases/handle_svelte_files.rs [hunk 15]
```diff
@@ -543,6 +590,85 @@ fn check_stdin_write_unsafe_successfully() {
...
+}
+
+#[test]
+fn no_undeclared_variables_handles_svelte_js_module_store_dereference() {
+    assert_no_undeclared_variables_svelte_snapshot(
+        "file.svelte.js",
+        SVELTE_MODULE_STORE_DEREFERENCE_FILE,
+        "no_undeclared_variables_handles_svelte_js_module_store_dereference",
+    );
+}
```
Comment (dyc3) [inline crates/biome_cli/tests/cases/handle_svelte_files.rs:586]: I appreciate wanting to DRY the test code up, but its not really the pattern we have for the cli tests. It's easier to tell what the test is asserting for when the full implementation is inlined.

File: crates/biome_cli/tests/cases/handle_svelte_files.rs [hunk 16]
```diff
@@ -40,6 +40,53 @@ var foo: string = "";
...
+$store;
+$missing;"#;
+
+const SVELTE_MODULE_TYPE_ONLY_STORE_DEREFERENCE_FILE: &str = r#"type store = number;
+$store;"#;
+
+const SVELTE_TS_SCRIPT_TYPE_GLOBAL_FILE: &str = r#"<script lang="ts">
+type B<T> = PromiseLike<T>;
+</script>
+<div></div>"#;
```
Comment (dyc3) [inline crates/biome_cli/tests/cases/handle_svelte_files.rs]: 1. Could we use more realistic examples? You probably only need one test tbh.
2. Missing a comment explaining what svelte stores are. We need to give context for these tests because not everybody working on biome is a svelte expert.

File: crates/biome_cli/tests/cases/handle_svelte_files.rs [hunk 17]
```diff
@@ -40,6 +40,53 @@ var foo: string = "";
...
+
+const SVELTE_MODULE_STORE_DEREFERENCE_FILE: &str = r#"const store = 1;
+$store;
+$missing;"#;
+
+const SVELTE_MODULE_TYPE_ONLY_STORE_DEREFERENCE_FILE: &str = r#"type store = number;
+$store;"#;
+
+const SVELTE_TS_SCRIPT_TYPE_GLOBAL_FILE: &str = r#"<script lang="ts">
+type B<T> = PromiseLike<T>;
```
Comment (dyc3) [inline crates/biome_cli/tests/cases/handle_svelte_files.rs]: `type B<T> = PromiseLike<T>;` has nothing to do with svelte stores. Why is this here?

File: crates/biome_js_semantic/src/semantic_model/flavor.rs [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+        if source_type.as_embedding_kind().is_svelte() {
+            Self::Svelte
+        } else {
+            Self::Vanilla
+        }
+    }
+}
+
+pub fn svelte_runes() -> &'static [&'static str; 7] {
+    &SVELTE_RUNES
```
Comment (dyc3) [inline crates/biome_js_semantic/src/semantic_model/flavor.rs]: nit: useless function, you can make `SVELTE_RUNES` pub

File: crates/biome_service/src/file_handlers/javascript.rs [hunk 19]
```diff
@@ -1364,6 +1352,24 @@ fn rename(
     }
 }
 
+fn js_file_source_for_path(path: &BiomePath) -> JsFileSource {
+    JsFileSource::try_from(path.as_path()).unwrap_or_default()
+}
```
Comment (dyc3) [inline crates/biome_service/src/file_handlers/javascript.rs]: nit: trivial function, I'd inline it

File: crates/biome_service/src/file_handlers/html.rs (hunk 11 above)
Comment (ematipico) [reply crates/biome_service/src/file_handlers/html.rs]: I understand now, but this function shouldn't be here, it doesn' have anything to do with html

File: crates/biome_js_analyze/src/utils/rename.rs
Comment (ematipico) [inline crates/biome_js_analyze/src/utils/rename.rs:1]: Revert all the code here. We don't use this capability at the moment

File: crates/biome_js_analyze/src/services/semantic.rs [hunk 20]
```diff
@@ -91,21 +91,35 @@ where
...
         }
     }
 }
 
 impl Visitor for SemanticModelBuilderVisitor {
     type Language = JsLanguage;
 
-    fn visit(&mut self, event: &WalkEvent<JsSyntaxNode>, _ctx: VisitorContext<JsLanguage>) {
+    fn visit(&mut self, event: &WalkEvent<JsSyntaxNode>, ctx: VisitorContext<JsLanguage>) {
+        if !self.flavor_configured {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/services/semantic.rs]: I don't see the point of this flag. Even less because there are no docs. Remember to add docs strings, they help

File: crates/biome_service/src/workspace/server.rs [hunk 21]
```diff
@@ -1604,9 +1624,12 @@ impl Workspace for WorkspaceServer {
                 services = CssDocumentServices::default()
                     .with_css_semantic_model(&parsed.any_parse.tree())
                     .into();
-            } else if document_source.is_javascript_like() {
+            } else if document_source.is_javascript_like()
+                && let Some(source_type) =
+                    self.semantic_js_source_type(&path, document_source, &content)
+            {
```
Comment (ematipico) [inline crates/biome_service/src/workspace/server.rs]: I really don't understand what we're doing here. We already have `document_source` that provides all the information we need. Just use `if let DocumentSource::Js()` instead of is_javascript_like.

The function `semantic_js_source_type` isn't needed

File: crates/biome_service/src/workspace/server.rs [hunk 22]
```diff
@@ -1896,21 +1919,22 @@ impl Workspace for WorkspaceServer {
...
+                snippet_services: None,
             });
 
-            for embedded_node in embedded_snippets {
+            for embedded_node in &embedded_snippets {
                 let Some(file_source) = self.get_source(embedded_node.file_source_index()) else {
                     continue;
                 };
-                let capabilities = self.features.get_capabilities(file_source);
+                let capabilities = self.features.get_capabilities(&path, file_source);
```
Comment (ematipico) [inline crates/biome_service/src/workspace/server.rs]: Again, `file_source` is our source of truth. Once we have it, we don't need paths anymore

**Review by ematipico — CHANGES_REQUESTED** [review]
Still, there are many foundmental issues in the code

File: crates/biome_service/src/workspace/server.rs (hunk 21 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/workspace/server.rs]: Thanks, I've switched to `if let DocumentSource::Js()` and removed the `is_javascript_like()` branch :)

File: crates/biome_service/src/workspace/server.rs (hunk 22 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/workspace/server.rs]: From what I can understand, today `JsFileSource` cannot distinguish `.svelte` component documents from `.svelte.js/.svelte.ts` source modules. ie. they can collapse to the same Svelte embedding shape
But we need different handling for source-type inference and capability routing :/

Would you be ok with me making this distinction explicit in `JsFileSource` (or maybe embedding metadata?) which would remove path checks entirely, or do you have another idea in mind to handle this problem?

File: crates/biome_js_analyze/src/services/semantic.rs (hunk 20 above)
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/src/services/semantic.rs]: Thanks, I've simplified this:
I removed the `flavor_configured` flag and now configure flavor on root `Enter` and I added doc comments explaining why flavor is set there.  
Is that better?

**Review by dyc3 — COMMENTED** [review]
I'm wondering if it would make more sense to handle svelte stores at the parser level instead of this. We could implement a JsSyntaxFeature that can conditionally enable the syntax. Then the changes to the semantic model could be much more precise. What do you think @ematipico?

File: crates/biome_js_analyze/src/utils/rename.rs
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/src/utils/rename.rs:1]: Oops... Reverted, I didnt know rename was not available!

File: crates/biome_service/src/workspace/server.rs (hunk 22 above)
Comment (dyc3) [reply crates/biome_service/src/workspace/server.rs]: Yes, you should make the distinction in the `JsFileSource`.

File: crates/biome_service/src/file_handlers/javascript.rs (hunk 19 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/file_handlers/javascript.rs]: inlined !

File: crates/biome_js_semantic/src/semantic_model/flavor.rs (hunk 18 above)
Comment (Hugo-Polloli) [reply crates/biome_js_semantic/src/semantic_model/flavor.rs]: SVELTE_RUNES is now pub

File: crates/biome_cli/tests/cases/handle_svelte_files.rs (hunk 17 above)
Comment (Hugo-Polloli) [reply crates/biome_cli/tests/cases/handle_svelte_files.rs]: This one is indeed not about stores, but since this branch adds Svelte source-type propagation we need a guard for that path too
this specific test checks that `.svelte` + `<script lang="ts">` is still treated as TypeScript when `checkTypes: true` so `PromiseLike` stays recognized.
If source-type inference regresses to JavaScript this starts reporting a false undeclared error

File: crates/biome_cli/tests/cases/handle_svelte_files.rs (hunk 16 above)
Comment (Hugo-Polloli) [reply crates/biome_cli/tests/cases/handle_svelte_files.rs]: Yep good call, I updated this by switching the fixtures to realistic store usage (`writable(...)` + `$count`) and added a comment explaining Svelte store auto-subscription syntax. Let me know if the comment is explicit enough !

On the multiplicity of tests, this is intentional because they cover different paths (`.svelte`, `.svelte.ts`, `.svelte.js`, and type-only/invalid cases) that could regress independently. I've commented each one of them to make it clearer, hope this helps

File: crates/biome_cli/tests/cases/handle_svelte_files.rs (hunk 15 above)
Comment (Hugo-Polloli) [reply crates/biome_cli/tests/cases/handle_svelte_files.rs:586]: I removed that helper and inlined each test function

File: crates/biome_service/src/workspace/server.rs (hunk 22 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/workspace/server.rs]: Done.

I made the distinction explicit in `JsFileSource` by extending Svelte embedding metadata with `kind: SvelteFileKind` (variants: `Component` and `SourceModule`), so `.svelte` and `.svelte.ts/.svelte.js` no longer collapse to the same shape.

Why:
- `.svelte` component documents need `<script ...>` extraction/inference behavior
- `.svelte.ts` / `.svelte.js` are already full JS/TS source modules and should use JS capabilities directly

This in turn allowed me to remove path-based routing checks and now route from source metadata :)
- `SourceModule` -> JS capabilities
- `Component` -> Svelte handler behavior

A small nuance: for source-type inference specifically, component files are still inferred from `<script ...>` content (`SvelteFileHandler::file_source(content)`), but this is now triggered from source metadata (`is_svelte_component`) rather than path checks.

This keeps `file_source` as the single source of truth and avoids threading path everywhere.
I've also added comments for this new system along the line

File: crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts [hunk 23]
```diff
@@ -0,0 +1 @@
+$location;
```
Comment (ematipico) [inline crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts:2]: Why so many files? Can't you add all the bindings in one file? 

Also, add `// should generate diagnostics` at the top of the file. This is part of our infrastructure (covered in the contribution guide). Please apply the comment to all the file that are supposed to fail.

You should add `// should not generate diagnostics` for the other way around

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs [hunk 24]
```diff
@@ -69,7 +70,14 @@ impl Rule for NoUndeclaredVariables {
     type Options = NoUndeclaredVariablesOptions;
 
     fn run(ctx: &RuleContext<Self>) -> Self::Signals {
-        ctx.query()
+        let model = ctx.query();
+        let source_type = ctx.source_type::<JsFileSource>();
+        let embedded_bindings = ctx
+            .get_service::<EmbeddedBindings>()
+            .expect("embedded bindings service");
+        let flavor = SemanticFlavor::from(source_type);
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: Why are you computing the semantic flavour from `source_type`? Shouldn't you have this information inside `model` already?

File: crates/biome_js_syntax/src/file_source.rs [hunk 25]
```diff
@@ -135,6 +147,10 @@ pub enum EmbeddingKind {
     Svelte {
         /// Where the bindings are defined
         is_source: bool,
+        /// `kind` models the document shape (`.svelte` component vs
+        /// `.svelte.ts` / `.svelte.js` source module), while `is_source`
+        /// tracks whether bindings come from source code or template expressions.
+        kind: SvelteFileKind,
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs]: It's good that we documented the new stuff, however we didn't document how they differ. `SvelteFileKind` simply says "it's a component" or "it's a file" but it doesn't actually explain how this affects things.

File: crates/biome_js_syntax/src/file_source.rs [hunk 26]
```diff
@@ -387,6 +434,24 @@ impl JsFileSource {
...
+        let Some(file_name) = path.file_name() else {
+            return false;
+        };
+
+        file_name.ends_with(".svelte.ts")
+            || file_name.ends_with(".svelte.test.ts")
+            || file_name.ends_with(".svelte.spec.ts")
+            || file_name.ends_with(".svelte.js")
+            || file_name.ends_with(".svelte.test.js")
+            || file_name.ends_with(".svelte.spec.js")
```
Comment (ematipico) [inline crates/biome_js_syntax/src/file_source.rs:485]: What about mts, mjs, cts, cjs? What about .d.ts?

File: crates/biome_service/src/workspace/document/mod.rs [hunk 27]
```diff
@@ -373,14 +373,33 @@ impl CssDocumentServices {
...
-            SemanticModelOptions::default(),
+            SemanticModelOptions::from(source_type),
         ));
+        self.source_type = Some(*source_type);
         self
     }
+
+    /// Builds document services for a JS snippet and includes semantic data only
+    /// when analyzer-backed features are enabled.
+    pub fn for_js_snippet(
```
Comment (ematipico) [inline crates/biome_service/src/workspace/document/mod.rs]: The `for_*` prefix isn't idiomatic in the Rust world. Plus, it's not idiomatic to NOT type `Self` from a method that doesn't use `self` as parameter.

**Review by ematipico — COMMENTED** [review]
I think we're getting somewhere, and it's taking a good shape. There are still a few things to address

File: crates/biome_js_syntax/src/file_source.rs (hunk 26 above)
Comment (Hugo-Polloli) [reply crates/biome_js_syntax/src/file_source.rs:485]: I could only justify `.svelte.js` / `.svelte.ts` from Svelte's documented source-module model plus the `.svelte.test.*` variants from their testing docs.
I’m less confident about `.svelte.mjs` / `.svelte.mts` / `.svelte.cjs` / `.svelte.cts` being valid Svelte source modules, and for `.svelte.d.ts` specifically, it seems wrong for runtime Svelte semantics.
If you want, I don't mind broadening the matcher, but I preferred to keep it aligned with the suffixes I could actually justify from Svelte docs instead of guessing.

File: crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs (hunk 24 above)
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs]: oops yes, the rule now reads the flavor from the semantic model itself `model.flavor()`

File: crates/biome_js_syntax/src/file_source.rs (hunk 25 above)
Comment (Hugo-Polloli) [reply crates/biome_js_syntax/src/file_source.rs]: Expanded the docs here so they explain the actual behavior difference too!

`Component` means `<script ...>` extraction / inference while `SourceModule` means standalone JS/TS module behavior

File: crates/biome_js_syntax/src/file_source.rs (hunk 26 above)
Comment (ematipico) [reply crates/biome_js_syntax/src/file_source.rs:485]: I realised after that comment that these files were essentially copied from code we already had. I'd say let's keep them as is.

File: crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts (hunk 23 above)
Comment (Hugo-Polloli) [reply crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts:2]: Added the missing diagnostics markers

On the file split: I kept these separate because they are covering different cases rather than just different bindings in the same scenario:
- plain JS/TS `$store` should still fail
- Svelte `$store` should resolve
- built-in globals like `$location` should still fail
- `$$state` should not be normalized
- type-only `store` should still fail

So merging them all into one file would make it harder to isolate which semantic/policy path regressed

Also small note: I did look through the repo’s `CONTRIBUTING.md` files after your comment, but I couldn’t find this marker convention documented there. I did find it in the test infrastructure itself (`biome_test_utils`), so I followed that going forward. I may have missed it though sorry!

File: crates/biome_service/src/workspace/document/mod.rs (hunk 27 above)
Comment (Hugo-Polloli) [reply crates/biome_service/src/workspace/document/mod.rs]: Renamed this to `from_js_snippet` is that better ?

File: crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts (hunk 23 above)
Comment (ematipico) [reply crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts:2]: You're right! It seems that we forgot about that. I thought it was written somewhere. Sorry about that

Comment (Hugo-Polloli) [reply crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidBuiltinGlobalStoreDereference.svelte.ts:2]: No worries!

**Comment by Hugo-Polloli** [comment]
> I think we're getting somewhere, and it's taking a good shape. There are still a few things to address

Absolutely no pressing matter, but I wanted to ensure we were in the same page, I think I've addressed all the existing concerns, but if you still need any follow-up from me I'm ready :)

**Comment by dyc3** [comment]
Hey @Hugo-Polloli, I rebased the branch to resolve the merge conflicts, and because we recently improved our testing infra. I believe we no longer need the CLI tests for this, we can use our normal per-rule snapshot infra to help verify this. I've added a commit [93a52b4](https://github.com/biomejs/biome/pull/9286/commits/93a52b40074d0ad5e873fbf8fc133d9a39393174) to explain what i mean

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
This PR should be ready to merge @dyc3

**Review by dyc3 — APPROVED** [review]
Sorry for the delay. Looks good.
