### PR TITLE
fix(noUnusedVariables): don't panic when renaming ref at the start

### LINKED ISSUE #4114: 🐛 `noUnusedVariables` makes the semantic model panics on invalid code
### Environment information

```block
Main
```

### What happened?

Given the following file named `main,js`:

```js
c;
const c = 0;
```

Execute the following command:

```shell
biome lint --only=correctness/noUnusedVariables main.js
````

And then notice the panics:

```shell
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_js_semantic/src/semantic_model/model.rs:138:21
Thread Name: biome::worker_4
Message: internal error: entered unreachable code: Expected global scope not present

main.js internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: internal error: entered unreachable code: Expected global scope not present
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

Checked 0 files in 1558µs. No fixes applied.
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No files were processed in the specified paths.
```

### Expected result

Biome should not panic.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #4114

## Test Plan

I added a test.

### CODE REVIEW

File: crates/biome_js_semantic/src/semantic_model/reference.rs [hunk 1]
```diff
@@ -58,9 +58,12 @@ impl Reference {
...
     /// Returns the scope of this reference
     pub fn scope(&self) -> Scope {
-        let id = self
-            .data
-            .scope(TextRange::new(self.range_start(), self.range_start()));
+        let start = self.range_start();
+        let id = self.data.scope(TextRange::new(
+            start,
+            // SAFETY: A reference name has at least a length of 1 byte.
+            start.checked_add(1.into()).unwrap(),
```
Comment (arendjr) [inline crates/biome_js_semantic/src/semantic_model/reference.rs:65]: Why use `checked_add()` if you're just going to `unwrap()` anyway?

```suggestion
            start + 1.into(),
```

**Review by arendjr — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

File: crates/biome_js_semantic/src/semantic_model/reference.rs (hunk 1 above)
Comment (Conaclos) [reply crates/biome_js_semantic/src/semantic_model/reference.rs]: I got tricked by `TextSize`. `start + 1.into()` doesn't compile. However, `start + TextSize::from(1)` compiles.
