### PR TITLE
fix(html/parser): support root element list 

### LINKED ISSUE #3976: 📝 Multiple elements at the root level don't get parsed or formatted correctly
### Environment information

```bash
playground
```

### Configuration

_No response_

### Playground link

https://biomejs.dev/playground?files.main.html=PABkAGkAdgA%2BADwALwBkAGkAdgA%2BAAoAPABkAGkAdgA%2BADwALwBkAGkAdgA%2BAAoA

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by suxin2017**
## Summary

fix #3976

## Test Plan
update snap test

### CODE REVIEW

File: crates/biome_html_formatter/tests/quick_test.rs [hunk 1]
```diff
@@ -14,10 +14,9 @@ mod language {
 // use this test check if your snippet prints as you wish, without using a snapshot
 fn quick_test() {
     let src = r#"
-<div>
-    <p>hello
-    </p>
-</div>
+<div></div>
+<div></div>
+
```
Comment (dyc3) [inline crates/biome_html_formatter/tests/quick_test.rs:19]: revert this change to the quick test

**Review by dyc3 — APPROVED** [review]
Looks good, just a minor thing to fix

File: crates/biome_html_formatter/tests/quick_test.rs (hunk 1 above)
Comment (suxin2017) [reply crates/biome_html_formatter/tests/quick_test.rs]: done
