### PR TITLE
fix(lint/noRedeclare): handle function and call overloads

### LINKED ISSUE #2372: 💅 noRedeclare | false positive
### Environment information

```bash
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "alacritty"
  JS_RUNTIME_VERSION:           "v21.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.6"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        complexity/noForEach = "off"
                                suspicious/noExplicitAny = "off"

Workspace:
  Open Documents:
```

### Rule name

suspicious/noRedeclare

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAYQBsAGwAQQBiAG8AdQB0AHMALAAgAHQAeQBwAGUAIABBAGIAbwB1AHQAIAB9ACAAZgByAG8AbQAgACIAYwBvAG4AdABlAG4AdABsAGEAeQBlAHIALwBnAGUAbgBlAHIAYQB0AGUAZAAiADsACgBpAG0AcABvAHIAdAAgAHQAeQBwAGUAIAB7ACAATQBlAHQAYQBkAGEAdABhACAAfQAgAGYAcgBvAG0AIAAiAG4AZQB4AHQAIgA7AAoACgBmAHUAbgBjAHQAaQBvAG4AIABBAGIAbwB1AHQAQwBhAHIAZAAoAGEAYgBvAHUAdAA6ACAAQQBiAG8AdQB0ACkAIAB7AAoACQByAGUAdAB1AHIAbgAgACgACgAJAAkAPABhAHIAdABpAGMAbABlACAAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAHAAcgBvAHMAZQAgAHAAcgBvAHMAZQAtAHMAbABhAHQAZQAgAG0AYgAtADgAIABkAGEAcgBrADoAcAByAG8AcwBlAC0AaQBuAHYAZQByAHQAIgA%2BAAoACQAJAAkAPABoADIAIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAbQBiAC0AMAAgAHQAZQB4AHQALQAzAHgAbAAgAGYAbwBuAHQALQBzAGUAbQBpAGIAbwBsAGQAIAB0AHIAYQBjAGsAaQBuAGcALQB0AGkAZwBoAHQAIAB0AHIAYQBuAHMAaQB0AGkAbwBuAC0AYwBvAGwAbwByAHMAIAAiAD4ACgAJAAkACQAJAHsAYQBiAG8AdQB0AC4AdABpAHQAbABlAH0ACgAJAAkACQA8AC8AaAAyAD4ACgAJAAkACQB7AC8AKgAgAGIAaQBvAG0AZQAtAGkAZwBuAG8AcgBlACAAbABpAG4AdAAvAHMAZQBjAHUAcgBpAHQAeQAvAG4AbwBEAGEAbgBnAGUAcgBvAHUAcwBsAHkAUwBlAHQASQBuAG4AZQByAEgAdABtAGwAOgAgAGkAbgB0AGUAbgB0AGkAbwBuAGEAbABsAHkAIAAqAC8AfQAKAAkACQAJADwAZABpAHYAIABkAGEAbgBnAGUAcgBvAHUAcwBsAHkAUwBlAHQASQBuAG4AZQByAEgAVABNAEwAPQB7AHsAIABfAF8AaAB0AG0AbAA6ACAAYQBiAG8AdQB0AC4AYgBvAGQAeQAuAGgAdABtAGwAIAB9AH0AIAAvAD4ACgAJAAkAPAAvAGEAcgB0AGkAYwBsAGUAPgAKAAkAKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABtAGUAdABhAGQAYQB0AGEAOgAgAE0AZQB0AGEAZABhAHQAYQAgAD0AIAB7AAoACQB0AGkAdABsAGUAOgAgACIAQQBiAG8AdQB0ACIALAAKAAkAZABlAHMAYwByAGkAcAB0AGkAbwBuADoAIAAiAEwAZQBhAHIAbgAgAGEAYgBvAHUAdAAgAHQAaABlACAAdABlAGMAaAAgAHMAdABhAGMAawAgAGEAbgBkACAAaQBuAHMAcABpAHIAYQB0AGkAbwBuACAAYgBlAGgAaQBuAGQAIABDAGgAYQBkAE4AZQB4AHQALgAiACwACgB9ADsACgAKAGUAeABwAG8AcgB0ACAAZABlAGYAYQB1AGwAdAAgAGYAdQBuAGMAdABpAG8AbgAgAEEAYgBvAHUAdAAoACkAIAB7AAoACQByAGUAdAB1AHIAbgAgACgACgAJAAkAPABkAGkAdgAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgBjAG8AbgB0AGEAaQBuAGUAcgAgAG0AaQBuAC0AaAAtAHMAYwByAGUAZQBuACAAcAB5AC0AOAAiAD4ACgAJAAkACQA8AGgAMQAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgB0AGUAeAB0AC0ANAB4AGwAIABmAG8AbgB0AC0AYgBvAGwAZAAgAHQAcgBhAGMAawBpAG4AZwAtAHQAaQBnAGgAdAAgAGwAZwA6AHQAZQB4AHQALQA1AHgAbAAiAD4ACgAJAAkACQAJAEEAYgBvAHUAdAAKAAkACQAJADwALwBoADEAPgAKAAkACQAJADwAcAAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgBtAGIALQAxADAAIABtAHQALQAyAC4ANQAgAHQAZQB4AHQALQB4AGwAIAB0AGUAeAB0AC0AbQB1AHQAZQBkAC0AZgBvAHIAZQBnAHIAbwB1AG4AZAAiAD4ACgAJAAkACQAJAEwAZQBhAHIAbgAgAGEAYgBvAHUAdAAgAHQAaABlACAAdABlAGMAaAAgAHMAdABhAGMAawAgAGEAbgBkACAAaQBuAHMAcABpAHIAYQB0AGkAbwBuACAAYgBlAGgAaQBuAGQAIABDAGgAYQBkAE4AZQB4AHQALgAKAAkACQAJADwALwBwAD4ACgAJAAkACQA8AGQAaQB2ACAAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAHMAcABhAGMAZQAtAHkALQAxADAAIgA%2BAAoACQAJAAkACQB7AGEAbABsAEEAYgBvAHUAdABzAC4AbQBhAHAAKAAoAHAAKQAgAD0APgAgACgACgAJAAkACQAJAAkAPABBAGIAbwB1AHQAQwBhAHIAZAAgAGsAZQB5AD0AewBwAC4AXwBpAGQAfQAgAHsALgAuAC4AcAB9ACAALwA%2BAAoACQAJAAkACQApACkAfQAKAAkACQAJADwALwBkAGkAdgA%2BAAoACQAJADwALwBkAGkAdgA%2BAAoACQApADsACgB9AAoA

### Expected result

It should not throw an error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### LINKED ISSUE #2394: 🐛 should report duplicate identifier error
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

- code:

```ts
// npx @biomejs/biome check --apply code.ts
function f(a: number) {
  const a = 1; // expected throw error here but not.
}
```

- playground:

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAZgAoAGEAOgAgAG4AdQBtAGIAZQByACkAIAB7AAoAIAAgAGMAbwBuAHMAdAAgAGEAIAA9ACAAMQA7AAoAfQA%3D

### Expected result

Report errors like ﻿`duplicated identifier`

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### LINKED ISSUE #2608: 💅 `noRedeclare` false positive when function overloading with destructured objects
### Environment information

```bash
CLI:
  Version:                      1.7.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  Recommended:                  true
  All:                          false
  Rules:
Workspace:
  Open Documents:               0
```

### Rule name

lint/suspicious/noRedeclare

### Playground link

https://biomejs.dev/playground/?code=dAB5AHAAZQAgAFgAIAA9ACAAewAKAAkAKABlADoAIAAiAGMAaABhAG4AZwBlAC0AawBpAG4AZAAiACwAIAB7ACAAawBpAG4AZAAgAH0AOgAgAHsAIABrAGkAbgBkADoAIAAiAGEAIgAgAH0AKQA6ACAAdgBvAGkAZAA7AAoACQAoAGUAOgAgACIAYwBoAGEAbgBnAGUALQBrAGkAbgBkACIALAAgAHsAIABrAGkAbgBkACwAIABlAHgAdAByAGEAIAB9ADoAIAB7ACAAawBpAG4AZAA6ACAAIgBiACIAOwAgAGUAeAB0AHIAYQA6ACAAbgB1AG0AYgBlAHIAIAB9ACkAOgAgAHYAbwBpAGQAOwAKAH0AOwAKAAoAbABlAHQAIAB4ADoAIABYADsACgAKAHgAKAAiAGMAaABhAG4AZwBlAC0AawBpAG4AZAAiACwAIAB7ACAAawBpAG4AZAA6ACAAIgBhACIAIAB9ACkAOwAKAAoAeAAoACIAYwBoAGEAbgBnAGUALQBrAGkAbgBkACIALAAgAHsAIABrAGkAbgBkADoAIAAiAGIAIgAsACAAZQB4AHQAcgBhADoAIAAxACAAfQApADsACgA%3D

### Expected result

The rule should not be triggered when writing function overload definitions since it is a type, not actual code.

The playground and the original code that triggered it is not completely equal, since it was a generic function input in a Vue component (as seen below).

```vue
<script setup lang="ts">
defineEmits<{
  (e: 'change-kind', { kind }: { kind: 'a' }): void;
  (e: 'change-kind', { kind, extra }: { kind: 'b'; extra: number }): void;
}>();
</script>
```

As far as I am aware it should not be triggered in either case, but it definitely shouldn't in the Vue snippet.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #2608
Fix #2394
Fix #2372

## Test Plan

I added a non-regression test for each issue.

### CODE REVIEW

File: crates/biome_js_syntax/src/binding_ext.rs [hunk 1]
```diff
@@ -137,6 +137,7 @@ impl AnyJsBindingDeclaration {
                 | AnyJsBindingDeclaration::TsModuleDeclaration(_)
                 | AnyJsBindingDeclaration::TsTypeParameter(_),
                 AnyJsBindingDeclaration::JsFunctionDeclaration(_)
+                | AnyJsBindingDeclaration::JsFunctionExportDefaultDeclaration(_)
```
Comment (Conaclos) [inline crates/biome_js_syntax/src/binding_ext.rs:140]: This change fixes #2608

File: crates/biome_js_semantic/src/events.rs [hunk 2]
```diff
@@ -334,6 +335,7 @@ impl SemanticEventExtractor {
             | TS_TYPE_ALIAS_DECLARATION
             | TS_DECLARE_FUNCTION_DECLARATION
             | TS_DECLARE_FUNCTION_EXPORT_DEFAULT_DECLARATION
+            | TS_CALL_SIGNATURE_TYPE_MEMBER
```
Comment (Conaclos) [inline crates/biome_js_semantic/src/events.rs:338]: This change fixed #2608 by creating a scope for every call signature.

File: crates/biome_js_analyze/src/lint/suspicious/no_redeclare.rs [hunk 3]
```diff
@@ -115,6 +115,37 @@ impl Rule for NoRedeclare {
...
+        // ```
+        if let Some(function_scope) = scope.parent() {
+            for binding in function_scope.bindings() {
+                let id_binding = binding.tree();
+                if let Some(decl) = id_binding.declaration() {
+                    let name = id_binding.text();
+                    declarations.insert(name, (id_binding.syntax().text_trimmed_range(), decl));
+                }
+            }
+        }
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/lint/suspicious/no_redeclare.rs:147]: I fixed #2394 by adding every parameter and every type parameter in `declarations`.
