### PR TITLE
fix(cli): disable colors when GitHub Actions auto-enables github reporter

### LINKED ISSUE #9189: 🐛 GitHub reporter output is invalid when colors are enabled
### What happened?

Following the change in #9120, running `biome ci` now enables the `github` reporter when the environment contains `GITHUB_ACTION=true`. However, by default, `biome ci` still uses color output, which currently breaks the intended functionality.

Specifically, Biome's color output causes lines of `github` reporter output (written to stdout) to be wrapped with the characters `0x1b 0x5b 0x30 0x6d` (or `ESC[0m`), which is the [ANSI escape sequence](https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b#colors--graphics-mode) to "reset all modes (styles and colors)". These extra characters breaks GitHub's ability to process such lines [as workflow commands](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-error-message), which defeats the purpose of the `github` reporter.

Note, if the command is run as `biome ci --reporter=default --reporter=github` color output is disabled (due to #3281) and the output is correctly detected by GitHub. However, `biome ci` ought to "just work" too.

---
I think there are 2 potential fixes:
1. Make `biome ci` (when `GITHUB_ACTION=true`) actually work the same as `--reporter=default --reporter=github`, which would effectively also set `--colors=off`, per #3281.
2. Ensure that the stdout output of the `github` has "clean" lines with no ANSI control characters. I suspect that control characters could still technically be output by the `github` reporter (if colors needed to be reset), but they'd have to be on totally separate lines from the actual "workflow commands". Additionally, maybe part of #3281 could actually be reverted, so that when `--reporter=default --reporter=github` is explicitly enabled, the `default` reporter could still produce color output.

I think 2 would be the most user-friendly behavior. However, 1 seems easier and would only deprive users of colors when running inside GitHub Actions.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by FrederickStempfle**
## Summary

Fixes #9189

When `biome ci` runs in GitHub Actions, the github reporter gets auto-enabled but colors are also force-enabled. This causes ANSI reset sequences to wrap the `::error`/`::warning` lines, which prevents GitHub from recognizing them as workflow commands.

The fix checks for `GITHUB_ACTIONS=true` before forcing colors on, so the auto-detected path behaves the same way as explicitly passing `--reporter=default --reporter=github` (which already works correctly).

Uses the same `cfg!(debug_assertions)` guard as the existing GitHub detection in `ci.rs` to avoid breaking tests.

### CODE REVIEW

File: crates/biome_cli/src/commands/mod.rs [hunk 1]
```diff
@@ -719,9 +719,17 @@ impl BiomeCommand {
...
                 // Unless users explicitly set the colors flag
                 if matches!(self, Self::Ci { .. }) && cli_options.colors.is_none() {
+                    // Disable colors when the github reporter is auto-enabled
+                    if !cfg!(debug_assertions)
+                        && std::env::var("GITHUB_ACTIONS")
+                            .ok()
+                            .is_some_and(|v| v == "true")
+                    {
+                        return Some(&ColorsArg::Off);
+                    }
```
Comment (Netail) [inline crates/biome_cli/src/commands/mod.rs]: >Please extract this code into a utility function. We have the same code in another place. Please keep the comment of the other code

Comment forwarded from another PR; https://github.com/biomejs/biome/pull/9236#discussion_r2851189967

Comment (FrederickStempfle) [reply crates/biome_cli/src/commands/mod.rs]: Ill extract it into a helper function one sec

**Review by ematipico — APPROVED** [review]
