### PR TITLE
fix(noUnknownProperty): prevent warning on CSS custom property

### LINKED ISSUE #3092: 💅 noUnknownProperty throws warning for CSS custom properties
### Environment information

```bash
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.7.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  nursery/useThrowOnlyError
  style/useImportType
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  nursery/noUndeclaredDependencies
  nursery/noConsole
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  nursery/noYodaExpression
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  suspicious/noAssignInExpressions
  suspicious/noDuplicateParameters
  suspicious/useNamespaceKeyword
  style/useTemplate
  suspicious/useValidTypeof
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  a11y/noAutofocus
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  nursery/noMisplacedAssertion
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  nursery/noUselessUndefinedInitialization
  suspicious/noEmptyInterface
  nursery/noInvalidPositionAtImportRule
  suspicious/noConstEnum
  nursery/noDuplicateElseIf
  correctness/noPrecisionLoss
  nursery/noRestrictedImports
  nursery/noUnmatchableAnbSelector
  nursery/noUnknownSelectorPseudoElement
  correctness/noStringCaseMismatch
  nursery/noUnknownFunction
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noGlobalIsNan
  a11y/useKeyWithClickEvents
  nursery/useExplicitLengthCheck
  complexity/noUselessThisAlias
  correctness/noUnreachable
  nursery/noImportantInKeyframe
  nursery/noUselessStringConcat
  complexity/noThisInStatic
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  suspicious/noDuplicateObjectKeys
  nursery/noLabelWithoutControl
  a11y/useValidAnchor
  suspicious/noFallthroughSwitchClause
  complexity/useRegexLiterals
  suspicious/noImplicitAnyLet
  correctness/noSelfAssign
  nursery/useThrowNewError
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noMisleadingCharacterClass
  nursery/noUnusedFunctionParameters
  suspicious/noRedeclare
  suspicious/noShadowRestrictedNames
  suspicious/noUnsafeDeclarationMerging
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  nursery/noDuplicateFontNames
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  nursery/noEvolvingTypes
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  complexity/noStaticOnlyClass
  nursery/noUnknownMediaFeatureName
  style/useWhile
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  nursery/noEmptyBlock
  correctness/noUnnecessaryContinue
  nursery/useTopLevelRegex
  style/useNumericLiterals
  suspicious/noApproximativeNumericConstant
  correctness/noGlobalObjectCalls
  suspicious/noImportAssign
  suspicious/noLabelVar
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  nursery/useNumberToFixedDigitsArgument
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  a11y/noSvgWithoutTitle
  correctness/noVoidElementsWithChildren
  nursery/useDefaultSwitchClause
  correctness/useJsxKeyInIterable
  style/useAsConstAssertion
  complexity/noUselessLoneBlockStatements
  style/noArguments
  a11y/useValidAriaValues
  style/useExportType
  suspicious/noCommentText
  suspicious/noDebugger
  suspicious/noGlobalAssign
  suspicious/noMisleadingInstantiator
  suspicious/noDuplicateJsxProps
  suspicious/noPrototypeBuiltins
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  nursery/noDuplicateJsonKeys
  a11y/useKeyWithMouseEvents
  nursery/useConsistentBuiltinInstantiation
  security/noDangerouslySetInnerHtmlWithChildren
  correctness/noRenderReturnValue
  correctness/useExhaustiveDependencies
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  style/useConst
  suspicious/noExtraNonNullAssertion
  nursery/useErrorMessage
  suspicious/noGlobalIsFinite
  suspicious/noAsyncPromiseExecutor
  suspicious/noSelfCompare
  suspicious/noThenProperty
  suspicious/useDefaultSwitchClauseLast
  security/noDangerouslySetInnerHtml
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  nursery/useFocusableInteractive
  complexity/noWith
  suspicious/noArrayIndexKey
  nursery/useImportRestrictions
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  suspicious/noConfusingLabels
  suspicious/noDuplicateClassMembers
  nursery/useSemanticElements
  suspicious/noSuspiciousSemicolonInJsx
  nursery/useGenericFontNames
  suspicious/useGetterReturn
  nursery/noDuplicateSelectorsKeyframeBlock
  suspicious/noConfusingVoidType
  a11y/useButtonType
  suspicious/noFocusedTests
  nursery/useDateNow
  nursery/useImportExtensions
  a11y/noAriaUnsupportedElements
  correctness/noFlatMapIdentity
  a11y/noBlankTarget
  a11y/useHeadingContent
  correctness/useValidForDirection
  nursery/noDoneCallback
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useAnchorContent
  complexity/noUselessRename
  correctness/noInvalidNewBuiltin
  style/useNumberNamespace
  complexity/noUselessConstructor
  a11y/noAccessKey
  nursery/useSortedClasses
  style/noUnusedTemplateLiteral
  complexity/noUselessSwitchCase
  style/useExponentiationOperator
  nursery/noUnknownUnit
  nursery/useAdjacentOverloadSignatures
  style/useSingleVarDeclarator
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  nursery/noUnknownProperty
  nursery/noReactSpecificProps
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  nursery/noDuplicateAtImportRules
  complexity/noForEach
  suspicious/noClassAssign
  suspicious/noMisrefactoredShorthandAssign
  suspicious/noFunctionAssign

Workspace:
  Open Documents:               0
```

### Rule name

noUnknownProperty

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&files.main.css=YgBvAGQAeQAgAHsACgAJAC0ALQBjAHUAcwB0AG8AbQAtAHAAcgBvAHAAZQByAHQAeQA6ACAAMQAwAHAAeAA7AAoAfQAKAA%3D%3D
### Expected result

noUnknownProperty rule should ignore all custom properties (starting with double dash)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by chansuke**
## Summary

Closes #3092.

Prevent warnings from being thrown for [Custom properties (--*)](https://developer.mozilla.org/en-US/docs/Web/CSS/--*).

### CODE REVIEW

File: crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs [hunk 1]
```diff
@@ -54,7 +54,7 @@ declare_rule! {
     /// ```
     ///
     pub NoUnknownProperty {
-        version: "1.8.0",
+        version: "next",
```
Comment (Sec-ant) [inline crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs:57]: I don't think we should update the version. The rule is introduced in v1.8.0, a bug fix like this shouldn't refresh its birthday.

**Comment by Sec-ant** [comment]
There must be so many custom properties in `bootstrap.css` given the performance numbers. 😆

File: crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs (hunk 1 above)
Comment (chansuke) [reply crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs:57]: @Sec-ant 
Ah, thanks

File: crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs [hunk 2]
```diff
@@ -70,7 +70,10 @@ impl Rule for NoUnknownProperty {
     fn run(ctx: &RuleContext<Self>) -> Option<Self::State> {
         let node = ctx.query();
         let property_name = node.name().ok()?.text().to_lowercase();
-        if !is_known_properties(&property_name) && !vendor_prefixed(&property_name) {
+        if !is_known_properties(&property_name)
+            && !vendor_prefixed(&property_name)
+            && !property_name.starts_with("--")
```
Comment (Sec-ant) [inline crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs:75]: Given the performance boost of adding this gate to the lint rule, I suggest changing the order of conditions into the following, because checking `starts_with("--")` is cheaper then multiple binary searching. I benched it locally and there's a very tiny performance gain (3%\~6% for `bootstrap.css`, 0\~1% for others).
```suggestion
        if !property_name.starts_with("--")
            && !is_known_properties(&property_name)
            && !vendor_prefixed(&property_name)
```

Comment (chansuke) [reply crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs:75]: YES, I appreciate your feedback!!

**Review by Sec-ant — APPROVED** [review]
