### PR TITLE
fix(js_formatter): don't duplicate dangling comments for mapped types

### LINKED ISSUE #1220: 📝 Comment near a computed key in a union type gets duplicated
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.18"

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### Configuration

_No response_

### Playground link

https://biomejs.dev/playground/?code=dAB5AHAAZQAgAHgAIAA9ACAAewAKAAkACQBjAG8AbABsAGUAYwB0AGkAbwBuAHMAOgAKAAkACQAJAHwAIABlAG0AcAB0AHkATwBiAGoAZQBjAHQACgAJAAkACQB8ACAAewAgAC8ALwAgAHQAaABpAHMAIABjAG8AbQBtAGUAbgB0ACAAbgBlAGEAcgAgAGEAIABjAG8AbQBwAHUAdABlAGQAIABrAGUAeQAgAGcAZQB0AHMAIABkAHUAcABsAGkAYwBhAHQAZQBkAAoACQAJAAkACQAJAFsAcwB0AG8AcgBlAE4AYQBtAGUAIABpAG4AIABrAGUAeQBvAGYAIABTAGMAaABlAG0AYQBbACIAcwB0AG8AcgBlAHMAIgBdAF0AOgAgAHsACgAJAAkACQAJAAkACQBsAGEAcwB0AEkAZAA6ACAAbgB1AG0AYgBlAHIAOwAKAAkACQAJAAkACQB9ADsACgAJAAkACQAgACAAfQA7ACAACgAJAH0AOwAKAAoACgB0AHkAcABlACAAYgAgAD0AIABlAG0AcAB0AHkATwBiAGoAZQBjAHQAIAB8AHsACgAgACAALwAvACAAdABoAGkAcwAgAG8AbgBlACAAYQBsAHMAbwAsACAAcwBvACAAdQBuAGkAbwBuACAAKwAgAGMAbwBtAHAAdQB0AGUAZAAgAGsAZQB5AAoAIAAgAFsAcwB0AG8AcgBlAE4AYQBtAGUAIABpAG4AIABrAGUAeQBvAGYAIABTAGMAaABlAG0AYQBbACIAcwB0AG8AcgBlAHMAIgBdAF0AOgAgAHsACgAgACAAIAAgACAAIABsAGEAcwB0AEkAZAA6ACAAbgB1AG0AYgBlAHIAOwAKACAAIAB9ADsACgB9AAoACgB0AHkAcABlACAAYwAgAD0AIAB7AAoAIAAgAC8ALwAgAGIAdQB0ACAAbgBvAHQAIAB0AGgAaQBzACAAbwBuAGUACgAgACAAWwBzAHQAbwByAGUATgBhAG0AZQAgAGkAbgAgAGsAZQB5AG8AZgAgAFMAYwBoAGUAbQBhAFsAIgBzAHQAbwByAGUAcwAiAF0AXQA6ACAAewAKACAAIAAgACAAIAAgAGwAYQBzAHQASQBkADoAIABuAHUAbQBiAGUAcgA7AAoAIAAgAH0AOwAKAH0ACgAKAAoAdAB5AHAAZQAgAHoAIAA9ACAAZQBtAHAAdAB5AE8AYgBqAGUAYwB0ACAAfAB7AAoAIAAgAC8ALwAgAGgAZQBsAGwAbwAKACAAIABwAHIAbwBwADoAIAAnAHYAYQBsAHUAZQAnAAoAfQAKAAoAdAB5AHAAZQAgAGEAIAA9ACAAewAKACAAIABuAGUAcwB0AGUAZAA6ACAAZQBtAHAAdAB5AE8AYgBqAGUAYwB0ACAAfAB7AAoAIAAgAC8ALwAgAGgAZQBsAGwAbwAKACAAIABwAHIAbwBwADoAIAAnAHYAYQBsAHUAZQAnAAoAfQAKAH0ACgAKAGMAbwBuAHMAdAAgAHkAIAA9ACAAewAKACAAIAAvAC8AIAB0AGUAcwB0AAoAIAAgAHAAcgBvAHAAOgAgACcAdgBhAGwAdQBlACcACgB9AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by faultyserver**
## Summary

Fixes #1220. The base case issue here was that dangling comments of mapped types _within a union type_ were getting printed twice, but another portion was that they were positioned incorrectly in the first place. Consider:

```typescript
| {
  // this dangling comment gets duplicated
  [A in B]: T
}// this dangling comment gets duplicated;
```

The comment is printed twice, so let's fix that first. The root cause was that `TsUnionType` formats all of the comments of each variant directly. All leading, dangling, and trailing. For most nodes this isn't a problem since they don't do any special handling for them. But for mapped types, the dangling comments are directly formatted by the node itself (and moved to act as leading coments instead), so when the union then formatted the comments as dangling comments, they were printed twice. The same was actually also true for empty object-like and tuple types, which also format their own dangling comments.

The solution here was just to opt-out of re-printing the comments in the union for those types of nodes. While working in there, I also copied over the rest of prettier's logic for trailing comments in mapped types as well.

This PR also addresses the `break-mode` tests from Prettier, where the mapped type should only break over multiple lines _if_ a newline occurs between the `{` and the start of the property name. Newlines in any other position don't cause the type to expand unless the inner groups break.

## Test Plan

The Prettier snapshots cover both of these cases, break mode for itself, and 11098 for the comment positioning.

### CODE REVIEW

File: crates/biome_cli/tests/commands/lint.rs [hunk 1]
```diff
@@ -992,6 +992,7 @@ fn fs_error_unknown() {
 //     ├── symlink_testcase1_1 -> hidden_nested
 //     └── symlink_testcase2 -> hidden_testcase2
 #[test]
+#[ignore = "It regresses on linux since we added the ignore crate, to understand why"]
```
Comment (faultyserver) [inline crates/biome_cli/tests/commands/lint.rs:995]: @ematipico I see you added a similar ignore in `commands/check.rs`, but it looks like this one in `lint` can also fail on linux, so I'm adding the same one here, unless you think there's another solution or this is actually something incorrect (but since this is just a formatter change, i don't imagine it is).

Comment (ematipico) [reply crates/biome_cli/tests/commands/lint.rs:995]: Thank you!

**Review by Conaclos — APPROVED** [review]
Looks good to me! Feel free to merge once you added a changelog entry :)
