### PR TITLE
fix(lsp): correctly resolve `extends` configs

### LINKED ISSUE #2159: 🐛 Extension does not work when using shared config from module
### VS Code version

1.87.1

### Extension version

2.2.2

### Biome version

1.6.0

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

After extending a configuration resolved from a node module, the extension stopped working, it says the Biome version on the status bar, but neither the linter nor the formatter are working.

### Steps to reproduce

1. Install a shareable configuration from npm (you can use [mine](https://npmjs.com/package/@kevinwolfcr/biome-config))
2. Extend the configuration on `biome.json` (see snippet below)

```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "extends": ["@kevinwolfcr/biome-config"],
}
```

### Expected behavior

Same behavior as extending a config using its path.

### Does this issue occur when using the CLI directly?

No

### Logs

```plain text
No logs are shown at all
```

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

This PR fixes an issue where the config files in external packages specified in the `extends` option cannot be resolved properly when running in LSP mode (e.g. integrated with an editor).

Fixes #2159.

## Test Plan

We didn't implement the method to resolve an external configuration file in a memory os, so I just test this locally with the VSCode extension.

### CODE REVIEW

File: crates/biome_fs/src/fs/os.rs [hunk 1]
```diff
@@ -83,9 +83,17 @@ impl FileSystem for OsFileSystem {
         path.is_file()
     }
 
-    fn resolve_configuration(&self, specifier: &str) -> Result<Resolution, ResolveError> {
-        self.configuration_resolver
-            .resolve(self.working_directory().unwrap(), specifier)
```
Comment (Sec-ant) [inline crates/biome_fs/src/fs/os.rs:88]: This is the root cause of the issue. The default working directory in LSP mode is the directory where the editor executable is at.

**Review by ematipico — APPROVED** [review]
I still need to come up with a solution to have the resolver available for the memory file system, that's why we don't have tests :( it's frustrating

Thank you for fixing this!
