### PR TITLE
fix(a11y): only use baseConcepts in useSemanticElements rule (#9245)

### LINKED ISSUE #9245: lint/a11y: Prefer native element rule incorrectly suggests <output> instead of role="status" for loading indicators
### Environment information

<details>

```bash
  × The elements with this role can be changed to the following elements:
    <output>
  
    23 │         aria-live="polite"
    24 │         className="container mx-auto max-w-3xl px-4 py-6"
  > 25 │         role="status"
       │         ^^^^^^^^^^^^^
    26 │       >
    27 │         <span className="sr-only">Loading dashboard</span>
  
  i For examples and more information, see WAI-ARIA Roles
  

Checked 1 file in 6ms. No fixes applied.
Found 1 error.
check 

```

</details>

### Environment
@biomejs/biome: 2.4.4
React + TSX

### What happened?

`lint/a11y/useSemanticElements` currently suggests using `<output>` instead of a `<div role="status">` for status messages such as loading indicators.

This conflicts with ARIA guidance to:
- Use native HTML elements when they match the needed semantics, but reserve `<output>` for calculation results / form-related output, not generic status messages.
- A generic “Loading dashboard…” indicator is a status message and is not the result of a calculation or form interaction. 
- ARIA’s own guidance is “prefer native semantics when they fit; otherwise use roles”, not “replace all role="status" with `<output>`”.

In other words, `<output>` is not the correct replacement for every role="status".

Here is a similar discussion on [sonarsource](https://community.sonarsource.com/t/typescript-rspec-6819-should-not-always-require-htmls-output-element-instead-of-aria-status-role/133611l)

### Minimal repro
```tsx
<div role="status" aria-busy="true" aria-live="polite">
  <span className="sr-only">Loading dashboard</span>
  <Skeleton className="h-8 w-52 rounded-md" />
</div>
```

### Expected result

Should not suggest `<output>` for a generic status message like a loading indicator.

The rule should either:
- Only suggest `<output>` when the element clearly represents the result of a calculation or form output, or
- Provide a configuration option to disable this specific suggestion.

### Suggested change
Adjust the rule (likely useSemanticElements or related a11y rule) so that:
- It does not recommend <output> as a blanket replacement for role="status".
- It considers context (e.g., form association, for/name attributes, calculator-like UI) before recommending `<output>`.

Alternatively, downgrade this to a weaker recommendation or allow opting out via rule configuration.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ruidosujeira**
## Summary

Fixes #9245

The `useSemanticElements` rule treated `baseConcepts` and `relatedConcepts` as equivalent when suggesting HTML element replacements. This caused incorrect suggestions — for example, suggesting `<output>` for `<div role="status">`, when `<output>` is only a `relatedConcept` of the "status" role.

The rule now only considers `baseConcepts` when suggesting semantic HTML elements.

## Test Plan

Added test case for `<div role="status">` to verify it no longer suggests `<output>`. Existing tests pass — roles with valid `baseConcepts` (e.g. `navigation` → `<nav>`) continue to work as expected.

### CODE REVIEW

File: crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx [hunk 1]
```diff
@@ -1,42 +1,17 @@
 // should generate diagnostics
 <>
-    <div role="checkbox" ></div>
-    <div role="radio" ></div>
-    <div role="heading" ></div>
-    <div role="separator" ></div>
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx:6]: Ah see, these feel like they _should_ be flagged by the rule.

We should align ourselves with the source rule's behavior: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/prefer-tag-over-role.js

Comment (ruidosujeira) [reply crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx:6]: @dyc3 Do you think the best approach would be to use both baseConcepts and relatedConcepts (aligning with the source rule), but add status to the exclusion list, similar to how combobox, listbox, and option are already excluded?

**Comment by ruidosujeira** [comment]
I’m currently reviewing the requested changes and comparing the current implementation against the source rule behavior to make sure we preserve the expected cases while fixing the incorrect suggestion. I’m still evaluating the best approach, but I’m actively working on it and will update the PR soon.

**Comment by ruidosujeira** [comment]
@dyc3 I added "status" and "alert" to an existing exclusion list in the code (along with combobox, listbox, and option).

**Review by dyc3 — CHANGES_REQUESTED** [review]
Losing these comments is not great. Also, include context for these new exclusions so we can remember why they are excluded.

**Comment by ruidosujeira** [comment]
> Losing these comments is not great. Also, include context for these new exclusions so we can remember why they are excluded.

I've reverted to the previous code with the necessary comments and context; thank you for letting me know.
