### PR TITLE
fix(lint/noUnusedPrivateClassMembers): handle class members declared in constructor parameters correctly

### LINKED ISSUE #7101: 🐛 Panic `Malformed list, node expected but found token...` in `biome_rowan/src/ast/mod.rs`
### Environment information

```block
CLI:
  Version:                      2.1.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.15.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         pnpm/10.13.1

Biome Configuration:
  Status:                       Not set
  Path:                         unset

Workspace:
  Open Documents:               0
```

### What happened?

1. Create a typescript file `index.ts`

```ts
export class Foo {
  constructor(private a: number, private b: number) {}
}
```

2. Run `npx @biomejs/biome@2.1.3 lint --fix --unsafe`

Result:

```
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue.

When opening the issue, please provide a minimal reproduction, or identify and share the file/code that triggers it. Without a way to reproduce the error, the error can't be fixed:

Source Location: /__w/biome/biome/crates/biome_rowan/src/ast/mod.rs:662:41
Thread Name: biome::workspace_worker_2
Message: Malformed list, node expected but found token COMMA@33..35 "," [] [Whitespace(" ")] instead. You must add missing markers for missing elements.

index.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: Malformed list, node expected but found token COMMA@33..35 "," [] [Whitespace(" ")] instead. You must add missing markers for missing elements.
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

Checked 1 file in 6ms. No fixes applied.
```

Playground: https://biomejs.dev/playground/?analyzerFixMode=safeAndUnsafeFixes&code=ZQB4AHAAbwByAHQAIABjAGwAYQBzAHMAIABGAG8AbwAgAHsACgAgACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgAcAByAGkAdgBhAHQAZQAgAGEAOgAgAG4AdQBtAGIAZQByACwAIABwAHIAaQB2AGEAdABlACAAYgA6ACAAbgB1AG0AYgBlAHIAKQAgAHsAfQAKAH0A

### Expected result

It should not throw an error.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by omasakun**
## Summary

This PR fixes #7101

1. If a class member defined in a constructor argument is only used within the constructor, remove the `private` modifier and make it a plain method argument.
2. If it is not used within the constructor, prefix it with an underscore, as with `no_unused_function_parameter`.

Note:
Previously, unused class members defined as constructor arguments were completely removed from the constructor arguments. However, this changed the constructor signature and was inconsistent with the behavior of `no_unused_function_parameter`.

As a side effect of this bug fix, the constructor signature is no longer changed, which has caused some existing tests to produce different results. (check changed files)

## Test Plan

New test file has been added.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs [hunk 1]
```diff
@@ -76,9 +80,27 @@ declare_node_union! {
     pub AnyMember = AnyJsClassMember | TsPropertyParameter
 }
 
+#[derive(Debug, Clone)]
+pub enum UnusedMemberAction {
+    Remove(AnyMember),
```
Comment (arendjr) [inline crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs]: nit: Maybe `RemoveMember(AnyMember)`? Calling it only `Remove` doesn't clarify how it differs from `RemovePrivateModifier`.

File: crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs [hunk 2]
```diff
@@ -160,6 +249,45 @@ fn traverse_members_usage(
...
+    ctx: &RuleContext<NoUnusedPrivateClassMembers>,
+    ts_property_param: &TsPropertyParameter,
+) -> bool {
+    if let Ok(AnyJsFormalParameter::JsFormalParameter(param)) = ts_property_param.formal_parameter()
+    {
+        if let Ok(binding) = param.binding() {
+            if let Some(identifier_binding) = binding
+                .as_any_js_binding()
+                .and_then(|b| b.as_js_identifier_binding())
+            {
```
Comment (arendjr) [inline crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs]: This would benefit from `let` chaining:

```suggestion
    if let Ok(AnyJsFormalParameter::JsFormalParameter(param)) = ts_property_param.formal_parameter()
        && let Ok(binding) = param.binding()
        && let Some(identifier_binding) = binding
            .as_any_js_binding()
            .and_then(|b| b.as_js_identifier_binding())
    {
```

File: crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_issue_7101.ts.snap [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+     3  3 │   		// This constructor has two unused private properties
+     4  4 │   
+  
+
+```
+
+```
+invalid_issue_7101.ts:9:23 lint/correctness/noUnusedPrivateClassMembers  FIXABLE  ━━━━━━━━━━━━━━━━━━
+
+  ! This private class member is defined but never used.
```
Comment (arendjr) [inline crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_issue_7101.ts.snap]: I think the diagnostic is not correct here. It should be something such as "This argument is never used outside of the constructor."

**Review by arendjr — COMMENTED** [review]
Nice work!

I think one of the diagnostics should be tweaked, but looks good otherwise! Do you want to add a changeset too?

**Comment by omasakun** [comment]
This PR changed the order of diagnostics output, probably because the rule now requires `Semantic<JsClassDeclaration>` instead of `Ast<JsClassMemberList>`.
This caused the test for `server::tests::pull_diagnostics_of_syntax_rules` in biome_lsp to fail, so I fixed the test code.

File: .changeset/rotten-knives-brush.md [hunk 4]
```diff
@@ -0,0 +1,9 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#7101](https://github.com/biomejs/biome/issues/7101)
+
+1. If a class member defined in a constructor argument is only used within the constructor, remove the private modifier and make it a plain method argument.
+
+2. If it is not used within the constructor, prefix it with an underscore, as with no_unused_function_parameter.
```
Comment (arendjr) [inline .changeset/rotten-knives-brush.md]:
```suggestion
Fixed [#7101](https://github.com/biomejs/biome/issues/7101): [`noUnusedPrivateClassMembers`](https://biomejs.dev/linter/rules/no-unused-private-class-members/) now handles members declared as part of constructor arguments:

1. If a class member defined in a constructor argument is only used within the constructor, it removes the `private` modifier and makes it a plain method argument.
1. If it is not used at all, it will prefix it with an underscore, similar to `noUnusedFunctionParameter`.
```
