### PR TITLE
fix(linter): avoid causing noUselessLoneBlockStatements for try/catch

### LINKED ISSUE #783: 💅 noUselessLoneBlockStatements false positive when using try/catch
### Environment information

```bash
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "rio"
  JS_RUNTIME_VERSION:           "v16.20.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/8.19.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

noUselessLoneBlockStatements

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=ZgB1AG4AYwB0AGkAbwBuACAAdgBhAGwAaQBkAGEAdABlAE8AcgBUAGgAcgBvAHcAKABkAGEAdABhADoAIAB1AG4AawBuAG8AdwBuACkAIAB7AAoAIAAgAC8ALwAgAEQAbwAgAHMAbwBtAGUAdABoAGkAbgBnACAAdwBpAHQAaAAgAGQAYQB0AGEACgAgACAAaQBmACAAKABNAGEAdABoAC4AcgBhAG4AZABvAG0AKAApACAAPgAgADAALgA3ADUAKQAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAATQBhAHQAaAAuAHIAYQBuAGQAbwBtACgAKQAgAD4AIAAwAC4ANQA7AAoAIAAgAH0ACgAKACAAIAAvAC8AIABvAHIAIAB0AGgAcgBvAHcAIABpAHQACgAgACAAdABoAHIAbwB3ACAAbgBlAHcAIABFAHIAcgBvAHIAKABkAGEAdABhACkAOwAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAGgAYQBuAGQAbABlAEUAcgByAG8AcgAoAF8AZQByAHIAbwByADoAIAB1AG4AawBuAG8AdwBuACkAIAB7AAoAIAAgAC8ALwAgAC4ALgAuAAoAfQAKAGYAdQBuAGMAdABpAG8AbgAgAGgAYQBuAGQAbABlAE4AbwB0AFYAYQBsAGkAZAAoACkAIAB7AAoAIAAgAC8ALwAgAC4ALgAuAAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAZABvAFMAbwBtAGUAdABoAGkAbgBnAEgAZQByAGUAKAApACAAewAKACAAIAAvAC8AIAAuAC4ALgAKAH0ACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAdgBhAGwAaQBkAGEAdABlAFMAdAB1AGYAZgAoACkAIAB7AAoAIAAgAGMAbwBuAHMAdAAgAGQAYQB0AGEAIAA9ACAAewB9ADsACgAKACAAIAB0AHIAeQAgAHsACgAgACAAIAAgAGMAbwBuAHMAdAAgAHYAYQBsAGkAZABhAHQAZQBkACAAPQAgAHYAYQBsAGkAZABhAHQAZQBPAHIAVABoAHIAbwB3ACgAZABhAHQAYQApADsACgAKACAAIAAgACAAaQBmACAAKAB2AGEAbABpAGQAYQB0AGUAZAAgAD0APQA9ACAAZgBhAGwAcwBlACkAIAB7AAoAIAAgACAAIAAgACAAaABhAG4AZABsAGUATgBvAHQAVgBhAGwAaQBkACgAKQA7AAoAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AOwAKACAAIAAgACAAfQAKAAoAIAAgACAAIAAvAC8AIABkAG8AIABzAG8AbQBlACAAbQBvAHIAZQAgAHMAdAB1AGYAZgAKACAAIAAgACAAZABhAHQAYQAuAHYAYQBsAGkAZAAgAD0AIAB0AHIAdQBlADsACgAgACAAfQAgAGMAYQB0AGMAaAAgACgAZQByAHIAbwByACkAIAB7AAoAIAAgACAAIABoAGEAbgBkAGwAZQBFAHIAcgBvAHIAKABlAHIAcgBvAHIAKQA7AAoAIAAgACAAIAByAGUAdAB1AHIAbgA7AAoAIAAgAH0ACgAKACAAIABkAG8AUwBvAG0AZQB0AGgAaQBuAGcASABlAHIAZQAoACkAOwAKAAoAIAAgAHIAZQB0AHUAcgBuACAAZABhAHQAYQA7AAoAfQAKAA%3D%3D

### Expected result

The `noUselessLoneBlockStatements` rule should not trigger for try/catch. 

image

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by TaKO8Ki**
## Summary

closes #783

## Test Plan

All existing tests should pass and I've added two test cases for try/catch and try/catch/finally.

### CODE REVIEW

File: crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs [hunk 1]
```diff
@@ -150,7 +150,16 @@ fn in_control_structure(block: &JsBlockStatement) -> bool {
...
             return true;
         }
+
+        if JsCatchClause::can_cast(syntax_kind) {
+            return true;
+        }
+
+        if JsFinallyClause::can_cast(syntax_kind) {
+            return true;
+        }
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs:160]: I think we could simplify to:

```suggestion
        matches!(syntax_kind, JsSYntaxKind::JS_ELSE_CLAUSE | JsSYntaxKind::JS_CATCH_CLAUSE | JsSYntaxKind::JS_FINALLY_CLAUSE)
```

You could even use:

```rs
    matches!(block.syntax().parent().kind(), Some(JsSYntaxKind::JS_ELSE_CLAUSE | JsSYntaxKind::JS_CATCH_CLAUSE | JsSYntaxKind::JS_FINALLY_CLAUSE))
```

**Review by Conaclos — APPROVED** [review]
Looks good to me :) I left a suggestion.

File: crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs (hunk 1 above)
Comment (TaKO8Ki) [reply crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs]: Since macros are no longer needed, I've made the following modifications.

```rust
if let JsSyntaxKind::JS_ELSE_CLAUSE
| JsSyntaxKind::JS_CATCH_CLAUSE
| JsSyntaxKind::JS_FINALLY_CLAUSE = syntax_kind
{
    return true;
}
```

Comment (Conaclos) [reply crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs]: > Since macros are no longer needed

Oh interesting. Have you a reference for context about that?

Comment (TaKO8Ki) [reply crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs]: [This](https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html) is the documentation for `if-let`, but it seems that the example you mentioned is not referred to. The relevant implementation of the parser can be found here, and as written in the comments, it's possible to write a pattern after `let` just like in a `match` statement.

https://github.com/rust-lang/rust/blob/a04d56b36d8f634abd7bdd64dd859a30655f1818/compiler/rustc_parse/src/parser/expr.rs#L2491

Comment (Conaclos) [reply crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs]: Ok I see. I am not sure it is more idiomatic to use `if let` than `matches!()` in this case.

Thanks for your contribution :)

Comment (TaKO8Ki) [reply crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs]: In my opinion, the `matches!` macro is useful for simplifying expressions like `matches!(foo, Some(bar) if bar == 2)` that require an `if` statement. Other than that, `if let` seems to be used more often. This is also the case in the Rust compiler's source code, where `if let` is often used for simple pattern matching.
