### PR TITLE
fix(noCommaOperator): disable rule in vue template expressions

### LINKED ISSUE #9069: 💅 `noCommaOperator` false positive in Vue `v-for`
### Environment information

<details>

```bash

CLI:
  Version:                      0.0.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Error:                        The configuration schema version does not match the CLI version 0.0.0
  Status:                       Loaded with errors
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               false
  VCS enabled:                  true
  HTML full support enabled:    true

Workspace:
  Open Documents:               0

```

</details>

### Rule name

lint/complexity/noCommaOperator

### Playground link

https://next.biomejs.dev/playground/?lintRules=noCommaOperator&code=PAB2AC0AbABpAHMAdAAtAGkAdABlAG0ACgAgACAAIAAgAHYALQBmAG8AcgA9ACIAKAByAGEAdABlACwAIABpAG4AZABlAHgAKQAgAGkAbgAgAHAAbABhAHkAYgBhAGMAawBSAGEAdABlAC4AYQB2AGEAaQBsAGEAYgBsAGUAUABsAGEAeQBiAGEAYwBrAFIAYQB0AGUAcwAuAHYAYQBsAHUAZQAiAAoAIAAgACAAIAA6AGsAZQB5AD0AIgBpAG4AZABlAHgAIgAKACAAIAAgACAAOgB2AGEAbAB1AGUAPQAiAHIAYQB0AGUAIgAKACAAIAAgACAAQABjAGwAaQBjAGsAPQAiAHMAZQB0AFIAYQB0AGUAKAByAGEAdABlACkAIgAKAD4ACgAgACAAIAAgADwAdgAtAGwAaQBzAHQALQBpAHQAZQBtAC0AdABpAHQAbABlAD4AewB7ACAAZgBvAHIAbQBhAHQAUgBhAHQAZQAoAHIAYQB0AGUAKQAgAH0AfQA8AC8AdgAtAGwAaQBzAHQALQBpAHQAZQBtAC0AdABpAHQAbABlAD4ACgA8AC8AdgAtAGwAaQBzAHQALQBpAHQAZQBtAD4A&language=vue

### Expected result

Should not emit the diagnostic. 

Related to #8062 

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

This PR is a hack that disables the `noCommaOperator` rule specifically in template expressions in vue files. The reason I chose to do this hack instead of the real fix (#8062) is because its a bit complicated, and I don't want this issue to block the 2.4 release. I also know that this specific `v-for` syntax is rather common. My test codebase had 14 false positives, despite it being relatively small compared to an enterprise codebase.

I've opened a new issue as a follow up task to remove this hack when v-for is parsed better. #9075

Generated by kimi k2.5. No changeset because the affected behavior has not been released yet.

fixes #9069

## Test Plan

Added 2 cli tests to show this only affects vue files. The tests will remain valid after the hack is removed.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/complexity/no_comma_operator.rs [hunk 1]
```diff
@@ -66,6 +66,14 @@ impl Rule for NoCommaOperator {
                 return None;
             }
         }
+
+        // HACK: Skip in Vue template expressions (e.g., v-for="(item, index) in items")
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/complexity/no_comma_operator.rs:70]: Could you add the issue here too, so we can quickly identify the hack to remove?

**Review by ematipico — APPROVED** [review]
