### PR TITLE
fix(lint/useLiteralKeys): unescaped newline false positive

### LINKED ISSUE #3160: 💅 There is a false positive in the `useLiteralKeys` rule
### Environment information

```bash
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.5.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  false
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  style/useImportType
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  suspicious/useNamespaceKeyword
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noAssignInExpressions
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  suspicious/noDuplicateParameters
  style/useTemplate
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  a11y/noAutofocus
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noConstEnum
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noImplicitAnyLet
  suspicious/noFallthroughSwitchClause
  suspicious/noUnsafeDeclarationMerging
  correctness/noUnreachable
  a11y/useKeyWithClickEvents
  suspicious/noDuplicateObjectKeys
  complexity/noUselessThisAlias
  complexity/noThisInStatic
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  a11y/useValidAnchor
  complexity/useRegexLiterals
  correctness/noSelfAssign
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  complexity/noStaticOnlyClass
  style/useWhile
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  style/useNumericLiterals
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  suspicious/noImportAssign
  suspicious/noLabelVar
  correctness/noGlobalObjectCalls
  suspicious/useDefaultSwitchClauseLast
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  suspicious/noSuspiciousSemicolonInJsx
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  a11y/noSvgWithoutTitle
  correctness/noVoidElementsWithChildren
  style/useAsConstAssertion
  correctness/useJsxKeyInIterable
  style/useExportType
  complexity/noUselessLoneBlockStatements
  suspicious/noPrototypeBuiltins
  suspicious/noMisleadingInstantiator
  suspicious/noDebugger
  style/noArguments
  a11y/useValidAriaValues
  suspicious/noCommentText
  suspicious/noThenProperty
  suspicious/noDuplicateJsxProps
  suspicious/noGlobalAssign
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  security/noDangerouslySetInnerHtmlWithChildren
  a11y/useKeyWithMouseEvents
  suspicious/noExtraNonNullAssertion
  suspicious/useGetterReturn
  correctness/noRenderReturnValue
  correctness/useExhaustiveDependencies
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  style/useConst
  suspicious/noGlobalIsFinite
  suspicious/noSelfCompare
  suspicious/noAsyncPromiseExecutor
  security/noDangerouslySetInnerHtml
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  suspicious/noArrayIndexKey
  complexity/noWith
  suspicious/noDuplicateClassMembers
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  suspicious/noConfusingLabels
  suspicious/noConfusingVoidType
  suspicious/noFocusedTests
  a11y/useButtonType
  a11y/noAriaUnsupportedElements
  correctness/noFlatMapIdentity
  a11y/noBlankTarget
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useAnchorContent
  complexity/noUselessRename
  correctness/noInvalidNewBuiltin
  style/useNumberNamespace
  complexity/noUselessConstructor
  a11y/noAccessKey
  style/useExponentiationOperator
  style/noUnusedTemplateLiteral
  complexity/noUselessSwitchCase
  style/useSingleVarDeclarator
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  suspicious/noMisrefactoredShorthandAssign
  complexity/noForEach
  suspicious/noClassAssign
  suspicious/noFunctionAssign

Workspace:
  Open Documents:               0
```

### Rule name

useLiteralKeys

### Playground link

https://biomejs.dev/playground/?code=YwBvAG4AcwB0ACAAbwBiAGoAIAA9ACAAewAKACAAIABbAGAAZgBpAHIAcwB0AAoAIAAgAHMAZQBjAG8AbgBkAAoAIAAgAHQAaABpAHIAZABgAF0AOgAgAHQAcgB1AGUALAAKAH0AOwA%3D

### Expected result

To write a string literal across multiple lines, you need backslashes, like this:

```javascript
const obj = {
  "first\
  second\
  third": true,
};
```

However, I understand that this method has been rarely used since the introduction of template literals.

Therefore, I expect this not to be diagnosed as an error.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

Fixes #3160. This rule now ignores the following kind of computed member name:

```js
const a = {
  [`line1
  line2`]: true,
};
```

## Test Plan

Test cases added.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs [hunk 1]
```diff
@@ -74,6 +74,17 @@ impl Rule for UseLiteralKeys {
...
         let value = value.as_string_constant()?;
+        // Bail if the value contains unescaped new line characters
+        // that can only appear in template strings.
+        //
+        // const a = {
+        //   `line1
+        //   line2`: true
+        // }
+        //
+        if has_unescaped_new_line(value) {
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs:85]: Do you think we could add this to the following if (line 97):

```js
if matches!(node, AnyJsMember::JsComputedMemberName(_)) || is_js_ident(value) {
```

as follows:

```js
if (matches!(node, AnyJsMember::JsComputedMemberName(_)) && has_unescaped_new_line(value)) || is_js_ident(value) {
```

`is_js_ident` should rule out newlines.

File: crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs [hunk 2]
```diff
@@ -161,3 +172,24 @@ impl Rule for UseLiteralKeys {
...
+                if !in_escape_mode {
+                    return true;
+                }
+            }
+            _ => {
+                in_escape_mode = false;
+            }
+        }
+    }
+    false
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs:194]: This code could be improved by iterating over bytes (this is more efficient) and directly using the iterator to skip the escaped item. Note that it is safe to skip a part of a single byte of a multi-byte character.

```suggestion
    let mut iter = text.as_bytes().iter();
    while let(c) = iter.next() {
        match c {
            b'\\' => {
                iter.next();
            }
            b'\n' => {
                    return true;
            }
            _ => {}
        }
    }
    false
```

**Review by ematipico — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs (hunk 2 above)
Comment (Sec-ant) [reply crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs]: TIL, thanks!

File: crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs (hunk 1 above)
Comment (Sec-ant) [reply crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs]: Yes, this further clarifies the logic.

File: crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap [hunk 3]
```diff
@@ -600,11 +615,109 @@ invalid.js:34:25 lint/complexity/useLiteralKeys  FIXABLE  ━━━━━━━
...
   
     34 │ a?.["b"]?.['c']?.d?.e?.["f"]
        │                        -- --
 
 ```
+
+```
+invalid.js:36:4 lint/complexity/useLiteralKeys  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+
+  ! The computed expression can be simplified without the use of a string literal.
```
Comment (Sec-ant) [inline crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap:631]: The message here doesn't fit well into object keys. Do you think we should change it to: 
```
The computed expression can be simplified to a string literal.
```
@Conaclos

Comment (Conaclos) [reply crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap:631]: This could be a nice improvement!

**Review by Conaclos — APPROVED** [review]
