### PR TITLE
fix(lint): handle namespace declaration merging in noUnusedVariables

### LINKED ISSUE #7664: 💅 `lint/correctness/noUnusedVariables` triggering on namespaces used to define component props
### Environment information

```bash
CLI:
  Version:                      2.2.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v20.19.2
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.2.19

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noImportantStyles
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useIndexOf
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useGraphqlNamedOperations
    correctness/useIsNan
    correctness/useParseIntRadix
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noDescendingSpecificity
    style/noInferrableTypes
    style/noNonNullAssertion
    style/noParameterAssign
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noBiomeFirstException
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noQuickfixBiome
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noTsIgnore
    suspicious/noUnknownAtRules
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noUselessEscapeInString
    suspicious/noUselessRegexBackrefs
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useBiomeIgnoreFolder
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useIterableCallbackReturn
    suspicious/useNamespaceKeyword

Workspace:
  Open Documents:               0
```

### Rule name

lint/correctness/noUnusedVariables

### Playground link

https://biomejs.dev/playground/?lintRules=noUnusedVariables&code=bgBhAG0AZQBzAHAAYQBjAGUAIABNAHkAQwBvAG0AcABvAG4AZQBuAHQAIAB7AAoAIAAgACAAIABlAHgAcABvAHIAdAAgAGkAbgB0AGUAcgBmAGEAYwBlACAAUAByAG8AcABzACAAZQB4AHQAZQBuAGQAcwAgAEMAbwBtAHAAbwBuAGUAbgB0AFAAcgBvAHAAcwA8ACcAZABpAHYAJwA%2BACAAewB9AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABNAHkAQwBvAG0AcABvAG4AZQBuAHQAKABwAHIAbwBwAHMAOgAgAE0AeQBDAG8AbQBwAG8AbgBlAG4AdAAuAFAAcgBvAHAAcwApACAAewAKACAAIAAgACAAcgBlAHQAdQByAG4AIAA8AGQAaQB2ACAAewAuAC4ALgBwAHIAbwBwAHMAfQAgAC8APgAKAH0A

### Expected result

A pattern gaining popularity recently is to define the props of a component in the namespace, which will allow access to those props to other files importing that component. However, biome is flagging that namespace as unused. I feel like this is in error, and if it's not, it would be nice to have a way to configure to ignore for namespaces or something similar. I don't want to disable this rule as it's a very critical rule for our team, but we also try avoiding littering our codebase with comments to ignore lines. Right now, there are a TON of warnings happening on our project due to this.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by taberoajorge**
## Summary

Fixes #7664.

TypeScript allows [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) between namespaces and value declarations (`const`, `function`, `class`) of the same name. Before this fix, `noUnusedVariables` flagged both sides of a merged declaration as unused even when one was exported or referenced, because Biome's semantic model treats each binding independently.

This PR adds `is_declaration_merged_with_used()` to `is_unused()`. When a namespace binding appears unused, it checks whether a non-namespace binding with the same name exists and is exported or has external references. The reverse is also handled: when a value binding appears unused, it checks whether a namespace with the same name is exported. This avoids infinite recursion by only checking `is_exported` (not `is_unused`) in the value→namespace direction.

### Covered patterns

```ts
// const + namespace + export default
const MyComponent = () => {};
namespace MyComponent {
    export type Props = { id: string };
}
export default MyComponent;

// export function + namespace
export function MyFunction() {}
namespace MyFunction {
    export type Config = { timeout: number };
}

// function + namespace + export default
function foo() {}
namespace foo {
    export function bar() { foo(); }
}
export default foo;
```

All three patterns are now correctly identified as used through declaration merging.

## AI Disclosure

> This PR was written with assistance from Cursor (Claude). The approach, code, and tests were reviewed and validated manually.

## Test Plan

- Added `validNamespaceDeclarationMerging.ts` — const + namespace + export default (no diagnostics)
- Added `validNamespaceDeclarationMerging2.ts` — export function + namespace (no diagnostics)
- Added `validNamespaceDeclarationMerging3.ts` — function + namespace + export default (no diagnostics)
- Added `invalidNamespaceUnused.ts` — standalone namespace and both-unused const+namespace (diagnostics emitted correctly)
- All 51 existing `noUnusedVariables` tests pass
- `cargo clippy -p biome_js_analyze -- -D warnings` passes clean
- `rustfmt --edition 2024 --check` passes clean

## Documentation

Rule documentation updated inline (valid example added to `declare_lint_rule!` doc comment).

### CODE REVIEW

**Comment by taberoajorge** [comment]
@ematipico @dyc3 It's a pleasure contributing in this project!

File: crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidNamespaceUnused.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+// Standalone unused namespace (no merged value declaration)
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidNamespaceUnused.ts:3]: missing magic comment `/* should generate diagnostics */`

**Comment by dyc3** [comment]
> https://github.com/biomejs/biome/pull/9320#issuecomment-4000629257

If we can, lets try to address the perf issue.

File: crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidNamespaceUnused.ts (hunk 1 above)
Comment (taberoajorge) [reply crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidNamespaceUnused.ts:3]: Done Sr!

File: crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs [hunk 2]
```diff
@@ -471,6 +481,80 @@ impl Rule for NoUnusedVariables {
...
+            a.kind(),
+            JsSyntaxKind::JS_MODULE_ITEM_LIST | JsSyntaxKind::JS_STATEMENT_LIST
+        )
+    })
+}
+
+fn is_declaration_merged_with_used(
+    model: &SemanticModel,
+    binding: &AnyJsIdentifierBinding,
+) -> bool {
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs]: Make this function return a `Option<bool>` so you can bubble up all the `Ok`/`Option` using `ok?` and `?`.

This is a pattern for all lint rules

Comment (taberoajorge) [reply crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs]: Refactored this to return `Option<bool>` and split the merge logic into small helpers so the namespace path can bubble `ok?`/`?` in the usual lint-rule style. I also moved the value-side lookup to `scope.get_binding(name)` so we avoid scanning the whole scope for every value declaration while keeping the namespace scan for the rarer path. Re-ran `cargo test -p biome_js_analyze no_unused_variables -- --show-output` and the targeted `js_analyzer/typescript_3735799142832611563.ts` benchmark locally; I did not reproduce a material regression on my machine.

File: crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs [hunk 3]
```diff
@@ -471,6 +481,110 @@ impl Rule for NoUnusedVariables {
...
+}
+
+fn is_namespace_merge_value_declaration(decl: &AnyJsBindingDeclaration) -> bool {
+    matches!(
+        decl,
+        AnyJsBindingDeclaration::JsVariableDeclarator(_)
+            | AnyJsBindingDeclaration::JsFunctionDeclaration(_)
+            | AnyJsBindingDeclaration::JsClassDeclaration(_)
+    )
+}
```
[the remark this answers is not in the document]
Comment (taberoajorge) [reply crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs:501]: Verified this against `binding_ext.rs`: `TsModuleDeclaration` can merge with `TsEnumDeclaration`, so the bot comment was correct. I added `TsEnumDeclaration` to `is_namespace_merge_value_declaration` and covered it with `validNamespaceDeclarationMergingEnum.ts`. Re-ran `INSTA_UPDATE=always cargo test -p biome_js_analyze no_unused_variables -- --show-output`, the targeted `js_analyzer/typescript_3735799142832611563.ts` benchmark, and the local `js_analyzer` bench suite; the rerun for the flagged benchmark came back as "No change in performance detected" locally.

**Comment by raashish1601** [comment]
One gap still looks open in the current helper: `is_namespace_merge_value_declaration()` only accepts variable/function/class/enum declarations, but Biome's own mergeability model in `crates/biome_js_syntax/src/binding_ext.rs` also treats `TsModuleDeclaration <-> TsInterfaceDeclaration` as a valid merge.

That means patterns like this still look like they would flag the namespace as unused even though it is part of an exported merged declaration:

```ts
export interface Cloner {
    clone(animal: Animal): Animal;
}

namespace Cloner {
    export type Metadata = string;
}
```

It may be safer to drive this check from `AnyJsBindingDeclaration::is_mergeable()` (or at least include `TsInterfaceDeclaration` and add a regression fixture) so `noUnusedVariables` stays aligned with the semantic binding rules instead of maintaining a narrower hand-written subset here.
