### PR TITLE
fix(lint/noExcessiveNestedTestSuites): don't alert if describe call is a member of some other object

### LINKED ISSUE #2599: 💅 noExcessiveNestedTestSuites rule violated by Zod schema
### Environment information

```bash
CLI:
  Version:                      1.7.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.2.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.6"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Linter:
  Recommended:                  false
  All:                          false
  Rules:                        complexity/useLiteralKeys = "off"
                                complexity/useOptionalChain = "warn"
                                correctness/noUnreachableSuper = "off"
                                correctness/noUnusedVariables = "warn"
                                performance/noDelete = "off"
                                style/noNonNullAssertion = "off"
                                style/useNamingConvention = "off"
                                suspicious/noExplicitAny = "off"
                                suspicious/noRedeclare = "off"
                                suspicious/noShadowRestrictedNames = "off"

Workspace:
  Open Documents:               0
```

### Rule name

noExcessiveNestedTestSuites

### Playground link

https://biomejs.dev/playground/?code=egAuAG8AYgBqAGUAYwB0ACgAewB9ACkACgAgACAALgBkAGUAcwBjAHIAaQBiAGUAKAAnACcAKQAKACAAIAAuAGQAZQBzAGMAcgBpAGIAZQAoACcAJwApAAoAIAAgAC4AZABlAHMAYwByAGkAYgBlACgAJwAnACkACgAgACAALgBkAGUAcwBjAHIAaQBiAGUAKAAnACcAKQAKACAAIAAuAGQAZQBzAGMAcgBpAGIAZQAoACcAJwApAAoAIAAgAC4AZABlAHMAYwByAGkAYgBlACgAJwAnACkAOwA%3D

### Expected result

A Zod schema definition with multiple `.describe()` statements should not violate the noExcessiveNestedTestSuites rule

For example:
```ts
z.object({})
  .describe('')
  .describe('')
  .describe('')
  .describe('')
  .describe('')
  .describe('');
```

Currently throws:
```
Excessive `describe()` nesting detected. biome(lint/complexity/noExcessiveNestedTestSuites)
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

Zod has a `describe` method for describing the fields of a zod schema. Now, this rule will no longer alert when presented with snippets like this:
```js
z.object({})
  .describe('')
  .describe('')
  .describe('')
  .describe('')
  .describe('')
  .describe('');
```

fixes #2599

## Test Plan

Added snippet to snapshot tests

```bash
cargo test -p biome_js_analyze no_excessive_nested_test_suites
```

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/complexity/no_excessive_nested_test_suites.rs [hunk 1]
```diff
@@ -138,6 +138,18 @@ impl Visitor for NestedTestVisitor {
...
+/// Determines whether or not the call expression is for a function that is a member of another object.
+///
+/// ```js
+/// const foo = {
+///   bar() {}
+/// }
+/// foo.bar(); // bar is a member of foo
+/// ```
+fn is_member(call: &JsCallExpression) -> bool {
+    call.parent::<JsStaticMemberExpression>().is_some()
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/complexity/no_excessive_nested_test_suites.rs:150]: You can use `JsStaticMemberExpression::can_cast`, which is more appropriate

**Review by ematipico — APPROVED** [review]
Awesome! Code is not more "Rusty"
