### PR TITLE
fix: noCommentText does not work when any other text is a child(#3298)

### LINKED ISSUE #3298: 💅 noCommentText does not work when any other text is a child
### Environment information

```bash
CLI:
  Version:                      1.8.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  false
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  suspicious/useNamespaceKeyword
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noDuplicateParameters
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noConstEnum
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noImplicitAnyLet
  suspicious/noDuplicateObjectKeys
  suspicious/noUnsafeDeclarationMerging
  correctness/noUnreachable
  suspicious/noFallthroughSwitchClause
  complexity/noUselessThisAlias
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  complexity/useRegexLiterals
  correctness/noSelfAssign
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  style/useWhile
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  style/useNumericLiterals
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  suspicious/noImportAssign
  suspicious/noLabelVar
  correctness/noGlobalObjectCalls
  suspicious/useDefaultSwitchClauseLast
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  suspicious/noSuspiciousSemicolonInJsx
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  a11y/noSvgWithoutTitle
  suspicious/noPrototypeBuiltins
  style/useAsConstAssertion
  correctness/useJsxKeyInIterable
  style/useExportType
  style/noArguments
  suspicious/noDebugger
  a11y/useValidAriaValues
  suspicious/noGlobalAssign
  suspicious/noCommentText
  correctness/noVoidElementsWithChildren
  suspicious/noMisleadingInstantiator
  suspicious/noThenProperty
  suspicious/noDuplicateJsxProps
  suspicious/useGetterReturn
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  security/noDangerouslySetInnerHtmlWithChildren
  suspicious/noExtraNonNullAssertion
  performance/noBarrelFile
  correctness/noRenderReturnValue
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  suspicious/noGlobalIsFinite
  suspicious/noSelfCompare
  suspicious/noAsyncPromiseExecutor
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  complexity/noWith
  suspicious/noDuplicateClassMembers
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  suspicious/noConfusingLabels
  a11y/useButtonType
  a11y/noAriaUnsupportedElements
  correctness/noFlatMapIdentity
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useAnchorContent
  complexity/noUselessRename
  correctness/noInvalidNewBuiltin
  complexity/noUselessConstructor
  a11y/noAccessKey
  style/useExponentiationOperator
  complexity/noUselessSwitchCase
  style/useSingleVarDeclarator
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/useIsArray
  a11y/noHeaderScope
  suspicious/noMisrefactoredShorthandAssign
  suspicious/noClassAssign
  suspicious/noFunctionAssign
```

### Rule name

noCommentText

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&lintRules=all&code=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABjADMAIAA9ACAAKAApACAAPQA%2BACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgADEAMgAzAAoAIAAgACAAIAAgACAALwAvACAAYQBiAGMACgAgACAAIAAgADwALwBkAGkAdgA%2BAAoAIAAgACkACgB9AAoACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAGMANAAgAD0AIAA8AGQAaQB2AD4AIAAvAC8AIABhAGIAYwA8AC8AZABpAHYAPgAKAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABjADUAIAA9ACAAPABkAGkAdgA%2BAAoAIAAgADwAYgByACAALwA%2BAAoAIAAgAC8ALwAgAGEAYgBjAAoAPAAvAGQAaQB2AD4A

### Expected result

Should show an error when text and comment is present (including multiline).

I'm not exactly sure of the desired behavior here, but I noticed eslint-plugin-react shows an error for multi-line children with a comment and biome does not.
image

Is it expected that all comments within children that are not wrapped in `{}` should show an error or just when they are the only child?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ryo-ebata**
## Summary

Changed logic to judge by regex, considering the case where a comment is inserted in the middle of a paragraph.

Expanded test cases and added explanation of rule.

The quick fix feature has also been developed to fix only the commented part.

Closes #3298 

### Invalid Case

Add comments, line breaks, etc. in sentences.

```tsx
<>
    <div>// comment</div>
    <div>/* comment */</div>
    <div>/** comment */</div>
    <div>text /* comment */</div>
    <div>/* comment */ text</div>
    <div>
        text
        // comment
    </div>
    <div>
        /* comment */
        text
    </div>
    <div>
        // comment
        text
    </div>
    <div>
        /* comment
        comment */
    </div>
</>
```

### Valid Case

```tsx
<>
    <div>{/* comment */}</div>
    <div>{/** comment */}</div>
    <div className={"cls" /* comment */}></div>
    <div>text {/* comment */}</div>
    <div>{/* comment */} text</div>
</>
```

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs [hunk 1]
```diff
@@ -16,23 +22,54 @@ declare_lint_rule! {
...
+    /// </div>;
     /// ```
     ///
     /// ### Valid
     ///
     /// ```jsx
-    /// const a = <div>{/* comment */}</div>;
-    /// const a1 = <div>{/** comment */}</div>;
-    /// const a2 = <div className={"cls" /* comment */}></div>;
+    /// <div>{/* comment */}</div>;
```
Comment (chansuke) [inline crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs:68]: You need to be warraped inside a FRAGMENT?

https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#document-the-rule

```suggestion
    /// ```jsx
    /// <>
    ///    <div>{/* comment */}</div>;
    ///    <div>{/** comment */}</div>;
    ///    <div className={"cls" /* comment */}></div>;
    ///    <div>text {/* comment */}</div>;
    ///    <div>{/* comment */} text</div>;
    /// </>
    /// ```
```

File: crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs [hunk 2]
```diff
@@ -77,29 +112,29 @@ impl Rule for NoCommentText {
     fn action(ctx: &RuleContext<Self>, _: &Self::State) -> Option<JsRuleAction> {
         let node = ctx.query();
         let mut mutation = ctx.root().begin();
+        let node_text = node.text().to_string();
+
+        // Replace the comments with JSX comments
+        let new_jsx_value = COMMENT_REGEX.replace_all(&node_text, |caps: &regex::Captures| {
```
Comment (chansuke) [inline crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs:118]: This is just my preference (not a suggestion) for readability. What do you think?

```
let new_jsx_value = COMMENT_REGEX.replace_all(&node_text, |caps: &regex::Captures| {
    let comment = caps[0]
        .trim_start_matches("//")
        .trim_start_matches("/*")
        .trim_end_matches("*/")
        .trim();
    format!("{{/*{}*/}}", comment)
});
```

File: crates/biome_js_analyze/tests/specs/suspicious/noCommentText/invalid.tsx.snap [hunk 3]
```diff
@@ -4,67 +4,261 @@ expression: invalid.tsx
...
   i Unsafe fix: Wrap the comments with braces
   
-    1   │ - const·a3·=·<div>//·comment</div>;
-      1 │ + const·a3·=·<div>{/*·comment*/}</div>;
-    2 2 │   const a4 = <div>/* comment */</div>;
-    3 3 │   const a5 = <div>/** comment */</div>;
+     3  3 │       <div>/* comment */</div>
+     4  4 │       <div>/** comment */</div>
+     5    │ - ····<div>text·/*·comment·*/</div>
+        5 │ + ····<div>text·{/*comment*/}</div>
```
Comment (ematipico) [inline crates/biome_js_analyze/tests/specs/suspicious/noCommentText/invalid.tsx.snap:121]: The previous suggestion was able to keep the spaces, but now we remove leading and trailing spaces between the word "comment".

Before: `const·a4·=·<div>{/*·comment·*/}</div>;`
Now: `<div>text·{/*comment*/}</div>`

Comment (ryo-ebata) [reply crates/biome_js_analyze/tests/specs/suspicious/noCommentText/invalid.tsx.snap]: @ematipico 
thanks your check, I had missed it...
I fixed in this commit!
[9c6f601](https://github.com/biomejs/biome/pull/3446/commits/9c6f601e8d9fd5134e5a921bb494185495811176)

File: crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs (hunk 1 above)
Comment (ryo-ebata) [reply crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs]: @chansuke 
I don't know why it would be better to enclose it in fragments, but I fixed it in the meantime.

If you don't mind, could you please tell me what you mean by this change?
I checked the link you provided, but don't really understand it...
[65ce3fe](https://github.com/biomejs/biome/pull/3446/commits/65ce3fed352f75724a56729f298931ef2f2b10bf)

File: crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs (hunk 2 above)
Comment (ryo-ebata) [reply crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs:120]: @chansuke 
To accommodate Doc comments(like `/** example */`), the code has been changed as follows

```rs
let new_jsx_value = COMMENT_REGEX.replace_all(&node_text, |caps: &regex::Captures| {
    let comment = caps[0].trim();
    match comment {
        c if c.starts_with("//") => format!("{{/* {} */}}", c[2..].trim()),
        c if c.starts_with("/**") => format!("{{/** {} */}}", &c[3..c.len() - 2].trim()),
        c => format!("{{/* {} */}}", &c[2..c.len() - 2].trim()),
    }
});
```

If you have any suggestions for a better code, I welcome them!

File: crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs (hunk 1 above)
Comment (chansuke) [reply crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs]: In the documentation, it is stated:

> When adding valid snippets in the ### Valid section, you can use one single snippet.

With this jsx example, I believe it should be treated as one single snippet using <></>.

Ex:https://github.com/dyc3/biome/blob/ec663b9fee9afa8bf9dec2e8a2d554628561128f/crates/biome_js_analyze/src/lint/nursery/use_consistent_curly_braces.rs#L39-L44

Comment (ryo-ebata) [reply crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs]: @chansuke 
thank you!
I understood, FRAGMENT is necessary.
