### PR TITLE
fix(core): don't ignore required files

### LINKED ISSUE #6089: 💅 Rules fail when `package.json` is not included in Biome configuration
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.5
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.15.1
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noBannedTypes
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUndeclaredDependencies
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useImportExtensions
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    nursery/noFloatingPromises
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noArguments
    style/noCommaOperator
    style/noDescendingSpecificity
    style/noInferrableTypes
    style/noNonNullAssertion
    style/noParameterAssign
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/useAsConstAssertion
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useEnumInitializers
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useNamespaceKeyword

Workspace:
  Open Documents:               0
```

### Rule name

lint/correctness/noUndeclaredDependencies

### Playground link

https://next.biomejs.dev/playground/?lintRules=all&files.main.tsx=aQBtAHAAbwByAHQAIAAiAHYAaQB0AGUAIgA7AA%3D%3D&files.package.json=ewAKACAAIAAiAGQAZQB2AEQAZQBwAGUAbgBkAGUAbgBjAGkAZQBzACIAOgAgAHsACgAgACAAIAAgACIAdgBpAHQAZQAiADoAIAAiACoAIgAKACAAIAB9AAoAfQA%3D

### Expected result

I have `"!package.json"` in my `files.includes`, because I don't want Biome to format the manifest. `npm pkg fix` disagrees with the formatting, causing flip-flops.

It seems like the solution is to additionally and explicitly include the `package.json` in the `linter.includes`, but maybe I'm missing something.

This is newly introduced from 2.0-beta.4 -> 2.0-beta.5

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

Fixes #6089. Also fixes an issue in our own CI: https://github.com/biomejs/biome/actions/runs/15120815401/job/42502525360?pr=6090

Now that we respect users `files.includes` and ignore settings better, we should also be even more careful to always load relevant manifests and other required files, _even when those are excluded by the users settings_. To fix this, we check whether required files are part of an ignored directory, and only ignore them when this is the case. Whether the file itself is ignored in the configuration is then irrelevant in such cases.

## Test Plan

Added another test.

### CODE REVIEW

File: crates/biome_fs/src/path.rs [hunk 1]
```diff
@@ -149,11 +149,22 @@ impl BiomePath {
...
         matches!(self.kind, FileKinds::Handleable)
     }
 
+    /// Returns `true` for file types that must be scanned (if the scanner is
+    /// enabled) because Biome's own functionality relies on them.
+    #[inline(always)]
+    pub fn is_required_during_scan(&self) -> bool {
+        matches!(
+            self.kind,
+            FileKinds::Config | FileKinds::Ignore | FileKinds::Manifest
```
Comment (ematipico) [inline crates/biome_fs/src/path.rs:164]: Are we intentionally adding `tsconfig.json` too?

File: crates/biome_service/src/workspace/scanner.rs [hunk 2]
```diff
@@ -322,18 +324,35 @@ impl TraversalContext for ScanContext<'_> {
...
+                .and_then(|dir_path| {
+                    ctx.workspace
+                        .is_path_ignored(IsPathIgnoredParams {
+                            project_key: ctx.project_key,
+                            path: dir_path.into(),
+                            features: FeaturesBuilder::new().build(),
+                        })
+                        .ok()
+                })
+                .unwrap_or_default()
```
Comment (ematipico) [inline crates/biome_service/src/workspace/scanner.rs:342]: I'm not sure I understand this case. Can you explain it to me?

**Review by ematipico — APPROVED** [review]
Looks good! Just left a couple of questions :)

File: crates/biome_fs/src/path.rs (hunk 1 above)
Comment (arendjr) [reply crates/biome_fs/src/path.rs:164]: Yes, because it's required for resolving imports in projects. Only inside `node_modules` we exclude them, because they shouldn't affect published packages (ideally, published packages don't even have them, but well... NPM).

File: crates/biome_service/src/workspace/scanner.rs (hunk 2 above)
Comment (arendjr) [reply crates/biome_service/src/workspace/scanner.rs:342]: Yes. So assume you have two directories: `src` and `vendor`. Both have a `package.json` inside. And our configuration looks like this:

```json
{
    "files": {
        "includes": [
            "**.js",
            "!vendor"
        ]
    }
}
```

No `package.json` is matched by these settings, but in a project scan, we should still include the one inside `src`, in order to correctly populate the project layout. But why should we populate the project layout for packages found inside `vendor`? We already know the directory isn't used for either linting or formatting.

In fairness, _maybe_ we'll run into problems if people have wired their projects such that `vendor` is another source of packages, just like `node_modules` is. But well, that may be something we need to solve another day...
