### PR TITLE
feat(lint/useIsNan): add code fix action

### LINKED ISSUE #96: 📎 `lint/useIsNan` should provide a code fix
### Description

[useIsNan](https://biomejs.dev/lint/rules/useIsNan/) could provide an unsafe code fix, such as:

```diff
- 123 == NaN
+ Number.isNan(123)
```

### PR DESCRIPTION
**Pull request by victor-teles**
## Summary
Closes #96 

Provide code fix for useIsNaN rule:

```diff
- 123 == NaN
+ Number.isNaN(123)
```

```diff
- 123 === NaN
+ Number.isNaN(123)
```

```diff
- 123 !== NaN
+ !Number.isNaN(123)
```

```diff
- 123 != NaN
+ !Number.isNaN(123)
```

Should this rule support other operators like > < >= <=?

## Test Plan

- [x] Manual testing code fix using CLI :)

### CODE REVIEW

File: crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap [hunk 1]
```diff
@@ -618,6 +939,15 @@ invalid.js:38:1 lint/correctness/useIsNan ━━━━━━━━━━━━
     39 │ 
     40 │ // switch-case
   
+  i Suggested fix: Use Number.isNaN() instead.
+  
+    36 36 │   123 == globalThis.NaN;
+    37 37 │   123 == window.NaN;
+    38    │ - 123·==·globalThis.Number.NaN;
+       38 │ + Number.isNaN(123);
```
Comment (ematipico) [inline crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: We should retain the `globalThis`

File: crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap [hunk 2]
```diff
@@ -603,11 +915,20 @@ invalid.js:37:1 lint/correctness/useIsNan ━━━━━━━━━━━━
     38 │ 123 == globalThis.Number.NaN;
     39 │ 
   
+  i Suggested fix: Use Number.isNaN() instead.
+  
+    35 35 │   
+    36 36 │   123 == globalThis.NaN;
+    37    │ - 123·==·window.NaN;
+       37 │ + Number.isNaN(123);
```
Comment (ematipico) [inline crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:923]: We should retain the `window`

**Review by ematipico — COMMENTED** [review]
Thank you! We're almost there, there are a couple of cases that need extra attention

File: crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap (hunk 1 above)
Comment (victor-teles) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: @ematipico 

I tried to use global_identifier function to identify `globalThis` and  `window` 
but im getting some unexpected behavior

globalThis.NaN -> returns globalThis
window.NaN ->  returns windows
globalThis.Number.NaN  ->  returns Number

am I misunderstanding the global_identifier function?

Comment (ematipico) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: cc @Conaclos

Comment (Conaclos) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: @victor-teles are you sure about the third case?

`global_identifier` returns two values: the leftmost value (which is the reference identifier) and the leftmost value (name of the member).
Thus, we should get the following results:

| input | result |
| - | - |
| globalThis.NaN | (globalThis, "NaN") |
| window.NaN | (windows,"NaN") |
| globalThis.Number.NaN | (globalThis, "NaN") |
| globalThis.windows.Number.NaN | (globalThis, "NaN") |

Comment (victor-teles) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: @Conaclos Yes, but the return is None, not Number as i said

https://github.com/biomejs/biome/assets/78874691/d9efda59-db9e-4278-a759-a6082f3693e4

Comment (Conaclos) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: Ah got it!

In fact `global_identifier` implicitly checks that `NaN` is a global variable. Unfortunately the function remarks that it is qualified by `Number`. Thus, it returns `None` because `NaN` is assumed a property of `Number`.

What I suggest: reuse the qualifier of `NaN` as qualifier for `isNaN`, adding `Number` if the qualifier does not end by `Number`.

Comment (victor-teles) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: @Conaclos Gonna try, thank you for the suggestion.

Comment (Conaclos) [reply crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap:947]: If you need more help, don't be afraid asking :)

File: crates/rome_js_analyze/src/semantic_analyzers/correctness/use_is_nan.rs [hunk 3]
```diff
@@ -142,6 +146,144 @@ impl Rule for UseIsNan {
...
+        .with_trailing_trivia_pieces([])?;
+    let right = right_expression
+        .with_leading_trivia_pieces([])?
+        .with_trailing_trivia_pieces([])?;
+
+    if !is_nan_on_left {
+        return Some((left, right));
+    }
+
+    Some((right, left))
```
Comment (ematipico) [inline crates/rome_js_analyze/src/semantic_analyzers/correctness/use_is_nan.rs:286]:
```suggestion
    if !is_nan_on_left {
       Some((left, right))
    } else {
       Some((right, left))
    }

    
```

**Review by ematipico — APPROVED** [review]
That's a significant contribution! Thank you!

**Review by Conaclos — APPROVED** [review]
Great contribution!

**Comment by ematipico** [comment]
Rebasing the PR should make the CI pass

**Comment by Conaclos** [comment]
Time to merge 🚀. Thanks!!
