### PR TITLE
fix(css_analyze): ignore at-rules supporting descriptors

### LINKED ISSUE #6567: 💅 CSS font-feature-values rules are not ignored by noUnknownProperty
### Environment information

```bash
Biome 5f42630
```

### Rule name

lint/correctness/noUnknownProperty

### Playground link

https://biomejs.dev/playground/?code=QABmAG8AbgB0AC0AZgBlAGEAdAB1AHIAZQAtAHYAYQBsAHUAZQBzACAAIgBUAGUAcwB0ACIAIAB7AAoAIAAgAEAAcwB0AHkAbABlAHMAZQB0ACAAewAKACAAIAAgACAAcwBvAG0AZQAtAGYAZQBhAHQAdQByAGUAOgAgADEAOwAKACAAIAB9AAoAfQAKAA%3D%3D&language=css

### Expected result

Any declarations are allowed inside the @namespace rules in @font-feature-values. It's how you define custom idents. The `noUnknownProperty` rule should not trigger.

See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values#using_styleset_in_a_font-feature-values_rule

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Netail**
## Summary

Closes #6567, ignore unknown properties if located in at-rules supporting descriptors

## Test Plan

Unit test

### CODE REVIEW

File: crates/biome_css_analyze/src/lint/correctness/no_unknown_property.rs [hunk 1]
```diff
@@ -76,12 +79,22 @@ impl Rule for NoUnknownProperty {
...
+                    || CssLayerAtRule::can_cast(ancestor.kind())
+                    || CssMediaAtRule::can_cast(ancestor.kind())
+                    || CssScopeAtRule::can_cast(ancestor.kind())
+                    || CssStartingStyleAtRule::can_cast(ancestor.kind())
+                    || CssSupportsAtRule::can_cast(ancestor.kind()))
+            {
+                return true;
+            }
+
+            false
```
Comment (ematipico) [inline crates/biome_css_analyze/src/lint/correctness/no_unknown_property.rs]: Two things:
- why did we remove skip()?
- in these cases, it's best to create a new node via `declare_node_union`. The code becomes more readable

File: crates/biome_css_analyze/tests/specs/correctness/noUnknownProperty/valid.at-rules.css.snap [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+	}
+}
+
+@foo {
+	bar: 0;
+}
+
+```
+
+_Note: The parser emitted 2 diagnostics which are not shown here._
```
Comment (ematipico) [inline crates/biome_css_analyze/tests/specs/correctness/noUnknownProperty/valid.at-rules.css.snap]: This seems important. There are parsing errors, and I believe you don't want to test broken syntax

Comment (Netail) [reply crates/biome_css_analyze/tests/specs/correctness/noUnknownProperty/valid.at-rules.css.snap]: Oops, didn't notice. Some syntax that would be valid with scss 😅

File: crates/biome_css_analyze/src/lint/correctness/no_unknown_property.rs [hunk 3]
```diff
@@ -116,3 +123,12 @@ impl Rule for NoUnknownProperty {
         )
     }
 }
+
+declare_node_union! {
+    pub DescriptorSupportingAtRules = TwApplyAtRule | CssContainerAtRule
```
Comment (ematipico) [inline crates/biome_css_analyze/src/lint/correctness/no_unknown_property.rs]:
```suggestion
    pub AnyDescriptorSupportingAtRules = TwApplyAtRule | CssContainerAtRule
```

As per internal coding guidelines, all unions must start with `Any*`

File: .changeset/tough-pans-greet.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#6567](https://github.com/biomejs/biome/issues/6567). Ignore unknown properties in at-rules which support descriptors.
```
Comment (ematipico) [inline .changeset/tough-pans-greet.md]: You might want to mention the rule. Without clicking the issue, there's little context, and it gets difficult to understand what's been fixed **and where**
