### PR TITLE
fix(linter): noUselessUndefinedInitialization false positive in svelte 4.

### LINKED ISSUE #6003: 💅 `noUselessUndefinedInitialization` false positive in svelte 4 file.
### Environment information

```bash
CLI:
  Version:                      2.0.0-beta.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v18.20.3
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.2.9

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.jsonc
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  unset
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/noSvgWithoutTitle
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useKeyWithClickEvents
    a11y/useKeyWithMouseEvents
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noBannedTypes
    complexity/noEmptyTypeParameters
    complexity/noExcessiveNestedTestSuites
    complexity/noExtraBooleanCast
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/noWith
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useLiteralKeys
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noFlatMapIdentity
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noUselessContinue
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useArrayLiterals
    correctness/useImportExtensions
    correctness/useIsNan
    correctness/useValidForDirection
    correctness/useYield
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    performance/useTopLevelRegex
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noArguments
    style/noCommaOperator
    style/noCommonJs
    style/noDefaultExport
    style/noDescendingSpecificity
    style/noDoneCallback
    style/noInferrableTypes
    style/noNegationElse
    style/noNonNullAssertion
    style/noParameterAssign
    style/noProcessEnv
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/noYodaExpression
    style/useAsConstAssertion
    style/useBlockStatements
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useEnumInitializers
    style/useExponentiationOperator
    style/useExportType
    style/useForOf
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useNumericLiterals
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    style/useThrowOnlyError
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSkippedTests
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/useAdjacentOverloadSignatures
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useNamespaceKeyword
    suspicious/useValidTypeof

Workspace:
  Open Documents:               0
```

### Rule name

lint/complexity/noUselessUndefinedInitialization

### Playground link

https://next.biomejs.dev/playground/?lintRules=all&files.main.svelte=PABzAGMAcgBpAHAAdAAgAGwAYQBuAGcAPQAiAHQAcwAiAD4ACgAJAHQAeQBwAGUAIAAkACQAUAByAG8AcABzACAAPQAgAHsACgAgACAAIAAgACAAIABjAGwAYQBzAHMAPwA6ACAAcwB0AHIAaQBuAGcAIAB8ACAAdQBuAGQAZQBmAGkAbgBlAGQAIAB8ACAAbgB1AGwAbAA7AAoAIAAgACAAIAB9ADsACgAKAAkAbABlAHQAIABjAGwAYQBzAHMATgBhAG0AZQA6ACAAJAAkAFAAcgBvAHAAcwBbACIAYwBsAGEAcwBzACIAXQAgAD0AIAB1AG4AZABlAGYAaQBuAGUAZAA7AAoACQBlAHgAcABvAHIAdAAgAHsAIABjAGwAYQBzAHMATgBhAG0AZQAgAGEAcwAgAGMAbABhAHMAcwAgAH0AOwAKADwALwBzAGMAcgBpAHAAdAA%2BAAoA

### Expected result

In svelte 4, exported values in components are the component's props. Assigning a default value makes the prop optional.

In the playground, the value is not immediately exported because it needs to be renamed. This triggers the false positive for the rule.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by codiini**
I used Claude Code to think through the issue and validate my solution with tests.

## Summary

Fixes #6003

The `noUselessUndefinedInitialization` rule was producing false positives for exported variables. In Svelte 4, exported variables with `undefined` initialization are used to declare optional component props:

​```js
let className = undefined;
export { className as class };
​```

The rule incorrectly flagged this pattern because it only looked at the variable declaration in isolation, without considering that it would be exported later.

### Solution

Changed the rule to use Biome's semantic model to check if a variable is exported before flagging it. This handles all export patterns:
- Direct exports: `export let x = undefined;`
- Named exports: `let x = undefined; export { x };`
- Renamed exports: `let x = undefined; export { x as y };`
- Default exports: `let x = undefined; export default x;`

## Test Plan

- Added test cases for all export patterns in `noUselessUndefinedInitialization/valid.js`
- Ran `cargo test -p biome_js_analyze --test spec_tests -- specs::complexity::no_useless_undefined_initialization` - all tests pass
- Manually verified with the exact pattern from the issue:
    - Before fix; `undefined` is incorrectly removed
    - After fix; `undefined` is preserved for exported variables

## Docs

Documentation is included in the rule's rustdoc comments with examples showing that exported variables are not flagged.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/complexity/no_useless_undefined_initialization.rs [hunk 1]
```diff
@@ -49,6 +51,17 @@ declare_lint_rule! {
     /// }
     /// ```
     ///
+    /// Exported variables are not flagged because in some frameworks (e.g., Svelte),
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/complexity/no_useless_undefined_initialization.rs]:
```suggestion
    /// Exported variables are not flagged because in some frameworks (e.g., Svelte 4),
```

File: crates/biome_js_analyze/tests/specs/complexity/noUselessUndefinedInitialization/valid.js.snap [hunk 2]
```diff
@@ -18,4 +17,23 @@ class Foo {
 	bar = undefined;
 }
 
+// Exported variables should not be flagged.
+// In frameworks like Svelte, exported variables with undefined initialization
```
Comment (dyc3) [inline crates/biome_js_analyze/tests/specs/complexity/noUselessUndefinedInitialization/valid.js.snap]:
```suggestion
// In frameworks like Svelte 4, exported variables with undefined initialization
```

File: crates/biome_js_analyze/src/lint/complexity/no_useless_undefined_initialization.rs [hunk 3]
```diff
@@ -96,6 +110,19 @@ impl Rule for NoUselessUndefinedInitialization {
             };
 
             if keyword.is_undefined() {
+                // Skip if the variable is exported.
+                // In frameworks like Svelte, exported variables with `undefined`
```
Comment (dyc3) [inline crates/biome_js_analyze/src/lint/complexity/no_useless_undefined_initialization.rs]:
```suggestion
                // In frameworks like Svelte 4, exported variables with `undefined`
```

File: .changeset/tender-cycles-draw.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#6003](https://github.com/biomejs/biome/issues/6003): `noUselessUndefinedInitialization` no longer reports exported variables initialized to `undefined`. In Svelte, this pattern is used to declare optional component props.
```
Comment (dyc3) [inline .changeset/tender-cycles-draw.md]:
```suggestion
Fixed [#6003](https://github.com/biomejs/biome/issues/6003): `noUselessUndefinedInitialization` no longer reports exported variables initialized to `undefined`. In Svelte 4, this pattern is used to declare optional component props.
```

**Comment by ematipico** [comment]
Lol, the output emitted in the PR description is bigger than the code itself

**Comment by dyc3** [comment]
@codiini You'll need to update the snapshots

**Comment by codiini** [comment]
@dyc3 All done.
