### PR TITLE
fix(lint/useArrowFunction): enclose with parens when needed

### LINKED ISSUE #1524: 🐛 useArrowFunction exception in operator expression ?
### Environment information

```block
CLI:
  Version:                      1.5.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

```js
const _setImmediate =  (typeof setImmediate === 'function' &&
function (fn) {
  setImmediate(fn);
}) ||
function (fn) {
  setTimeout(fn, 0);
};
```

after `check --apply`

```js
const _setImmediate =  (typeof setImmediate === 'function' &&
(fn) => {
  setImmediate(fn);
}) ||
(fn) => {
  setTimeout(fn, 0);
};
```

> Uncaught SyntaxError: Malformed arrow function parameter list

### Expected result

```js
const _setImmediate =  (typeof setImmediate === 'function' &&
((fn) => {
  setImmediate(fn);
})) ||
((fn) => {
  setTimeout(fn, 0);
});
```

Arrow functions should be wrapped with `()` ?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #1524

## Test Plan

New tests dded.

### CODE REVIEW

File: crates/biome_js_analyze/src/analyzers/complexity/use_arrow_function.rs [hunk 1]
```diff
@@ -165,20 +180,41 @@ impl Rule for UseArrowFunction {
...
-        .parent()
-        .kind()
-        .is_some_and(|parent_kind| {
-            matches!(
-                parent_kind,
-                JsSyntaxKind::JS_CALL_EXPRESSION
+    function_expression.syntax().parent().is_some_and(|parent| {
+        // Copied from the implementation of `NeedsParentheses` for `JsArrowFunctionExpression`
+        // in the `biome_js_formatter` crate.
+        // TODO: Should `NeedsParentheses` be moved in `biome_js_syntax`?
```
Comment (ematipico) [inline crates/biome_js_analyze/src/analyzers/complexity/use_arrow_function.rs:186]: Reply to the TODO: since the logic is the same, I think so

File: crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap [hunk 2]
```diff
@@ -268,108 +273,285 @@ invalid.ts:30:12 lint/complexity/useArrowFunction  FIXABLE  ━━━━━━
...
+    48 │ const non_null_assertion = function () {}!;
+  
+  i Function expressions that don't use this can be turned into arrow functions.
+  
+  i Safe fix: Use an arrow function instead.
+  
+    44 44 │   const satisfies = function () {} satisfies () => void;
+    45 45 │   const unary = +function () {};
+    46    │ - const·conditionalTest·=·function·()·{}·?·true·:·false;
+       46 │ + const·conditionalTest·=·(()·=>·{}·)·?·true·:·false;
```
Comment (ematipico) [inline crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap:402]: nit: it seems there a space between `}` and `) ?`

**Review by ematipico — APPROVED** [review]
