### PR TITLE
fix(lint/useImportType): respect `jsxRuntime`

### LINKED ISSUE #2004: 💅 `useImportType` fixes `import React from 'react'` into `import type React from 'react'`
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        a11y/noSvgWithoutTitle = "off"
                                a11y/useKeyWithClickEvents = "off"
                                a11y/useKeyWithMouseEvents = "off"
                                a11y/useValidAnchor = "off"
                                complexity/noUselessLoneBlockStatements = "error"
                                correctness/noInvalidUseBeforeDeclaration = "off"
                                correctness/noNewSymbol = "error"
                                correctness/noUnusedPrivateClassMembers = "error"
                                correctness/noUnusedVariables = "error"
                                correctness/useExhaustiveDependencies = "off"
                                correctness/useHookAtTopLevel = "error"
                                nursery/noExportsInTest = "error"
                                nursery/noSemicolonInJsx = "error"
                                nursery/noUselessTernary = "error"
                                performance/noDelete = "off"
                                style/noNegationElse = "error"
                                style/noNonNullAssertion = "off"
                                style/noRestrictedGlobals = "error"
                                style/noShoutyConstants = "error"
                                style/noUnusedTemplateLiteral = "off"
                                style/useBlockStatements = "error"
                                style/useCollapsedElseIf = "error"
                                style/useForOf = "error"
                                style/useNodejsImportProtocol = "error"
                                style/useNumberNamespace = "error"
                                style/useShorthandAssign = "error"
                                style/useShorthandFunctionType = "error"
                                style/useSingleCaseStatement = "error"
                                suspicious/noConsoleLog = "error"
                                suspicious/noRedeclare = "off"

Workspace:
  Open Documents:               0
```

### Rule name

lint/style/useImportType

### Playground link

not possible to reproduce in playground

### Expected result

Don't touch this import

image

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

Don't treat `React` as a type-only import when the `jsxRuntime` is set to `reactClassic`.

Fixes #2004.

## Test Plan

Test cases added.

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/style/use_import_type.rs [hunk 1]
```diff
@@ -135,6 +145,12 @@ impl Rule for UseImportType {
                     AnyJsCombinedSpecifier::JsNamespaceImportSpecifier(namespace_specifier) => {
                         let namespace_binding = namespace_specifier.local_name().ok()?;
                         let namespace_binding = namespace_binding.as_js_identifier_binding()?;
+                        if ctx.has_jsx_runtime(JsxRuntime::ReactClassic)
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/lint/style/use_import_type.rs:148]: Why not directly return the value of the runtime?

```suggestion
                        if ctx.jsx_runtime() == JsxRuntime::ReactClassic
```

**Review by Conaclos — APPROVED** [review]

File: crates/biome_js_analyze/src/lint/style/use_import_type.rs (hunk 1 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/lint/style/use_import_type.rs:148]: No particular reason, really. I'll change it.
