### PR TITLE
fix(biome_js_analyze): false positive for range operator in regular expression

### LINKED ISSUE #4950: 💅 incorrect `noMisleadingCharacterClass` on regexp
### Environment information

```bash
CLI:
  Version:                      1.9.4
```

### Rule name

noMisleadingCharacterClass

### Playground link

https://biomejs.dev/playground/?code=JwB0AGUAcwB0ACAAXAB1ADAAMwAwADEAIAB0AGgAaQBzACcALgByAGUAcABsAGEAYwBlACgALwBbAFwAdQAwADMAMAAwAC0AXAB1ADAAMwAwADIAXQAvAGcALAAgACcAWABYAFgAJwApAA%3D%3D

### Expected result

I don't think `/[\u0300-\u0302]/` warrants this error, it seems to be working well (it did work for me way before I installed biome 😁).

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by bushuai**
## Summary
Closes #4950 

In `/[\u0300-\u0302]/`, the character class defines a valid range from `\u0300` to `\u03002`, this is syntactically correct. Although these are combinatorial characters, they are used here as separate characters, not in combination with other characters to form a new character, so no warning will be triggered.

This PR adds a validation to check whether the hyphen is treated as a range operator or not in the character class, for example:

**1. treated as a valid range operator** ✅

```
/[\u0300-\u0302]/
```
it will match \u0300 or \u0301 or \u0302

**2. forms a new character with the following unicode escape sequences** ⚠️

```
/[-\u0302]/g
```
the rule will be trigged

**3. treated as a string literal** ✅
```
/[\u0302-]/g
```
it will match "-" or "\u0302".

## Test Plan
added tests and updated the snapshots.

### CODE REVIEW

File: crates/biome_js_analyze/src/lib.rs [hunk 1]
```diff
@@ -198,18 +198,18 @@ mod tests {
 
     use super::*;
 
-    #[ignore]
+    // #[ignore]
```
Comment (arendjr) [inline crates/biome_js_analyze/src/lib.rs:201]: This should remain ignored.

```suggestion
    #[ignore]
```

**Review by arendjr — COMMENTED** [review]
Thanks! I have to admit this code is becoming quite hard to read. What is preventing this from matching against `\u1000-\u1001` outside of a character class (`[]`)?

**Comment by bushuai** [comment]
> I have to admit this code is becoming quite hard to read. What is preventing this from matching against `\u1000-\u1001` outside of a character class (`[]`)? It may be good to at least have a test for that.

:( sorry for the late reply. I'll add comments to the code and add a test for this case.

**Review by arendjr — APPROVED** [review]
Thanks!
