### PR TITLE
fix(10024): eslint generation

### LINKED ISSUE #10024: 🐛 Eslint migration generation multi rule support
## What happened?

Currently when 2 biome rules came out of a single eslint rule, we do not correctly enable both biome rules from that single eslint rule. Instead the last or first found from the visitor gets used. On top of that, when the same rule got inspired() and the other same(), then it will generate 2 entries in the migration map, with the second entry never being able to reach.

## Expected result

Correctly map a single eslint rule to multiple biome rules

### PR DESCRIPTION
**Pull request by Netail**
## Summary

- Support migrating a single Eslint rule to multiple Biome rules (if there are multiple sources) 
- Correctly generate the mapping file if the same Eslint source is mentioned as inspired & same in the same Biome rule, but different language analyzers. Prefer same over inspired

Closes #10024 

Ref [Discord](https://discord.com/channels/1132231889290285117/1132602754276274216/1496993681327263854)

### CODE REVIEW

File: xtask/codegen/src/generate_migrate_eslint.rs [hunk 1]
```diff
@@ -17,37 +17,44 @@ pub(crate) fn generate_migrate_eslint(mode: Mode) -> Result<()> {
...
+        });
         lines.push(quote! {
             #eslint_name => {
-                #check_inspired
-                #check_nursery
-                let group = rules.#group_ident.get_or_insert_with(Default::default);
-                let rule = group.unwrap_group_as_mut().#name_ident.get_or_insert(Default::default());
-                rule.set_level(rule.level().max(rule_severity.into()));
+                #( #rules )*
             }
```
[the remark this answers is not in the document]
Comment (Netail) [reply xtask/codegen/src/generate_migrate_eslint.rs]: https://github.com/biomejs/biome/pull/10118/commits/e3530d683f2c5fd0ea945b2b35bd5047368a921f

File: xtask/codegen/src/generate_migrate_eslint.rs [hunk 2]
```diff
@@ -1,54 +1,146 @@
...
-    biome_js_analyze::visit_registry(&mut visitor);
-    biome_json_analyze::visit_registry(&mut visitor);
-    biome_graphql_analyze::visit_registry(&mut visitor);
-    biome_css_analyze::visit_registry(&mut visitor);
-    biome_html_analyze::visit_registry(&mut visitor);
-    let mut lines = Vec::with_capacity(visitor.0.len());
-    for ((eslint_name, source_kind), (group_name, rule_metadata)) in visitor.0 {
-        let name = rule_metadata.name;
-        let name_ident = format_ident!("{}", Case::Snake.convert(name));
+fn generate_multi_mapping(eslint_name: Box<str>, mapped_rules: Vec<RuleMapping>) -> TokenStream {
```
Comment (Netail) [inline xtask/codegen/src/generate_migrate_eslint.rs:13]: Made 2 generators, due linting errors on the blocked & migrated variable if it was as single rule without nursery & inspired. As the value was only read and never changed

Comment (Netail) [reply xtask/codegen/src/generate_migrate_eslint.rs:13]: And those variables are dragged to a higher level to prevent an early exit

File: .changeset/weak-kiwis-post.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@biomejs/biome": patch
+---
+
+Fixed [#10024](https://github.com/biomejs/biome/issues/10024): `biome migrate eslint` now correctly maps a single Eslint rule to multiple Biome rules (if applicable).
```
Comment (ematipico) [inline .changeset/weak-kiwis-post.md]: It's not very clear what's the impact of this change to the users. See if this suggestions works. I removed the word "map", and used "migrates" instead. 

```suggestion
Fixed [#10024](https://github.com/biomejs/biome/issues/10024): `biome migrate eslint` correctly migrates `eslint` rules that belong to multiple Biome rules.
```

Maybe we should add an example.

File: crates/biome_js_analyze/src/lint/a11y/no_access_key.rs [hunk 4]
```diff
@@ -41,7 +41,7 @@ declare_lint_rule! {
         version: "1.0.0",
         name: "noAccessKey",
         language: "jsx",
-        sources: &[RuleSource::EslintJsxA11y("no-access-key").same()],
+        sources: &[RuleSource::EslintJsxA11y("no-access-key").same(), RuleSource::HtmlEslint("no-accesskey-attrs").inspired()],
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/a11y/no_access_key.rs:44]: Isn't this a separate bug fix?

Comment (Netail) [reply crates/biome_js_analyze/src/lint/a11y/no_access_key.rs:44]: I added these sources changes to check if the eslint migrate generation went correctly. (No duplicate entry) It's mainly docs changes as the migration script is not impacted by these changes

**Review by ematipico — APPROVED** [review]
