### PR TITLE
fix(js_parser): desambigaute JSX and const type param of arrow function

### LINKED ISSUE #846: 🐛 Adding a `const` modifier for the first type parameter of an arrow function produces a parsing error
### Environment information

```block
Playground
```

### What happened?

When enabling TypeScript and JSX, the following code produces a parsing error:

```ts
<const T,>() => {};
```

`<const T,>` is erroneously parsed as a JSX tag.

[Playground link](https://biomejs.dev/playground?lintRules=all&code=PABjAG8AbgBzAHQAIABUACwAPgAoACkAIAA9AD4AIAB7AH0AOwA%3D)

### Expected result

The input should be parsed as an arrow function.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Fix #846.

This fixes a parsing error that rejected the following valid code when TypeScript and JSX are both enabled:

```ts
<const T,>() => {};
```

See these two comments for some context:
- https://github.com/biomejs/biome/issues/739#issuecomment-1823476061
- https://github.com/biomejs/biome/issues/739#issuecomment-1823747500

## Test Plan

I added tests and updated snapshots.

### CODE REVIEW

File: crates/biome_js_parser/src/syntax/function.rs [hunk 1]
```diff
@@ -754,34 +754,36 @@ fn is_parenthesized_arrow_function_expression_impl(
...
-            // <A extends B<C>>() => {}
-
-            // <a... JSX override
-            else if JsSyntaxFeature::Jsx.is_supported(p) {
+            // <A extends B<C>>() => {};
+
+            if JsSyntaxFeature::Jsx.is_supported(p) {
+                // Disambiguate between JSX and type parameters
+                // Type parameters of arrow functions accept only the `const` modifier.
+                let n = if p.nth(n + 1) == T![const] { n + 1 } else { n };
```
Comment (denbezrukov) [inline crates/biome_js_parser/src/syntax/function.rs:777]: nit: 
You can use `p.nth_at` here.

**Comment by ematipico** [comment]
@Conaclos Is the regression expected?

**Comment by Conaclos** [comment]
> Is the regression expected?

No. I updated the code to avoid the regression. However, the post seems not updated yet?

File: crates/biome_js_parser/src/syntax/function.rs (hunk 1 above)
Comment (Conaclos) [reply crates/biome_js_parser/src/syntax/function.rs:777]: Thanks for the suggestion. By the way, why do we have this helper? Using `nth(<n>) = <kind>` looks cleaner?

Comment (denbezrukov) [reply crates/biome_js_parser/src/syntax/function.rs]: Hm, we can discuss it.

1.
`p.nth_at(n, T![abstract]) && p.nth_at(n + 1, T![class])` 
vs 
`p.nth(n) == T![abstract] && p.nth(n + 1) == T![class]`

2.
`matches!(p.nth(n), T![abstract] | T![const]) && matches!(p.nth(n + 1), T![class] | T![const)`
 vs 
`p.nth_at_ts(n, FIRST_SET) && p.nth_at_ts(n + 1, SECOND_SET)`

**Comment by Conaclos** [comment]
@ematipico Taking a closer look to the regression it is expected. In fact TypeScript expects an error because the tag `T` is not declared. We previously emitted an error because we were expecting an arrow function. Now we correctly parse it to a JSX element.
