### PR TITLE
fix(parse/html/vue): parse dynamic slot directives that contain quotes

### LINKED ISSUE #8710: 📝 Vue custom slot with template literal cause parse error
### Environment information

<details>

```bash

CLI:
  Version:                      2.3.11
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.16.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.3.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true
  HTML full support enabled:    true

Formatter:
  Format with errors:           unset
  Indent style:                 Space
  Indent width:                 2
  Line ending:                  unset
  Line width:                   100
  Attribute position:           unset
  Bracket spacing:              unset
  Includes:                     unset

JavaScript Formatter:
  Enabled:                      unset
  JSX quote style:              unset
  Quote properties:             As needed
  Trailing commas:              unset
  Semicolons:                   As needed
  Arrow parentheses:            Always
  Bracket spacing:              unset
  Bracket same line:            unset
  Quote style:                  Single Quotes
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset
  Expand lists:                 unset

CSS Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  unset

GraphQL Formatter:
  Enabled:                      unset
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0

```

</details>

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/2.3.11/schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true,
    "defaultBranch": "development"
  },
  "files": {
    "ignoreUnknown": false,
    "includes": ["**", "!worker-configuration.d.ts"]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "nursery": {
        "useSortedClasses": "error"
      },
      "correctness": {
        "noUnusedVariables": {
          "level": "warn",
          "options": {
            "ignoreRestSiblings": true
          }
        }
      },
      "style": {
        "noNonNullAssertion": "off"
      }
    },
    "domains": {
      "vue": "all"
    },
    "includes": ["**", "!worker-configuration.d.ts"]
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "attributePosition": "auto",
      "quoteProperties": "asNeeded",
      "arrowParentheses": "always",
      "semicolons": "asNeeded"
    },
    "globals": []
  },
  "json": {
    "formatter": {
      "enabled": true
    }
  },
  "css": {
    "linter": {
      "enabled": false
    },
    "formatter": {
      "enabled": false
    },
    "parser": {
      "tailwindDirectives": true
    }
  },
  "html": {
    "experimentalFullSupportEnabled": true,
    "parser": {
      "interpolation": true
    },
    "formatter": {
      "enabled": true,
      "indentScriptAndStyle": false,
      "selfCloseVoidElements": "always",
      "attributePosition": "multiline"
    }
  },
  "assist": {
    "enabled": true,
    "actions": {
      "source": {
        "organizeImports": "on"
      }
    }
  },
  "overrides": [
    {
      "includes": ["**/*.vue"],
      "linter": {
        "rules": {
          "style": {
            "useConst": "off",
            "useImportType": "off"
          },
          "correctness": {
            "noUnusedVariables": "off",
            "noUnusedImports": "off"
          }
        }
      }
    }
  ]
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=120&code=PAB0AGUAbQBwAGwAYQB0AGUACgAgACAAdgAtAGYAbwByAD0AIgBlAHAAaQBzAG8AZABlACAAaQBuACAAZQBwAGkAcwBvAGQAZQBzACIACgAgACAAIwBbAGAAJAB7AGUAcABpAHMAbwBkAGUALgBpAGQAfQAtAGMAZQBsAGwAYABdAD0AIgB7ACAAcgBvAHcAIAB9ACIACgAgACAAOgBrAGUAeQA9ACIAZQBwAGkAcwBvAGQAZQAuAGkAZAAiAAoAPgAKACAAIAAgACAALgAuAC4ACgA8AC8AdABlAG0AcABsAGEAdABlAD4A&language=vue&ruleDomains.project=recommended

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

This PR lets the HTML parser parse v-slot directives that have more complex expressions inside them: ``#[`${episode.id}-cell`]="{ row }"``

Primarily generated by gpt-5.2-codex, but added a couple more test cases myself.

fixes #8710

## Test Plan

added snapshots

### CODE REVIEW

File: crates/biome_html_parser/src/lexer/mod.rs [hunk 1]
```diff
@@ -155,6 +155,40 @@ impl<'src> HtmlLexer<'src> {
...
+    fn consume_token_vue_directive_argument(&mut self) -> HtmlSyntaxKind {
+        let start = self.text_position();
+        let mut brackets_stack = 0;
+        let mut quotes_seen = QuotesSeen::new();
+
+        while let Some(byte) = self.current_byte() {
+            quotes_seen.check_byte(byte);
+
+            if quotes_seen.is_empty() {
+                match byte {
```
Comment (ematipico) [inline crates/biome_html_parser/src/lexer/mod.rs]: Nit: we should use the lookup table to check the bytes
