### PR TITLE
fix(html/useAltText): handle Vue dynamic :alt and v-bind:alt bindings

### LINKED ISSUE #9349: 🐛 lint/a11y/useAltText: False positive for Vue dynamic :alt binding in .vue files
### Environment information

<details>

```bash

$ biome rage
CLI:
  Version:                      2.4.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:                    unset
  BIOME_LOG_PREFIX_NAME:             unset
  BIOME_LOG_LEVEL:                   unset
  BIOME_LOG_KIND:                    unset
  BIOME_CONFIG_PATH:                 unset
  BIOME_THREADS:                     unset
  BIOME_WATCHER_KIND:                unset
  BIOME_WATCHER_POLLING_INTERVAL:    unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v25.7.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.3.10

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true
  HTML full support enabled:    true

Workspace:
  Open Documents:               0

```

</details>

### What happened?

`useAltText` triggers a false positive in Vue SFCs when the `alt` attribute
is bound dynamically via `:alt` (i.e. `v-bind:alt`).
```vue
<template>
  <img :src="image.src" :alt="image.description" />
</template>
```

Playground reproduction: [Playground](https://biomejs.dev/playground/?code=PAB0AGUAbQBwAGwAYQB0AGUAPgAKACAAIAA8AGkAbQBnACAAOgBzAHIAYwA9ACIAaQBtAGEAZwBlAC4AcwByAGMAIgAgADoAYQBsAHQAPQAiAGkAbQBhAGcAZQAuAGQAZQBzAGMAcgBpAHAAdABpAG8AbgAiACAALwA%2BAAoAPAAvAHQAZQBtAHAAbABhAHQAZQA%2BAA%3D%3D&language=vue)

### Expected result

`:alt="..."` should be treated as a valid `alt` attribute, equivalent to
`alt="..."`, and should suppress the `useAltText` diagnostic.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by SchahinRohani**
## Summary

Fixes #9349

`useAltText` was triggering a false positive in Vue SFCs when the `alt` attribute is bound dynamically via `:alt` (Vue v-bind shorthand) or `v-bind:alt` (explicit form).

The root cause: `:alt` and `v-bind:alt` are not parsed as `HtmlAttribute` nodes but as `AnyVueDirective` variants (`VueVBindShorthandDirective` and `VueDirective` respectively). The previous implementation only called `find_attribute_by_name("alt")` which internally skips any non-`HtmlAttribute` nodes, so Vue directives were never matched.

The fix iterates over the full `HtmlAttributeList` and explicitly handles:
- `alt="..."` — standard `HtmlAttribute`
- `:alt="..."` — `VueVBindShorthandDirective`, arg text is `":alt"` (leading colon stripped)
- `v-bind:alt="..."` — `VueDirective` with `name_token == "v-bind"`, arg text is `":alt"` (leading colon stripped)

## Test Plan

Tested with:
```
 cargo test -p biome_html_analyze
```

Added `crates/biome_html_analyze/tests/specs/a11y/useAltText/vue/valid.vue` covering all three cases. 

All 132 tests pass:
```
test result: ok. 132 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

## Docs

No documentation changes needed — this is a bug fix for an existing rule, not a new rule or option.

---

## AI Assistance Disclosure

This PR was developed with assistance from Claude (claude.ai). Claude helped debug the Biome AST structure (`AnyVueDirective`, `VueVBindShorthandDirective`, etc.) and iterate on the implementation. The final solution was reviewed and understood by me throughout the process.

### CODE REVIEW

File: crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs [hunk 1]
```diff
@@ -199,9 +199,60 @@ fn has_type_image_attribute(element: &AnyHtmlElement) -> bool {
...
-    element.find_attribute_by_name("alt").is_some()
+    /// Returns the bare argument name from a Vue directive arg node,
+    /// stripping the leading colon (e.g. `":alt"` → `"alt"`).
+    fn vue_arg_name(arg: &biome_html_syntax::VueDirectiveArgument) -> String {
+        arg.syntax()
+            .text_trimmed()
+            .to_string()
+            .trim_start_matches(':')
+            .to_string()
+    }
```
Comment (dyc3) [inline crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs]: - `.to_string()` allocates strings on the heap, and we shouldn't need to do that for this check. Use borrowed strings, or if you really need an owned string, use `TokenText`.
- you also shouldn't need to trim `:`, you can simply check the static directive argument.

File: crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs [hunk 2]
```diff
@@ -199,9 +199,60 @@ fn has_type_image_attribute(element: &AnyHtmlElement) -> bool {
...
+
+    let is_alt = |attrs: &biome_html_syntax::HtmlAttributeList| {
```
Comment (dyc3) [inline crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs]: nit: this shouldn't need to be a closure

File: crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs (hunk 1 above)
Comment (SchahinRohani) [reply crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs]: No more `.to_string()` or `:` trimming, using `as_vue_static_argument()` → `name_token()` directly

File: crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs (hunk 2 above)
Comment (SchahinRohani) [reply crates/biome_html_analyze/src/lint/a11y/use_alt_text.rs]: Moved the logic to `has_attribute_or_vue_binding` on `AnyHtmlElement` in `element_ext.rs` — no more closure

**Comment by SchahinRohani** [comment]
@dyc3 added the changeset and addressed all review comments.

Should I split the has_attribute_or_vue_binding into two separate functions — one for plain HTML attributes and one for Vue bindings — or is the combined function preferred for now?

File: crates/biome_html_syntax/src/element_ext.rs [hunk 3]
```diff
@@ -123,6 +124,53 @@ impl AnyHtmlElement {
...
     }
+
+    /// Check if the element has a given HTML attribute or a Vue v-bind binding
+    /// targeting the same attribute name.
+    ///
+    /// Handles:
+    /// - `name="..."` — standard HTML attribute
+    /// - `:name="..."` — Vue v-bind shorthand (`VueVBindShorthandDirective`)
+    /// - `v-bind:name="..."` — explicit Vue v-bind (`VueDirective`)
+    pub fn has_attribute_or_vue_binding(&self, name_to_lookup: &str) -> bool {
```
Comment (dyc3) [inline crates/biome_html_syntax/src/element_ext.rs]: This should return an `Option<AnyHtmlAttribute>` with the found attribute. It would give the function more utility.

**Comment by dyc3** [comment]
The combined function is preferred, thank you.

**Comment by SchahinRohani** [comment]
You are welcome!

CodeRabbit had a good catch for the `v-bind` case-insensitivity, so fixing that:
```diff
- let is_bind = d.name_token().is_ok_and(|t| t.text_trimmed() == "v-bind");
+ let is_bind = d.name_token().is_ok_and(|t| t.text_trimmed().eq_ignore_ascii_case("v-bind"));
```
