### PR TITLE
fix(lint/useHookAtTopLevel): detect early returns before calls to hooks

### LINKED ISSUE #696: 🐛 `useHookAtTopLevel` doesn't flag hook usages after an early return
### Environment information

```block
N/A, I used the playground.
```

### What happened?

When a React component contains an early return, calls to hooks after that point are not correctly identified as being conditional.

For instance, see the following playground example: https://www.biomejs.dev/playground?lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUAUwB0AGEAdABlACAAfQAgAGYAcgBvAG0AIAAiAHIAZQBhAGMAdAAiADsACgAKAGYAdQBuAGMAdABpAG8AbgAgAE0AeQBDAG8AbQBwAG8AbgBlAG4AdAAoAHsAIABiAGEAcgAgAH0AKQAgAHsACgAgACAAaQBmACAAKAAhAGIAYQByACkAIAB7AAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAG4AdQBsAGwAOwAKACAAIAB9AAoACgAgACAAYwBvAG4AcwB0ACAAWwBmAG8AbwAsACAAcwBlAHQARgBvAG8AXQAgAD0AIAB1AHMAZQBTAHQAYQB0AGUAKAAxACkAOwAKAAoAIAAgAHIAZQB0AHUAcgBuACAAPABkAGkAdgA%2BAHsAZgBvAG8AfQA8AC8AZABpAHYAPgA7AAoAfQA%3D

### Expected result

The call to `useState()` should be flagged as conditional.

As a sidenote, I think it would be better if the `useHookAtTopLevel` rule were named `noConditionalHookCalls` instead, since that's its real purpose. As this example shows, being at the top-level isn't a guarantee something is not conditional.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by arendjr**
## Summary

This PR implements early return detection for the `useHookAtTopLevel` rule. This is an important feature to prevent conditional hook invocations.

Since the rule was already able to track hook invocations across function calls, I needed an additional model for tracking early returns in all functions, which lead to a bit of a complex solution that requires 3 visitors. I'm open to suggestions if this can be simplified :)

Fixes #696.

## Test Plan

Test cases have been added.

### CODE REVIEW

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 1]
```diff
@@ -100,14 +121,159 @@ fn enclosing_function_if_call_is_at_top_level(call: &JsCallExpression) -> Option
...
+            }
+            WalkEvent::Leave(node) => {
+                if AnyFunctionLike::can_cast(node.kind()) {
+                    self.stack.pop();
+                    return;
+                }
+
+                if let Some(entry) = self.stack.last_mut() {
+                    if let Some(early_return) = JsReturnStatement::cast_ref(node) {
+                        entry.early_return = Some(early_return.syntax().text_range());
```
Comment (Conaclos) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:176]: I think we could avoid the cast:
```suggestion
                    if JsReturnStatement::can_cast(node.kind()) {
                        entry.early_return = Some(node.text_range());
```

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:176]: Good catch :+1:

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 2]
```diff
@@ -100,14 +121,159 @@ fn enclosing_function_if_call_is_at_top_level(call: &JsCallExpression) -> Option
         .and_then(|body| body.parent::<AnyJsFunction>())
 }
 
+/// Model for tracking which function calls are preceeded by an early return.
+#[derive(Clone, Default)]
+struct EarlyReturnsModel(HashMap<JsCallExpression, TextRange>);
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:126]: We usually try to use `FxHashMap`

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 3]
```diff
@@ -100,14 +121,159 @@ fn enclosing_function_if_call_is_at_top_level(call: &JsCallExpression) -> Option
...
+#[derive(Default)]
+struct EarlyReturnDetectionVisitor {
+    early_returns: EarlyReturnsModel,
+    stack: Vec<EarlyReturnDetectionVisitorStackEntry>,
+}
+
+#[derive(Default)]
+struct EarlyReturnDetectionVisitorStackEntry {
+    early_return: Option<TextRange>,
+}
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:151]: nit: 

```rs
struct EarlyReturnDetectionVisitorStackEntry(Option<TextRange>);
```

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 2 above)
Comment (ematipico) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:126]: I believe we don't need to track `JsCallExpression`. By looking at the code, it seems we only need to track the range of the call expression. This means that we can use a `FxHashSet<TextRange>`.

And then below, the code will be:

```rs
if let Some(early_return_range) = early_returns.get(call.range()) {
    return Some(Suggestion::None {
        hook_name_range,
        path,
        early_return: Some(early_return_range.clone()),
    });
}
```

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs [hunk 4]
```diff
@@ -116,10 +282,11 @@ impl Rule for UseHookAtTopLevel {
         let options = ctx.options();
         let options = ReactExtensiveDependenciesOptions::new(options.clone());
 
-        let call = ctx.query();
+        let FunctionCall(call) = ctx.query();
         let hook_name_range = call.callee().ok()?.syntax().text_trimmed_range();
         if react_hook_configuration(call, &options.hooks_config).is_some() {
-            let model = ctx.model();
+            let model = ctx.semantic_services.model();
+            let early_returns = &ctx.early_returns;
```
Comment (ematipico) [inline crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:289]: nit: I would create two functions to abstract the consumption of these two models:

```rs
let semantic_model = ctx.semantic_model();
let early_returns_model = ctx.early_returns_model();
```

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 2 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:126]: I'll change to use a `FxHashMap` :+1:

We can't use a set though, because the range of the return isn't the same as the range of the call. We need to determine for every call site, whether there was an early return *prior to* that call site.

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 3 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:151]: I wanted to be a bit explicit about what the text range applies to, because we care about text ranges for different purposes here. I think the previous conversation already showed some confusion on front :sweat_smile:

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 4 above)
Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:289]: Sure.

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 2 above)
Comment (ematipico) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:126]: The description of the model is a bit cryptic, though, because it seems that a function call is associated to **one** early return, but now it seems that we can have two function calls with the same text range. Is that correct?

Would it be possible to expand the model's description to understand better how this data structure is handled? I believe there's room for optimisation

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs]: Every function call is associated with zero or one early return, that's correct. But yes, it's also possible that multiple function calls get associated with the same early return, so in that case the text range for such early returns would be cloned multiple times. Do you think that would be significant? I suppose it's feasible to wrap them in an `Rc` or `Arc`.

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs]: I see a `TextRange` is only 8 bytes and derives `Copy`, so I don't think we'd win anything by wrapping it.

Comment (arendjr) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs]: Also pushed a bit of extra documentation.

File: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs (hunk 3 above)
Comment (ematipico) [reply crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs:157]: I mean, the name of the struct already has "EarlyReturn", I think it's already explicit enough 🤔

**Review by ematipico — APPROVED** [review]
Thank you for adding more documentation. ❤️  As you might have noticed, I am particularly picky about it, because I think we arrived at this point thanks to how thoroughly we explain our internal code.
