### PR TITLE
fix: recognize format_range and format_on_type as Format capabilities…

### LINKED ISSUE #8209: 🐛 "Request textDocument/codeAction failed" shows when saving JSON files
### Environment information

```block
$ npx biome rage
CLI:
  Version:                      2.3.6
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v24.11.1
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/11.6.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  true

Workspace:
  Open Documents:               0
```

### What happened?

Whenever saving .vscode/settings.json, it throws this error. It does it all the time, even when no adjustments are made and the file stays the same. Ctrl + S = Getting this error

```
2025-11-21 20:23:51.934 [info] [Error - 8:23:51 PM] Request textDocument/rangeFormatting failed.
2025-11-21 20:23:51.934 [info]   Message: Biome doesn't support this feature for the language JSONC
  Code: -32603 
Biome doesn't support this feature for the language JSONC//
```

It is probably what other people in the comments for #6529 refer to.

My biome.json file content - https://pastebin.com/xXDE1a8C
My settings.json file content - https://pastebin.com/MQWY1jU8

### Expected result

It should not throw an error.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by ruidosujeira**
fixes #8209

## Summary

The workspace capability detection only treated `formatter.format` as a signal that a file supports formatting. As a result, file handlers that only rely on `format_range` or `format_on_type` were not marked as supporting `Format`, causing `SourceFileNotSupported` for valid range-formatting requests (e.g. JSONC `.vscode/settings.json`).  
This change updates `FeaturesSupported::with_capabilities()` to consider any of `format`, `format_range`, or `format_on_type` when enabling `FeatureKind::Format`.

## Test Plan

Build Biome with this change.
Open a project containing `.vscode/settings.json` (JSONC) in VS Code.
Trigger: **Format Selection** (sends `textDocument/rangeFormatting`) and full document formatting (`textDocument/formatting`), if configured.

Expectations:

- JSONC range formatting no longer throws `SourceFileNotSupported`.
- The selected range is formatted correctly.
- Full-document formatting still works for languages/files that provide `format()`.
- Format-on-type (where supported) still works and is not blocked by capability detection.

### CODE REVIEW

File: crates/biome_service/src/workspace.rs [hunk 1]
```diff
@@ -147,7 +147,12 @@ impl FeaturesSupported {
     /// Adds the features that are enabled in `capabilities` to this result.
     #[inline]
     pub fn with_capabilities(mut self, capabilities: &Capabilities) -> Self {
-        if capabilities.formatter.format.is_some() {
+        // Fix for #8209: Check if ANY formatting capability exists, not just format()
+        // This ensures that files with format_range/format_on_type support are recognized
```
Comment (ematipico) [inline crates/biome_service/src/workspace.rs]:
```suggestion
        // Check if ANY formatting capability exists, not just format()
        // This ensures that files with format_range/format_on_type support are recognized
```

**Review by ematipico — APPROVED** [review]
Good catch!!

**Comment by ruidosujeira** [comment]
@ematipico Are the additions and modifications made satisfactory?

**Review by dyc3 — APPROVED** [review]
LGTM
