### PR TITLE
fix(parse/js): fix a case where valid js was being interpretted as ts

### LINKED ISSUE #9548: 🐛 Valid JS parsed as TS
### Environment information

<details>

```bash
@biomejs/biome: 2.4.8

```

</details>

### What happened?

```js
const slotFn = isFirstMount
  ? i => ({ [CONTENT_SLOT]: i })
  : i => wrapSlotExpr(newExprs[i]);
```

Prints 2 errors:
```txt
expected `:` but instead found `=>`
```

and

```txt
return type annotation are a TypeScript only feature. Convert your file to a TypeScript file or remove the syntax.
```

See https://biomejs.dev/playground/?code=YwBvAG4AcwB0ACAAcwBsAG8AdABGAG4AIAA9ACAAaQBzAEYAaQByAHMAdABNAG8AdQBuAHQACgAgACAAPwAgAGkAIAA9AD4AIAAoAHsAIABbAEMATwBOAFQARQBOAFQAXwBTAEwATwBUAF0AOgAgAGkAIAB9ACkACgAgACAAOgAgAGkAIAA9AD4AIAB3AHIAYQBwAFMAbABvAHQARQB4AHAAcgAoAG4AZQB3AEUAeABwAHIAcwBbAGkAXQApADsA&language=ts

### Expected result

No errors.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

I used gpt 5.4 to find the bug and fix it. I can post the agent's rationale if needed, because the fix looks a bit odd at a glance.

fixes #9548

## Test Plan

snapshots

### CODE REVIEW

File: crates/biome_js_parser/tests/js_test_suite/ok/conditional_arrow_return_type_in_consequent.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+const slotFn = isFirstMount
+  ? ((i): Slot => ({ [CONTENT_SLOT]: i }))
+  : i => wrapSlotExpr(newExprs[i]);
```
Comment (ematipico) [inline crates/biome_js_parser/tests/js_test_suite/ok/conditional_arrow_return_type_in_consequent.ts:3]: What are we testing here?

Comment (dyc3) [reply crates/biome_js_parser/tests/js_test_suite/ok/conditional_arrow_return_type_in_consequent.ts:3]: it's supposed to assert we still parse it the same way when its typescript, i just realized its slightly different

**Comment by ematipico** [comment]
We still regressed, we shouldn't have merged this one
