### PR TITLE
fix(js_analyze): skip `noAutofocus` check if eligible

### LINKED ISSUE #4339: 🐛 `lint/a11y/noAutofocus` contradicts with MDN recommendations for <dialog>
### Environment information

```block
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

A `lint/a11y/noAutofocus` contradicts with MDN recommendations for <dialog>:

> The [autofocus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute should be added to the element the user is expected to interact with immediately upon opening a modal dialog. If no other element involves more immediate interaction, it is recommended to add autofocus to the close button inside the dialog, or the dialog itself if the user is expected to click/activate it to dismiss.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

[Code example](https://biomejs.dev/playground/?indentStyle=space&code=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABBAHMAawBQAGEAcwBzAHcAbwByAGQARABpAGEAbABvAGcAIAA9ACAAKAApACAAPQA%2BACAAewAKACAAIABjAG8AbgBzAHQAIABpAGQAIAA9ACAAdQBzAGUASQBkACgAKQA7AAoAIAAgAGMAbwBuAHMAdAAgAFsAcABhAHMAcwB3AG8AcgBkACwAIABzAGUAdABQAGEAcwBzAHcAbwByAGQAXQAgAD0AIAB1AHMAZQBTAHQAYQB0AGUAKAAiACIAKQA7AAoACgAgACAAYwBvAG4AcwB0ACAAaABhAG4AZABsAGUAQwBoAGEAbgBnAGUAIAA9ACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACgAKABlAHYAZQBuAHQAKQAgAD0APgAgAHsACgAgACAAIAAgAHMAZQB0AFAAYQBzAHMAdwBvAHIAZAAoAGUAdgBlAG4AdAAuAHQAYQByAGcAZQB0AC4AdgBhAGwAdQBlACkAOwAKACAAIAB9ACwAIABbAF0AKQA7AAoACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AGQAaQBhAGwAbwBnACAAbwBwAGUAbgA%2BAAoAIAAgACAAIAAgACAAPABmAG8AcgBtAD4ACgAgACAAIAAgACAAIAAgACAAPABsAGEAYgBlAGwAIABoAHQAbQBsAEYAbwByAD0AewBpAGQAfQA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIABFAG4AdABlAHIAIABwAGEAcwBzAHcAbwByAGQACgAgACAAIAAgACAAIAAgACAAPAAvAGwAYQBiAGUAbAA%2BAAoAIAAgACAAIAAgACAAIAAgADwAaQBuAHAAdQB0AAoAIAAgACAAIAAgACAAIAAgACAAIAB0AHkAcABlAD0AIgBwAGEAcwBzAHcAbwByAGQAIgAKACAAIAAgACAAIAAgACAAIAAgACAAdgBhAGwAdQBlAD0AewBwAGEAcwBzAHcAbwByAGQAfQAKACAAIAAgACAAIAAgACAAIAAgACAAbwBuAEMAaABhAG4AZwBlAD0AewBoAGEAbgBkAGwAZQBDAGgAYQBuAGcAZQB9AAoAIAAgACAAIAAgACAAIAAgACAAIABhAHUAdABvAEYAbwBjAHUAcwAKACAAIAAgACAAIAAgACAAIAAgACAAYQB1AHQAbwBDAG8AbQBwAGwAZQB0AGUAPQAiAG8AZgBmACIACgAgACAAIAAgACAAIAAgACAAIAAgAGkAZAA9AHsAaQBkAH0ACgAgACAAIAAgACAAIAAgACAALwA%2BAAoAIAAgACAAIAAgACAAPAAvAGYAbwByAG0APgAKACAAIAAgACAAPAAvAGQAaQBhAGwAbwBnAD4ACgAgACAAKQA7AAoAfQA7AAoA)

### Expected result

It should permit `autoFocus` when it is used inside a dialog.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by seeintea**
## Summary

Closes #4339 

Use a custom visitor to detect that an element with the `autofocus` attribute is a child element of `dialog` element  or `popover` attribute.

## Test Plan

Updated the snapshot tests

### CODE REVIEW

File: crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs [hunk 1]
```diff
@@ -50,6 +52,16 @@ declare_lint_rule! {
     /// <MyComponent autoFocus={true} />
     ///```
     ///
+    /// ```jsx
+    /// // `autoFocus` prop in element has `popover` attribute is valid
```
Comment (ematipico) [inline crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs:56]: Nit: generally, when we need to explain a particular case, we tend to add a paragraph before the code, like in these cases

**Review by ematipico — APPROVED** [review]
Looks good! Just a nit around docs

File: crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs (hunk 1 above)
Comment (seeintea) [reply crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs:58]: Okay, I've perfected it.
